### ISSUE TITLE
C++ Design Guidelines

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#1]
- [ ] Get C++ SDK DRAFT Design Guidelines reviewed and committed to azure-sdk repo
  - [ ] Add Missing Items to this list

**Comment by gilbertw** [comment]
@BillyONeal Can you do a read over the design guidelines for any must have topics.  Please add them to the description section of this issue.  I will do the same.

**Comment by RickWinter** [comment]
Lets plan to deliver a completed DRAFT guideline by Sept 4th.

**Comment by RickWinter** [comment]
Closing issue, individual guideline issues are tracked in the azure-sdk repository
