### ISSUE TITLE
Headers files should not include JSON library. Include JSON from each cpp file that uses it.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1009]
Headers files should not include JSON library. Include JSON from each cpp file that uses it.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/1004#discussion_r527498642_

**Comment by Jinming-Hu** [comment]
why?

**Comment by Jinming-Hu** [comment]
I noticed core sdk includes curl headers in header file [ref](https://github.com/Azure/azure-sdk-for-cpp/blob/a09584a925522610256cd6c179acea3cd4c63293/sdk/core/azure-core/inc/azure/core/http/curl/curl_connection.hpp#L15). To me, both of them are C headers, there's not difference. So why core sdk team can do it while storage sdk team cannot?

**Comment by vhvb1989** [comment]
> 
> 
> why not?

Because the JSON lib gets externally exposed by doing that. 

> I noticed core sdk includes curl headers in header file

That is a bug!  I need to fix it.

**Comment by Jinming-Hu** [comment]
> > I noticed core sdk includes curl headers in header file
> 
> That is a bug! I need to fix it.

Sure, then i'll wait until you fix it. Also, json library is only used in DataLake and File service, both of which are owned by @katmsft . So i'll assign this issue to @katmsft

**Comment by vhvb1989** [comment]
@Jinming-Hu , just wanted to share the fix for libcurl: https://github.com/Azure/azure-sdk-for-cpp/pull/1023

@katmsft  please update the storage headers and remove the "#include json" from them. 
Include the json header from the cpp files.

If json is used from headers, then move that implementation to cpp.

**Comment by ahsonkhan** [comment]
Following up from offline conversation, other than curl and json, a similar fix needs to be applied to blobs and its dependency on libxml2. In general, we want to avoid (as much as possible), exposing header files related to an implementation detail from our public/customer facing header files. This is especially true about our third party dependencies, which we want to be able to change between versions without impacting the customer.

**Comment by katmsft** [comment]
Blobs going to use JSON in the near future, also adding @Jinming-Hu .

**Comment by Jinming-Hu** [comment]
> Blobs going to use JSON in the near future, also adding @Jinming-Hu .

which API?

**Comment by Jinming-Hu** [comment]
We have to rewrite the auto-generator to fix this issue. There's no timeline for the new auto-generator

**Comment by vhvb1989** [comment]
@Jinming-Hu  Since the json library is not in the ::Internal layer, this is not super important any more.

We are still exposing the Json API to customers but it's somehow hidden in the Internal layer which is not expected to be used by end users.
