### ISSUE TITLE
Need a mechanism to unrelease package

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1018]
Storage teams recently finds it necessary to have a mechanism (might be Azure pipeline or whatever else) to unrelease our packages in case of emergency like when we find some packages might have a data integrity issue. The packages we need to unrelease includes:

* tags and releases on GitHub
* vcpkg
* NuGet

This is necessary because we did experience severe issues several times in the past, not only in C++, but also in JS and DMlib. Every time the actions we took is to delete or deprecate the packages we'd released. We have a pipeline for this in JS. We can also deprecate NuGet package for DMLib. But we still don't have such kind of facility for C++. Last time we had to deprecate beta3 release, we simply deleted the GitHub release packages and ended up having invalid links on the [Azure SDK Releases Page](https://azure.github.io/azure-sdk/releases/latest/#c). Storage team thinks this process can be improved for better customer experience.

**Comment by RickWinter** [comment]
@weshaggard Is this something your team plans to support in the pipleines?

**Comment by weshaggard** [comment]
No this isn't something we have plans to support. In general undoing a release is not a good experience, as publicly published artifacts are generally immutable. For C++ for example when we start publishing to vcpkg what would you expect an undo to look like? I think the best course here is to ensure you do the correct level of testing before you do an official public release and if you find issues that need to be addressed after you do a public release you should simply do another release to fix those issues.

I'm not entirely sure what process you are referring to for JS as npm will not let you remove a package after publishing ([after 24 hours](https://docs.npmjs.com/cli/v6/commands/npm-unpublish)), the only option is to deprecate or release a new version. Even with that support that doesn't undo the release tags or documentation that was published. Other package managers like nuget will not let you unpublish anything, you can unlist from search results but that is it. I don't know what options there are for vcpkg but I think the real solution is to do another release if you find an issue as opposed to trying to roll-back a release.

**Comment by RickWinter** [comment]
@Jinming-Hu Can you provide more details on the JS deprecation/deletion pipeline you mentioned.

**Comment by Jinming-Hu** [comment]
@ljian3377 Hi Lin, can you provide some details about JS package deprecation?

**Comment by ljian3377** [comment]
The JavaScript Storage SDK use the NPM to publish packages. It supports the depreciation of versions of a package via a simple npm command. 
```bash
npm deprecate <package-name>@<version> "<message>"
```
And the EngSys team provide us a [npm-admin-tasks pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2067&_a=summary) for these kind of NPM tasks as they require the admin permission.

I guess what you need is to figure out a way to deprecate a version or whatever else that could make a version less accessible to the user.

**Comment by weshaggard** [comment]
All that does is essentially tag a release with a message. It doesn't prevent folks from using it nor does it clean-up any other things created during the release process (i.e. docs, release tags, etc).

So for cpp there isn't any real way to mark things as deprecated, currently I think the best we could do would be to add a note perhaps in the github release for the version.  Once we start moving to vcpkg I'm not sure they have support for deprecate either, at least not one that I found from a quick search. 

So from my prospective the guidance should basically be you cannot unrelease all you can do is make sure you are ready to release before doing a public release and if you find an issue after release do another release to fix that issue.

**Comment by Jinming-Hu** [comment]
Hi @RickWinter @weshaggard , storage team had a discussion about this topic today, and a method brought up by @katmsft to undo a vcpkg release is to revert that commit. For example, we have 1.0 2.0 3.0, once we find some severe issue in release 3.0, we can open another PR to revert that commit which upgrades 2.0 to 3.0. What do you think of this way?

Also about GitHub tags/releases, we want to be aligned with other languages. What does other sdk do under the circumstances of a severe bug like data integrity issue. Besides shipping a new release, are we going to remove the problematic tags?

**Comment by weshaggard** [comment]
Even if you revert a vcpkg commit there is really nothing stopping folks from using the older commit before the revert. So I think that is just building a false sense of security. Instead perhaps just adding a deprecation message to advise folks not to use it, that is more aligned to what happens with other languages.

As for the github tags/releases and docs the other languages do nothing to try and clean those up. Once a release is in the wild there is really nothing you can do except try and move people forward to the newest release with the fix.

**Comment by RickWinter** [comment]
@Jinming-Hu We will not be adding an unrelease package pipeline.  The expectation is the package is thoroughly tested and ready to ship when it releases.  In the unfortunate and hopefully unlikely scenario that a package is broken, the workflow will be to fix the package, publish it, and update documentation mentioning the broken package is deprecated.
