### ISSUE TITLE
revise changelog in storage sdk

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1019]
```suggestion
- Removed constructors in clients that takes a `Azure::Identity::ClientSecretCredential`.
```

Azure CORE and all other languages uses `-` instead of `*` for the markdown bullets.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/1015#discussion_r529139124_

**Comment by vhvb1989** [comment]
It is fine if you want to change/update the current changelog.
However, it would be enough to just start using `-` from now on.
