### ISSUE TITLE
Move MD5 Hash API from Storage to Core

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1021]
•	MD5 hash function

The API should be re-usable from any SDK service

**Comment by Jinming-Hu** [comment]
Plus it's also mentioned in review meeting that the interface should be redesigned, like returning binary or base64 encoded string, `std::vector<uint8_t>` or `std::string`.

**Comment by katmsft** [comment]
What about CRC64?

**Comment by Jinming-Hu** [comment]
> What about CRC64?

I guess we have to admit CRC64 is a storage-specific thing.

**Comment by RickWinter** [comment]
@ahsonkhan please move this one when you do the Base64 move to core
