### ISSUE TITLE
CI failed in DataLake

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1029]
CI failed in DataLake [log](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/634286/logs/339), @katmsft can you take a look?

_Originally posted by @Jinming-Hu in https://github.com/Azure/azure-sdk-for-cpp/issues/1028#issuecomment-734213096_

**Comment by katmsft** [comment]
Should be a server end transient issue. Cannot see it in any other CIs.
