### ISSUE TITLE
Adapters for abstracting the Azure.Core buffers

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#103]
•	Storage Team would prefer the std::streambuf vs an Azure.Core buffer
•	Ask is that a customer can use ostream, this can be adapters over our types 
•	There could be overloads on functions to use the adapters

**Comment by RickWinter** [comment]
@JeffreyRichter does this need further working discussion to close on using the StreamBuf?

**Comment by JeffreyRichter** [comment]
I don't think so. An adapter can easily be created that takes an ostream or StreamBuf and converts it to a BodyStream. We could do it or the Storage team could do it. It could also be done later.
