### ISSUE TITLE
update test files to follow guidelines for including headers

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1043]
https://azure.github.io/azure-sdk/cpp_design.html#physical-design

>  YOU SHOULD include files using quotes (“) for files within the same git repository, and angle brackets (<>) for external dependencies.

I think this violates our guidelines

_Originally posted by @Jinming-Hu in https://github.com/Azure/azure-sdk-for-cpp/pull/1040#discussion_r533011753_

**Comment by RickWinter** [comment]
@vhvb1989 The tests are written to represent customer usage patterns (as much as possible).  Thus the tests should reference the public headers via '<>' in the same way customers would. 

We should make the guidelines more crisp around how to author tests.

**Comment by vhvb1989** [comment]
Closing this as not to be fixed.

Created a PR for the guidelines to mention reflect this in there.

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk/pull/2088
