### ISSUE TITLE
What is the default encryption level

### ISSUE THREAD

**Issue by leskodan** [Azure/azure-sdk-for-cpp#1051]
What is the default level of encryption available in this SDK when uploading information to blob?

I am investigating the efficacy of using this SDK to upload protected health information under HIPAA to Blob storage containers and need to understand the default encryption functionality in this SDK and to what extent (if any) I will need to implement additional encryption tools.

**Comment by Jinming-Hu** [comment]
Hi @leskodan , we support two kinds of server-side encryptions, [encryption scope](https://docs.microsoft.com/en-us/azure/storage/blobs/encryption-scope-overview) and [encryption with customer provided keys](https://docs.microsoft.com/en-us/azure/storage/blobs/encryption-customer-provided-keys).

But this SDK doesn't do client-side encryption (for now). That means if you use HTTP instead of HTTPS, your data will be in plaintext on the wire. if this is something you want to avoid, my suggestion is that you always use HTTPS or you do client-side encryption yourself and then upload the encrypted data as a blob.

**Comment by leskodan** [comment]
Thanks for the answers, that is very helpful context! Looking forward to working with this SDK.

**Comment by leskodan** [comment]
Forgive me for such a fundamental question, but if I am looking at [https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-blobs/sample/blob_getting_started.cpp](this sample), as long as the connection string that I am using for my blob container uses https protocol, my data will be encrypted on the wire?

**Comment by Jinming-Hu** [comment]
> as long as the connection string that I am using for my blob container uses https protocol, my data will be encrypted on the wire?

Yes!

**Comment by leskodan** [comment]
Thanks! Final question: If I am looking to use this sdk in a local, distributable application would it be bad practice to have the connection string compiled in the application code? Perhaps a better solution would be to have the local application communicate with an api that facilitates this connection? Appreciate the insights!

**Comment by Jinming-Hu** [comment]
@leskodan That depends. If the users of this application are trustworthy, then I think it's okay as long as it meets your requirements and solve your problems. I do want to remind you that hardcoded connection strings are easily extracted from the binary application. You should consider anybody that has access to this binary application has access to your storage account, which means they can read/write/delete everything in the storage account. Plus it makes it harder to revoke the connection string once it's compromised. (please refer to [this](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#manually-rotate-access-keys) link for rotating connection strings).

If you want more granular control over your data, please refer to https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview

**Comment by leskodan** [comment]
@Jinming-Hu Thank you very much for the extensive help!
