### ISSUE TITLE
Remove the #ifdef from the code and replace it for #if

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1057]
Current C++ guidelines advice to use #if and #if defined() instead of #ifdef
https://azure.github.io/azure-sdk/cpp_implementation.html#miscellaneous

Let's decide if we want to follow this guideline and update our code or if we need to update the guideline.

@RickWinter @JeffreyRichter  @ahsonkhan  @antkmsft

**Comment by Jinming-Hu** [comment]
I'd vote for `#if defined()` because we can use `||` and `&&` to implement complex logic.

**Comment by ahsonkhan** [comment]
The reasoning given in the guidelines against the use of `#ifdef` seems reasonable to me, so let's follow it in our code. @CaseyCarter, any concerns with it?
