### ISSUE TITLE
Fix GoogleTest warnings.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#106]
When I use Google test as the test framework, there are following warnings prompt when building the code. This will block building after Warning As Error being enabled.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C26812	The enum type 'testing::internal::Mutex::StaticConstructorSelector' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	az	E:\dev\src\cpp\azure-sdk-for-cpp\out\build\x64-Debug\_deps\googletest-src\googletest\include\gtest\internal\gtest-port.h	1379	
Warning	C26812	The enum type 'testing::TestPartResult::Type' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	az	E:\dev\src\cpp\azure-sdk-for-cpp\out\build\x64-Debug\_deps\googletest-src\googletest\include\gtest\gtest-test-part.h	63	
Warning	C26495	Variable 'testing::internal::Mutex::critical_section_' is uninitialized. Always initialize a member variable (type.6).	az	E:\dev\src\cpp\azure-sdk-for-cpp\out\build\x64-Debug\_deps\googletest-src\googletest\include\gtest\internal\gtest-port.h	1379	
Warning	C26495	Variable 'testing::internal::Mutex::critical_section_init_phase_' is uninitialized. Always initialize a member variable (type.6).	az	E:\dev\src\cpp\azure-sdk-for-cpp\out\build\x64-Debug\_deps\googletest-src\googletest\include\gtest\internal\gtest-port.h	1379	
Warning	C26495	Variable 'testing::internal::Mutex::owner_thread_id_' is uninitialized. Always initialize a member variable (type.6).	az	E:\dev\src\cpp\azure-sdk-for-cpp\out\build\x64-Debug\_deps\googletest-src\googletest\include\gtest\internal\gtest-port.h	1379	
Warning	C26495	Variable 'testing::internal::Mutex::type_' is uninitialized. Always initialize a member variable (type.6).	az	E:\dev\src\cpp\azure-sdk-for-cpp\out\build\x64-Debug\_deps\googletest-src\googletest\include\gtest\internal\gtest-port.h	1379

**Comment by kurtzeborn** [comment]
@vhvb1989 can you take a look at this?

**Comment by vhvb1989** [comment]
@katmsft
Can you provide more info about how are you building and getting those warnings?

We have already using `failed on warnings` option.
We are setting warning level to `/W4` (see https://github.com/Azure/azure-sdk-for-cpp/blob/master/cmake-modules/global_compile_options.cmake#L7)

So, I wonder about how are you getting those warning on your side.
I tried Linux and Windows and I don't see it.

**Comment by katmsft** [comment]
I don't think there is anything special for my setting:
```
{
    "configurations": [
        {
            "name": "x64-Debug",
            "generator": "Ninja",
            "configurationType": "Debug",
            "inheritEnvironments": [ "msvc_x64_x64" ],
            "buildRoot": "${projectDir}\\out\\build\\${name}",
            "installRoot": "${projectDir}\\out\\install\\${name}",
            "cmakeCommandArgs": "-DINSTALL_GTEST=OFF -DBUILD_TESTING=ON -DBUILD_CURL_TRANSPORT=ON",
            "buildCommandArgs": "-v",
            "ctestCommandArgs": "",
            "variables": [],
            "cmakeToolchain": "E:\\dev\\src\\cpp\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
        }
    ]
}
```

**Comment by quetzalcoatl** [comment]
I can't help much, I don't know what tool or compiler flags trigger those warnings, but they are easily visible in VS2019

![image](https://user-images.githubusercontent.com/1564880/85904398-e8034900-b808-11ea-924b-2de8a0f56e27.png)

as you can see, I selected 'Warnings" and "Build+Intellisense" options.
I also think it's related to "Analyze" menu and "Run Code Analysis on Solution" or "Run Code Analysis on File" features.

**Comment by RickWinter** [comment]
These warnings are from googletest code.

@antkmsft Take a look and see if there is an elegant solution to suppress these.
