### ISSUE TITLE
TransportAdapter.connectionPoolTest is failing on Linux x64 because expected ConnectionsOnPool is 2 instead of 3.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1060]
103 - azure-core.*/TransportAdapter.connectionPoolTest/* (Failed)

**Comment by ahsonkhan** [comment]
@vhvb1989 can we disable this test for now?

https://github.com/Azure/azure-sdk-for-cpp/blob/d61e106e89fa188a88e6fa5d6d91219136fb8439/sdk/core/azure-core/test/ut/transport_adapter_curl.cpp#L71

**Comment by vhvb1989** [comment]
Yes @ahsonkhan , disabling the test for now : https://github.com/Azure/azure-sdk-for-cpp/pull/1065

Then I will continue to enhance and fix this test
