### ISSUE TITLE
Disable language extensions

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1063]
In order for us to compile on more compilers, let's use compiler flags to disable compiler-specific language extensions.
We currently should be pretty compliant anyways, but, for instance, if we explicitly disable language extensions via compiler flag for MSVC, then, if you develop on a Windows machine and use a compiler extension unwittingly, there is a shorter loop for you to see the error, before it fails in CI on Mac or Linux.

**Comment by antkmsft** [comment]
Research /permissive, /std /Za/Ze etc. https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-160

**Comment by Jinming-Hu** [comment]
Hi @antkmsft , what kind of language extensions are we using in our project? I didn't quite catch you, can you give some examples?

**Comment by RickWinter** [comment]
The use of 'and' vs '&&' is one example of a language extension.  'and' keyword is a language extension.

**Comment by antkmsft** [comment]
I wonder if this would prevent us from using `__declspec(llimport/export)`, or there is a way
