### ISSUE TITLE
As an Azure service developer, I want to know how to consume the Json library from Azure Core and have documentation about it so I can use it.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1066]
Add documentation for service developers. 
This documentation does not need to be in contribute or readme since its not intended for end-customers.

For contributors and end-users we only need to mention that Azure Core needs the dependency to be available, Similar to libcurl

**Comment by katmsft** [comment]
https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#third-party-dependencies
Please also update this document.

**Comment by vhvb1989** [comment]
This issue is basically the same as https://github.com/Azure/azure-sdk-for-cpp/issues/137

We need to close and decide what's going to be the Azure Core strategy for Json support
