### ISSUE TITLE
We need to check the output of this function call.  If it fails we need to throw,  Failure is denoted by the return code of INVALID_HANDLE_VALUE

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1074]
We need to check the output of this function call.  If it fails we need to throw,  Failure is denoted by the return code of INVALID_HANDLE_VALUE

_Originally posted by @RickWinter in https://github.com/Azure/azure-sdk-for-cpp/pull/1070#r535383111_

**Comment by antkmsft** [comment]
Note that there is also a similar comment, need to check `int f = open(testDataPath.data(), O_RDONLY);` in transport_adapter_base.cpp for failure; and I assume Rick would want us to do the same for the Windows part too.

**Comment by vhvb1989** [comment]
Won't be fixed because the files are opened as part of the test cases and not as part of any API

**Comment by RickWinter** [comment]
Tests need to be written with proper validation.  If a test fails to open the file it should report that into the test output and fail.  Debugging of test failures is far easier when good logging exists.

**Comment by vhvb1989** [comment]
We control the input. We create the file that we read. And the test will fail anyway in that case when trying to use the Read().
If there is no issue on generation time for writing the file we will read later, the chances to Opening that file for reading are almost 0.  It would mean greater issues on the system, like if the file disappears or something like that. Then the entire system is not trusty.

Anyway, I can add it for you :P
