### ISSUE TITLE
Need to validate and check failure condition on open call

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1076]
This is not a goal of this PR, I am just moving things around, let's take care of this in a separate PR. @vhvb1989 will you look into this, should be a simple fix, or should I create a work item?

_Originally posted by @antkmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/1070#discussion_r535527294_

**Comment by vhvb1989** [comment]
duplicated from https://github.com/Azure/azure-sdk-for-cpp/issues/1074
