### ISSUE TITLE
Have only one FileBodyStream definition instead of one for Win and one for Lin.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1080]
Use the #if pre-procesor inside the method  implementation instead of doing a re-definition

**Comment by ahsonkhan** [comment]
@vhvb1989, you had marked this issue as blocked by https://github.com/Azure/azure-sdk-for-cpp/issues/1070. Is this unblocked now?

**Comment by ahsonkhan** [comment]
This isn't MQ related, assigning the milestone that fits the next release cycle, even if the goal is to get it done in December, since the SDK won't ship the v-next until January.
