### ISSUE TITLE
Add Getting Started sections to the README

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1084]
Add a walkthrough for acquiring the SDK and building an application.

Should include instructions for command line and Visual Studio.

**Comment by RickWinter** [comment]
@ahsonkhan Lets leverage the doc work we did for the studies and get them into the repo.  When we have a better home on msdocs we can move the conceptuals there.

**Comment by ahsonkhan** [comment]
> Lets leverage the doc work we did for the studies and get them into the repo. When we have a better home on msdocs we can move the conceptuals there.

For reference, this is the doc work that we can incorporate into master:
https://github.com/ahsonkhan/azure-sdk-for-cpp/tree/AddReadMeDetails#using-the-sdk-within-your-application

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/2394
