### ISSUE TITLE
Should BearerTokenAuthenticationPolicy be at Azure::Core::HTTP namespace instead of Azure::Core

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1088]
I wonder if all policies should be discoverable from http::  and from the same header policy.hpp

**Comment by JeffreyRichter** [comment]
Since it only works with the HTTP pipeline, I'd say that is should be in the HTTP namespace

**Comment by ahsonkhan** [comment]
@schaabs I am interested to hear what you think about this? What do other languages do around linking the `BearerTokenAuthenticationPolicy` to an "http"-related namespace/group?
