### ISSUE TITLE
As a contributor, when a unit tests fails because of gtest's `EXPECT_NO_THROW`, it should be easier to understand the potential causes by looking at the logs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1097]
When a test fails because of the use of `EXPECT_NO_THROW`, the error and logs show up as:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=645512&view=logs&j=85fce603-27e7-519e-7104-469f916f4b56&t=edb25b00-9fec-5e59-0001-6ccd95be0f23
```text
108: [ RUN      ] DataLakeFileSystemClientTest.DataLakeSasTest
108: D:\a\1\s\sdk\storage\azure-storage-files-datalake\test\datalake_sas_test.cpp(405): error: Expected: verify_file_read(sasToken) doesn't throw an exception.
108:   Actual: it throws.
108: [  FAILED  ] DataLakeFileSystemClientTest.DataLakeSasTest (10818 ms)

```

Unless the issue is reproducible easily (and locally), it is very hard to understand what the possible failure reasons could be. Tests need to be written with debugging and isolating failures in mind. Therefore, it is important that the type of exception and exception message itself also show up in the logs when a test fail. Bonus points if a callstack and sanitized request and response headers are also visible. We need to provide more info in the logs when tests fail.

The goal of this issue is to come up with code sample for better testing of `EXPECT_NO_THROW` and recommend that to be used across all of the SDK unit tests.

cc @vhvb1989, @RickWinter, @Jinming-Hu, @katmsft

**Comment by Jinming-Hu** [comment]
We split test cases `DataLakeFileSystemClientTest.DataLakeSasTest` (and other similar ones) into several small cases. This will help us figure out the reason if it fails again.

**Comment by ahsonkhan** [comment]
It's good that you were able to improve the specific unit test, but it would be great to get a solution that is more general purpose as a testing coding pattern.

> The goal of this issue is to come up with code sample for better testing of `EXPECT_NO_THROW` and recommend that to be used across all of the SDK unit tests.

Do you have any suggestions or recommendations on how to improve test logging whenever an `EXPECT_NO_THROW` fails (similar to how we recommend using `EXPECT_EQ(x, y)` in tests instead of `EXPECT_TRUE(x == y)`, since the failure logs are clear with values of x and y printed)?

**Comment by Jinming-Hu** [comment]
This can be easily done with some macros, like in this link https://stackoverflow.com/questions/42956538/can-i-know-which-exception-was-thrown-inside-a-gtest-expect-no-throw-or-assert.

It's been almost 3 years since this issue was opened, and I don't think it's an issue anymore (at least not for storage). Because we've enabled logging in Azure Pipeline, we can see all the HTTP requests & responses, we can easily figure out the problem with the log.
