### ISSUE TITLE
Figure out how to re-use the same session handle when using WinHTTP across all the requests within the entire application

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1098]
Currently, every request creates a new session.
This also requires figuring out the appropriate time to do the session handle cleanup.

See https://github.com/Azure/azure-sdk-for-cpp/pull/897#discussion_r517812289

**Comment by mikeharder** [comment]
## Overview
Currently, each HTTP request sent via WinHTTP creates a new TCP connection, which has two major impacts:

1.  Performance is significantly reduced, over 10x for small requests.  Creating a new TCP connection (and completing the HTTPS handshake) is very expensive compared to sending a request over an existing connection.

2.  After each request, the TCP connection is closed, and the client port is left in state TIME_WAIT for 2 minutes.  On Windows, there are 63475 available client ports by default.  So if an application makes 63475 requests in under 2 minutes, all future TCP connections will be blocked until the TIME_WAIT on each port expires, effectively blocking any network activity from the machine.

## Repro Steps
You can repro this using the Storage Blob performance tests, and use a tool like WireShark to monitor the TCP traffic.

1. Create a storage account
    A. Performance: Premium
    B. Premium account type: Block blobs
    C. Redundancy: Locally-redundant storage (LRS)
2. Compile azure-storage-blobs-perf.exe per instructions at https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/core/perf/README.md
3. Set env var `STORAGE_CONNECTION_STRING` pointing to your storage account
4. Run perf test to verify it's working.  The exact throughput doesn't matter, just verify the test passes with some reasonable throughput.

```
> azure-storage-blobs-perf.exe DownloadBlob --warmup 0 --duration 5 --size 1024

=== Results ===
Completed 115 operations in a weighted-average of 5s (22.834333 ops/s, 0.0437937 s/op)
```
5. Install a network monitoring tool like WireShark.
6. Open WireShark, select "Ethernet" interface to start capturing
7. Run perf test again
8. In WireShark, click "Capture -> Stop".
9. Find the IP address of your storage account, by running "nslookup your-storage-account.blob.core.windows.net".
10. In WireShark, add a filter with text `ip.addr==your.storage.ip.address`.
11. You will see that a new TCP connection is used for each HTTPS request
    A. The start and end of TCP sessions are shown with a dark gray background, and will contain `SYN` for the start and `FIN` for the end of a session.
    B. Rows containing `TLSv1.2 Client Hello` are the start of an HTTPS handshake.
