### ISSUE TITLE
Find a better way to wait until config comes into effect rather than just sleep

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1115]
https://github.com/Azure/azure-sdk-for-cpp/blob/414a5769f11c0d56f1469ca0299d451dd6657b24/sdk/storage/azure-storage-files-datalake/test/datalake_file_client_test.cpp#L574

**Comment by ahsonkhan** [comment]
The same issue applies for these other datalake tests that also use `SetAccessPolicy`:
https://github.com/Azure/azure-sdk-for-cpp/blob/8f0380710104c78dd652f3cebb84e41e81ec2f07/sdk/storage/azure-storage-files-datalake/test/datalake_directory_client_test.cpp#L375-L385

https://github.com/Azure/azure-sdk-for-cpp/blob/8f0380710104c78dd652f3cebb84e41e81ec2f07/sdk/storage/azure-storage-files-datalake/test/datalake_path_client_test.cpp#L328-L336

**Comment by Jinming-Hu** [comment]
close in favor of https://github.com/Azure/azure-sdk-for-cpp/issues/3592
