### ISSUE TITLE
Add UTF-8 and UTF-16 specific tests for hosts to verify correctness of transcoding in the transport layer and add code comments do document the behavior

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1120]
See https://github.com/Azure/azure-sdk-for-cpp/pull/897#discussion_r517808859

Verify that `WideCharToMultiByte` and `MultiByteToWideChar` are working as expected.

**Comment by RickWinter** [comment]
This would be a data corruption bug if its wrong.  We need to test cases to cover this scenario before GA
