### ISSUE TITLE
Add logging to the WinHTTP transport adapter similar to curl to provide progress info to the user.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1125]
For example:
https://github.com/Azure/azure-sdk-for-cpp/blob/8f0380710104c78dd652f3cebb84e41e81ec2f07/sdk/core/azure-core/src/http/curl/curl.cpp#L28-L38
https://github.com/Azure/azure-sdk-for-cpp/blob/8f0380710104c78dd652f3cebb84e41e81ec2f07/sdk/core/azure-core/src/http/curl/curl.cpp#L152-L155

**Comment by LarryOsterman** [comment]
This has effectively been done with the async winhttp changes - we get logs as the HTTP operation proceeds through the WinHTTP status machine. It doesn't encapsulate every possible operation but it provides significant amounts of additional data.
