### ISSUE TITLE
Add TimeSpan in Core SDK

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1132]
```c  
Azure::Storage::Blobs::BreakBlobContainerLeaseOptions.BreakPeriod
```
#
Option 1: Add duration type.
Option 2: Add `InSeconds` suffix.

**Comment by Jinming-Hu** [comment]
If core sdk doesn't want to add such a class, please assign this issue back to storage sdk. We'll go with Option 2.

**Comment by RickWinter** [comment]
Using std::chrono makes sense.  Are there problems with storage using that type?

**Comment by Jinming-Hu** [comment]
> Using std::chrono makes sense. Are there problems with storage using that type?

Fine with me.
