### ISSUE TITLE
`[Blob|Container][States|Traits]` flags enums

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1133]
```c  
Azure::Storage::Blobs::ListContainersSegmentOptions.Include
```
#
Where is this defined in the ApiView?  We found these kind of annoying to use in .NET and switched to `[Blob|Container][States|Traits]` flags enums.

**Comment by katmsft** [comment]
Add Flags suffix instead.

**Comment by Jinming-Hu** [comment]
blob service done in https://github.com/Azure/azure-sdk-for-cpp/pull/1466

**Comment by RickWinter** [comment]
Adding Flags to guidelines tracked in 
https://github.com/Azure/azure-sdk/issues/2315
