### ISSUE TITLE
Rename MatchConditions

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1138]
```C  
struct ETagAccessConditions
```
#
Consider moving into `::Core`.  Should this be called `MatchConditions`?

**Comment by Jinming-Hu** [comment]
should be moved to `Azure::Core` according to Ted's suggestion

**Comment by RickWinter** [comment]
Added new match conditions and request conditions to core.  Storage needs to switch to those types.
