### ISSUE TITLE
Consider if ModifiedTime/EtagAccess Conditions should be moved to core.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#1157]
```c  
Azure::Storage::ModifiedTimeConditions
Azure::Storage::ETagAccessConditions
```
#
Consider move this to Core.

**Comment by katmsft** [comment]
Storage team is OK with either decision. Please close or assign back to Storage team if pushing back.

**Comment by RickWinter** [comment]
MatchConditions and RequestConditions added to core

**Comment by RickWinter** [comment]
Storage needs to switch to the new types

**Comment by Jinming-Hu** [comment]
blocked by https://github.com/Azure/azure-sdk-for-cpp/issues/1608
