### ISSUE TITLE
List related max result should be renamed to PageSizeHint.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#1158]
```c  
Azure::Storage::Blobs::FindBlobsByTagsOptions.MaxResults
```
#
Is this PageSizeHint?  Can we make it look closer to the eventual Pageable APIs in C  ?

**Comment by Jinming-Hu** [comment]
blob service done in PR https://github.com/Azure/azure-sdk-for-cpp/pull/1242

**Comment by katmsft** [comment]
Done in https://github.com/Azure/azure-sdk-for-cpp/pull/1259
