### ISSUE TITLE
Pin down the name for destination when download to file.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#1159]
```c  
Azure::Storage::Blobs::BlobClient.DownloadTo:const_std::string_&:const_Azure::Storage::Blobs::DownloadBlobToOptions_&::Azure::Core::Response<DownloadBlobToResult>
```
#
Nit - `fileName` vs `filePath` or just `path`?

**Comment by katmsft** [comment]
@JeffreyRichter @tg-msft @RickWinter @ahsonkhan @vhvb1989 @antkmsft 
Any thoughts? Jinming and I don't have a strong preference here.

**Comment by RickWinter** [comment]
I prefer filePath b/c the value is the full path we are writing the blob to.  This aligns with C++17 filesystem class which is 'path', https://en.cppreference.com/w/cpp/filesystem/path

**Comment by ahsonkhan** [comment]
To clarify, this is the API we are talking about, correct?
https://github.com/Azure/azure-sdk-for-cpp/blob/1699bb72d5c656965f812468f0ed4e9651f515ac/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp#L243-L253

`filePath` seems reasonable to me as well.

**Comment by JeffreyRichter** [comment]
I would use whatever name C++ typically uses when opening a file. If fopen is typical, then 'filename'.
https://www.tutorialspoint.com/c_standard_library/c_function_fopen.htm
or http://www.cplusplus.com/reference/fstream/fstream/open/

**Comment by Jinming-Hu** [comment]
> To clarify, this is the API we are talking about, correct?
> https://github.com/Azure/azure-sdk-for-cpp/blob/1699bb72d5c656965f812468f0ed4e9651f515ac/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp#L243-L253
> 
> `filePath` seems reasonable to me as well.

Yes, that's the one we're referring to.

**Comment by JeffreyRichter** [comment]
So, filename (all lowercase)

**Comment by katmsft** [comment]
> So, filename (all lowercase)

I believe this only applies to the name of the file that `DownloadTo` is targetting, not the name of the file in file/datalake service right?

**Comment by Jinming-Hu** [comment]
> I believe this only applies to the name of the file that `DownloadTo` is targetting, not the name of the file in file/datalake service right?

I think @katmsft means we use `filename` for a local file, `fileName` for a datalake file. Well, I don't see any differences between a file on the local disk and a file on the cloud. I'd suggest we keep consistent, use `fileName` or `filename` everywhere in this sdk.

**Comment by Jinming-Hu** [comment]
Removing `blocking-release` tag since changing formal parameter name is not a breaking change.

**Comment by Jinming-Hu** [comment]
Close due to inactivity. Feel free to reopen if anybody has different opinions. I'll just keep things as is for now
