### ISSUE TITLE
How our customers are supposed to work with default HTTP transport

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1169]
Now we have two HTTP transport layers working on Windows, WinHTTP and libcurl, and the default one is WinHTTP.

I think the ideal way for beginners to use our storage sdk with default transport layer (which is important, because I don't want to introduce the concept of replaceable transport layer to beginners at the very beginning in case they feel our sdk is over complicated) would be 1. include blob header in their source file 2. specify the library path in Visual Studio project settings. No extra steps should be required.

Now for more advanced users who want to try the non-default libcurl transport, they have to specify one transport layer at build-time, because we don't support runtime switch yet. Now that the build is done, there is only one transport in the binary lib. I think the ideal way for them to use our library is still 1. include the header 2. specify library path.

Above is what I have in my head about how our library should be consumed by customers. I'm not sure if we're on the same page, so feel free to disagree. But I believe the two steps above won't be enough at the moment. Because we have another build time check here in header file. https://github.com/Azure/azure-sdk-for-cpp/blob/1699bb72d5c656965f812468f0ed4e9651f515ac/sdk/core/azure-core/inc/azure/core/http/policy.hpp#L124
If the user doesn't define anything (which is almost always the case for beginners), it will go to the custom transport path, which apparently won't compile.

I want to know if this is an implementation defect or by design behavior. Storage team does have concern if this is by design. The **default** does not look like default anymore. Because they have to explicitly specify a transport layer before including storage headers. Also it would be inconvenient for the customers who want to try and compare several different transport layers.

My proposal to improve user experience is to move the `ifdef`s to .cpp file. So the code path is fixed once the build is done. Customers don't need to do anything at runtime to specify a transport layer.

**Comment by vhvb1989** [comment]
>  it will go to the custom transport path, 

This is not true. The currently expected usage is just like you described. The end-user shouldn't even need to set the library path (we expect them to use vcpkg).  Once they install the SDK (like storage) they can then add the header and create the sdk client they want. 
The default transport adapter is defined with a CMake module `DefineTransportAdapter.cmake`. It makes sure to pick the default adapter depending on the OS and the end-user input.

Let me know if you have any questions about it.

@ahsonkhan  FYI.

**Comment by ahsonkhan** [comment]
@Jinming-Hu the desired end-user scenario you described is how I foresee customers getting started. There might be one extra step of installing dependencies, if they aren't using vcpkg but that is not the mainline beginner-friendly path. As @vhvb1989 described, that is how the SDK is behaving today (or at least the goal is that it should be) and if it isn't, please let us know.

> My proposal to improve user experience is to move the `ifdef`s to .cpp file. So the code path is fixed once the build is done. 

@vhvb1989, do you think there is still some value to move this to the source file to create a clearer separation between the API surface, and  the transport-layer specific underlying implementation. I think that's a reasonable suggestion even though the design and behavior already aligns with what @Jinming-Hu is suggesting.

**Comment by vhvb1989** [comment]
I see, yes, @ahsonkhan , we need it in the /src.
The problem of having it the way we do in headers is that even after installing the SDK , the header will still require the symbol everytime it is included.  This is a bug.

**Comment by Jinming-Hu** [comment]
The situation is, users have to define `BUILD_TRANSPORT_WINHTTP_ADAPTER` or `BUILD_TRANSPORT_CURL_ADAPTOR` before including storage header to be able to build their application. I think we all agree this isn't how our customers are supposed to do.

**Comment by vhvb1989** [comment]
Yes, it is a bug.
I think we can use the `GetCustomHttpTransport()` function (maybe rename it to GetHttpTransport).
Then, on out cpp, we do the #ifdef to define this function and return the transport adapter that we want or do not define the function at all when the end-user want to use custom (so the end user can implement this function on his/her code).

**Comment by Jinming-Hu** [comment]
@vhvb1989 Thanks for the acknowledgement. In this case, I'll unassign myself.
