### ISSUE TITLE
For Windows CI builds, calculate the number of jobs for parallelization as part of the build steps

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1187]
The yaml configuration needs to be updated to run something like
 `WMIC CPU Get NumberOfLogicalProcessors` 
with powershell and use the result to set the `--parallel NumberOfLogicalProcessors` option.

Use a default value of 8 in case getting the number fails for any reason. But, if we success to get the logical count, we need to use it.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/1183#discussion_r543720898_

**Comment by ahsonkhan** [comment]
@weshaggard, @mitchdenny - do you know if there is an optimal number for running the build step in parallel, or if there is an already established good way to ask the build machines for number of cores?

**Comment by mitchdenny** [comment]
Our build machines at the moment generally have 2 cores. But standard WMI commands should be able to return those values for you. I think it makes sense to use WMI commands to obtain this detail.
