### ISSUE TITLE
Update the testing approach in storage to follow core by not having a single exe containing all the tests for all the storage services.

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1200]
@Jinming-Hu, @katmsft - consider updating the testing approach in storage to follow core, if for nothing else but this change. The ability to modify tests and only need the tests to be built and not the SDK source code, and running them in VS test explorer within seconds alone is worth the effort!

_Originally posted by @ahsonkhan in https://github.com/Azure/azure-sdk-for-cpp/issues/1195#issuecomment-747173290_

**Comment by ahsonkhan** [comment]
Thanks for filing the issue @Jinming-Hu. I thought we already had an existing issue to track this, but can't find it in:
https://github.com/Azure/azure-sdk-for-cpp/issues?q=is%3Aissue+is%3Aopen+label%3AStorage+label%3A%22test+enhancement%22

**Comment by Jinming-Hu** [comment]
should have been fixed in #3194
