### ISSUE TITLE
Follow up on the WinHTTP transport layer performance

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1201]
I've sent out an email about the side-by-side comparison of WinHTTP transport, libcurl transport and Track 1 cpplite. Storage team would like to know if there's any plan of keeping optimizing the performance of WinHTTP transport layer.

**Comment by ahsonkhan** [comment]
Yes, the first step is to investigate various approaches to see where we can get some quick performance wins.
For example, one thing I want to try is re-use the same session handle across the application: https://github.com/Azure/azure-sdk-for-cpp/issues/1098

**Comment by RickWinter** [comment]
cc @ahsonkhan Add the three fixes that you plan to make.

**Comment by ahsonkhan** [comment]
1) Increase the default read buffer size from 64KB to 256KB+ (up to 1 MB).
2) Reuse the same session handle across multiple requests - https://github.com/Azure/azure-sdk-for-cpp/issues/1098
3) Call WHRD with large buffers rather than WHQDA.
4) Investigate the perf benefits of using TCP Fast Open.

**Comment by ahsonkhan** [comment]
The bulk of this issue has been fixed, at least at the GA quality bar. 

Investments in performance can always continue. Until some of the exploratory improvements (and open PRs) are closed, keeping the issue open, but moving to the next milestone.
