### ISSUE TITLE
Prevent clang-format from reordering two header files

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1209]
In that case, please add a comment and leave a new line between the two include statements. Otherwise, every time someone opens in VS and re-formats it, the header order will change and break the build.

_Originally posted by @ahsonkhan in https://github.com/Azure/azure-sdk-for-cpp/pull/1199#discussion_r545334824_

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/1208

**Comment by ahsonkhan** [comment]
Thanks @vhvb1989
