### ISSUE TITLE
Suggestions for improving azure-core CMake files

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1235]
I've been testing storage sdk on different platforms (Windows, Linux, macOS) and build as both dynamic and static libraries. I found some build errors and I've fixed some of them or opened GitHub issues (#1230, #1233, #1234). I also found some imperfect usages of CMake commands in core sdk CMake files, which can be improved. So I'd like to give some suggestions here so that you guys can consider.

1. core-sdk doesn't depend on nlohmann_json library. This will cause extra, useless library to be installed when customers just want to use `azure-storage-blobs` package via `vcpkg`. Because only DataLake service and File service depends on json. So I suggest we move json related stuff to storage sdk CMake files.

2. libcurl linkage should be `PUBLIC`. However it's defined `PRIVATE` now.

https://github.com/Azure/azure-sdk-for-cpp/blob/606dd98ea246cfd5631225463d94ac94b1e4c2e4/sdk/core/azure-core/CMakeLists.txt#L126

as Rick has suggested in this issue https://github.com/Azure/azure-sdk-for-cpp/issues/70, customers are supposed to include `curl/curl.h` and call curl init functions. That's also what you guys are doing in test code (https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/core/azure-core/test/ut/main.cpp).

3. Unnecessary `target_include_directories` call. https://github.com/Azure/azure-sdk-for-cpp/blob/606dd98ea246cfd5631225463d94ac94b1e4c2e4/sdk/core/azure-core/CMakeLists.txt#L121

`target_link_libraries` will automatically populate the include directories for us. So these `target_include_directories` calls are redundant in most cases. [Here](https://cmake.org/pipermail/cmake/2016-May/063400.html) is a very good post elaborating how `target_link_libraries` works.

4. Nit. https://github.com/Azure/azure-sdk-for-cpp/blob/606dd98ea246cfd5631225463d94ac94b1e4c2e4/sdk/core/azure-core/CMakeLists.txt#L130

Maybe it's better if we just write `target_link_libraries(azure-core PRIVATE winhttp)`? I don't see the benefits of defining a variable that's only used once.

**Comment by ahsonkhan** [comment]
> 1. core-sdk doesn't depend on nlohmann_json library. This will cause extra, useless library to be installed when customers just want to use `azure-storage-blobs` package via `vcpkg`. Because only DataLake service and File service depends on json. So I suggest we move json related stuff to storage sdk CMake files.

Maybe, but I suspect most folks won't be installing or using core-sdk on its own. And today, only Datalake and fileservice use it, but in the future, other service SDKs would want to leverage a JSON library as well. Theoretically, we could defer the move down to core to that point, but it is helpful to establish where key components come from. JSON serialization and processing is a fundamental part of most Azure SDKs and all other languages either expose that through Azure Core or rely on the language/underlying framework to provide such a library. Azure core will likely continue to grow with components or features that are more commonly used across multiple services (at least two), which means it might pull in dependencies that not all services use. The goal is to minimize external dependences though.

> 4. Nit. https://github.com/Azure/azure-sdk-for-cpp/blob/606dd98ea246cfd5631225463d94ac94b1e4c2e4/sdk/core/azure-core/CMakeLists.txt#L130

> Maybe it's better if we just write `target_link_libraries(azure-core PRIVATE winhttp)`? I don't see the benefits of defining a variable that's only used once.

That nit makes sense. Agreed.

**Comment by Jinming-Hu** [comment]
> > 1. core-sdk doesn't depend on nlohmann_json library. This will cause extra, useless library to be installed when customers just want to use `azure-storage-blobs` package via `vcpkg`. Because only DataLake service and File service depends on json. So I suggest we move json related stuff to storage sdk CMake files.
> 
> Maybe, but I suspect most folks won't be installing or using core-sdk on its own. And today, only Datalake and fileservice use it, but in the future, other service SDKs would want to leverage a JSON library as well. Theoretically, we could defer the move down to core to that point, but it is helpful to establish where key components come from. JSON serialization and processing is a fundamental part of most Azure SDKs and all other languages either expose that through Azure Core or rely on the language/underlying framework to provide such a library. Azure core will likely continue to grow with components or features that are more commonly used across multiple services (at least two), which means it might pull in dependencies that not all services use. The goal is to minimize external dependences though.

Sure

**Comment by Jinming-Hu** [comment]
> > 1. Nit. https://github.com/Azure/azure-sdk-for-cpp/blob/606dd98ea246cfd5631225463d94ac94b1e4c2e4/sdk/core/azure-core/CMakeLists.txt#L130
> 
> > Maybe it's better if we just write `target_link_libraries(azure-core PRIVATE winhttp)`? I don't see the benefits of defining a variable that's only used once.
> 
> That nit makes sense. Agreed

https://github.com/Azure/azure-sdk-for-cpp/pull/1240

**Comment by sjoubert** [comment]
I agree with these changes, especially the visibility of the curl dependency. As it currently is, the generated target file for azure-core is not relocatable since the curl include directories found during build are used to populate the target. Using only the CMake targets (as PUBLIC) would prevent that issue as well.

**Comment by ahsonkhan** [comment]
> As it currently is, the generated target file for azure-core is not relocatable since the curl include directories found during build are used to populate the target.

@sjoubert - in what scenario would you want  to relocate the generated target file for azure-core?

> Using only the CMake targets (as PUBLIC) would prevent that issue as well.

Does that apply to both flavors of building the SDK and the consuming library - static and dynamic?

**Comment by Jinming-Hu** [comment]
> in what scenario would you want to relocate the generated target file for azure-core?

C runtime will do run-time relocation when running a executable linked against dynamic library. I guess this is what this customer is referring to

> Does that apply to both flavors of building the SDK and the consuming library - static and dynamic?

I guess dynamic only.

**Comment by ahsonkhan** [comment]
> The library is built once ,somewhere in a temporary install path with its dependencies resolved in non standard paths as well. Then I distribute the built and packaged library elsewhere.

Since curl, in some sense (http stack is replaceable), is an optional dependency, and since the end customer has to include the curl header and call curl global init and cleanup in their application code directly, wouldn't it be better for the consuming application to explicitly link curl themselves rather than relying on an indirect linking via azure core as their dependency?

The scenario you brought up is interesting and I hadn't thought about this separation previously. I will have to understand the relocation aspect a bit better myself to realize the implication. Do you have some resources or clear steps I can look up to try it myself locally and observe the issue by fleshing out the "build in a non standard path" and "distribute elsewhere" steps? 

> (relocatable in the sense they don't depend on the location they were produced or on the location they are placed)

Right, that is important. Is it the consuming application being built once which is linking the SDK, or just the SDK? It would be helpful to me to understand the relationship between the consuming application and SDK/other library dependency, while building the different components.
