### ISSUE TITLE
Should we use `Cancelled` or `Canceled` ?

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1255]
We are currently using both, like:

OperationCanceledException

and

OperationStatus::Cancelled

**Comment by vhvb1989** [comment]
@RickWinter  Can you confirm what we should use?

@ahsonkhan  @antkmsft  FYI

**Comment by ahsonkhan** [comment]
> Americans favor canceled (one L), while cancelled (two Ls) is preferred in British English and other dialects

There is no hard and fast rule (since it ends up depending on the form of the word), but this is what I have seen done most often:
- cancel
- canceled
- cancellation

**Comment by vhvb1989** [comment]
From @JeffreyRichter 

The guidelines indicate that Cancelled comes over the wire and we have an extensible enum for it; at least these should be spelled with `Cancelled`.
