### ISSUE TITLE
Add spell check to CI

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#1260]

**Comment by ahsonkhan** [comment]
What type of spell check were you thinking? Which of these aspects were you hoping to catch spelling errors for?
- C++ Code (like variable names)?
- Inline Comments?
- or just CI and other scripts?

**Comment by ahsonkhan** [comment]
The other concern that I have seen come up with this is getting a lot of false positives, where correctly spelled words in the context of code, are flagged as misspelled. How are we planning to address that? Will we have an allow list or will we leverage a tool that is targeted specifically for C++ programs and is conservative and on what it considers incorrect spelling to reduce changes of false positives?

**Comment by RickWinter** [comment]
@danieljurek Can you update the milestone and estimate.  Is there any work outside of the central-engsys necessary to complete this item?

**Comment by ahsonkhan** [comment]
@danieljurek moving this to May. Let me know what you are planning for this.
