### ISSUE TITLE
BlobContainerClientTest.AccessConditionLastModifiedTime failing nightly LiveTest runs because SetAccessPolicy is throwing

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1263]
This is failing across all the nightly runs (for all OSes).

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=673975&view=logs&j=b28a1a35-334b-5681-3876-e5562b5e8062&t=63769913-9c82-5a57-b1c4-2fe29b9a87d3&l=361

```text
126: [ RUN ] BlobContainerClientTest.AccessConditionLastModifiedTime 
126: /home/vsts/work/1/s/sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp:673: Failure 
126: Expected: containerClient.SetAccessPolicy(options) doesn't throw an exception. 
126: Actual: it throws. 
126: /home/vsts/work/1/s/sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp:673: Failure 
126: Expected: containerClient.SetAccessPolicy(options) doesn't throw an exception. 
126: Actual: it throws. 
126: [ FAILED ] BlobContainerClientTest.AccessConditionLastModifiedTime (1692 ms) 
```

https://github.com/Azure/azure-sdk-for-cpp/blob/bce390946b7acff186b1ab20181ae0d6e2807df3/sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp#L671-L674

cc @katmsft, @Jinming-Hu

**Comment by Jinming-Hu** [comment]
This is a bug introduced during auto-generator refactoring.
