### ISSUE TITLE
Change std::runtime_error to std::exception for the base exception for the KeyVault exception

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1266]
https://github.com/Azure/azure-sdk-for-cpp/pull/1147#discussion_r542988548

I think I can handle that as part of a next PR after adding the first API
I will create issue for it

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/1147#r552330897_

**Comment by RickWinter** [comment]
@vhvb1989 Please update the title and description with descriptions of the work to be done
