### ISSUE TITLE
Update cgmanifest.json since we don't include source code of nlohmann json anymore

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1269]
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-blobs/cgmanifest.json#L17

**Comment by Jinming-Hu** [comment]
Is this file auto-generated? How should we edit this file? Can I just remove that item of nlohmann json? Will it break something?

**Comment by ahsonkhan** [comment]
The cg manifest is meant to declare third party dependencies, and not just for code that is directly included in the SDK.

The file is not auto-generated. If the JSON dependency is coming from core now, we would want to move this to core's cgmanifest.

**Comment by RickWinter** [comment]
@ahsonkhan please move/update the declaration of the dependency to make it accurate for the where the dependency is coming from.

**Comment by Jinming-Hu** [comment]
We also need to update the `NOTICE.txt` files, right? Because it still contains license notice for json library.


https://github.com/Azure/azure-sdk-for-cpp/blob/fb33402844be8aaeedcbcec645b8be9c69fa6242/sdk/storage/azure-storage-blobs/NOTICE.txt#L68
