### ISSUE TITLE
Consider renaming DataLakePathClient::GetFileClient to AsFileClient

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1278]

**Comment by katmsft** [comment]
There isn't such API.

**Comment by Jinming-Hu** [comment]
@katmsft FYI, this is a suggestion from Ted during arch board review. You cannot just disregard it like this.

**Comment by katmsft** [comment]
There isn't an API called `DataLakePathClient::GetFileClient`, so why the renaming?
Are you suggesting adding `AsFileClient`?

**Comment by Jinming-Hu** [comment]
okay
