### ISSUE TITLE
The Other versions drop down duplicates the current version within the index page causing the current version to show up twice

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1302]
The latest version already shows up when you land on the page. It doesn't need to show up again when you click on and expand the "Other versions"

https://azure.github.io/azure-sdk-for-cpp/core.html
![image](https://user-images.githubusercontent.com/6527137/104111315-5a171900-5295-11eb-9de5-b018fd45e898.png)

This occurs on the other pages do, including Identity and Storage. And also for other languages, like Embedded C and .NET:
https://azure.github.io/azure-sdk-for-c/core.html
![image](https://user-images.githubusercontent.com/6527137/104111331-82067c80-5295-11eb-8a09-708e7900e535.png)

Similar issue in .NET:
https://azure.github.io/azure-sdk-for-net/core.html
![image](https://user-images.githubusercontent.com/6527137/104111354-b7ab6580-5295-11eb-87b8-7f0bf4ae9210.png)

cc @weshaggard, @sima-zhu - this doesn't seem intentional. Can we fix it across the board?

**Comment by weshaggard** [comment]
@sima-zhu is it easy to filter out the versions or perhaps we instead of saying other versions we just say "All versions"

**Comment by RickWinter** [comment]
@sima-zhu This is fix is needed for the March release.

**Comment by sima-zhu** [comment]
Will change `other version` to `All versions`

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-tools/pull/1396

**Comment by danieljurek** [comment]
@sima-zhu -- I think this change has merged. Can we close this? 

![image](https://user-images.githubusercontent.com/2158838/110375710-2f341180-8007-11eb-9ae7-06dc415fb492.png)

**Comment by sima-zhu** [comment]
Right, it got resolved. Closed the issue and feel free to reopen if any other issues left
