### ISSUE TITLE
Remove NamespaceEnabled 

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1308]
Actually, I'm going to remove this, since blob is not supporting this return value.

_Originally posted by @katmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/1282#discussion_r554681231_

**Comment by katmsft** [comment]
Already removed.

**Comment by Jinming-Hu** [comment]
> Already removed.

In which PR? I didn't remember I reviewed such a PR

**Comment by katmsft** [comment]
https://github.com/Azure/azure-sdk-for-cpp/pull/1282.

**Comment by Jinming-Hu** [comment]
Is this change reflected in the PR title or description or Changelog? Because it looks like a breaking change.
