### ISSUE TITLE
DataLake CreateIfNotExists/DeleteIfExists should call Blob ones internally

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1314]
It does not have `Deleted` in the response.

_Originally posted by @katmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/1282#discussion_r554670754_

**Comment by Jinming-Hu** [comment]
added in https://github.com/Azure/azure-sdk-for-cpp/pull/1313

**Comment by katmsft** [comment]
Why this is blocking-release?
