### ISSUE TITLE
Create Internal API layer for `SDK Services only` functionally in Azure::Core

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1319]
Currently API to migrate to Azure::Core::Internal
- strings
-

**Comment by ahsonkhan** [comment]
Moving to February since it isn't critical for this release. Here's the PR for it: https://github.com/Azure/azure-sdk-for-cpp/pull/1337

cc @RickWinter, in case you disagree

**Comment by RickWinter** [comment]
Lets get this one in early in case there are breaking changes discovered.
