### ISSUE TITLE
Evaluate the current implementation of Base64, design for errors, and consider removing dependency on openssl and OS-specific APIs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1338]
We have APIs to convert to and from binary data and base64 encoded text:

Encoding accepts any amount of bytes and constructs a string, and therefore most inputs are valid
Decoding, however, can only succeed if a valid base64 encoded string is provided (with the correct character set, number of padding, and length).
The purpose of this issue is to:

Re-implement the APIs in standard C++ and avoid any native dependencies that have more complex error handling and lifetime management.
Ensure to validate and throw for invalid input while decoding.
Out-of-scope:

Some folks may provide partial text data to the Base64 decode APIs, to support streaming. These APIs wouldn't support that today, and only work for single calls where all the data is provided up front.
Another scenario is providing a buffer with a lot of data, including some after the bytes/strings needed to be encoded/decoded, and let the API consume as much as possible and return the partial result. This scenario isn't supported either.

See some of the feedback from https://github.com/Azure/azure-sdk-for-cpp/pull/1297#pullrequestreview-564685471
cc @vhvb1989

**Comment by RickWinter** [comment]
@ahsonkhan Add additional details to this issue for specific work to be done,

**Comment by RickWinter** [comment]
This is about underlying implementation

**Comment by ahsonkhan** [comment]
We have APIs to convert to and from binary data and base64 encoded text:
- Encoding accepts any amount of bytes and constructs a string, and therefore most inputs are valid
- Decoding, however, can only succeed if a valid base64 encoded string is provided (with the correct character set, number of padding, and length).

**The purpose of this issue is to:**
1) Re-implement the APIs in standard C++ and avoid any native dependencies that have more complex error handling and lifetime management.
2) Ensure to validate and throw for invalid input while decoding.

**Out-of-scope:**
- Some folks may provide partial text data to the Base64 decode APIs, to support streaming. These APIs wouldn't support that today, and only work for single calls where all the data is provided up front.
- Another scenario is providing a buffer with a lot of data, including some after the bytes/strings needed to be encoded/decoded, and let the API consume as much as possible and return the partial result. This scenario isn't supported either.

**Comment by RickWinter** [comment]
This type needs more extensive testing of inputs.  Also we should make this into a header only implementation.  I don't see a need on this one for a .cpp file.
With an extensive test suite we should be able to modify the underlying implementation post GA.

**Comment by vhvb1989** [comment]
@RickWinter @ahsonkhan  I don't think this issue should be blocking-release, neither for April.

Also, I don't think we should re-implement the wheel instead of using the libraries. We are already using openSSL with libcurl and Windows.h for winhttp.  We will not remove the dependencies anyway.

**Comment by antkmsft** [comment]
I wrote an implementaition for C SDK at one time. I can port it over, with tests, in 2 days from starting work to checked in.

**Comment by vhvb1989** [comment]
@ahsonkhan , I am closing this as we already ported Anton's C99 implementation and even improved with Larry :)

Feel free to re-open if you consider it
