### ISSUE TITLE
Clean up the package show up in Github IO "Other" page

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-cpp#1358]
Clean up the package show up in [Other page](https://azure.github.io/azure-sdk-for-cpp/other.html).

Either have the right service name or make hide=true in csv release page. [Link](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/cpp-packages.csv)
Change service name:
![image](https://user-images.githubusercontent.com/48036328/104527115-d1f88280-55b8-11eb-9615-a41a459eee18.png)

Hide the package:
![image](https://user-images.githubusercontent.com/48036328/104527237-197f0e80-55b9-11eb-960b-9abf960a2123.png)

**Comment by kurtzeborn** [comment]
All I see on the "other" page is azure-template.  This should just be hidden.  It's a template for teams onboarding to our engineering system and we'll basically never want to publish docs on it.  So just make the change to hide this one.

**Comment by sima-zhu** [comment]
The issue has been resolved. Removed the template from Github IO. Closed the issue.
