### ISSUE TITLE
The PR title or description for the vcpkg auto generated PR should increment and list all port updates, not just the first one.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1365]
See https://github.com/microsoft/vcpkg/pull/15635 for example which has the PR title matching the first commit and doesn't mention anything in the PR title or description about the subsequent commits:
`Update port for azure-core-cpp`, even though that PR later introduces azure-identity as well.

Ideally the PR title would be of a form like:
`Update port for <release 1>`
then changed to:
`Update port for <release 1>, <release 2>`
etc.

If updating the PR title is not easy, then enumerating the list of ports in the PR description is good enough.
![image](https://user-images.githubusercontent.com/6527137/104532999-5a315480-55c6-11eb-9cb0-9a0e23a2a6ad.png)

cc @danieljurek, @weshaggard

**Comment by weshaggard** [comment]
It should be fairly use to use the set the some sort of release identifier when queuing the build and use that for both the shared branch name and the name of the port.

**Comment by danieljurek** [comment]
We support overriding the PR title today at queue time. I've opened https://github.com/Azure/azure-sdk-tools/issues/1474 to track the possibility of updating the PR title.
