### ISSUE TITLE
Enable an arm64 windows CI leg to make sure the SDK continues to build for the supported platform

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1368]
See the supported platform matrix:
https://azure.github.io/azure-sdk/cpp_introduction.html#supported-platforms

We have found one linker issue on arm64-windows already, see https://github.com/Azure/azure-sdk-for-cpp/issues/1367.
This will help us uncover any other issues that need to be fixed and also stay green going forward.

cc @danieljurek, @vhvb1989

**Comment by ahsonkhan** [comment]
@antkmsft, can you please manually open a draft PR in vcpkg to confirm our repo is green based on today's commit?

**Comment by antkmsft** [comment]
Adding Daniel because #2025 closes this issue.
