### ISSUE TITLE
Adding support for JSON parser.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#137]
**Is your feature request related to a problem? Please describe.**
Currently, there is a lack of functionality to parse the JSON raw string into a JSON object to retrieve its elements.

**Describe the solution you'd like**
First party implmentation/3rd party dependency.

We need to decide what azure core's stance is on the JSON library. Some questions that are important to answer:

	
-  Is it OK for us to take a dependency on a 3rd party library, or do we need our own (storage team seems to be expecting us providing one)?

nlohmaan Json:
-  Why did we pick that particular one? Are we happy with its performance?
-  Is it pluggable/replaceable by the customer?
-  Do we expose or intend to expose any of the 3rd party library APIs in our public surface area?
-  How do we plan to add features and what happens if there are breaking or other changes in the dependency?
-  What's our plan for keeping things in sync?
-  How do AWS/GCP solve this concern?

**Comment by katmsft** [comment]
Storage team is going to use https://github.com/nlohmann/json as a temporary solution and migrate to Azure::Core's implementation when it's ready.

**Comment by JeffreyRichter** [comment]
GCP uses nlohmann: https://github.com/googleapis/google-cloud-cpp/search?q=json

AWS uses cJSON: https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/external/cjson/cJSON.h.
There is a not here that cJSON is NOT thread safe: https://github.com/DaveGamble/cJSON#thread-safety.
 
You know, we could use our own C JSON library to create/parse. This way, we'd own all the code/security/perf issues and it is thread safe (which matters a lot for us). We would NOT expose it to customers (at least initially) so span and other structures would be internal to us.

**Comment by RickWinter** [comment]
I don't see any reason to expose JSON to the user.  We have model types and strings.  Customers that want to parse the raw json can use any json parser they want.
Internally within the SDK the clients should use the same json library.  We need to provide internal json support for client libraries.  I suggest using nholmanjson as it seems to meet our needs for size, perf, thread safety.

**Comment by ahsonkhan** [comment]
> You know, we could use our own C JSON library to create/parse. This way, we'd own all the code/security/perf issues and it is thread safe (which matters a lot for us). We would NOT expose it to customers (at least initially) so span and other structures would be internal to us.

@RickWinter any reason not to investigate using our own from C, instead of nlohmann (possibly post-GA)?

**Comment by vhvb1989** [comment]
> any reason not to investigate using our own from C

I would say:
- It's not as easy to use as nlohman. Does not offer the cool operators to parse json fields as:
```cpp
// To create:
json j;
  j["pi"] = 3.141;

// to parse
auto jsonParser = Azure::Core::Internal::Json::json::parse(bodyBuffer);
    auto& error = jsonParser["error"];
    errorCode = error["code"].get<std::string>();
    message = error["message"].get<std::string>();
```

We would need to create an extra adapter layer to the C json lib to implement those operators using the C lib.  That seems like not a very trivial work to do.

**Comment by ahsonkhan** [comment]
Since this is not part of the public surface area (i.e. not meant to be used by the end user), and in most cases it will be protocol layer code that is auto-generated rather than human generated, ease of use via convenience method isn't as critical compared to the other factors (and one we can always add to, in the future).
