### ISSUE TITLE
Move internal header to a cpp file. Since hpp should not be including internal header

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1376]
let's create an issue here about moving this to a cpp file. Since this hpp should not be including internal header

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/1337#r557620118_

**Comment by Jinming-Hu** [comment]
Technically not doable, explained in https://github.com/Azure/azure-sdk-for-cpp/pull/1337/files/bf3a09802e4b80c035a7c190132711c496ea06fd#r557808637
