### ISSUE TITLE
Http::Response should be a template class. E.g. Response<DownloadBlobInfo>

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#138]
**Describe the bug**
Http::Response is currently just a plain class. Previous agreement (and to align with other SDKs) is that this should be Response<T>, where T is the serialized object that customer is likely to use on their end.

**Comment by katmsft** [comment]
This is going to be a huge breaking change for the customer.

**Comment by vhvb1989** [comment]
I remember we were going to have 2 types of response.
First one is this raw response that is returned by the HTTP Pipeline which doesn't know anything about the T.  It only contains the stream body and HTTP Response details.

Then, we would have another Response<T> which consumes the previous one and knows the type of <T>.
It can then read the stremBody to build <T>.
We can have this template on Core and then the logic to create them on services.

@RickWinter  @JeffreyRichter
