### ISSUE TITLE
Consume from VCPKG

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1388]
Add Sample which shows building an app with azure-sdk-for-cpp vcpkg dependency

Ideally sample is "template" starting point for users

**Comment by danieljurek** [comment]
It might make sense to add the ability to consume this from a "nightly" drop to a vcpkg fork so we can test against releases from master on any given day

**Comment by ahsonkhan** [comment]
@vhvb1989 if you plan on working on this, feel free to use the samples from here as a starting point: https://github.com/ahsonkhan/azure-sdk-ux-study-answers
