### ISSUE TITLE
General Samples

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1390]
## General Integration Samples

An integration sample is one small project (typically CMake project) which demonstrates how to integrate/consume the Azure SDK for C++ to one application/library.

### Motivation

One of the Azure SDK for C++ end-customer adoption problems could eventually be `having issues` while trying to consume the client SDKs using a popular method like VCPKG or CMake-fetch-content.  As an effort to anticipate the possible consuming issues, we need to have demos or real-life scenarios of how end-users would integrate the SDK.
While building and running each application, we would find out if there is any problem that needs to be fixed before releasing new versions.

The projects would also become a valid example to guide new customers on how to acquire and build the SDK.

### Focus area

In contrast to the unit, live and smock testing, these samples are not mainly focus about exploring any particular client SDK feature/API. Instead, it is intended to validate real-life building scenarios. Such scenarios might be, for example:
- Using multiple sdk clients (storage, keyvault, etc) and with different versions in one application.
- Creating a new library `A` that consumes one SDK package, another library `B` that consumes the same package, but different version and then one application that consumes A and B libraries.
- One application that consumes one SDK package (like storage blobs) with VCPKG and nother package (like storage datalake) with CMake fetch content.
- etc, etc.

In the scenarios mentioned before, it doesn't really matter how the source code uses the client SDK (create, call APIs). What matters is actually just making sure that the scenario is achievable and can be built.

### Strategy

Each sample project would live inside the main mono repo inside the root folder `samples`, next to the `sdk` folder.

#### Stage 1

Projects are manually tested after the code freeze is called.

List of samples for stage 1.0:
- using CMake-fetchcontent to consume one SDK package
- using VCPKG to consume one SDK package

List of samples for stage 1.2:
- More than one sdk client in one app
- 3rd party lib consuming SDK. static and shared compilation tests
- TBD
- TBD
- ...

#### Stage 2

Projects are automatically run from a nightly pipeline.  The EngSys team needs to design some strategy for it.

### Sample project properties

Each sample could define its own steps for:
- Consuming: 
Getting the Azure SDK from some source
- Building:
platform / arch / etc
- Running:

**Comment by danieljurek** [comment]
@vhvb1989 and I chatted about this problem. 

This is cross-cutting, like smoke testing because it requires multiple packages to be compiled together into the same project across services. It's also like min-max testing in the sense that we're picking up various versions of packages and testing them compiling together in the same project. 

At this point, compiling the various versions together is more important than running the code. 

We also want to test various delivery methods of the code (like vcpkg, CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html), etc.) that may not fall under the name "package"

**Comment by ahsonkhan** [comment]
So, how do you suggest we make sure we stay green in the mean time, between now and GA (and beyond)? Is there a short-term stop gap that may not be a complete solution but possible given the timeline?

**Comment by danieljurek** [comment]
General samples for today: 

* Consume FetchContent
* Consume vcpkg
* App that consumes a library that consumes the SDK

Proposed project layout: 

```
common/smoke-test/
  package-consumption/     < -- Consume vcpkg and FetchContent set in CMake 
  3rd-party-lib/                    <-- 3rd party library that consumes the SDK 
  3rd-party-client/               <-- Client application that consumes 3rd party library
  smoke-test/                      <-- App that consumes samples from package-level samples in the repo
```

We'll think more about min/max testing once we have something in place. 

@vhvb1989 - Create sample applications, get started on `smoke-test.yml`, work w/ Daniel if you need help.

@danieljurek - Review `smoke-test.yml` and set up pipelines.
