### ISSUE TITLE
Improve the Storage Windows live tests to also test libcurl http transport adapter

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1407]
After adding the winHttp transport adapter as default for Windows, we are missing test coverage for using libcurl adapter for Storage tests on Windows.

Please update the cpp - storage pipeline to have 2 more legs with Windows+libcurl adapter

**Comment by katmsft** [comment]
+1 Vote to prioritize this. It is important for CI to catch regressions and I think manual efforts need to be made to run Storage's test with curl backend before this is ready.
