### ISSUE TITLE
We should be consistent and call these APIs `GetUrl` not `GetUri`, similar to:

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1409]
We should be consistent and call these APIs `GetUrl` not `GetUri`, similar to:
https://github.com/Azure/azure-sdk-for-cpp/blob/e0e04cfee04988dad0a2bcbbbd1e40fc04da436a/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp#L122

For example, change this (and everywhere else `Uri` shows up):
https://github.com/Azure/azure-sdk-for-cpp/blob/e49ceabf85b2250c08241c27a52bbfaddbef1b85/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_service_client.hpp#L67

_Originally posted by @ahsonkhan in https://github.com/Azure/azure-sdk-for-cpp/pull/1394#discussion_r560410370_

**Comment by katmsft** [comment]
How about `StartCopyFromUri` or `AppendFromUri`? Should they be consistent as well?
Imagine customer code:
```
destBlobClient.StartCopyFromUri(sourceBlobClient.GetUrl());
```
Isn't it strange?

**Comment by katmsft** [comment]
BTW, change done in https://github.com/Azure/azure-sdk-for-cpp/pull/1414.

**Comment by Jinming-Hu** [comment]
> How about `StartCopyFromUri` or `AppendFromUri`? Should they be consistent as well?
> Imagine customer code:
> 
> ```
> destBlobClient.StartCopyFromUri(sourceBlobClient.GetUrl());
> ```
> 
> Isn't it strange?

Copy operation is different, as you can see in the [API reference](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob#request-headers), the source doesn't have to be a link, it can also be something like `/accountName/containerName/blobName?snapshot=<DateTime>`, in which case it's not a **link**, it's an **identifier**. So this API name should be **Uri** rather than **Url**.

But function `GetUrl` always returns a link.

Hope this answers your questions.
