### ISSUE TITLE
Unify the code that is for Win32 and UWP

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1433]
Research the possibility to use the very same API that we use on UWP and on the good old Win32. 
These places currently are:
* Get OS version
* Open file
(search the code base for `PARTITION`, if there are any possible places in the future)

**Comment by antkmsft** [comment]
Suggestions so far (not tried):
* https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlgetversion
* https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexw

**Comment by RickWinter** [comment]
@antkmsft Is the code structured in a way that this can be changed post GA?  If so move this to backlog otherwise we need to fix in April
