### ISSUE TITLE
Update CI step - validate clang-format - to run from Windows as well

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1439]
Current step is valid only for macOS because it installs the clang-format-11 using `brew install`

We can use this script from any other OS or it would fail

We need to split the validation in two steps, first one to install clang-format-11 and then a second one to run it.
The install step needs to depend on the OS for the installation strategy to use.

**Comment by Jinming-Hu** [comment]
Why do we need to validate clang-format on two platforms? Are we gonna get different results on macOS and Windows?

**Comment by vhvb1989** [comment]
> Why do we need to validate clang-format on two platforms? Are we gonna get different results on macOS and Windows?

I got confused on how it was working on macOS. But the issue was something different that what I initially thought. This is not required. Closing it
