### ISSUE TITLE
Add missing field from `GetBlobPropertiesResult`

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#1473]
AcceptRanges/CopyStatusDescription/IsIncrementalCopy
Blocking https://github.com/Azure/azure-sdk-for-cpp/issues/1472

**Comment by Jinming-Hu** [comment]
```c++
Azure::Storage::Blobs::Models::GetBlobPropertiesResult
```
#
.NET also has AcceptRanges, CopyStatusDescription, DestinationSnapshot, IsIncrementalCopy, IsLatestVersion, RehydratePriority, and VersionId

originally posted by @tg-msft

**Comment by Jinming-Hu** [comment]
I can add these missing fields except for `AcceptRanges`? Why would our customers want to check that value?

**Comment by katmsft** [comment]
It's a standard HTTP request header that Storage supports: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges

**Comment by Jinming-Hu** [comment]
> It's a standard HTTP request header that Storage supports: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges

Yeah, same for `Transfer-Encoding`, `Date`, `x-ms-version` and `Server`
