### ISSUE TITLE
Review Http policies and their options, if anything needs to go to Internal namespace - move it

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1480]
This came up during the ValuePolicy (#1458) review meeting. Let's review, if anything public in `azure/core/http/policy.hpp` needs to move to `Details` namespace. If so, then move it.

**Comment by antkmsft** [comment]
This will probably take 15 minutes, let's get on a call to review, and we need Jeffrey.

**Comment by ahsonkhan** [comment]
Not `Details` as that is for "private" but rather `Internal` so client libraries can still take a dependency on it.

**Comment by antkmsft** [comment]
@ahsonkhan, you are right, and Value Policy should be there as well - https://github.com/Azure/azure-sdk-for-cpp/pull/1494.

**Comment by antkmsft** [comment]
Everything public looks good to me, nothing relevant to this came up during the Core design review as well. The only thing that could be hidden is ValuePolicy, which is alredy where it should be (in Internal)
