### ISSUE TITLE
Replace unused() with (void) for unused variables

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1483]

**Comment by Jinming-Hu** [comment]
This requires changes to auto-generator. I don't think we have to do it before GA.

**Comment by katmsft** [comment]
What's the rationale for this change?

**Comment by Jinming-Hu** [comment]
@ahsonkhan @vhvb1989

**Comment by Jinming-Hu** [comment]
need to remove all `unused()` in new auto-generator
