### ISSUE TITLE
SegFault on Windows + Libcurl when application finishes and there are available handles in the connection pool

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1499]
For the next simple program:
```cpp
int main(int argc, char** argv)
{
  curl_global_init(CURL_GLOBAL_ALL);
  
  // Code that uses Azure SDK

  curl_global_cleanup();
  return 0;
}
```

The Azure SDK will create libcurl connections and after using them, the connections are moved to the connection pool.
Those connections will be cleaned/destroyed by the Connection Manager if they are not used in some time.

However, if the application finishes and reach to a point where `curl_global_cleanup()` is called, all the libcurl resources are clean. 
Then, when the connections from the pool are destroyed, they will try to clean/destroy the handler again producing a segmentation fault.

See this PR: https://github.com/Azure/azure-sdk-for-cpp/pull/1500 for the example of the failure on Windows.

**Comment by vhvb1989** [comment]
@RickWinter @JeffreyRichter @ahsonkhan 

I am planning to fix this issue by using a try/catch for when the Connection Manager clean up the connections from the pool.  That way, if the   `curl_global_cleanup()` was called before, we might catch the exception and ignore.

Let me know what you think

**Comment by RickWinter** [comment]
Catching a segfault exception isn't the right pattern.  I would expect when we release the libcurl connection it would notify libcurl that its been free'd.  How are we releasing the libcurl handle is a way that results in it being released twice?

**Comment by ahsonkhan** [comment]
I agree with Rick here. We need a better lifetime mechanism to clean up the connections (maybe even something that is resilient to whenever `curl_global_cleanup()` is called).

I am curious, do we have to periodically cleanup the connection pool at all?

**Comment by JeffreyRichter** [comment]
We could add a method to the TransportAdapter to cleanup and then customer code can call this method before calling curl_global_cleanup(). This enables this to work for ALL Transport Adapters for any HTTP stack. The customer can also call our function that returns the default Transport Adapter can call this method.

**Comment by vhvb1989** [comment]
> I would expect when we release the libcurl connection it would notify libcurl that its been free'd

I would expect the same :) .
The problem is that I create a libcurl handle,
then open a connection and start an http transfer.

Now, before closing that connection and/or cleaning its resources, the end-user might call `global_cleanup` which will close my connection and clean all related to libcurl. However, I still have my handle which is basically a ptr to an address.  There's no way for me to know that the global_cleanup was called and the address is no longer valid.

Another approach is to wrap the global_cleanup with some azure_global_cleanup() , but this is not a general solution because end-user can still call global-cleanup.

> I am curious, do we have to periodically cleanup the connection pool at all?
Yes, it starts as soon as a connection is created and it ends if all connection from pool are removed

**Comment by vhvb1989** [comment]
> We could add a method to the TransportAdapter to cleanup....

This is basically a `AzureSdkCleanUp()` right?  We would say that if you don't call it, you might get errors?

**Comment by JeffreyRichter** [comment]
No, not really because an AzureSdk clean up is 1 per process and what I'm proposing is 1 per transport adapter which we may not know about





Jeffrey Richter (watch Architecting Distributed Cloud Apps)

________________________________

**Comment by vhvb1989** [comment]
Talked to @JeffreyRichter  and agreed to create and expose a static function from the CurlTransport as `Azure::Core::Http::CurlTransport::CleanUp()` which would take care of manually cleaning the pool.

End user is expected to call this function before the global clean up.

Adding documentation about it in the PR

**Comment by RickWinter** [comment]
@JeffreyRichter @vhvb1989 If we are going to force folks to call "Shutdown" then lets make it a generic `Azure::Shutdown()` method.  We will need that method if we decide to support memory allocation hooks.

**Comment by vhvb1989** [comment]
> @JeffreyRichter @vhvb1989 If we are going to force folks to call "Shutdown" then lets make it a generic `Azure::Shutdown()` method. We will need that method if we decide to support memory allocation hooks.

`Azure::Shutdown()`  wouldn't have any sense when not using libcurl.  It might be just a placeholder of nothing until we add the memory allocation, and if that never happen, once that we add the method, we can't remove it. Hence, I am happier with having the Clean function as part of the CurlTransportAdapter only
