### ISSUE TITLE
Some functions should not have default Options like SetAccessPolicy

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1509]
https://github.com/Azure/azure-sdk-for-cpp/blob/836a8a591a87ee8664475011a6bb88ed9a98e93d/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp#L243

**Comment by Jinming-Hu** [comment]
Hi @JeffreyRichter 

I want to remove the default options from functions like 

```C++
SetAccessPolicy(const SetBlobContainerAccessPolicyOptions& options = SetBlobContainerAccessPolicyOptions())
```

so it will be changed to

```C++
SetAccessPolicy(const SetBlobContainerAccessPolicyOptions& options)
```

because for this kind of functions, customer has to specify one or more fields in `options` to make this operation meaningful. Or it will just clear the properties (access policies etc.) from server side, which is not the behavior the function name suggests.

What do you think?

**Comment by JeffreyRichter** [comment]
Yes, I agree.

**Comment by katmsft** [comment]
> Yes, I agree.

Source: [Set Container ACL](https://docs.microsoft.com/en-us/rest/api/storageservices/set-container-acl)
> x-ms-blob-public-access : If this header is not included in the request, container data is private to the account owner.

I'm afraid I cannot agree with this approach. For this exact API, set acl with default option means resetting to the service's default behavior. It is also the case for many other APIs with only the default option in the parameter list.

For some APIs, the default behavior means nothing is changed for an API call. However, it is not impossible for those APIs to be having a default behavior just like the Set Container ACL API in the future. Making the option for these API `required` now will cause it a breaking change to change it back to its current state. 

Also, this does not prevent customers from writing code like below. I don't see an improvement here.
```
myContainer.SetAccessPolicy(SetBlobContainerAccessPolicyOptions());
```

At last, I think it would be a more unified experience for the customer to know that `options` are always not mandatory in this SDK.

@JeffreyRichter, please consider my input and I don't have further push back if you insist on this design. In that case, please also confirm that this design applies to all `PUT`/`POST` APIs with only one parameter being the `options` parameter.

**Comment by katmsft** [comment]
BTW, The example of an API change to have a default behavior even if no useful headers are set after an API version upgrade:
https://docs.microsoft.com/en-us/rest/api/storageservices/set-share-properties

x-ms-root-squash: <NoRootSquash \| RootSquash \| AllSquash> | Optional. Supported in version 2020-02-10 and above. Specifies the root squashing behavior on the share when NFS is enabled. **If not specified, the default is NoRootSquash.**

**Comment by Jinming-Hu** [comment]
> For this exact API, set acl with default option means resetting to the service's default behavior.

Well, I don't think it's a good idea to allow our users to reset properties with some function like `client.SetAccessPolicy()`. Why is a reasonable person expected to know that to **set** properties without any input would just **reset** everything? At lease to me this is not intuitive, so I don't think it's good API design.

But things would be different if we force our users to do so

```C++
SetAccessPolicyOptions options;
client.SetAccessPolicy(options);
```

because the user explicitly initializes an `options` and then passes it into the API we provide. So it's safe for us to assume what's in the `options` struct is the user's real intention. If he just leaves all those fields in `options` to be default value, he should expect those default values to be set to server side, which is exactly the effect of **reset**.

**Comment by Jinming-Hu** [comment]
> BTW, The example of an API changed to have a default behavior even if no useful headers are set after an API version upgrade:
> https://docs.microsoft.com/en-us/rest/api/storageservices/set-share-properties
> 
> x-ms-root-squash: <NoRootSquash | RootSquash | AllSquash> | Optional. Supported in version 2020-02-10 and above. Specifies the root squashing behavior on the share when NFS is enabled. **If not specified, the default is NoRootSquash.**

I do believe this should be a mandatory parameter rather than optional. So it's not relevant to this topic.

**Comment by katmsft** [comment]
> Well, I don't think it's a good idea to allow our users to reset properties with some function like client.SetAccessPolicy(). Why is a reasonable person expected to know that to set properties without any input would just reset everything?

[.NET's SetAccessPolicy](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L2103)
.NET is making `client.SetAccessPolicy()` a valid call to the customer, so it is at least agreed by the devs of .NET SDK and the arch board to be a reasonable enough design.

**Comment by Jinming-Hu** [comment]
> > Well, I don't think it's a good idea to allow our users to reset properties with some function like client.SetAccessPolicy(). Why is a reasonable person expected to know that to set properties without any input would just reset everything?
> 
> [.NET's SetAccessPolicy](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L2103)
> .NET is making `client.SetAccessPolicy()` a valid call to the customer, so it is at least agreed by the devs of .NET SDK and the arch board to be a reasonable enough design.

Things are very different for .Net from C++, because .Net doesn't support options bag. Who's to say they don't want to forbid `client.SetAccessPolicy()`? Maybe they also want, but they can't. I think this is an advantage of options bag design in C++.

**Comment by Jinming-Hu** [comment]
> At last, I think it would be a more unified experience for the customer to know that `options` are always not mandatory in this SDK.

I'm not sure I can agree with this. From users' perspective, the unified experience is that they have to provide things that is necessary to make a function call clear and actionable, and can leave out things without which the function call is still meaningful. So in upload function

```C++
blobClient.upload(stream);
```

the stream is what's gonna be uploaded, without which this function is just meaningless, so they have to provide it in parameter list. Other options like metadata, properties and tier stuff are not necessary, so they can omit these. Another example is create function, by

```C++
appendBlobClient.Create()
```

users have clearly conveyed a message that they want to create an append blob. This action is operable without any other information. So all other information should be optional and go into options bag.

But function

```C++
client.SetAccessPolicy()
```

I don't think this message is clear enough for us to know the user wants to reset properties on server side.

**Comment by katmsft** [comment]
> > > Well, I don't think it's a good idea to allow our users to reset properties with some function like client.SetAccessPolicy(). Why is a reasonable person expected to know that to set properties without any input would just reset everything?
> > 
> > 
> > [.NET's SetAccessPolicy](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L2103)
> > .NET is making `client.SetAccessPolicy()` a valid call to the customer, so it is at least agreed by the devs of .NET SDK and the arch board to be a reasonable enough design.
> 
> Things are very different for .Net from C++, because .Net doesn't support options bag. Who's to say they don't want to forbid `client.SetAccessPolicy()`? Maybe they also want, but they can't. I think this is an advantage of options bag design in C++.

I don't believe what you claim here is true. below is the approach they can achieve what you proposed without an option bag. But they clearly did not choose to do this.
```
/// overload 1, sets access type.
        public virtual Response<BlobContainerInfo> SetAccessPolicy(
            PublicAccessType accessType,
            BlobRequestConditions conditions = default,
            CancellationToken cancellationToken = default) 
/// overload 2, sets permission.
        public virtual Response<BlobContainerInfo> SetAccessPolicy(
            IEnumerable<BlobSignedIdentifier> permissions,
            PublicAccessType accessType = PublicAccessType.None,
            BlobRequestConditions conditions = default,
            CancellationToken cancellationToken = default) 
```
> Who's to say they don't want to forbid `client.SetAccessPolicy()`? Maybe they also want, but they can't. I think this is an advantage of options bag design in C++.

Please confirm that it is their actual thought before you make this assumption based on your personal opinion.

> When you say unified experience, I tend to think it's actually make our, storage sdk developers' experience unified, rather than our customers. Because apparently sticking to an established practice can cut down our research and maintenence effort. But this sdk is written for our customers to use. Our experience means nothing to them, their experience means everything to us. So I think we should really consider from their perspective when making decisions of API design.

This again assumes my thought on my behalf and this assumption is far from correct. The unified experience I was referring to is all about not requesting our customer to learn each API's uniqueness or developer's personal preference when using this SDK.
In your own example you mentioned, the `appendBlobClient.Create()` API. This API also resets the existing state of the destination blob according to what the server defines it to do, just as what `SetAccessPolicy`'s behavior is. Why would we assume that one behavior is very obvious and the other is implicit?

**Comment by Jinming-Hu** [comment]
whatever man, you win, I quit. Not that i'm convinced by you. I'm tired of fighting with you
