### ISSUE TITLE
Add a bug fix changelog entry for retry policy with the casing fix for retry-after

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1526]
@antkmsft we would also need changelog entry for this

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/issues/1522#issuecomment-769974212_

**Comment by antkmsft** [comment]
#1535 fixed the changelog, #1570 is to track unit test update.
