### ISSUE TITLE
[Perf Fw] Add statistics

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1555]

**Comment by vhvb1989** [comment]
this feature is not yet fully implemented/supported in other languages and requires some standard to be created across languages. At some point, sync with @mikeharder  and @g2vinay about this feature across languages

**Comment by gearama** [comment]
Per Mike's instructions 
[11:47 AM] Mike Harder
Not really, I think you can just close this.
 like 1
