### ISSUE TITLE
[Perf Fw] Add noCleanup

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1556]

**Comment by gearama** [comment]
@vhvb1989  what was this about  ?

**Comment by vhvb1989** [comment]
Adding an input argument to skip running the cleanup functions at the end of the test.
It's been low priority.
The only use case might be if you want to run some debugging after running the perf test and you don't want to clean whatever the test might be created.

**Comment by vhvb1989** [comment]
You can ask @mikeharder if this input argument is still part of NET or other languages Perf framework.  If not, you can close this issue.
If the other languages still support this input argument, then it needs to be added.

**Comment by gearama** [comment]
The nocleanup flag is in the framework , it is used similar to the .Net framework .
