### ISSUE TITLE
Internal (source only) json.hpp shouldn't be visible in docs since it isn't public

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1576]
`doctest` and others are coming from json.hpp and the source-copy tests. We should skip publishing doc strings from that since it is an internal implementation detail: https://github.com/Azure/azure-sdk-for-cpp/blob/9b7849c155ffd89acf9cd00152b74446287d61ef/sdk/core/azure-core/inc/azure/core/internal/json.hpp#L30

https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-core/1.0.0-beta.5/annotated.html
![image](https://user-images.githubusercontent.com/6527137/106694914-5f167200-658e-11eb-9b02-77fbb916a51b.png)

**Comment by vhvb1989** [comment]
closed by #1621
