### ISSUE TITLE
Apply suggestions for VcPkg files

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1583]
From here: https://github.com/microsoft/vcpkg/pull/15984
* Look into possibly thinner depends-on dependencies (azure-core[core], curl[core], etc)
* Implicit self-dependencies on default set of features don't need to be there
* Convert to vcpkg.json
* (=> #1664) Remove comment headers from portfile.cmake and CONTROL/vcpkg.json file (per blocking feedback from https://github.com/microsoft/vcpkg/pull/16013). Ideally, files in our repo would live with copyright headers, but `az_vcpkg_export()` vcpkg macro would strip them when copying to output directory. Cheaper/simpler fix is to remove them from these two files in our repo.

**Comment by RickWinter** [comment]
@antkmsft Update the description with what must be done and seperate out the nice to haves into another backlog issue.  Add an estimate to this item (and if applicable the other issues you create).
