### ISSUE TITLE
Update CI release scripts for VcPkg

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1584]
From here: microsoft/vcpkg#15984
1. Do commit, then run `vcpkg x-add-version --overwrite-version azure-<xxx>-cpp`, then amend commit. We would need vcpkg for that, so we would need to `./bootstrap-vcpkg`, which builds it, if it is not installed on build machine. And if it is installed, we would need to also set `VCPKG_ROOT` to local directory containing the port update, and not the installed location, because `vcpkg x-add-version` seem to depend on the repo set by `VCPKG_ROOT`, and not the repo you run if from.

2. The name of the PR we create needs to be something like "`[azure-<xxx>-cpp] $version release`", or "`[azure-<xxx>-cpp] Publish version $version`" (so that wording works for both initial releases and subsequent updates?), see the commit history in their repo - https://github.com/microsoft/vcpkg/commits/master, everybody start commits with `[portname]` (in https://github.com/microsoft/vcpkg/pull/16013, PR title was updated by reviewers)

3. See how we ended up pushing two PRs at the same time. when the second depends on the first to be checked in, https://github.com/microsoft/vcpkg/pull/16013, then https://github.com/microsoft/vcpkg/pull/16014 and https://github.com/microsoft/vcpkg/pull/16020. Is there anything that can be done to make this go smoother? If that's not technical, and there are human readable instructions for release process somewhere, let's update them to mention this fact.

**Comment by ahsonkhan** [comment]
cc @danieljurek, @RickWinter

**Comment by danieljurek** [comment]
Item 2 is also addressed in https://github.com/Azure/azure-sdk-for-cpp/issues/1365

**Comment by antkmsft** [comment]
I also think it would be great if the commit message line 2+ was the release changelog, so it would become a commit description in VcPkg commit history, and also we can paste the changelog to PR description. IMO, very useful for the customers.
This is probably too big of a request to sneak into this issue, please let me know if you'd like me to open a new issue for this.

**Comment by danieljurek** [comment]
This should go in another issue

**Comment by danieljurek** [comment]
Closing. This shipped in February.
