### ISSUE TITLE
Standardize Azure::Core with ToString()

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1590]
Some Azure::Core classes use GetString, others use ToString.  

Standardize on ToString()

**Comment by Jinming-Hu** [comment]
What's the motivation of this change? Does it also apply to storage? We also get some string conversion methods with different names like https://github.com/Azure/azure-sdk-for-cpp/blob/5f523f7030459bc8ca77b0ac96ff3f2c7b593d03/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_attributes.hpp#L18 https://github.com/Azure/azure-sdk-for-cpp/blob/5f523f7030459bc8ca77b0ac96ff3f2c7b593d03/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L147

**Comment by vhvb1989** [comment]
Since the changes for Core are done, I am assigning this to @Jinming-Hu

**Comment by Jinming-Hu** [comment]
I take it to mean this also applies to storage, and I ought to make the same changes to storage.
