### ISSUE TITLE
Fix download links from azure.microsoft.com

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1597]
Need to update the docs links to point to our documentation and steps for getting the SDK
https://azure.microsoft.com/en-us/downloads/

**Comment by vhvb1989** [comment]
@RickWinter  please provide more info about where is the repo to be updated or who to contact for working on this issue.
I can try to fix it for May.
Otherwise, move this issue to backlog

**Comment by kyle-patterson** [comment]
@RickWinter the C++ link points to this github repo now, do you want to include any other links?

**Comment by RickWinter** [comment]
Please add the "Get the SDK" and "Documentation" links to the page as well

- Get the SDK -> https://aka.ms/azsdk/cpp
- Documentation -> https://aka.ms/azsdk/cpp/docs
