### ISSUE TITLE
Add section to documentation for getting started

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1598]
The current getting started links back to the internal readme.  That readme has nothing on how to acquire/use/samples.  I'd expect a page similar to .NET/Java/JS/Python/GO explaining how to use Azure from C++.
example:
https://docs.microsoft.com/en-us/dotnet/azure/

**Comment by ahsonkhan** [comment]
We want to make this landing page better, more discoverable, and up-to-date for this SDK:
https://azure.microsoft.com/en-us/develop/cpp/

**Comment by kyle-patterson** [comment]
There's also https://docs.microsoft.com/azure/developer/ which needs a C++ section
