### ISSUE TITLE
Implement Continuous Access Evaluation

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1601]
Add a Claims field of type String to support Continuous Access feature.

**Comment by antkmsft** [comment]
@RickWinter, I talked to Scott,

There is no need for CAE if:
* There is no user authentication (any credential which authenticates a user account. Most notably InteractiveBrowserCredential, DeviceCodeCredential, AuthorizationCodeCredential, and UsernamePassword credential).
* If there aren't management plane libraries.
