### ISSUE TITLE
Add edge case tests for improper use of Md5 Update and Digest APIs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1619]
It is important to have the following behavior well-defined and documented, along with unit tests which enforce them:
- What happens if the user calls `Digest()` before any data is provided and no previous calls to `Update()`? Error or assume data is empty string?
- What happens if the user calls `Digest()` twice on the same Md5 instance? Error or return empty vector?
- What happens if the user calls `Update()` or `Digest()` after the Md5 instance has been freed? Throw?
- Does one instance of Md5 interfere with another? They shouldn't share state at all, is the use of static OK here?
https://github.com/Azure/azure-sdk-for-cpp/blob/06f7028bad9ad15446e004c369111320746c1336/sdk/storage/azure-storage-common/src/crypt.cpp#L261

cc @JeffreyRichter

**Comment by Jinming-Hu** [comment]
> What happens if the user calls Digest() before any data is provided and no previous calls to Update()? Error or assume data is empty string?

MD5 of empty data is totally valid. This is defined behavior.

> What happens if the user calls Digest() twice on the same Md5 instance? Error or return empty vector?

`Digest()` is a const function. We just return the hash of the data that has been fed to that instance. Is there any problem here?

> What happens if the user calls Update() or Digest() after the Md5 instance has been freed?

It also works. But it's up to you whether or not to make it defined behavior.

> Does one instance of Md5 interfere with another? They shouldn't share state at all, is the use of static OK here?

Yeah, I wrote the code and I believe it will work. DO NOT make it a global static variable. That is problematic.,

**Comment by Jinming-Hu** [comment]
@ahsonkhan I suggest you take a look at MD5 interfaces of other libraries, or libraries of other languages. Most languages have built-in MD5.

**Comment by ahsonkhan** [comment]
@Jinming-Hu I asked all these questions to get clarity on such behavior because what you are suggesting doesn't match what actually happens.

> MD5 of empty data is totally valid. This is defined behavior.

```C++
  Md5 md5Instance;

  // throw error: C++ exception with description "BCryptHashData failed" thrown in the test body.
  md5Instance.Digest();
```

> `Digest()` is a const function. We just return the hash of the data that has been fed to that instance. Is there any problem here?

Yes, currently, repeated calls fail, which means we need to fix the implementation:
```C++
  EXPECT_EQ(md5Instance.Digest(), Md5::Hash(data));
  //   unknown file: error: C++ exception with description "BCryptFinishHash failed" thrown in the test body.
  EXPECT_EQ(md5Instance.Digest(), Md5::Hash(data));
```

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu I asked all these questions to get clarity on such behavior because what you are suggesting doesn't match what actually happens.
> 
> > MD5 of empty data is totally valid. This is defined behavior.
> 
> ```c++
>   Md5 md5Instance;
> 
>   // throw error: C++ exception with description "BCryptHashData failed" thrown in the test body.
>   md5Instance.Digest();
> ```
> 
> > `Digest()` is a const function. We just return the hash of the data that has been fed to that instance. Is there any problem here?
> 
> Yes, currently, repeated calls fail, which means we need to fix the implementation:
> 
> ```c++
>   EXPECT_EQ(md5Instance.Digest(), Md5::Hash(data));
>   //   unknown file: error: C++ exception with description "BCryptFinishHash failed" thrown in the test body.
>   EXPECT_EQ(md5Instance.Digest(), Md5::Hash(data));
> ```

If this is the case, I would say it's a bug we should fix 😂
