### ISSUE TITLE
Logging: review once again

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1639]
* Default log level, what it should be -  `Verbose`, or Warning, or something else?
* Do we like free functions inside the `Azure::Core::Logging::` namespace, or should we make a class?
* `std::function`, or something else for callback?
* Add `string componentId`? (other proposal was string serviceId) Or don't? Or not a string, but some enum?
* LogLevels order - ascending or descending? - https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=dotnet-plat-ext-5.0
* Do we want more log levels? Any problems if we add more in the future?

Victor had cool proposal for the LoggingOptions, so logging callback+logLevel would behave something like HttpTransport - you don't have to specify it, or use different transport, but if you want, it is overridable.

* Go and instrument more code with logging? One person does it, or everyone does their part? Storage does not currently have logging at all. Let's also come up with pattern, which log levels we use. Create a separate work item for that?

* Use atomic instead of mutex? I'm pretty sure no one would disagree, but what if would require us to not use `std::function` in the user-facing API? (#1638)

(Just in case: https://github.com/Azure/azure-sdk-for-cpp/pull/1568)

**Comment by ahsonkhan** [comment]
> * `std::function`, or something else for callback?

@CaseyCarter, I would love to hear your perspective on this. One of our goals with logging within the SDK is simplicity. We have quite a straightforward API set and model, which relies on the customer defining this callback method and registering it.
Is using `std::function` the best (and simplest or the customer) for such a callback?

https://github.com/Azure/azure-sdk-for-cpp/blob/2d4d766c6d454bfbd2a3627c5a3d8a4d81196480/sdk/core/azure-core/inc/azure/core/logging/logging.hpp#L41-L57
