### ISSUE TITLE
Create Azure::Core::(<?>::)CaseInsensitiveMap?

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1640]
Inspired by https://github.com/Azure/azure-sdk-for-cpp/pull/1536 and PR comments/proposals

* Should it be `<string, T>`, or `<string, string>`?
* We do lowercase on set, not only compare case insensitively. Right?
* Do we lowercase values?
* Which namespaceshould it be in?
* Bring up a "Follow up on Review Comments - Case-insensitive Metadata Lookup" email thread from December 2020.

**Comment by Jinming-Hu** [comment]
> Should it be <string, T>, or <string, string>?

storage team only requires <string, string>

> We do lowercase on set, not only compare case insensitively. Right?

I'd suggest case-preserving.

> Do we lowercase values?

No, metadata value in storage service is case-sensitive

**Comment by antkmsft** [comment]
@Jinming-Hu Thanks for the feedback! The only consideration for case-altering to lowercase would be that Request and Response DO `ToLower()` anyway, when a value is set, I am not sure if it will be useful/not confusing to preserve the case in the map itself. But we will discuss it anyway, it is not I am 100% sure. Fully agree with everything else. If you think of the reasons why it should be preserving the case, please comment.
What should the value be here:

```
CaseInsensitiveMap map;

// Question 1:
map["Retry-After"] = "5";
map["retry-after"] = "10";
map.find("RETRY-AFTER")->first // "Retry-After", or "retry-after"?

// Question 2
map["Content-Type"] = "text/html";
map["content-type"] = "text/html";
map.find("CONTENT-TYPE")->first // "Content-Type", or "content-type"?
```
My opinion is that it should be "retry-after" and "content-type".

**Comment by Jinming-Hu** [comment]
> The only consideration for case-altering to lowercase would be that Request and Response DO ToLower() anyway

In blob service, we send out metadata in the following format

```
x-ms-meta-key1: value1
x-ms-meta-key2: value2
```

so `key1` and `key2` here will be converted to lowercase anyway. But this is not the case for DataLake service, where we send out metadata in the following format

```
x-ms-properties: key1=Base64Encoded(value1), key2=Base64Encoded(value2)
```

so `key1` and `key2` here are case-preserved.

**Comment by Jinming-Hu** [comment]
> My opinion that the least confusing are "retry-after", "content-type, "transfer-encoding", and "content-length".

I agree, but I don't think it's a big problem. Doing what you proposed takes much more efforts, which I don't think is worth it. But I'm okay with it if you want to.

**Comment by antkmsft** [comment]
@Jinming-Hu, thank you, all the useful info, we should bring up that email as well during the discussion.

If we were to preserve casing, and you use it in DataLake today, and you add value multiple times, would you expect the casing of the first insertion, and not from updates, or vice versa (Q1 above)? What if the value ends up being exactly the same, and, as a result, no update happens (Q2 above)?
// There are some more expensive implementation outcomes, some less expensive, depending on the answers, but I'd rather don't consider costs too much for now, and focus on the behavior that we ultimately end up needing anyway. Not to dismiss perf considerations entirely, just better knowing of the all cases is useful for design, in my opinion, - when we go from requirements to implementation.

**Comment by Jinming-Hu** [comment]
> If we were to preserve casing, and you use it in DataLake today, and you add value multiple times, would you expect the casing of the first insertion, and not from updates, or vice versa (Q1 above)? What if the value ends up being exactly the same, and, as a result, no update happens (Q2 above)?

I'd say it's best to be the last update. But I don't expect anybody would do this (multiple insertions with the same key with different casings). So it's really not a big deal

**Comment by Jinming-Hu** [comment]
> but I'd rather don't consider costs too much for now

I'm not sure if you plan to provide something that has similar interface with STL container (specifically `std::map`). If so, you really should take costs into consideration. Doing so is not easy, or I'd have done it when I was working on case-insensitive metadata.

There is [a long list](https://en.cppreference.com/w/cpp/container/map) of functions you need to overload. You need to provide an iterator, so that STL algorithms can still work on your map. You need to be compatible with

```C++
for (auto pair : your_map) {}
for (auto [key, value] : your_map) {}
```

you'll also need to define your own iterator invalidation rule to meet customers' expectation. This could be a tricky one. If some customer writes

```C++
auto ite = map.find("Content-Encoding");
map["content-encoding"] = "gzip";
assert(ite->second == "gzip");
```

he would expect the assertion at Line 3 to work because this map is supposed to be case-insensitive, so the iterator should not become invalid.

Another kind of embarassing scenario I can think of is `.at()`. When using the non-const overload version, you wouldn't know if customer expects the key to be changed

```C++
map["Content-Encoding"] = "gzip";
map.at("content-encoding") = "deflate";
// now it's expected to be ("content-encoding", "deflate")
std::cout << map.at("content-ENCODING") << std::endl;
// now it's ("content-ENCODING, "deflate"), even though the customer doesn't intend to modify the value at all
```
