### ISSUE TITLE
VcPkg releasing: put release changelog to commit/PR description

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1641]
I also think it would be great if the commit message line 2+ was the release changelog, so it would become a commit description in VcPkg commit history, and also we can paste the changelog to PR description. IMO, very useful for the customers.
This is probably too big of a request to sneak into this issue, please let me know if you'd like me to open a new issue for this.

_Originally posted by @antkmsft in https://github.com/Azure/azure-sdk-for-cpp/issues/1584#issuecomment-775673874_

**Comment by danieljurek** [comment]
We have infrastructure that will allow us to put the CHANGELOG.md in the commit message. Adding iteratively to the PR body is not supported at this time.

**Comment by danieljurek** [comment]
This is merged.
