### ISSUE TITLE
[Perf] Add option to show throughput per parallel workstream

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1648]
Related to .Net request: 
https://github.com/Azure/azure-sdk-for-net/issues/18614

**Comment by ahsonkhan** [comment]
Is the `performance` issue label newly created or was it always there? If it's new, maybe remove it and use the existing `tenet-performance` one.

**Comment by RickWinter** [comment]
@gearama Is this option relevant still?  Can you update the cost in days field.
