### ISSUE TITLE
Consider removing the TransportKind enum in Azure::Core::Http since it is not used anywhere

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1650]
Why did we have this to begin with?
https://github.com/Azure/azure-sdk-for-cpp/blob/a858a77ac0929a84ae79662e255853dd6a511d1a/sdk/core/azure-core/inc/azure/core/http/http.hpp#L90-L98

cc @JeffreyRichter, @vhvb1989

**Comment by vhvb1989** [comment]
I think it was initially added by Rick and expected to be used as an sdk client option to choose the transport adapter. But it was later abandoned :).
I thought I removed it in some PR where I was checking coverage, but looks like I didn't.

Yes, this needs to go.

**Comment by vhvb1989** [comment]
It could have survived that long just thanks to the API view issue that let it be hidden over there 😆
