### ISSUE TITLE
Add template2 package

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#1651]
The steps are different first pushing a port and then pushing another port to the same branch. To simulate the differences in doing so we need 2 ports to test publishing. This is different from other package repositories where you can push packages as needed and don't need to make atomic updates.

**Comment by RickWinter** [comment]
@danieljurek There is a PR attached to this issue which appears to address the issue.  Is this issue closed?

**Comment by danieljurek** [comment]
This issue is mentioned in the PR. This issue is not completed yet.

**Comment by danieljurek** [comment]
Closing the issue as this is a subset of the verification we could be doing with vcpkg nightly: https://github.com/Azure/azure-sdk-for-cpp/issues/1749
