### ISSUE TITLE
Automate trimming out the copyright/license headers from vcpkg control, potfile when submitting a PR

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1664]
https://github.com/Azure/azure-sdk-for-cpp/blob/fcd64f7bd2b983148c0b5099afa8edf3ba05091c/sdk/core/azure-core/vcpkg/CONTROL#L1-L4

Example manual effort: https://github.com/microsoft/vcpkg/pull/16160

cc @antkmsft, @danieljurek

**Comment by antkmsft** [comment]
We should be doing this part, no the CentralEngSys
