### ISSUE TITLE
VcPkg release automation puts an extra newline to portfile.cmake

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1687]
I am comparing the files generated by our build with the files checked it to the VcPkg repo, and I see that in VcPkg repo they do have an extra newline at the end of file, in addition to the new empty lines that we already have in our repo.
It is likely being added by the release automation, by the code that does SHA512 update.
I think we should not be adding that, because it generates extra changes, when looking at the files produced by automation vs "manually", and makes me want to re-check that we indeed do have newlines in our files (which we do, VcPkg automation adds an extra one; it isprobably that it uses `WriteLn()` instead of `Write()` somewhere).

**Comment by ahsonkhan** [comment]
cc @danieljurek

**Comment by danieljurek** [comment]
This should be fixable with `-NoNewLine` https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-7.1 

Will give it a try.
