### ISSUE TITLE
Installing azure-storage-blobs-cpp via vcpkg on windows is bringing in curl dependency

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1689]
I expected winhttp to be used as the transport layer when installing the Azure SDK packages such as `azure-storage-blobs-cpp` via vcpkg, and for curl to **not** be installed. How come it depends on curl by default?

**Steps to reproduce:**
1) Clone the vcpkg repo: `git clone https://github.com/microsoft/vcpkg.git`
2) From VS developer command prompt, run: `.\bootstrap-vcpkg.bat`
3) Install the vcpkg without specifying any triplet or feature to get the default behavior: `vcpkg.exe install azure-storage-blobs-cpp`
4) Wait ~15 minutes for the installation to complete and observe the packages and dependencies installed:
```text
> vcpkg.exe list
azure-core-cpp:x86-windows                         1.0.0-beta.6     Microsoft Azure Core SDK for C++
azure-core-cpp[curl]:x86-windows                                    Build an HTTP transport implementation with LibCURL
azure-core-cpp[http]:x86-windows                                    Build all HTTP transport implementations, depend...
azure-core-cpp[winhttp]:x86-windows                                 Build an HTTP transport implementation with WinHTTP
azure-storage-blobs-cpp:x86-windows                12.0.0-beta.8    Microsoft Azure Storage Blobs SDK for C++
azure-storage-common-cpp:x86-windows               12.0.0-beta.8    Microsoft Azure Common Storage SDK for C++
curl:x86-windows                                   7.74.0#3         A library for transferring data with URLs
curl[non-http]:x86-windows                                          Enables protocols beyond HTTP/HTTPS/HTTP2
curl[schannel]:x86-windows                                          SSL support (Secure Channel)
curl[ssl]:x86-windows                                               Default SSL backend
curl[sspi]:x86-windows                                              SSPI support
curl[winssl]:x86-windows                                            Legacy name for schannel
libiconv:x86-windows                               1.16#8           GNU Unicode text conversion
liblzma:x86-windows                                5.2.5#2          Compression library with an API similar to that ...
libxml2:x86-windows                                2.9.10#2         Libxml2 is the XML C parser and toolkit develope...
zlib:x86-windows                                   1.2.11#9         A compression library
```

cc @antkmsft, @vhvb1989

**Comment by vhvb1989** [comment]
I think the default behavior when installing vcpkg packages without explicitly defined features is to install all available features for the OS. @antkmsft should know better here

But I think if you don't want curl, you have to do vcpkg install azure-blobs-cpp[winhttp]:x86-windows, for example

**Comment by Jinming-Hu** [comment]
can we make `azure-blobs-cpp[winhttp]` the default one and leave out `azure-core-cpp[curl]` unless explicitly specified? or is there a limitation of vcpkg?

**Comment by vhvb1989** [comment]
@antkmsft  can you take a look to this?  My understanding was that we created the required configuration for taking libcurl on windows on demand only

**Comment by antkmsft** [comment]
@ahsonkhan I installed SDK like this on Windows:
```
vcpkg install azure-storage-files-shares-cpp:x64-windows azure-identity-cpp:x64-windows azure-storage-files-datalake-cpp:x64-windows
```

Like this on Linux:
```
./vcpkg install azure-storage-files-shares-cpp:x64-linux azure-identity-cpp:x64-linux azure-storage-files-datalake-cpp:x64-linux
```

I then made this project - CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.19)
project(MyApp LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED True)

find_package(azure-storage-blobs-cpp CONFIG REQUIRED)
find_package(azure-identity-cpp CONFIG REQUIRED)

add_executable(MyApp src/main.cpp)

target_link_libraries(MyApp PRIVATE Azure::azure-storage-blobs)
target_link_libraries(MyApp PRIVATE Azure::azure-identity)
```

main.cpp file:
```cpp
#include <azure/core/http/policies/policy.hpp>
#include <azure/core/http/win_http_transport.hpp>
#include <azure/core/http/curl_transport.hpp>

#include <iostream>

int main()
{
    const Azure::Core::Http::Policies::TransportOptions options;
    std::cout << "Transport pointer   : " << options.Transport.get() << std::endl;
    std::cout << "As WinHttpTransport : " << dynamic_cast<Azure::Core::Http::WinHttpTransport*>(options.Transport.get()) << std::endl;
    std::cout << "As CurlTransport    : " << dynamic_cast<Azure::Core::Http::CurlTransport*>(options.Transport.get()) << std::endl;
}
```

Output on Windows:
```
Transport pointer   : 00000138DCEE7960
As WinHttpTransport : 00000138DCEE7960
As CurlTransport    : 0000000000000000
```

Output on Linux (not really able to test for "WinHttpTransport", because it fails to compile if you include win_http_transport.hpp):
```
Transport pointer   : 0x7fffdeb0fc30
As CurlTransport : 0x7fffdeb0fc30
```

I.e. the main thing it illustrates is that you install vcpkgs using default options, you use them and you get the default transport.
Your default transport on Windows is WinHttp, your transport on non-Windows is CURL.
Which is what we want, and is what this github issue is about. But it was good to verify/confirm.
In my understanding, we can close it.

**Comment by antkmsft** [comment]
The feature set you get installed is
```
azure-core-cpp:x64-windows                         1.0.0-beta.7     Microsoft Azure Core SDK for C++
azure-core-cpp[curl]:x64-windows                                    Build an HTTP transport implementation with LibCURL
azure-core-cpp[http]:x64-windows                                    Build all HTTP transport implementations, depend...
azure-core-cpp[winhttp]:x64-windows                                 Build an HTTP transport implementation with WinHTTP
azure-identity-cpp:x64-windows                     1.0.0-beta.4     Microsoft Azure Identity SDK for C++
azure-storage-blobs-cpp:x64-windows                12.0.0-beta.9    Microsoft Azure Storage Blobs SDK for C++
azure-storage-common-cpp:x64-windows               12.0.0-beta.9    Microsoft Azure Common Storage SDK for C++
azure-storage-files-datalake-cpp:x64-windows       12.0.0-beta.9    Microsoft Azure Storage Files Data Lake SDK for C++
azure-storage-files-shares-cpp:x64-windows         12.0.0-beta.9    Microsoft Azure Storage Files Shares SDK for C++
```

i.e. it does install Curl, which is expected. But the default transport is WinHttp, that is the desired behavior, and that is what you get when building our SDK outside of VcPkg.

**Comment by antkmsft** [comment]
What if you `vcpkg install azure-storage-blobs-cpp`, and it installs both winhttp and curl, but `vcpkg install azure-core-cpp[winhttp] azure-storage-blobs-cpp` - would only winhttp - would that solve the issue? This is not how it is today, but I think that is the direction we should take this fix.
We of course can duplicate features into all packages, but I don't think we should do it. I.e. [winhttp] should not be a feature of storage, it is a feature of core.

**Comment by bhardwajs** [comment]
Seems this can be changed by changing the `CONTROL` in `azure-storage-common-cpp` to 'azure-core-cpp[http]` and changing the CONTROL in azure-core-cpp to `azure-core-cpp[core, winhttp] (windows&!uwp)`?

**Comment by antkmsft** [comment]
After #2149 goes in:
By default, if you `vcpkg install azure-storage-blobs-cpp`, you get both Curl and WinHTTP transport implementations (all available on the platform) for Windows (WinHTTP is used by default and not Curl, but Curl is also available).
On Linux and Mac, you only get Curl implementation (expected).
However, if you want only WinHTTP to be installed, you should install as `vcpkg install azure-core-cpp[core,winhttp] azure-identity-cpp` *, and it won't build Curl transport and won't bring curl dependency.
And the last thing, if you install only Curl on Windows, it will be the default transport (as expected).

--
`*` - you could be thinking, why not `vcpkg install azure-core-cpp[winhttp] azure-identity-cpp`, i.e. why do we have to also put `core` (i.e. `azure-core-cpp[core,winhttp]`)? That is how VcPkg works. If you don't put `core`, that means "install default features + winhttp".
