### ISSUE TITLE
Define the test file structure and namespaces

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1694]
The current approach/design on the sdk for c++ repo is

## Test file structure

All kind of tests are grouped inside a folder `test` inside each project-service like:

![image](https://user-images.githubusercontent.com/24213737/108401239-fc011e00-71d0-11eb-9605-fdc963f65a35.png)

Any new kind of tests (stress, regression, etc) would be a new test project under the test folder from the package.

## Namespaces for tests

The test namespaces are created under `Azure::<service-name>::<package-name>::Test::` grouping namespace like:

![image](https://user-images.githubusercontent.com/24213737/108401904-b729b700-71d1-11eb-93b0-09336b45b722.png)

The namespace, in this case, follows the same structure as the file structure when it gets included to test src files:

![image](https://user-images.githubusercontent.com/24213737/108402061-e6402880-71d1-11eb-878c-12b491ceaf8c.png)

# New proposal

based on comments from https://github.com/Azure/azure-sdk-for-cpp/pull/1655/files#r578041014  

## Test file structure

Move all test kinds (unit, performance, etc) to be at the same level as the src and inc folders like:

- sdk
  - core
    - azure-core
      - inc
      - src
      - test (for unit only)
      - performance
      - <any-other-test-kind>

## Namespaces for tests

Move the namespaces out of the package namespace to be directly under the Azure:: namespace like
`Azure::<Test-kind>::<service-name>::<package-name>::`
example:
`Azure::Test::Core::`
`Azure::Test::KeyVault::Keys::`
`Azure::Performance::KeyVault::Keys::`

In this case, the include statement won't be following the file structure (only the namespace structure):
```cpp
#include <azure/performance/keyvault/keys/...>
#includ <azure/test/core/...>
```

**Comment by RickWinter** [comment]
@vhvb1989 You had a proposal to do this
- sdk/core/azure-core
  - test
    - unit
    - performance
    - stress
    - continuous-operation
    - functional
  - src
  - inc
  - vcpkg

I put this on disk and I very much prefer it over my original thoughts of placing at toplevel.  The clean toplevel folder for each service is a major win for customers trying to understand the code.

**Comment by RickWinter** [comment]
Moving to backlog.  This is test related and can be fixed/adjusted at a later time
