### ISSUE TITLE
[Perf] Rename Performance fw name to Perf 

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1696]
I favor "Perf" over PerformanceStress/Performance.  Perf is very common name for Perf testing.  Its short and concise.  If you want to go with Performance that would be my second choice

_Originally posted by @RickWinter in https://github.com/Azure/azure-sdk-for-cpp/pull/1655#r578041668_

**Comment by RickWinter** [comment]
This change sets a precedence for future services.  we need to set guidelines and fix
