### ISSUE TITLE
Blob storage depending on libxml2 is bringing in other large dependencies such as msys and libiconv, on Windows

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1697]
Consider using built-in xml APIs on Windows, such as the [win32 APIs](https://docs.microsoft.com/en-us/windows/win32/wsw/xml-reader) to reduce the footprint of the SDK on disk.

Here's a sample application build output, and the statically linked executable starts around ~5 MB:
![image](https://user-images.githubusercontent.com/6527137/108422925-0aa8fe80-71ec-11eb-8947-1f1a509c8894.png)

cc @RickWinter, @JeffreyRichter, @Jinming-Hu

**Comment by JeffreyRichter** [comment]
Performance may be terrible for this if you pass to pas XML strings to/from Windows.

**Comment by RickWinter** [comment]
Using libxml2 could be fine if we can get the install time down.  Right now it takes more than 15mins to boot strap the storage dependencies from vcpkg
