### ISSUE TITLE
It is difficult for new customers to differentiate between track1/legacy and the modern C++ SDK for storage when using vcpkg

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1699]
When searching for packages on vcpkg, for discovery, the search `azure-storage` brings up these 5 results, and it is very difficult to tell which one to choose, especially given how similar the descriptions look.

![image](https://user-images.githubusercontent.com/6527137/108431401-aab85500-71f7-11eb-8d7d-adcb56fb2f48.png)

Consider adding [legacy] to the description of the track1 `azure-storage-cpp` description and explore other ways to differentiate/increase visibility of the other packages

Related `vcpkg search` issue: https://github.com/microsoft/vcpkg/issues/16286

cc @Jinming-Hu, @RickWinter

**Comment by RickWinter** [comment]
cc: @maggiepint Here is a case of where C++ customers may find it difficult to pick the right package.

**Comment by RickWinter** [comment]
@kyle-patterson @maggiepint Is there a deprecation strategy we should follow?

**Comment by Jinming-Hu** [comment]
> Consider adding [legacy] to the description of the track1 azure-storage-cpp description and explore other ways to differentiate/increase visibility of the other packages

Storage team agrees with this approach.

**Comment by ahsonkhan** [comment]
@Jinming-Hu can you enumerate some of the other commonplace acquisition points/docs/search results of the track1 storage-SDK that we should route to our newer SDK and notify readers about it.

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu can you enumerate some of the other commonplace customer acquisition points/docs/search results of the track1 storage-SDK that we should route to our newer SDK and notify readers about it.

We're planning to put a notice at the top of Track1 README https://github.com/Azure/azure-storage-cpp/pull/390

**Comment by Jinming-Hu** [comment]
https://github.com/microsoft/vcpkg/pull/18618
