### ISSUE TITLE
Public storage model types that are returned from client library APIs need doxygen docs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1708]
For example:
https://github.com/Azure/azure-sdk-for-cpp/blob/5e97c8f67f279148ba475fe6a0a7a8650449a603/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L342-L348

cc @katmsft, @Jinming-Hu

**Comment by Jinming-Hu** [comment]
partial done in https://github.com/Azure/azure-sdk-for-cpp/pull/2159

**Comment by Jinming-Hu** [comment]
I added docs for return types of blob service in PR https://github.com/Azure/azure-sdk-for-cpp/pull/2206
