### ISSUE TITLE
LRO operations should be returning Operation<T> types with Operation suffix and not Response<Model> types with Result suffix

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1725]
Should the LRO function signatures be as follows?
- Rename `StartCopyBlobResult` to `StartCopyBlobOperation`
- Return that `Operation<T>` type directly rather than as a `Response<T>`
- Move the `StartCopyBlobOperation` type outside of the `::Models` namespace.
```C++
StartCopyBlobOperation BlobClient::StartCopyFromUri(
      const std::string& sourceUri,
      const StartCopyBlobFromUriOptions& options,
      const Azure::Core::Context& context);
```

Currently, the API is defined as follows. Is there a particular reason for us to define it this way?
https://github.com/Azure/azure-sdk-for-cpp/blob/a02d8a2693a2846886e9e8dc74f77d606878b656/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp#L211-L214

For example, compare this with .NET, which returns an `Operation<T>`:
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.copyfromurioperation?view=azure-dotnet

Look at how other LRO operations are written by @vhvb1989 , for example, KeyVault:
https://github.com/Azure/azure-sdk-for-cpp/blob/f9eea4d22d4fbc5856f381f198f0ef0f587dd84e/sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client.hpp#L115-L117

cc @Jinming-Hu, @katmsft, @JeffreyRichter, @RickWinter

**Comment by Jinming-Hu** [comment]
`StartCopyBlobResult` inherits from `Operation<T>` https://github.com/Azure/azure-sdk-for-cpp/blob/f48a850284f3b9694dd5f6a763191cfea53cbf2f/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_responses.hpp#L71

`StartCopyBlobResult` is just following the naming rules https://azure.github.io/azure-sdk/general_design.html#network-requests

Following are suggestions from Jeffrey, word by word. So I don't think I did anything wrong here. The current return type is just fine.

*  ALL functions that call a service API must return a `Response<T>`. 
* We should be following this in C++. The C# Storage types names are wrong and will remain broken but we should fix C++ now.

**Comment by RickWinter** [comment]
> The C# Storage types names are wrong and will remain broken but we should fix C++ now.

@Jinming-Hu Can you elaborate on what is wrong and broken in C#

**Comment by Jinming-Hu** [comment]
> > The C# Storage types names are wrong and will remain broken but we should fix C++ now.
> 
> @Jinming-Hu Can you elaborate on what is wrong and broken in C#

Jeffrey said that in an email with subject "FW: Model type naming in Go" on Aug. 12, 2020

**Comment by ahsonkhan** [comment]
I believe that conversation happened prior to us adding support for LRO and `Operation<T>` and likely refers to general pattern around regular operations which return `Response<T>` and the models having `Result` prefix. LROs don't return models.

LRO operations are different, and we should follow the naming and coding pattern for those that is consistent with other language SDKs, unless there is a strong C++ specific reason to deviate. I don't have such reason.

**Comment by Jinming-Hu** [comment]
> I believe that conversation happened prior to us adding support for LRO and `Operation<T>` and likely refers to general pattern around regular operations which return `Response<T>` and the models having `Result` prefix. LROs don't return models.
> 
> LRO operations are different, and we should follow the naming and coding pattern for those that is consistent with other language SDKs, unless there is a strong C++ specific reason to deviate. I don't have such reason.

I don't know, I thought that was a general guideline going through the beginning to the end.
If this is the case, shall we ask Jeffrey to clarify?

**Comment by ahsonkhan** [comment]
We had chatted with Jeff earlier today and he was fine with making this change. Up to you to reach out and get confirmation, or wait for @JeffreyRichter to respond to this GitHub issue.

**Comment by Jinming-Hu** [comment]
okay, if Jefferey said so

**Comment by ahsonkhan** [comment]
FYI @tg-msft just in case you have any strong disagreements with the proposed change recommended in the original post of this issue, or found something I might have missed.

**Comment by tg-msft** [comment]
Your proposal looks good.  `Response<T>`, `Operation<T>`, and `Pageable<T>` are .NET's three return types.  We wrap models with them, but not each other.
