### ISSUE TITLE
UWP build is broken

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1728]
```
hkeyholder.hpp(37): error C2039: 'RegCloseKey': is not a member of '`global namespace'' (compiling source file telemetry_policy.cpp)
hkeyholder.hpp(37): error C3861: 'RegCloseKey': identifier not found (compiling source file telemetry_policy.cpp)
```

(It is HKeyHolder)

**Comment by antkmsft** [comment]
Solution:

After
```
#pragme once
```

Add this:
#include "azure/core/platform.hpp"

And then, after
```
#if defined(AZ_PLATFORM_WINDOWS)
#if !defined(WIN32_LEAN_AND_MEAN)
#define WIN32_LEAN_AND_MEAN
#endif
#if !defined(NOMINMAX)
#define NOMINMAX
#endif

#include <windows.h>
```
Add this:
```
#if !defined(WINAPI_PARTITION_DESKTOP) \
    || WINAPI_PARTITION_DESKTOP // See azure/core/platform.hpp for explanation.
```

and then add the corresponding
```
#endif
```

**Comment by antkmsft** [comment]
@RickWinter, this one is blocking release, still not assigned, I can implement it by EOD, but late.

**Comment by antkmsft** [comment]
If you are fine with that - assign to me, I know how to fix it.

**Comment by ahsonkhan** [comment]
> Do not attempt to use WINAPI_PARTITION_DESKTOP check before you include windows.h, and do not include windows.h until you check for AZ_PLATFORM_WINDOWS, and do not check AZ_PLATFORM_WINDOWS until you include azure/core/platform.hpp.

Is there a way we can spread this guidance more broadly to the team so we know how to use the `windows.h` correctly in all cases? Do we have other usages that need to be corrected?

**Comment by antkmsft** [comment]
@ahsonkhan - it is, already: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/core/azure-core/inc/azure/core/platform.hpp#L9-L42

Plus, every comment that checks for UWP sends the reader to go read that comment.
