### ISSUE TITLE
ClientOptions base class

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1732]
All client options should derive from a base client options.  Allows for common client options to be specified.

Common client options:

- LoggingOptions
- ProxySettings
- RetryOptions
- PerCallPolicies
- PerRetryPolicies
- TransportAdapter

**Comment by Jinming-Hu** [comment]
okay, I can do this

**Comment by vhvb1989** [comment]
> I see the label Azure.Core. So in my understanding, core sdk is going to provide a base client options and storage sdk is going to inherit from it

Working on it. Expect a PR later
