### ISSUE TITLE
Update Http request for retryPolicy and all per-retry policies

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1737]
Add `uint GetRetryNumber()` api for the HttpRequest.

Make the RetryPolicy a friend class of the HttpRequest so it can update the retry number on every retry intent.

This information will allow the per-retry policies to make decisions based on the number of retries intended for the request. 

More info:

Other languages uses a `RequestContext` object to share one state across the pipeline.
This feature is require to implement a policy that reacts to some of the output of a previous policy. For example, the `StorageSwitchServerPolicy` needs to know if the request is on retry mode or not in order to switch to a second server.

I consider adding the entire RequestContext object as a map<string, string> to allow any state to be recorded, but this becomes more expensive for what we currently need right now ( just one int value)

**Comment by vhvb1989** [comment]
@Jinming-Hu , this feature will let you create a per-retry policy for Storage which would switch to the secondary server depending on the retry number.

**Comment by Jinming-Hu** [comment]
hack, but works

**Comment by RickWinter** [comment]
I don't like this design.  Friend use is almost always a hack.  It makes more sense to allow overriding the retry policy and storage extends the retry policy to support this behavior.  This way storage can customize retry while still leveraging the core of retry behavior that everyone gets.

**Comment by vhvb1989** [comment]
>  It makes more sense to allow overriding the retry policy and storage extends the retry policy to support this behavior

This would break the model of Core standardization across services where Core provide the default policies and won't accept a service overriding one of this policies.  We got this feedback from the arch board and it is the motivation behind #1732 🤣 

We can create an entire RequestContext object to be inside the HttpRequest for policies to share state between them, but we need to protect the access to that context anyway.  

We already use the friend access approach for `StartRetry()`  which we want to run only from the retryPolicy.

**Comment by ahsonkhan** [comment]
> I consider adding the entire RequestContext object as a map<string, string> to allow any state to be recorded, but this becomes more expensive for what we currently need right now ( just one int value)

Can you share some links, I couldn't find this type and would like to see how it's used. I found `TokenRequestContext` in .NET, but that doesn't seem to be the one you are referring to.

**Comment by vhvb1989** [comment]
> > Other languages uses a `RequestContext` object to share one state across the pipeline.
> 
> Can you share some links to sources, I couldn't find this type and would like to see how it's used. I found `TokenRequestContext` in .NET, but that doesn't seem to be the one you are referring to.

.NET uses what they call a HttpMessage: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/HttpMessage.cs#L17  and it has the dictionary<string, object> as the context

Java call it HttpPipelineCallContext: https://github.com/Azure/azure-sdk-for-java/blob/632bb56d744549f6857289a7df3391731660ac7e/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpPipelineCallContext.java#L14
