### ISSUE TITLE
[Bug] Http stack does not throw exception when content length mismatches actual response body length.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#175]
When the response's body's actual length does not match the content-length header, the response body should be considered corrupted and an exception should be raised.

**Comment by vhvb1989** [comment]
http transport won't try to pull more data from wire than what Content-Length header reported in the response.

As soon as customer reads all data, bodyStream.Read() will return 0;

@katmsft would that be enough to close this issue?  I can probably add a few tests for it

**Comment by RickWinter** [comment]
@vhvb1989 update and close once verified fixed
