### ISSUE TITLE
Implementation detail of many storage APIs shows up as public doxygen docs, confusing the end customer reading them

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1751]
The doxygen API reference docs published show a lot of the implementation detail of the storage APIs which make readers think these are usage samples for them to copy.
This makes the docs filled with a lot of noise that isn't relevant to the end customer.

Instead, example calling code or code snippets that end users can leverage should be written and displayed.

https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-storage-blobs/12.0.0-beta.8/class_azure_1_1_storage_1_1_blobs_1_1_blob_container_client.html#ad58f17faab40f56b891b3ba442b8bf8a
![image](https://user-images.githubusercontent.com/6527137/109346035-eb325700-7825-11eb-9cb7-49d56c6eeeef.png)

This is a side-effect of having all the implementation of the APIs within header files. There is probably some knob on doxygen to address this concern, in the short term.

cc @Jinming-Hu, @katmsft

**Comment by Jinming-Hu** [comment]
what caused this issue? Is this some kind of bug of doxygen?

**Comment by Jinming-Hu** [comment]
![image](https://user-images.githubusercontent.com/52266153/116175485-f846c600-a742-11eb-9b7a-ef4a76dbbf8d.png)
https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-core/1.0.0-beta.8/class_azure_1_1_core_1_1_http_1_1_raw_response.html

**Comment by Jinming-Hu** [comment]
This is not a problem specific to storage.

**Comment by Jinming-Hu** [comment]
https://github.com/Azure/azure-sdk-for-cpp/blob/fe9002e9054b04a2375da242e49badb1f6880252/cmake-modules/AzureDoxygen.cmake#L21 Change this value to `NO` will fix the problem
