### ISSUE TITLE
Allow custom RequestID per operation

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1758]
Make RequestID to check the Context for overriding RequestId to be used

```C  
RequestIdPolicy();
```
#
we could use the Context. But the requestPolicy needs to be updated for that.
Is that a typical scenario?

Based on: https://apiview.dev/Assemblies/Review/3bd21beb2d9941a78683ac117c7bae33#Azure::Core::Http::RequestIdPolicy

**Comment by Jinming-Hu** [comment]
Is this a customer feature request?

We randomly generate request Id for each operation. I think it's enough already

**Comment by vhvb1989** [comment]
based on arch bord review: https://apiview.dev/Assemblies/Review/3bd21beb2d9941a78683ac117c7bae33#Azure::Core::Http::RequestIdPolicy

**Comment by vhvb1989** [comment]
> Is this a customer feature request?
> 
> We randomly generate request Id for each operation. I think it's enough already

It's a way for a customer to control exactly what id is sending to the server.

**Comment by Jinming-Hu** [comment]
> > Is this a customer feature request?
> > We randomly generate request Id for each operation. I think it's enough already
> 
> It's a way for a customer to control exactly what id is sending to the server.

okay, I don't understand why customer wants to do that

**Comment by Jinming-Hu** [comment]
Customer who wants to do it can do it via policy, right? This is not a common feature request
