### ISSUE TITLE
Version script cleanup

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#1764]
* Remove code path for `version.txt` as we have since migrated away from that approach 
* Move code common to version parsing from `SdkVersion-Common.ps1` into somewhere like `Language-Settings.ps1`

**Comment by weshaggard** [comment]
>Move code common to version parsing from SdkVersion-Common.ps1 into somewhere like Language-Settings.ps1

It doesn't have to be moved to Language-Settings but it should probably be imported from their if you keep it separate and we probably should also move more of the update/get functions into that common versioning scripts.
