### ISSUE TITLE
The SDK should have some mechanism to validate arguments passed in to public APIs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1769]
One typical answer is to add argument checks and throw `std::invalid_argument` error. If we like this approach, let's add such argument validation along with unit tests to all the public APIs that don't yet have it.

For example, validate negative input lengths or null pointers.
https://github.com/Azure/azure-sdk-for-cpp/blob/d782c99777a234fb5c479d176063a7fe169d6b6a/sdk/core/azure-core/inc/azure/core/io/body_stream.hpp#L154-L156
https://github.com/Azure/azure-sdk-for-cpp/blob/a55aba01bee22189fc4b1d741cd56e7095dde79c/sdk/core/azure-core/src/http/raw_response.cpp#L21-L25
https://github.com/Azure/azure-sdk-for-cpp/blob/a55aba01bee22189fc4b1d741cd56e7095dde79c/sdk/core/azure-core/inc/azure/core/http/http.hpp#L539

We already do this in certain places today:
https://github.com/Azure/azure-sdk-for-cpp/blob/a55aba01bee22189fc4b1d741cd56e7095dde79c/sdk/core/azure-core/inc/azure/core/cryptography/hash.hpp#L62-L66
https://github.com/Azure/azure-sdk-for-cpp/blob/a55aba01bee22189fc4b1d741cd56e7095dde79c/sdk/core/azure-core/src/datetime.cpp#L163-L168

This PRs adds some input validation to `FileBodyStream`, to see what it would look like in practice:
https://github.com/Azure/azure-sdk-for-cpp/pull/1730

What should we do about `empty strings` or `invalid options` like RetryOptions where MaxRetries is negative, or Range has negative length?
https://github.com/Azure/azure-sdk-for-cpp/blob/bf347d24c24d8a46d0013e2b4a34197c424ecff2/sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp#L67-L74
https://github.com/Azure/azure-sdk-for-cpp/blob/a5ff474118e2d502ff05ffdfd4386ea20ce14724/sdk/core/azure-core/inc/azure/core/http/policy.hpp#L166-L171
https://github.com/Azure/azure-sdk-for-cpp/blob/a5ff474118e2d502ff05ffdfd4386ea20ce14724/sdk/core/azure-core/src/http/retry_policy.cpp#L78-L81

cc @JeffreyRichter, @RickWinter, @antkmsft, @vhvb1989

**Comment by vhvb1989** [comment]
@ahsonkhan  this one seams complicated to be completed as part of March-2021.  Can we move it to backlog or at least to April?

**Comment by ahsonkhan** [comment]
Yes. It shouldn't be API breaking.

**Comment by Jinming-Hu** [comment]
Some of the examples are pre-conditions, and according to the [guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html#cpp-errors), we should crash rather than throw.

**Comment by Jinming-Hu** [comment]
And I believe it's fine if we don't validate at all, just leave it undefined. Undefined behavior is widely used in C++ world.

**Comment by Jinming-Hu** [comment]
> For example, validate negative input lengths or null pointers.
https://github.com/Azure/azure-sdk-for-cpp/blob/d782c99777a234fb5c479d176063a7fe169d6b6a/sdk/core/azure-core/inc/azure/core/io/body_stream.hpp#L154-L156

for this example, we only check if it's null pointer. What if it's a dangling pointer? And what if the length is larger than the memory actually allocated? We cannot validate all the bad cases anyway. So I don't suggest to take half measures.

**Comment by ahsonkhan** [comment]
This issue depends on the results of https://github.com/Azure/azure-sdk-for-cpp/pull/2170
