### ISSUE TITLE
Should ClientSecretCredentialOptions derive from clientOptions?

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1770]
`ClientSecretCredentialPolicy ` is an special policy which needs to send an Http request to get an auth token.

The policy can send the request with any of the next strategies:
- Get the default transport adapter directly, create the request and send it. (easiest approach, no retry capabilities)
- The policy can export `TrasportOptions` as part of the `ClientSecretCredentialOptions ` so anyone using the policy can chose which http client to use (or use the default if none selected). The policy will create a new httpPipeline to send the request and will hardcode the settings for retry policy with default configuration.  No other policy is used but retry and transport.  This is the current strategy.
- The policy can make the `ClientSecretCredentialOptions` to derive from `clientOptions` and let anyone using the policy to set up all the default policies like retry, telemetry, requestId and transport.  This is how other languages like .Net behaves.

**Comment by vhvb1989** [comment]
leaving ClientSecretCredentialOptions derive from clientOptions as that's how it works in other langs

**Comment by antkmsft** [comment]
Agree - I just tested something in .NET SDK with ClientSecretCredential, and it was very convenient to override Log options.
And now I am writing tests for the ClientSecretCredential, and I'm going to override transport.
