### ISSUE TITLE
per-call and per-retry policies in ClientOptions should be public

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1772]
There are 2 things I will follow up after this PR is merge that you mentioned:
- Should ClientSecretCredentialOptions derive from clientOptions?
- Should per-call and per-retry end-user's policies array be public?

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/issues/1734#issuecomment-790146745_

**Comment by Jinming-Hu** [comment]
* We do not need AddPolicy/GetPerCallPolicies/GerPerRetryPolicies methods.

* Making it a struct is good as all members should be public

_Originally posted by @JeffreyRichter in https://github.com/Azure/azure-sdk-for-cpp/issues/1734#issuecomment-789953349_

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk-for-cpp/pull/1771
