### ISSUE TITLE
Add operator<<(std::ostream&, AzSdkType)

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1773]
This came up during usability studies / manually putting ourselves into customer shoes.

* There should be an overload for HttpStatusCode (casts to int)
* For DateTime (I suggest Rfc3339 with all digits, as it has fractional seconds, and gives maximum precision)
* Review if anything else needs it.
* Extensible enums probably don't, because they are strings.

**Comment by antkmsft** [comment]
cc @ahsonkhan

**Comment by ahsonkhan** [comment]
We might want to include other types too like `RawResponse`, `Url`, `Response<T>`, `Uuid`, etc. It's almost equivalent to .NET's `ToString()` methods on types and `DebuggerDisplay` for ease of diagnosability while using the SDK types so users can quickly output useful string representation of such types to `std::cout`.

Any others come to mind @vhvb1989 and @RickWinter that could benefit from this?

**Comment by vhvb1989** [comment]
I remember sometime ago @JeffreyRichter  mentioned something about why these operators are better not to have.

I am adding all team to the assigner list to comment and work the designing.

**Comment by antkmsft** [comment]
JFYI, https://github.com/Azure/azure-sdk-for-cpp/pull/1752 adds it for DateTime.

**Comment by ahsonkhan** [comment]
> JFYI, #1752 adds it for DateTime.

Please do that in a separate PR.

**Comment by RickWinter** [comment]
@ahsonkhan @antkmsft This seems like a reasonable feature to add in the future.  Is there any class that wouldn't work with this feature in the future.

**Comment by antkmsft** [comment]
We can add it later, if we don't do it today, it will not prevent us from adding it in the future.
