### ISSUE TITLE
compiler warning in client_options.hpp

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1776]
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C26439	This kind of function may not throw. Declare it 'noexcept' (f.6).	azure-core	C:\Users\Jamis\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\inc\azure\core\internal\client_options.hpp	34	
```

https://github.com/Azure/azure-sdk-for-cpp/blob/3eab83a635af6ece7554c8a3a4fab1ba63a748e2/sdk/core/azure-core/inc/azure/core/internal/client_options.hpp#L35

**Comment by vhvb1989** [comment]
Same as the other, please add more info for how to reproduce. Then please assign to me
