### ISSUE TITLE
compiler warning in json.hpp

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1777]
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C26439	This kind of function may not throw. Declare it 'noexcept' (f.6).	azure-storage-files-shares	C:\Users\Jamis\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\inc\azure\core\internal\json.hpp	4630	
```

https://github.com/Azure/azure-sdk-for-cpp/blob/3eab83a635af6ece7554c8a3a4fab1ba63a748e2/sdk/core/azure-core/inc/azure/core/internal/json.hpp#L4630

**Comment by vhvb1989** [comment]
Can you add more details @Jinming-Hu ?
- What compiler ?  what version?
- What's the CMake generate script ?  triplet ??    

I need this to reproduce, fix and test.

**Comment by vhvb1989** [comment]
After adding more data, please assign it to me

**Comment by ahsonkhan** [comment]
@Jinming-Hu how come you closed the issue? Did you figure out what went wrong? If so, please share.

**Comment by Jinming-Hu** [comment]
@ahsonkhan No, I just came across this issue last night, but when I tried to repro this morning, it's gone. Maybe I'll reopen next time I run into it

**Comment by ahsonkhan** [comment]
Sounds good. Make sure to capture the repro environment and the steps you took if any such issues occur again, especially if they are difficult to reproduce or intermittent :)
