### ISSUE TITLE
Reconsider the constructor of HttpPipeline

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1778]
https://github.com/Azure/azure-sdk-for-cpp/blob/3eab83a635af6ece7554c8a3a4fab1ba63a748e2/sdk/core/azure-core/inc/azure/core/internal/http/pipeline.hpp#L72

Jeffrey's this https://github.com/Azure/azure-sdk-for-cpp/pull/1734#discussion_r586688975 inspired me.

```
the client library code can just add this to the end of the clientLibraryPerRetryPolicies vector.
```

Then why do we need parameter `perRetryPolicies` and `perCallPolicies` in `HttpPipeLine` constructor? Client code can prepend or append all the policies to the vectors in `ClientOptions`. Then this constructor can be simplified. This also solves the problem that storage auth polily has to be the last one.

**Comment by vhvb1989** [comment]
> why do we need parameter perRetryPolicies and perCallPolicies in HttpPipeLine

Those parameters are for the policies defined by the service client. It is different from the ones in the client options which belongs to the end-users.

The end-user policies are expected to be after the client-service policies. This is because end-user is the last possible overriding possibility for the request.

If we use only the policies from the client options, then service-clients would need push polices as stack. 

It is just more complicated to keep a good ordering separation between the service-client's policies and the one from end-users.

**Comment by Jinming-Hu** [comment]
@vhvb1989 service client knows which policy is from service client itself and which policy is from end user. So service client can properly sort these policies. Once these policies are passed down to core sdk, there isn't this kind of difference any more. Because core sdk deals all these policies in the same way, it doesn't need to know which policy is from service client and which policy is from end user.

Also, as Rick suggested "the client library code can just add this to the end of the clientLibraryPerRetryPolicies vector.", we mix storage key auth policy (which is a service client policy) with end-user per-retry policies anyway. So what's the point of separating them?

**Comment by Jinming-Hu** [comment]
anyway, just a suggestion. If you think it doesn't make sense, i'll jus close it

**Comment by vhvb1989** [comment]
> we mix storage key auth policy (which is a service client policy) with end-user per-retry policies anyway.

Nop, The end-user policies are meant to override any value from the service.  If the service needs to take care of the order, the policies would need to be pushed in to the vector at the first position (and not to the end), how would that work with std::vector? (would it require to copy all the array to new memory?)

Service don't really need to worry about the ordering.
