### ISSUE TITLE
Add unit tests for various Nullable<T> operators

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1786]
@RickWinter 
Add a test for the operators:

```cpp
TEST(Nullable, Operator)
{
  Nullable<std::string> val1("12345");
  EXPECT_EQ(*val1, "12345");
  val1->append("aaaa");
  EXPECT_EQ(*val1, "12345aaaa");
}
```

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/issues/1761#issuecomment-789248396_

**Comment by ahsonkhan** [comment]
> Yes, forgot about unit tests. Please do add some :)
> 
> Thank for the reminder Victor.
> 
> @RickWinter when adding tests, please include what happens to the original `Nullable<T>` instead after calling the operator that moves the ownership. Similar to this, from [std::optional](https://en.cppreference.com/w/cpp/utility/optional/operator*):
> 
> ```c++
> auto taken = *std::move(opt2);
> std::cout << "taken: " << taken << " opt2: " << *opt2 << "size: " << opt2->size()  << '\n';
> ```

**Comment by RickWinter** [comment]
@ahsonkhan Please review and add any tests that you see are missing.
