### ISSUE TITLE
Non-optional Options

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1795]
`TokenRequestOptions` can have no meaningful default value. It is its only problem, other than the fact that it has a name that ends with "Options", which means a specific thing within our SDK - it is that it could be made optional / so there must be some default value that makes sense.
Let's rename it to `TokenRequestContext`/`TokenRequestParameters`?
Or, redefine our guidelines a bit, to allow non-default options. Because `RetryPolicy` and `LogPolicy` do also have constructors with non-default options, and I also think they should not have implicit default options. If you use default options on any of these places, you are writing erroneous (TokenRequest)/error-prone/problematic code (RetryPolicy, LogPolicy - that means you are creating a pipeline that does not respect ClientOptions. Which is maybe ok in some circumstances (I can't think of any, but there might be some), and also it does not mean the code will explode, I'd prefer that if you chose to ignore ClientOptions, do so explicitly). Default options in these cases is doing us a disservice. So, as alternative, rename RetryOptions/LogOptions to RetryParameters/RetrySettings/LogParameters/LogSettings/DiagnosticsParameters/DiagnosticsSettings.

_Originally posted by @ahsonkhan in https://github.com/Azure/azure-sdk-for-cpp/pull/1779#r588737969_

**Comment by ahsonkhan** [comment]
cc @RickWinter, @JeffreyRichter
