### ISSUE TITLE
Refactor Context withValue to not taking an std::string for key. Use pointer directly

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1815]
As mentioned in team meeting.
Suggested by @JeffreyRichter  and @antkmsft

**Comment by RickWinter** [comment]
Comment from Jeff:

> There are a few things we can do here and they are related.
> 
> For the key, I'd prefer to avoid having a string field in the Context because it adds significant % overhead to the Context and I'd also prefer to not do string comparisons. Rember that we have a linked-list of contexts and so there may be several of them (which multiplies the size) and comparing each Context's string is a perf hit too. Furthermore, there is just no value to the key being a string; the key could be an integer or something else - we just need uniqueness so small & fast is worth striving for. And code that sets the key and looks up the key is written by the same person and so only this code needs to know what the key is.
> 
> So, one option is that actually make the typeid be the key. We already have this field and so WithValue can take just 1 parameter (the T) and GetValue uses typeid(T) to compare when scanning the Context linked-list. So now, the structure data type is (implicitly) the key itself: small and fast and simpler API.
> 
> If you really prefer an explicit key for some reason, then I propose a void*; just some memory address which is unique. Then the code that sets/gets the key can pass in the address to something that only it knows about (like a global Boolean variable).
> 
> If the key can't be found, then return the default. Or, if this is problematic due to the const reference, I'd change Get to TryGet and have it return a Boolean and an output T parameter.

**Comment by Jinming-Hu** [comment]
> So, one option is that actually make the typeid be the key. 

Cannot use typeid as the key. If we have two variables both of which are boolean, typeid will be the same, then there's no way to tell one from the other.

**Comment by JeffreyRichter** [comment]
Most of the calls to set/get values is by Core/client libraries; not customer code. So, we'd just mandate that the Boolean (to use your example) be wrapped in a struct:
struct Foo {
   bool on
}

then the typeids will be unique.

The ONLY time I'd expect a customer to get/set a value is if the customer defines their own policy which is a super advanced scenario.  And, in this case, if they want to support per-operation feature overriding, then we just tell them that they must also use their own struct.

**Comment by Jinming-Hu** [comment]
> Most of the calls to set/get values is by Core/client libraries; not customer code. So, we'd just mandate that the Boolean (to use your example) be wrapped in a struct:
struct Foo {
bool on
}

This makes context less convenient to use.

> then the typeids will be unique.

Unfortunately, no. Multiple calls to `typeid()` don't guarantee to return the same pointer. https://stackoverflow.com/questions/5778560/will-multiple-calls-to-typeidt-name-return-the-same-pointer

**Comment by Jinming-Hu** [comment]
@antkmsft 's proposal in this https://github.com/Azure/azure-sdk-for-cpp/pull/1824#discussion_r590942383 can work very well.

**Comment by JeffreyRichter** [comment]
Well, I don't feel that strongly about this. So I'm fine with an explicit key and I think a void* is smaller/faster than a string.

**Comment by Jinming-Hu** [comment]
We compare key by pointer in Anton's proposal. It's as fast as comparing `void*` and easy to use. That's why I think it's the best option.
