### ISSUE TITLE
[Refinement] Aggregate shared http headers into one struct.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#182]
CacheControl
ContentType
ContentDisposition
ContentEncoding
ContentLanguage

These headers are used for many blobs/files/datalake APIs, it should be put into a struct to avoid duplicate code.

**Comment by JinmingHu-MSFT** [comment]
Blobs Service defines it in protocol layer. So I think DataLake should also do so. If you cannot because of limitation of swagger, please `using DalaLakeHttpHeaders = Blobs::BlobHttpHeaders` somewhere.

**Comment by katmsft** [comment]
As Datalake is going to use blob protocol layer due to interop, this is no longer an issue of depending on blob service.
