### ISSUE TITLE
Investigate alternative ways to get the OS information on windows without relying on registry keys

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1842]
Today, we use the registry to fetch the OS info.
https://github.com/Azure/azure-sdk-for-cpp/blob/76870c44144cc426f0a0c4d3104eeb915ac002b6/sdk/core/azure-core/src/http/telemetry_policy.cpp#L35-L42

Consider using an alternative like GetVersion (investigate other approaches that might be better suited):
https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversion

That said, we need to figure out how to handle differences between 8.1 and 10.
One approach could be to use the version helpers and specify the version strings explicitly (but we lose some fidelity of info):
https://docs.microsoft.com/en-us/windows/win32/sysinfo/version-helper-apis

With this approach, we could remove:
https://github.com/Azure/azure-sdk-for-cpp/blob/76870c44144cc426f0a0c4d3104eeb915ac002b6/sdk/core/azure-core/inc/azure/core/internal/hkeyholder.hpp#L31

cc @JeffreyRichter, @RickWinter, @antkmsft

**Comment by RickWinter** [comment]
We get a much richer set of information about the OS using the registry.  We could change this in the future as the telemetry is an implementation detail.
