### ISSUE TITLE
Avoid, or minimize, exposing windows.h header from our public headers (either directly or indirectly)

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1853]
1) For places where we have private fields coming from that header, use `void*` and cast it to the appropriate type in the cpp source file. This is similar to:
https://github.com/Azure/azure-sdk-for-cpp/blob/a9c0637e462f80340ac7b912fe9c52df0b4d39ec/sdk/storage/azure-storage-common/inc/azure/storage/common/xml_wrapper.hpp#L40
https://github.com/Azure/azure-sdk-for-cpp/blob/a9c0637e462f80340ac7b912fe9c52df0b4d39ec/sdk/storage/azure-storage-common/src/xml_wrapper.cpp#L42

2) For places where windows.h is needed as an implementation, split that out of the header file and into cpp.
3) No public APIs should be accepting types from windows.h.

**Here's the list in order of priority:**
- [ ] body_stream.hpp https://github.com/Azure/azure-sdk-for-cpp/blob/3d6cd38658548747587adb84462a7a2d2910275b/sdk/core/azure-core/inc/azure/core/io/body_stream.hpp#L22
- [ ] hkeyholder.hpp (though it is an internal header, not exposed via any public headers) https://github.com/Azure/azure-sdk-for-cpp/blob/bc564dbddd0371e222105bd539bbbe8ba8e45fe1/sdk/core/azure-core/inc/azure/core/internal/hkeyholder.hpp#L21
- [ ] environment_log_level_listener_private.hpp (low priority, but is the include even needed here?) https://github.com/Azure/azure-sdk-for-cpp/blob/a9c0637e462f80340ac7b912fe9c52df0b4d39ec/sdk/core/azure-core/src/environment_log_level_listener_private.hpp#L16

**Comment by Jinming-Hu** [comment]
I'll handle `file_io.hpp`

**Comment by ahsonkhan** [comment]
@RickWinter let's consider adding this to the guidelines too.

**Comment by RickWinter** [comment]
@ahsonkhan please split this work item into two tasks.  One for the work in Azure::Core and the other for work in Azure::Storage

**Comment by ahsonkhan** [comment]
@RickWinter - done - https://github.com/Azure/azure-sdk-for-cpp/issues/2182
