### ISSUE TITLE
Response::GetRawResponse needs to return a const&

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1865]
GetRawResponse is return a ref to the underlying response data.  That should be const& b/c we do not want the response modified.

**Comment by ahsonkhan** [comment]
Similar to `Operation<T>` which was fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/1852.

**Comment by antkmsft** [comment]
Fixed by #1825.

**Comment by antkmsft** [comment]
We need to only have the const version. But then GetBodyStream() needs to return const ref. And if we want a version that returns a unique_ptr,  it needs to be named ExtractBodyStream().
No methods named "Get..." should return unique_ptrs. It should be Extract... or Create... - Review SDK for that.

**Comment by ahsonkhan** [comment]
@RickWinter did we end up fixing this issue?

**Comment by vhvb1989** [comment]
It returns & but not const&

**Comment by vhvb1989** [comment]
After @ahsonkhan  refactor / simplification for Response<T> #1954  this is no longer required. Closing.
