### ISSUE TITLE
[Blob/DataLake Service] Parallel Upload/Download Support in storage SDK

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#187]
1. Download to file
2. Download to buffer
3. Upload from file
4. Upload from buffer

for 

1. ~~Block blob~~ (finished)
2. ~~Page blob~~ (We decided not to do this for now because storage sdk of other languages don't do this.)
3. Datalake file
4. Files Service file

We won't support download/upload to/from buffer directly, because buffer can be easily wrapped into a stream.

**Comment by JinmingHu-MSFT** [comment]
The current implementation of `BodyStream` in Azure Core doesn't support seek to random offset. It only supports seek to zero (`Rewind`). This makes concurrent download/upload very hard to implement.

**Comment by JinmingHu-MSFT** [comment]
Download to buffer for block blob is done.
Upload from buffer for block blob is done.

https://github.com/Azure/azure-sdk-for-cpp/pull/244

**Comment by JinmingHu-MSFT** [comment]
Download to file for blob is done.
Upload from file for block blob is done.

https://github.com/Azure/azure-sdk-for-cpp/pull/247

**Comment by katmsft** [comment]
DataLake is interop using blob service's implementation.
