### ISSUE TITLE
No methods named "Get..." should return unique_ptrs. It should be Extract... or Create...

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1873]
No methods named "Get..." should return unique_ptrs. It should be Extract... or Create... - Review SDK for that.

_Originally posted by @antkmsft in https://github.com/Azure/azure-sdk-for-cpp/issues/1865#issuecomment-797087985_

`std::unique_ptr<Azure::Core::IO::BodyStream> GetBodyStream()` - Extract?
`std::unique_ptr<RawResponse> GetRawResponse(...)` - Create?
`std::unique_ptr<CurlNetworkConnection> GetCurlConnection`(...) - Create?
`std::unique_ptr<RawResponse> GetResponse()` - Extract?
`std::unique_ptr<Azure::Core::Http::RawResponse> GetResponse()` - Extract?
`std::unique_ptr<Azure::Core::Http::RawResponse> GetResponse()` - Extract?

**Comment by RickWinter** [comment]
@antkmsft Please update the issue describe with all offending instances.

**Comment by antkmsft** [comment]
Updated.
