### ISSUE TITLE
CurlTransportSSLOptions should be named CurlTransportSslOptions

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1877]
2 letter acronyms are all caps, 3 letter acronyms go Pascal, correct?
Also, write a regex and verify the entire code base.

**Comment by RickWinter** [comment]
I suggest we bring this up in the Working Group.  SSL and TLS are typcially referred to in all Caps

**Comment by antkmsft** [comment]
I am fine, as long as there is a guideline. Maybe we should change guidelines for leaving  three-letter-abbreviations capitalized? For example, we have `DateTimeFormat::Rfc1123/Rfc3339`, SHA, HKEY etc. But also have Http, Url, and Uuid. Let's grab the list and review the real examples, decide how they look the best to an eye and try to construct a guideline on top of the desired outcome.

**Comment by ahsonkhan** [comment]
FWIW, .NET framework uses Pascal case for these, so `Ssl` and `Tls`
