### ISSUE TITLE
Context: review `CancelAtMsecSinceEpoch(ToMsecSinceEpoch(cancelAt))`

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1880]
That looks like something that can be rewritten to use DateTime / may not work correctly if it currently uses DateTime

**Comment by RickWinter** [comment]
@antkmsft I'm not sure we want to use DateTime.  I agree we should optimize the performance of this method, the time conversions are expensive.

**Comment by antkmsft** [comment]
@RickWinter I think DateTime ended up being useful for more than just the initial goal of over-the-wire parseable string dates. There is also no penalty for using them compared to chrono, because they are basically std::chrono::time_points (just customized for guaranteed precision and years range). I think all the SDK code uses it now, and it is convenient - we use them for token expirations / checking against std::chrono::system_clock::now(), we use them for timestamps of log messages for ConsoleLogger.

So, the main reason I opened this is not about code uniformity at all - it is because our own DateTime does exactly these epoch conversions, and also does them well, so it is easy to use, and if we utilize it, the code gets simpler - to very straighforward DateTime use, context would not need to worry about the correctness of epoch conversions.
