### ISSUE TITLE
Context::GetApplicationContext() can be a static data member (Context::Application)

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1881]
Suggestion:
`Context::GetApplicationContext()` can be a static data member `Context::Application`

**Comment by RickWinter** [comment]
@antkmsft Can you elaborate on your proposal.  The design we have was used to avoid static initializer order issues.
https://isocpp.org/wiki/faq/ctors#static-init-order

**Comment by ahsonkhan** [comment]
And please add a target milestone + estimate.

**Comment by antkmsft** [comment]
@RickWinter I know that sometimes it is tricky to ensure the right static initialization order`*`, but I do not see anything in the Context, that would not work with plain and simple static initialization. Construction of empty context does not rely on any other static instance of anything. Maybe at a time it was, but not anymore.

`*` - nevertheless, it is often still possible to do some tricks to still have static data members initialized in the right order: see the tricks that are done in order to make `static Logger::Listener g_logListener`, `Log::g_isLoggingEnabled`, and `Log::g_logLevel` to be in sync while not assuming any order of static initialization between them.
Or, also, the context code can be written in a way that the application context is something simpler that can be constructed without initialization-order dependency, and the rest of the code would recognize that value and treat it as application context.
But I don't think we even need to invent complicated things - I think we should be able to simply declare static data class member instance.

@ahsonkhan, for Milestone, I'd like the triage v-team to answer, what you think is appropriate, but in general I'd say that if we want to fix this, it needs to be before GA. Cost-wise, again, it would be up to the dev to estimate, but I think it should be a couple of hours to fix, debug, update docs and pass a code review. I'll put that estimate.

Please re-triage, and put the milestone if you agree with me it should be done. I recommend pre-GA milestone, or Won't Fix after that.
For he decision, I think you should ask yourself, if you think if `Context::Application`(or, `Context::ApplicationContext`) looks better/clearer than `Context::GetApplicationContext()`. I think it is.

**Comment by ahsonkhan** [comment]
@antkmsft when I file issues, I set a milestone and estimate for what I think makes the most sense. Others on the team (and the person doing the work) can always update it.

**Comment by vhvb1989** [comment]
Moving to May as it still need more discussion about it.

**Comment by vhvb1989** [comment]
@CaseyCarter can you help us to understand if updating this static function to an static member would put us into the init fiasco ?
