### ISSUE TITLE
Explicit/required options

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1894]
I don't want LogPolicy and RetryPolicy to have default options in constructor. I want clients to explicitly pass them. If they want the default behavior, they should create empty options themselves. But if they simply don't provide them, they are likely writing bad code, becuse they will not be respecting client options / something that they will get for free, if only they passed that option to constuctor.
Yes, unlike TokenRequestContext (formarly TokenRequestOptions), the default values in RetryOptions and LogOptions do have better degree of sense, but still I want the parameter to be explicit., so please give me guidance if I should rename types, or update the guidance to have exceptions. Out of all outcomes, I don't want to get worse code for the sake of code uniformity. I want options to always be the parameter; plus, after all, what is the sense of having default value you know you should not be using?

(Split from #1795)

**Comment by ahsonkhan** [comment]
> I don't want LogPolicy and RetryPolicy to have default options in constructor. I want clients to explicitly pass them.

Why?

The default behavior of RetryPolicy makes sense to me. We shouldn't force users to pass something when we can provide a simpler starting point. This follows progressive disclosure. This also matches other languages.
https://github.com/Azure/azure-sdk-for-cpp/blob/fc79c5b3ad69fd2c75eae0cd8f9b3a951fff4a11/sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp#L186-L201
https://github.com/Azure/azure-sdk-for-net/blob/79223575e7693c46165d50f7232fafa77449aee7/sdk/core/Azure.Core/src/RetryOptions.cs#L12

**Comment by Jinming-Hu** [comment]
> I don't want LogPolicy and RetryPolicy to have default options in constructor. I want clients to explicitly pass them.

That would be a very bad user experience, especially for beginners, it makes our sdk less easy to use.

**Comment by antkmsft** [comment]
@ahsonkhan, @Jinming-Hu, this is not about the Options themselves being default-constructible. I agree - they should be default-constructible, and the ClientOptions should have default values for them without requiring the SDK user to specify them - I can't agree more.

But I don't want `std::make_unique<RetryPolicy>()` to compile. I want it to be `std::make_unique<RetryPolicy>(clientOptions.Retry)`, or, for the deliberately default options, `std::make_unique<RetryPolicy>(RetryOptions())`.

**Comment by Jinming-Hu** [comment]
> But I don't want std::make_unique<RetryPolicy>() to compile. I want it to be std::make_unique<RetryPolicy>(clientOptions.Retry), or, for the deliberately default options, std::make_unique<RetryPolicy>(RetryOptions()).

What's the point? Customers won't use `RetryPolicy` anyway.

**Comment by Jinming-Hu** [comment]
You can remove default constructor of `RetryPolicy`. It's fine by me

**Comment by antkmsft** [comment]
I agree with both. But this question is about guidelines. Formally, our guidelines are so that all options rather must be optional, always. I might be violating that by having `RetryPolicy::RetryPolicy(RetryOptions retryOptions)` instead of `RetryPolicy::RetryPolicy(RetryOptions retryOptions = RetryOptions())`, and this what this issue is created for.

**Comment by Jinming-Hu** [comment]
> Formally, our guidelines are so that all options rather must be optional, always.

This doesn't make any sense. I think your proposal here makes a lot of sense that `RetryPolicy` should NOT be default-constructible. I always have the feeling that you guys have been trying to make guidelines cover everything. But the real world is complex, we often need human intervention or to make judgement calls, rather than just to follow some rigid guidelines.

So if you want to fix the guideline, or remove this item from guideline, I support you.
