### ISSUE TITLE
docker pull docker.pkg.github.com/arnab-developer/githubpackagedemo/githubpackagedemo:24

### ISSUE THREAD

**Issue by benzapos** [Azure/azure-sdk-for-cpp#1895]
**Query/Question**
A clear and concise ask/query.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Que[]()```
```
``
```
```ry Added
- [[]() ] Setup information Added

**Comment by benzapos** [comment]
> **Query/Question**
> A clear and concise ask/query.
> 
> ***Why is this not a Bug or a feature Request?***
> A clear explanation of why is this not a bug or a feature request?
> 
> **Setup (please complete the following information if applicable):**
>  - OS: [e.g. iOS]
>  - IDE : [e.g. IntelliJ]
>  - Version of the Library used
>  
>  **Information Checklist**
>  Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
> - [ ] Que[]()```
> ```
> ``
> ```
> ```ry Added
> - [[]() ] Setup information Added
>     

[]()

**Comment by benzapos** [comment]
https://github.com/Azure/azure-sdk-for-cpp/issues/1895

**Comment by ahsonkhan** [comment]
@benzapos I don't understand the purpose of this issue. Please only open issues that are relevant to this repository and avoid spam. As a reminder, here's our code of conduct: https://github.com/Azure/azure-sdk-for-cpp/blob/master/CODE_OF_CONDUCT.md

**Comment by ahsonkhan** [comment]
Closing as spam.
