### ISSUE TITLE
#!/system/bin/sh# If you're implementing this in a custom kernel/firmware,# I suggest you use a different script name, and add a service# to launch it from ...

### ISSUE THREAD

**Issue by benzapos** [Azure/azure-sdk-for-cpp#1896]
Package version 69308909

**Comment by benzapos** [comment]
#!/system/bin/sh

# If you're implementing this in a custom kernel/firmware,
# I suggest you use a different script name, and add a service
# to launch it from init.rc

# Launches SuperSU in daemon mode only on Android 4.3+.
# Nothing will happen on 4.2.x or older, unless SELinux+Enforcing.
# If you want to force loading the daemon, use "--daemon" instead

/system/xbin/daemonsu --auto-daemon &

# Some apps like to run stuff from this script as well, that will 
# obviously break root - in your code, just search this file
# for "install-recovery-2.sh", and if present, write there instead.

/system/etc/install-recovery-2.sh[]()

**Comment by ahsonkhan** [comment]
@benzapos this GitHub repo is for the C++ Azure SDK used to talk to services like Azure Storage.

How is your issue related to this repository? Please make sure to file issues in the right location.

**Comment by benzapos** [comment]
https://docs.google.com/spreadsheets/d/1ougaqFRKHxD_N7TIvJlmnL-BuJeZ7naXSEkutFR34ZI/edit?usp=drivesdk

**Comment by benzapos** [comment]
[]()[]()

**Comment by ahsonkhan** [comment]
Closing as spam.
