### ISSUE TITLE
https://github.com/Azure/azure-sdk-for-cpp/issues/1896

### ISSUE THREAD

**Issue by benzapos** [Azure/azure-sdk-for-cpp#1898]
**Describe the bug**

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by benzapos** [comment]
https://github.com/Azure/azure-sdk-for-cpp/issues/1896

**Comment by benzapos** [comment]
``

**Comment by ahsonkhan** [comment]
Closing as spam.
