### ISSUE TITLE
[datalake] How to copy files in same account and container

### ISSUE THREAD

**Issue by ysriram-adobe** [Azure/azure-sdk-for-cpp#1900]
**Query/Question**
How to copy files in same account and container. Example `datalake_file_client.CopyTo(targetUri)` . 

***Why is this not a Bug or a feature Request?***
I'm assuming that the existing `datalake_file_client.DownloadTo(string &path)` but not sure ?

**Setup (please complete the following information if applicable):**
 - OS: MacBook Pro / MacOS Catalina
 - IDE : VSCode
 - Version of the Library used: azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.8
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by ahsonkhan** [comment]
@Jinming-Hu can you help answer this question. Thanks.

**Comment by Jinming-Hu** [comment]
datalake and blob services are interoperable, so you can use blob client on datalake storage account. Take a look at [StartCopyFromUri](https://github.com/Azure/azure-sdk-for-cpp/blob/009260c50aa8d981594ea67c0e8a00beeb86e8ee/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp#L211)

**Comment by ysriram-adobe** [comment]
Thank you - Does `StartCopyFromUri` involve data transfer from `src -> client -> target` ? also to improve ease of use a `datalake_file_system::Copy(from, to)` would be much appreciated.

**Comment by Jinming-Hu** [comment]
> Does StartCopyFromUri involve data transfer from src -> client -> target

No, storage server performs the copy operation.

**Comment by ysriram-adobe** [comment]
Question answered. Thank you.
