### ISSUE TITLE
Should an exception be thrown on an invalid header or silently ignore it?

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#191]
Should an exception be thrown on an invalid http header or silently ignore it?

_Originally posted by @katmsft in https://github.com/Azure/azure-sdk-for-cpp/diffs_

**Comment by RickWinter** [comment]
@vhvb1989 @JeffreyRichter I expect the http_client to validate the name and value are valid per http spec.  For instance, adding a header with a null or empty name is invalid.  We should throw when we detect headers which are not compliant with http specification.  We should NOT be in the business of determining which headers are legal for a given request.
