### ISSUE TITLE
[Refine] Extract the logic of connection string parsing and move to an abstract class for code reuse.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#192]
This is in Storage SDK.
See comment: https://github.com/Azure/azure-sdk-for-cpp/pull/178#discussion_r442547880

**Comment by JinmingHu-MSFT** [comment]
What the interface would be like?

**Comment by JinmingHu-MSFT** [comment]
https://github.com/Azure/azure-sdk-for-cpp/pull/181/commits/59e83aadc7cff6ee3aef1ad5b285af545d2da87b

**Comment by JinmingHu-MSFT** [comment]
done in https://github.com/Azure/azure-sdk-for-cpp/pull/181
