### ISSUE TITLE
vcpkg release of azure-template-cpp should always open PR as a draft

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#1949]
We've seen testing of the template package release generate extra noise while testing changes to the common engineering system.  This noise is impacting our customers in addition to the vcpkg team ([example](https://github.com/microsoft/vcpkg/pull/16778#discussion_r597364585)). 

Any time we open a PR for an `azure-template-cpp` port that PR should be opened as a draft as we will never need to publish it.

**Comment by ahsonkhan** [comment]
We should also delete the Git release and tag, as part of the release test artifact cleanup.

**Comment by danieljurek** [comment]
This is fixed here: https://github.com/Azure/azure-sdk-for-cpp/pull/1936/files .. The PR is opened as a draft. It's also closed immediately after opening (one can re-open if vcpkg CI is needed) today https://github.com/Azure/azure-sdk-for-cpp/blob/master/eng/pipelines/templates/stages/archetype-cpp-release.yml#L191 

I've opened https://github.com/Azure/azure-sdk-for-cpp/issues/2031 to track adding a job to clean up the tags and releases.
