### ISSUE TITLE
Simplify the public surface area for Response<T> for usability

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1954]
# Context and Problem:
- When customers of the SDK call client library APIs which talk to Azure services that return cloud-hosted resources, their properties, or result of "crud-like" REST operations, they primarily care about two things (in the success path):
  - Did the API call succeed and complete the operation as expected?
  - How can I get the returned result to take further meaningful action on the value returned?
- The Azure services that the SDK talks to on behalf of the customer would continue to evolve and add new features, response headers, or append to the returned body. The SDK needs a version resilient mechanism so that existing applications written against the SDK that do not use the new features would continue to work without needing to react to breaking changes within the SDK. This lead to a `Response<T>` templated type returned by almost all client library APIs which wraps the value the user cares about (created by deserializing meaningful operation-specific information from the response into a model) and the HTTP response returned by the service which exposes all the headers, status code, and body. Most customers wouldn't care about this raw response but it provides an escape hatch to the customer for version resiliency. This notion is a natural part of REST APIs and the HTTP protocol domain. Therefore, the concept of `Response<T>` exists in all the Azure SDK languages, not just C++: https://azure.github.io/azure-sdk/general_design.html#response-formats
- During the SDK usability studies, we observed some customers with limited cloud and REST experience, getting overwhelmed and confused by what they could do with the returned `Response<T>` type. This highlighted a need to simplify the type and to provide more conceptual and sample docs which explain what the user is expected to do. This is a classical example of "less is more". A common feeling expressed by participants: I just want to get the blob properties, and the `Response<T>` complexities get in the way.
  - One participant stumbled to find the `->` operator on `Response<T>`
  - VS IntelliSense doesn't show the returned model type, just `Response<...>`
  - Another question that came up: If `ExtractValue` and `RawResponse` have identical functionality, why not just use Http Response? Does `ExtractValue` has simpler functionality?
  - Verbatim: Usually we apply -> on pointers. Validating feedback like this from @BillyONeal: https://github.com/Azure/azure-sdk-for-cpp/pull/316#discussion_r455443256

![image](https://user-images.githubusercontent.com/6527137/112390682-eb523500-8cb3-11eb-99ad-34e4c98e4258.png)

# Motivation and Goal:
- Reduce concept count along with questions that would come up when customers approach any of the service client APIs, all of which return `Response<T>`.
- Be idiomatic to the language and leverage concepts that C++ developers are already familiar with, following the principle of least surprise.
- Avoid multiple ways of doing the same or very similar things while continuing to enable all existing use cases.

# Design Change:
- Make the `Value` and `RawResponse` fields public that the caller can access directly.
- Do not make `Value` nullable, since it should always exist. This allows us to defer introducing the `Nullable<T>` concept (enabling progressive disclosure) and can remove noisy methods like `HasValue()`.
- Remove the notion of "Get" and "Extract" by leveraging a `unique_ptr` field directly. This minimizes another subtle concept and decision point for the user. Any user wanting to get ownership of either part of `Response<T>` can do so using `std::move`, and that avoids forcing the concept on everyone. For example, we remove questions like the following that the customer might ask: `Which API should I call and what's the difference?`
- Remove the pointer-like convenience APIs (such as `->` and `*`) by deferring their addition to the future, because they don't follow the principle of least surprise. Even though they enable users to write abbreviated code, the nuances of when to use one versus the other are complex, hurt auditability (such as "Find all references"), and conflates the pointer/reference operator semantics to a domain that doesn't necessarily need it. If we see strong evidence that customers understand and benefit from these, we can always add them back in the future, but removing it would be a breaking change.
![image](https://user-images.githubusercontent.com/6527137/112390869-31a79400-8cb4-11eb-8941-e0b8b4805309.png)

## API Design:
```C++
template <class T> class Response {
public:
  T Value;
  std::unique_ptr<Azure::Core::Http::RawResponse> RawResponse;

  // If it was possible in C++, this would be internal only, but having this as a convenience ctor
  // to enable correctness is valuable.
  explicit Response(T value, std::unique_ptr<Azure::Core::Http::RawResponse> rawResponse)
      : Value(std::move(value)), RawResponse(std::move(rawResponse))
  {
  }
};
```
In the future, depending on the need to return "value-less" response types, which are more user-friendly when we are confident there is little chance for the service to return anything meaningful, we'd add `void` specialization since C++ allows it, following precedence in other languages like [Java](https://docs.microsoft.com/en-us/java/api/com.azure.storage.blob.specialized.blobclientbase.deletewithresponse?view=azure-java-stable#returns):
```C++
template <> class Response<void> {
public:
  std::unique_ptr<Azure::Core::Http::RawResponse> RawResponse;
  
  explicit Response(std::unique_ptr<Azure::Core::Http::RawResponse> rawResponse)
      : RawResponse(std::move(rawResponse))
  {
  }
};
```
Here's the list of "empty placeholder structs" in the SDK today, from storage, which _could_ be removed to return `Response<void>` on a case-by-case basis, where we are reasonably confident nothing will be added by the service in the future:
**blob_rest_client.hpp**
- AbortBlobCopyFromUriResult: https://github.com/Azure/azure-sdk-for-cpp/blob/c3a9d67d01f5e75f050048514f80b9826fce76d8/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L38-L40
- SetBlobExpiryResult
- SetBlobTagsResult
- SetServicePropertiesResult
- UndeleteBlobResult

**share_responses.hpp**
- ForceCloseDirectoryHandleResult: https://github.com/Azure/azure-sdk-for-cpp/blob/0d422b95a074d77c95d19c0cd74fc638fc86970d/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp#L70-L72
- ForceCloseFileHandleResult

**share_rest_client.hpp**
- ServiceSetPropertiesResult: https://github.com/Azure/azure-sdk-for-cpp/blob/0d422b95a074d77c95d19c0cd74fc638fc86970d/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/protocol/share_rest_client.hpp#L656-L658
- ShareDeleteResult
- FileDeleteResult
- DirectoryDeleteResult
- FileAbortCopyResult

# Questions:
## Why is status code not exposed directly on `Response<T>` to make it more visible?
- Most customers shouldn't need to concern themselves with the status code in the success path as long as the client libraries handle all the error cases correctly. Quoting @tg-msft who provided valuable insight: Getting a 200 vs. a 201 vs. a 202. vs a 204 shouldn't really matter most of the time, but you've got the raw response if for some reason it really does. `Response<T>` is composed of two main parts: data related to your model representing the resource or operation result from the service (represented by the T) and the stuff related to the HTTP response. Duplicating parts of the response (such as the status code) muddies that a bit and would result in  the user having multiple ways to get to the status code.
- In the error handling and recovery code paths (such as in try/catch exception blocks), it remains critical for the user to access the HTTP status code easily. This can be addressed by increasing the visibility of that on our exception types like `RequestFailedException`: https://github.com/Azure/azure-sdk-for-cpp/issues/1973
## What if there is no `Value` within the `Response<T>`?
- For almost all cases where we return a  `Response<T>` from our client libraries during the success path, the request returns both a `Value` and a response. In cases where the service doesn't return a model type today (when there are no meaningful response headers or body), we either return an empty placeholder struct as the `T` to be resilient to additions in the future OR we return a specialized `Response<void>` which wouldn't contain the `T Value` field. Therefore, when returning a `Response<T>`, the `T` must always exist.
- Like many of the other returned objects, it is not required to set the `Value` or `RawResponse` fields to something defined or meaningful when an exception or error occurs. The user shouldn't be accessing the fields of the `Response<T>` object in such cases anyway.
## Without a method, how can we validate if the user moved the raw response already, if they try again?
- We rely on the C++ developer calling the `Response<T>` APIs to understand C++ primitives and common coding patterns around the lifetime semantics of smart pointers like `std::unique_ptr`. Like any library API returning a `unique_ptr`, if the user accesses the `RawResponse` without moving it or taking ownership, repeated field access will continue to work. It is the caller's responsibility to track ownership if they use `std::move` to extract the `RawResponse` from the `Response<T>` and know not to make multiple field access calls after that.

# Breaking Change Mitigation
- Callers previously calling `Response<T>::GetRawResponse()`, replace it with `Response<T>::RawResponse`
```diff
- for (auto& header : response.GetRawResponse().GetHeaders())
+ for (auto& header : response.RawResponse->GetHeaders())
```
- Callers previously calling `Response<T>::ExtractRawResponse()`, replace it with `std::move(Response<T>::RawResponse)`
```diff
- res.m_rawResponse = response.ExtractRawResponse();
+ res.m_rawResponse = std::move(response.RawResponse);
```
- Callers previously calling `Response<T>::ExtractValue()`, replace it with either `Response<T>::Value` or `std::move(Response<T>::Value)`
```diff
- auto key = responseT.ExtractValue();
+ auto key = responseT.Value;
```
- Previous use of `*` and `->` operator can be replaced by `.Value.`
```diff
- for (auto& i : response->Items)
+ for (auto& i : response.Value.Items)
```
```diff
- auto properties = *m_fileShareServiceClient->GetProperties();
+ auto properties = m_fileShareServiceClient->GetProperties().Value;
```
- There was never a need for callers to use `HasValue()`, so remove that if-block and code path if it exists.

cc @CaseyCarter, @JeffreyRichter, @RickWinter, @vhvb1989, @kyle-patterson, @Jinming-Hu, @vinjiang

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/1974

**Comment by JeffreyRichter** [comment]
Good write-up and I approve of this proposal

**Comment by vhvb1989** [comment]
Question:
- By using the template specialization `Response<void>`, if the server makes a change in the future to return something, wouldn't be easier for the `sdk client` to have the empty placeholder model to just add fields into it? (instead of changing from Response<void> to Response<T>)

**Comment by ahsonkhan** [comment]
> if the server makes a change in the future to return something

This is about trade-offs and a balance between future uncertainty and usability of customers today. If we foresee that future happening for some particular API, it makes sense to use an empty placeholder model.
However, if the likelihood of that is low and we create a bunch of empty models that remain empty, we hurt the overall usability of the SDK due to "death-by-thousand-cuts". How often would the customer try to grab the `T` value from the `Response<T>` to find nothing in it, that they learn the wrong pattern or feel the usability pain?

Life doesn't give guarantees :)

Keep in mind, even when the server makes the change in the future, the customer isn't automatically blocked. Us returning the `RawResponse` acts as the escape hatch for exactly that purpose. The addition must be deemed important enough, in mainline user scenarios, for us to address it. This issue exists today already, especially when the server adds things to the body/header that don't get deserialized into the model being returned.

> wouldn't be easier for the `sdk client` to have the empty placeholder model to just add fields into it? (instead of changing from `Response<void>` to `Response<T>`)

We wouldn't do that as it would be considered a breaking change. If, 9/10 times we made the right call, it is reasonable for us to introduce a new method that returns the `Response<T>` and leave the void-returning one as is. This calculus would be done on a per-API basis following recommendations of the service owners, and expectations from a user, rather than painting everything with a broad brush. Other language SDKs have already made such calls in some places (which include both correct calls in favor of usability, and missteps that weren't yet deemed important enough to add new methods).
