### ISSUE TITLE
Release pipeline update package version failed

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1959]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=797597&view=results

WARNING: Unable to find module repositories.
Value cannot be null.
Parameter name: input
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'powershell-yaml'. Try Get-PSRepository to see all available registered module repositories.
At C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711 char:34
+ … talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.PowerShel…lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
##[error]PowerShell exited with code '1'.

**Comment by ahsonkhan** [comment]
@danieljurek once we have root caused and fixed this issue, can we re-run just the update package version step from that release pipeline to auto-generate the version increment PRs for storage?

**Comment by ahsonkhan** [comment]
Re-running the failed step seems to have succeeded. Looks like it was an intermittent issue:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=797597&view=logs&j=423eb92c-7468-532c-ae4a-c088a3b56da1&t=80f356e6-e64a-5db4-6c37-d9e6814bcd0a

**Comment by danieljurek** [comment]
That job is idempotent and can be re-run when it fails.

**Comment by danieljurek** [comment]
Some more digging into the errors looks like this error message frequently accompanies network failures. It's likely that this is a transient network failure.
