### ISSUE TITLE
CMake doxygen generation should not require installation of Vcpkg dependencies

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#196]
In order for the initial cmake generate step to succeed when building documentation curl must be installed on the machine. 

example error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=431955&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=619d3ee0-51fe-5b36-f7ec-da0e0c5252d8

```
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find CURL (missing: CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindCURL.cmake:169 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:331 (_find_package)
  sdk/core/azure-core/CMakeLists.txt:13 (find_package)

```

This adds several unnecessary minutes to docs generation.

**Comment by danieljurek** [comment]
This is nice to have but vcpkg caching, when implemented, will bring build times down enough that this process won't be as painful for EngSys.

**Comment by kurtzeborn** [comment]
@danieljurek, I think you've already started working on this, so assigning it to you.  If that's not the case, bring it up in standup.
