### ISSUE TITLE
Question: how to switch between curl transport layer and winHTTP transport layer when installing via vcpkg

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1975]

**Comment by vhvb1989** [comment]
By default, on Windows, installing an SDK service (like storage) with VCPKG will make VCPKG to install all available features for the service and its dependencies. Both libcurl and winhttp are package features, and will be installed.
Then, when generating the project with CMake, we need to use the CMake options to build the the transport adapter we want to use. If we don't explicitly add any transport adapter for Generating, the default will be selected based on the OS, so for Windows, it will be WinHttp.
See more info here: https://github.com/Azure/azure-sdk-for-cpp/blob/master/doc/HttpTransportAdapter.md#default-http-transport-adapter

**Comment by vhvb1989** [comment]
@Jinming-Hu if there is still more info that I can share or questions, please let me know, otherwise, please close the issue
