### ISSUE TITLE
SDK should never use abort()

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1986]
abort() does not even unwind the stack or close files. Doesn't even call `atexit()`.
http://www.cplusplus.com/reference/cstdlib/abort/

Our SDK is important, but it is not the center of the universe. There's a plenty of things customer application might want to have a chance to do before take the decision to terminate customer's app (which we don't have a right to).

No library should ever call abort() - it is the only privilege of the end products, such as exe apps. We don't know enough about the importance of a role role of our SDK in the resulting code.

What we need to do is to throw an exception. Maybe it is not recoverable, but still, there's a plenty of useful things that app might want to do.

Imagine having a Photoshop app, and you have a function "Add picture element from Azure". I was working without saving, decided to add an element from Azure, program quit without saving my work.

**Comment by bhardwajs** [comment]
Yes, a library calling `abort()` is not a good situation. Looking at some of the use-cases, such as `BlobLeaseClient::Acquire`, would it be possible to return `std::nullopt` or throw an exception that the caller can handle?

**Comment by antkmsft** [comment]
Unfortunately, we can't do `std::nullopt`, because it is C++17, and we so far don't go beyond C++14 for wider compatibility. But something of that sort would be applicable. Or, again, an exception - either is way better than `abort()`.

**Comment by ahsonkhan** [comment]
@antkmsft what's the plan for this issue? Is this a breaking change, or can it move to May?

**Comment by antkmsft** [comment]
It can be moved to May if necessary. BTW, this issue is not assigned to anyone.

**Comment by RickWinter** [comment]
@vhvb1989 Please review the uses of abort() to ensure they correctly fit as preconditions

**Pre-Conditions**
Pre-Condition errors occur when a caller violates the expectations of a function, for example by passing an out-of-range value or a null pointer. These are always avoidable by the direct caller, and will always require a source code change (by the caller) to fix.

✔️ YOU MAY check preconditions on function entry.

✔️ YOU MAY provide a means to disable precondition checks in release / optimized builds.

✅ DO crash, if possible. This means calling some form of fast failing function, like `abort`.

⛔️ DO NOT throw a C++ exception.
