### ISSUE TITLE
Support for Azure Queue Storage

### ISSUE THREAD

**Issue by ahojnnes** [Azure/azure-sdk-for-cpp#1993]
Support for https://docs.microsoft.com/en-us/rest/api/storageservices/queue-service-rest-api to replace the existing functionality in https://azure.github.io/azure-storage-cpp/

**Comment by amishra-dev** [comment]
Thanks for reaching out Johannes, we have added this to our backlog.

**Comment by RickWinter** [comment]
@vinjiang @kyle-patterson This is required to close the gap between SDKs.

**Comment by Jinming-Hu** [comment]
Milestone: protocol layer done https://github.com/Azure/azure-sdk-for-cpp/pull/2531

**Comment by Jinming-Hu** [comment]
Milestone: production code complete https://github.com/Azure/azure-sdk-for-cpp/pull/2671

**Comment by Jinming-Hu** [comment]
Beta release https://github.com/Azure/azure-sdk-for-cpp/releases/tag/azure-storage-queues_12.0.0-beta.1
