### ISSUE TITLE
[Identity] Add Readme for Identity like the other langs

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2020]
Please add Readme for Identity with description for what's supported and available on C++, just like the one from .Net: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md

The current Readme is too general: https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/identity/azure-identity

**Comment by antkmsft** [comment]
Duplicate of #1950?
