### ISSUE TITLE
Remove SecondaryHostReplicaStatusKey from public header?

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2022]
I don't think the Storage client library needs a key at all. We have a key in the retry policy and we have a static function which the storage policy can call to get the retry count. This internally uses a context key but Storage doesn't need to do anything in regards to this at all; just call the function that returns the retry count.

_Originally posted by @JeffreyRichter in https://github.com/Azure/azure-sdk-for-cpp/pull/1988#discussion_r605842929_

**Comment by vhvb1989** [comment]
Adding @Jinming-Hu  to update the storage code

**Comment by Jinming-Hu** [comment]
@JeffreyRichter Sorry I didn't get it. This key is not for retry count, it's for logging whether the resource(blob) exists on secondary tenant so that we can decide whether or not to switch between primary and secondary host on retry.

We can move this key to .cpp file so that it's not accessible to anybody else. But I don't think I can remove it.

**Comment by JeffreyRichter** [comment]
Sorry then, I misunderstood its purpose; maybe a better name would be good here. 
In this case keep it. 
But, if the blob is not in the secondary, maybe it makes sense to try again on a later retry because it might show up soon? And, in this case, you wouldn't need this key.

**Comment by Jinming-Hu** [comment]
> maybe a better name would be good here.

Okay, it's in internal namespace, so we can change the name anytime.

> But, if the blob is not in the secondary, maybe it makes sense to try again on a later retry because it might show up soon? And, in this case, you wouldn't need this key.

That wouldn't be aligned with other SDK.
