### ISSUE TITLE
Classes and structs: add final

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2030]
I think we should. 

_Originally posted by @antkmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/1988#discussion_r605995855_

**Comment by Jinming-Hu** [comment]
If we can follow [Declaration Order](https://google.github.io/styleguide/cppguide.html#Declaration_Order) of members from Google C++ Style Guide, explicit private won't be a problem anymore.

**Comment by RickWinter** [comment]
@CaseyCarter Is there a general design pattern we should add to guidelines surrounding the use of final?

**Comment by CaseyCarter** [comment]
> @CaseyCarter Is there a general design pattern we should add to guidelines surrounding the use of final?

To me, `final` is a micro-optimization for classes with `virtual` functions. For example, this program fragment (https://godbolt.org/z/ev3Mnea7x):

```c++
struct Base {
  virtual int meow() const = 0;
};

struct Derived final : Base {
  int meow() const override { return 42; }
};

int f(Derived& d) {
    return d.meow();
}
```
the fact that `Derived` is `final` tells the compiler that the argument to `f` must be exactly `Derived` and not some other more-derived type. Consequently, it can inline the call to `meow` - avoiding virtual dispatch. Guidelines naturally lack the level of detail and context necessary to describe when to use micro-optimizations, so it seems to me that developing such a guideline would be a waste of both our time and the time of every future SDK designer who has to explain why the guideline doesn't fit their particular use case.

The remainder of this issue - explicit `private` and exhaustive explicitly-declared special member functions - feels more like a style guideline to me than anything technical. Making implicit things explicit can be useful for those who are less familiar with the defaults, but for the more experienced it's just added noise distracting from the meat of the code. That said, we have other guidelines that feel like style to me - who cares how people name private data members? - so this may be something you all want.
