### ISSUE TITLE
Consider cancelling the context set the deadline value to `now` rather than `min`

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2038]
https://github.com/Azure/azure-sdk-for-cpp/pull/2033#discussion_r607295853

cc @antkmsft

**Comment by antkmsft** [comment]
We can store `system_clock::now()` as cancelation but then the context state should have `bool m_isCanceled`. Currently, all that `Cancel()` does is it sets the deadline to `DateTime::min()`. What I don't want to happen is the context getting resurrected once system clock gets adjusted.

**Comment by antkmsft** [comment]
If we want this, it is better to get this before the GA. It is not very likely, but users may have an expectation that canceled context's `GetDeadline()`  == `DateTime::min()`.

**Comment by ahsonkhan** [comment]
> It is not very likely, but users may have an expectation that canceled context's `GetDeadline()`  == `DateTime::min()`.

I would hope not since that means they are relying on some underlying, undocumented behavior, that we should be allowed to break.

Is that documented anywhere?

> If we want this, it is better to get this before the GA.

Regardless, I agree  :)

**Comment by ahsonkhan** [comment]
> We can store `system_clock::now()` as cancelation but then the context state should have `bool m_isCanceled`. 

Why do we need the bool in the state?

> What I don't want to happen is the context getting resurrected once system clock gets adjusted.

I agree that could be concerning. How would that happen?

**Comment by antkmsft** [comment]
> Why do we need the bool in the state?
So that context does not considered non-canceled after being canceled, after system clock gets adjusted. See below
 
> > What I don't want to happen is the context getting resurrected once system clock gets adjusted.
> I agree that could be concerning. How would that happen?

```
context.Cancel();
context.IsCancelled(); // retrurns true

// move system clock back 1 hour
context.IsCancelled(); // retrurns false
```

**Comment by antkmsft** [comment]
> > It is not very likely, but users may have an expectation that canceled context's `GetDeadline()`  == `DateTime::min()`.
> 
> I would hope not since that means they are relying on some underlying, undocumented behavior, that we should be allowed to break.
> 
> Is that impl detail documented anywhere or exposed to the user?
> 
> > If we want this, it is better to get this before the GA.
> 
> Regardless, I agree :)

Luckily, it is not documented. Only `max()` is:
```
    /**
     * @brief Get a deadline associated with this context or the branch of contexts this context
     * belongs to.
     *
     * @return A deadline associated with the context found; `Azure::DateTime::max()` value if a
     * specific value can't be found.
     */
    DateTime GetDeadline() const;
```

I agree with you, but even if relation between `Cancel()` and `GetDeadline()` is not documented, it is still possible users would have expectations build around that. I amso agree it if we are doing this, it is better to do it before the GA.

**Comment by ahsonkhan** [comment]
@JeffreyRichter should `GetDeadLine()` throw or even abort if the context doesn't have a deadline, rather than returning a potentially incorrect sentinel `Azure::DateTime::max()`?

**Comment by JeffreyRichter** [comment]
There is always a deadline.

- Jeffrey Richter (see Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FRichterCloudApps&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TeBH6rge3q8VyFBwCrBXfSXND4oajfqayGLiZq1gmFo%3D&reserved=0> & Designing HTTP APIs<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9Ng00IlBCtw%26list%3DPL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65%26index%3D1&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nzunz4x55lMRzHb6qJVXuRkrlAAI03wXjPdexaPavzs%3D&reserved=0>)

________________________________

**Comment by RickWinter** [comment]
@ahsonkhan Setting this to min() is a good approach because it guarantees cancellation.  Is there an actual scenario where you want to know when the item was cancelled?  

Note that most other languages that do cancellation only have a boolean.  There is no tracking of when cancelation was triggered.

**Comment by RickWinter** [comment]
Tracking when the cancellation happened is not supported.  We only guarantee that calling cancelled guarantees the context's state is cancelled
