### ISSUE TITLE
Consider marking Context::IsCancelled as `noexcept`.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2039]
https://github.com/Azure/azure-sdk-for-cpp/blob/c5ddbbc430790fb8718dab7df792633c63f33d19/sdk/core/azure-core/inc/azure/core/context.hpp#L221

- Adding `noexcept` in the future is non-breaking, removing it is breaking though.
- Adding `const` is non-breaking, removing it is breaking.

cc @RickWinter

**Comment by Jinming-Hu** [comment]
> Adding noexcept in the future is non-breaking, removing it is breaking though.

This is not that simple. I remember once I got a compiler warning for not adding `noexcept`. But when I added it, I got build error on Visual Studio. It worked fine on GCC or clang. I suspect it was a bug of VC compiler.

We should do thorough test after adding `noexcept` keywords.
