### ISSUE TITLE
Consider removing `Url::AppendQueryParameters` and update storage connection string parsing logic.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2041]
This method is too bespoke and has custom logic that isn't commonly useful in a `Url` class:
https://github.com/Azure/azure-sdk-for-cpp/blob/9c7d4c61e48dc4b76da937c194840dc90b172894/sdk/core/azure-core/inc/azure/core/url.hpp#L186-L192

Currently, this API only has one usage scenario, which is in parsing the connection string, which is storage specific:
https://github.com/Azure/azure-sdk-for-cpp/blob/9c7d4c61e48dc4b76da937c194840dc90b172894/sdk/storage/azure-storage-common/src/storage_credential.cpp#L99-L102

cc @vhvb1989

**Comment by ahsonkhan** [comment]
This connection parser is doing a lot of repetitive work, by first creating the map an d then parsing it repeatedly using `AppendQueryParameters`. This can be simplified and remove the call-sites.

cc @Jinming-Hu

**Comment by Jinming-Hu** [comment]
@ahsonkhan Sure, I'll remove all usages of this API first, then you can remove the API.

**Comment by Jinming-Hu** [comment]
done in https://github.com/Azure/azure-sdk-for-cpp/pull/2050
