### ISSUE TITLE
Change the `StorageError` to derive from `Azure::Core::Http::RequestFailedException` when its ready.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#205]
As title, this will be a top priority after `Azure::Core::Http::RequestFailedException` is ready.

**Comment by vhvb1989** [comment]
Adding RequestFailException here: https://github.com/Azure/azure-sdk-for-cpp/pull/717

**Comment by katmsft** [comment]
Done by @Jinming-Hu  in https://github.com/Azure/azure-sdk-for-cpp/pull/1463/files
