### ISSUE TITLE
Consider using ostringstream, it should be more performance-effective for building strings

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2059]
For example: https://github.com/Azure/azure-sdk-for-cpp/blob/308e5363adaa00ace2f06ff0f1a31747a0a28062/sdk/core/azure-core/src/http/request.cpp#L62-L76

_Originally posted by @antkmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/2056#discussion_r608250965_

**Comment by Jinming-Hu** [comment]
I doubt that. I think string stream is usually slower than string.

Anyway, do some benchmark before making the change in case of any regression.
