### ISSUE TITLE
Feature Request: Progress Handler for upload/download functions

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2065]
We have a customer asking for this feature.

.Net has it: https://github.com/Azure/azure-sdk-for-net/blob/2645a8dd0d817c41fc9c512629a25a5ae678cc96/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L1069

JS also has this feature.

**Comment by Jinming-Hu** [comment]
I'm thinking, maybe this feature is just as simple as two integers, one cosntant integer indicating the total download/upload size, one atomic integer indicating how many bytes has been transferred.

We use atomic so that reading/writing this variable is thread-safe. `std::atomic` even has [wait](https://en.cppreference.com/w/cpp/atomic/atomic/wait) and [notify](https://en.cppreference.com/w/cpp/atomic/atomic/notify_one) mechanism since C++ 20.

But I don't think wait/notify mechanism would be useful for us. I mean, .Net may need it because .Net support async operations. But in C++ all operations are sync.

**Comment by Jinming-Hu** [comment]
+ @JeffreyRichter since it's a design topic
+ @RickWinter for timeline.

**Comment by Jinming-Hu** [comment]
cc @ahsonkhan @vhvb1989 @antkmsft

**Comment by vhvb1989** [comment]
Can we add overload for Download and Upload that returns an Operation<T> ?  
The Operation would be created with a thread to perform the operation (Upload/Download) and to hold the progress counter that the operation (transportAdapter would update as it performs...).. Just an idea here :)

**Comment by Jinming-Hu** [comment]
> Can we add overload for Download and Upload that returns an Operation ?
> The Operation would be created with a thread to perform the operation (Upload/Download) and to hold the progress counter that the operation (transportAdapter would update as it performs...).. Just an idea here :)

I don't know. Overloaded functions sound like a lot of maintenance work. More importantly, it looks to me that you're starting asynchronous pattern. We've made a big decision (actually it's not made by us, it's from leadership team) like a year ago that this sdk will only provide synchronous functions.


We have the pattern that every API (except single-thread download) returns only after the operation is finished. So this progress handler thing cannot be part of return type. Because by the time we get the return type, the operation is finished, the progress is definitely 100%.
I don't think it's a good idea to put it in the API options either. Because all other options are input parameters and can be shared among multiple API calls. This progress handler thing is more like an output parameter and cannot be shared among multiple API calls.

So it cannot be in input parameters, it cannot be in output return types either. This is kind of awkward.

**Comment by Jinming-Hu** [comment]
How about we use the context?

the definition is like

```C++
struct ProgressHandler {
    int64_t TotalBytes;
    std::atomic<int64_t> BytesTransferred;
};
```

it works like

```C++
ProgressHandler progress;
blobClient.Upload(context.WithValue(ProgressKey, &progress));
```

in another thread, users can check the progress

```C++
printf("%d/%d Transferred\n", progress.BytesTransferred, progress.TotalBytes);
```

**Comment by JeffreyRichter** [comment]
I have a design for doing progress reporting. that requires NO overloaded methods.
Can this wait until after GA? I'm trying to design the new Pageable right now and I think you want this to be higher priority.

**Comment by JeffreyRichter** [comment]
Let's start with this:
•	Define ProgressReport callback lambda data type which returns void and takes an int64 bytesTransferred
•	Define ProgressBodyStream class derived from BodyStream
        o	ctor takes BodyStream innerStream (null is not allowed) and ProgressReport lambda (null is not allowed)
        o	Fields: inner BodyStream innerStream, ProgressReport progressReport and bytesTransferred = 0
        o	Rewind calls innerStream's rewind and resets the bytesTransferred field to 0
        o	Read reads calls innerStream's Read and then adds the return count to the bytesTransferred field and then invokes callback passing bytesTransferred.


This provides progress reporting to ALL operations that talk to the service directly. The customer just has to wrap the passed stream with a ProgressBodyStream using the decorator pattern. NOTE: we must document that the number of bytes transferred does NOT always go up.  For example, after 1MB has uploaded, the connection could fail and we rewind the stream to retry the upload. This means that the number of bytes transferred would reset to 0 when starting over - I think this is desired behavior but customers should be aware of it.

Adding progress reporting to the parallel functions builds on top of the above design and has some more tricks to it due to the threading issues. I have a design for this ready to go but let's do the top stuff first and then we can build on it.

**Comment by Jinming-Hu** [comment]
> Adding progress reporting to the parallel functions builds on top of the above design and has some more tricks to it due to the threading issues. I have a design for this ready to go but let's do the top stuff first and then we can build on it.

I believe you design can work very well for single-thread operations (operation with `BodyStream` as input or output). I'd love to know how it works for concurrent operations before we start writing code.

**Comment by JeffreyRichter** [comment]
Well, OK; here's the design I fleshed out for parallel operations:

For parallel upload/download:
•	Add a ProgressReport field to UploadToBlockBlobOptions
•	If dataSize <= BlockBlobMaxUploadBlobBytes
o	Before calling a 1:1 client function, wrap the BodyStream with a ProgressBodyStream (if ProgressReport is not null)
•	Else
o	Stack based totalBytesTransfered = 0 (int64-not atomic) & progressLock mutex
o	if o.Progress != nil {
   blockProgress := int64(0)           // 1 per block (captured)
   body = ProgressBodyStream(innerStream, lambda)

   lambda = func(bytesTransferred int64) {
   diff := bytesTransferred – blockProgress             // How many MORE bytes transferred for this block
   blockProgress = bytesTransferred                          // Update this block’s bytes transferred so far
   progressLock.Lock()                                                  // 1 thread at a time gets a progress report
   totalBytesTransfered += diff                                   // atomic update of the global bytes transferred
   o.Progress(totalBytesTransfered)                          // Invoke the progress lambda
   progressLock.Unlock()                                              // Let another thread invoke the lambda
}

•

**Comment by Jinming-Hu** [comment]
@JeffreyRichter If we are to use callback in API options, why not also do the same for single-thread functions? This way, we will have uniform API interface.

I have some concern about this callback method. Our customers can define their the callback function. It's not a problem if they just do something very simple in this function.
But they are also capable of doing something more complex in this callback function. Now they are prone to a performance bottleneck, because the callback is called with a mutex.

**Comment by JeffreyRichter** [comment]
The API is already not uniform. Put block takes a stream while upload from file takes a path. But, even if you take the callback, you still have to know when to call it and the ProgressBodyStream enables this. Furthermore, the decorator pattern is very powerful. For put block, it takes a linked list of BodyStream objects which the user constructs so they can create a file stream, then a progress stream, then a compression stream, etc. The order matters and if the SDK API just took the progress callback then it has to go at the head of the linked list.

I agree that the callback calls into customer code which could not be fast. Do you have a counter proposal? If you don't take the lock around the callback, then multiple threads invoke the callback simultaneously and there are race conditions making the bytes transferred number jump up and down. I don't have a better alternative but I'm open to suggestions.

- Jeffrey Richter (see Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FRichterCloudApps&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TeBH6rge3q8VyFBwCrBXfSXND4oajfqayGLiZq1gmFo%3D&reserved=0> & Designing HTTP APIs<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9Ng00IlBCtw%26list%3DPL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65%26index%3D1&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nzunz4x55lMRzHb6qJVXuRkrlAAI03wXjPdexaPavzs%3D&reserved=0>)

________________________________

**Comment by Jinming-Hu** [comment]
> Put block takes a stream while upload from file takes a path. But, even if you take the callback, you still have to know when to call it and the ProgressBodyStream enables this.

On a second thought, I don't think adding callback in options is a good idea at all. Because options are sent to server side while callback is not. This is the motivation of moving context out of options two months ago. (Refer to the email titled _One more try to have Context be a formal method parameter_ you sent on Feb. 7 2021)
