### ISSUE TITLE
[Datalake] Unable to open/read file created via create/append/flush methods

### ISSUE THREAD

**Issue by ysriram-adobe** [Azure/azure-sdk-for-cpp#2078]
**Describe the bug**
Seeing `404 The specified blob does not exist` when trying to open/read file created via create/append/flush methods of sdk. Happens all the for files created via client using c++ SDK.

***Exception or Stack Trace***
`404 The specified blob does not exist`

**To Reproduce**
- Create/Append/Flush file in some directory
- Open or GetProperties of same file and error is produced

***Code Snippet***
`fs_client->GetFileClient(path).GetProperties()`
where
- fs_client is `DataLakeFileSystemClient` constructed via `url: https://name.blob.core.windows.net/container` and credentials
- `path` is relative path to parquet file

**Expected behavior**
Must not throw `404` but return the properties of the file. 

**Screenshots**

**Setup (please complete the following information):**
- OS: MacBook Pro / MacOS Catalina
- IDE : VSCode
- Version of the Library used: azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.8

**Additional context**
- Able to read files not created by spark client using sdk
- Able to download same file via java/azure/datalake sdk and also verified that it is valid parquet (so don't think the writer is issue)
- Checked permission `666`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ahsonkhan** [comment]
@Jinming-Hu please take a look

@ysriram-adobe can you provide a minimal reproducible sample (sanitized to exclude any connection strings or secrets), which includes more code snippet than just the one line. It will help root cause the issue, especially if there is something else in how you created the blob in the first place.

**Comment by ysriram-adobe** [comment]
@ahsonkhan - thanks for response. Working on exactly the ask you have. Note that I'm able to open/read/download the same file via the java/sdk.

**Comment by ysriram-adobe** [comment]
Hope this helps.
```      
      auto path = "relative/path/7_test.parquet";
      auto adls_uri = "https://name.dfs.core.windows.net/container/";
      auto creds = std::make_shared<ClientSecretCredential>("tenant",
                                                            "client_id",
                                                            "client_key";
      auto fs_client = std::make_shared<DataLakeFileSystemClient>(adls_uri, creds);
      auto file_client = fs_client->GetFileClient(path);
      auto create_result = file_client.Create();
      if(create_result->Created){
        std::string str = "Helo";
        std::vector<uint8_t> buffer(str.begin(), str.end());
        auto bufferStream = Azure::Core::Http::MemoryBodyStream(buffer);
        file_client.Append(&bufferStream, 0);
        file_client.Flush(str.size());
        std::cout << "created file " << file_client.GetUrl() << std::endl;

        //throws Azure::Storage::StorageException: 404 The specified blob does not exist.
        auto file_client2 = fs_client->GetFileClient(path);
        auto props = file_client2.GetProperties();
      }
      std::cout << "ok" << std::endl;
```

**Comment by Jinming-Hu** [comment]
Hi @ysriram-adobe , can you try the latest beta9 release? Your code snippet works for me with beta 9 release.

**Comment by ahsonkhan** [comment]
@Jinming-Hu could you reproduce the issue with beta.8? If so, do you know what change ended up fixing it?

**Comment by ysriram-adobe** [comment]
> Hi @ysriram-adobe , can you try the latest beta9 release? Your code snippet works for me with beta 9 release.

@Jinming-Hu - Thank you for taking look at it. The beta.9 release worked. I would be interested in knowing if it was reproduced in beta.9 .

@ahsonkhan Thank you for follow-up.

**Comment by Jinming-Hu** [comment]
@ysriram-adobe  still works for me with beta.8 release.

**Comment by ysriram-adobe** [comment]
🤷 closing ticket.
