### ISSUE TITLE
Update VCPKG Control file to manifest

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2085]
See: https://github.com/microsoft/vcpkg/pull/17143

**Comment by vhvb1989** [comment]
@antkmsft  @RickWinter  The VCPKG team is asking us to use manifest instead of CONTROL file.  It would be better to update all ports together instead of only updating the new ones. 
@danieljurek mostly we will need to update the release scripts for using manifest file

**Comment by ahsonkhan** [comment]
Either we need to get an exception for keyvault from the vcpkg team, or we need to make this change sooner rather than later. Moving it to May milestone rather than backlog since it is required to ship.

**Comment by antkmsft** [comment]
To clarify, this is not required, they just recommend it. We still should do it.

**Comment by antkmsft** [comment]
Was done in https://github.com/Azure/azure-sdk-for-cpp/pull/2132
