### ISSUE TITLE
Operation<T> should take a context const& but it takes context& - possible breaking change

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2091]
Poll and PollUntilDone takes a ref context instead of a const reference.
These methods don't need to take the context as a mutable reference because no changes are expected to the context.  Also, the current signature is preventing an SDK client operation to use a const reference to invoke Poll(context).

We can add overloads with const& to avoid a breaking change, but keeping the mutable reference might not make sense.

Note also that GetApplicationContext() is returning a non-const reference, which should not be the case.

**Comment by vhvb1989** [comment]
@RickWinter please review and comment how should we fix this:
- Adding overloads with const& context 
- Updating the current signatures `breaking change`

**Comment by ahsonkhan** [comment]
From the API review discussion: Adding `const` is non-breaking, removing it is breaking.

So, if we know that it needs to be marked as const, we can do so without worrying about adding overloads.
