### ISSUE TITLE
Curl connections to the wrong port may be used from the pool

### ISSUE THREAD

**Issue by johnwheffner** [Azure/azure-sdk-for-cpp#2097]
When issuing requests against multiple instances of Azurite running locally on different ports, requests sometimes go to the wrong server.  This is because the curl connection pool is keyed on hostname (plus SSL config) but not port.

**Comment by ahsonkhan** [comment]
@vhvb1989 we should use more parts of the endpoint Url to generate the key that we know are unique and remain stable. I don't know but that might even include the path, not just the port. @johnwheffner what do you think?

Probably the only thing that shouldn't be used is query parameters.

https://github.com/Azure/azure-sdk-for-cpp/blob/5de76e7a2168259bccd0a6c1f61b7aca802dbf2e/sdk/core/azure-core/src/http/curl/curl.cpp#L1116-L1152

**Comment by vhvb1989** [comment]
@ahsonkhan using the path would disable connection re-use to the same server and leave it as `only if it is the same request`.
I will add the port. Makes sense

**Comment by johnwheffner** [comment]
:+1:
