### ISSUE TITLE
Change the title of vcpkg PR created by CI

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2100]
https://github.com/microsoft/vcpkg/pull/17142#issuecomment-815566333

**Comment by Jinming-Hu** [comment]
Also, is it possible to create the PR as draft?

**Comment by ahsonkhan** [comment]
> Also, is it possible to create the PR as draft?

It is possible, but why would we want to do that?

**Comment by ahsonkhan** [comment]
> Change the title of vcpkg PR created by CI

The PR title is defined by the person triggering the release pipeline by setting the `VcpkgPRTitle` build variable.

We can set the "correct" name at that time. I am not sure what the best default fallback value should be when that variable isn't set. It is currently: `<Port Name> publish version <Version>`
https://github.com/Azure/azure-sdk-for-cpp/blob/5a99f38df17c8961b01bc6c79af194ed44a52840/eng/pipelines/templates/stages/archetype-cpp-release.yml#L117-L123
