### ISSUE TITLE
Make libxml2 -> libxml2-dev in the documentation

### ISSUE THREAD

**Issue by salsal97** [Azure/azure-sdk-for-cpp#2103]
**Describe the bug**
The documentation everywhere in the repo describes a dependency on libxml2, but it really seems to depend on the specific package libdml2-dev

***Exception or Stack Trace***
```
By default, if no option is selected, on Unix, CURL transport adapter is used.
CMake Error at /usr/local/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/FindLibXml2.cmake:91 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  sdk/storage/azure-storage-common/CMakeLists.txt:30 (find_package)
```

**To Reproduce**
Run `cmake build -DCMAKE_BUILD_TYPE=Debug` in your root directory

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] ubuntu 
 - IDE : [e.g. IntelliJ] VS Code 
 - Version of the Library used

**Additional context**
The fix would be to install libxml2-dev using `sudo apt-get install libxml2-dev`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
`libxml2-dev` is on debian (ubuntu). Packages have different name pattern on different platforms, like on RedHat, it's called `libxml2-devel`.
