### ISSUE TITLE
The vcpkg portfile.cmake should be updated to avoid using deprecated functions

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2107]
For example, update usages of `vcpkg_configure_cmake`this for all the portfiles:
https://github.com/Azure/azure-sdk-for-cpp/blob/cf071db26a16180d3ba091b62212349c877554b5/sdk/core/azure-core/vcpkg/portfile.cmake#L18-L24

For the deprecated function, can you update it as the new function `vcpkg_cmake_configure()` automatically?
Please see the reference here https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md

Other related functions are also deprecated, such as `vcpkg_install_cmake`， `vcpkg_fixup_cmake_targets()`.

We prefer to use the new functions in new ports.

_Originally posted by @NancyLi1013 in https://github.com/microsoft/vcpkg/pull/17143#discussion_r610297882_

cc @antkmsft

**Comment by RickWinter** [comment]
@ahsonkhan @antkmsft Is this an issue after moving to manifests?  If so fix, otherwise it can be closed as part of the manifest migration work.

**Comment by ahsonkhan** [comment]
>  Is this an issue after moving to manifests?

Yes, it still is. The manifest json file is migrating from CONTROL to json which is unrelated to this.

This issue is about the portfile.cmake which is a different vcpkg package definition component.

**Comment by ahsonkhan** [comment]
Here's a reference to the vcpkg PR checklist:
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/pr-review-checklist.md#c000001

> c000001: No deprecated helper functions are used
