### ISSUE TITLE
Uuid is not unique on Linux

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2115]
Tests have failed on linux:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=841074&view=logs&jobId=fda9a6e2-14f0-5864-d894-5f56622f20fa&j=fda9a6e2-14f0-5864-d894-5f56622f20fa&t=4d31d3ea-4e03-5255-0249-577ed0f8d090

https://dev.azure.com/azure-sdk/public/_build/results?buildId=834364&view=logs&jobId=fda9a6e2-14f0-5864-d894-5f56622f20fa&j=fda9a6e2-14f0-5864-d894-5f56622f20fa&t=4d31d3ea-4e03-5255-0249-577ed0f8d090&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c

**Comment by ahsonkhan** [comment]
We should investigate this further for the May milestone. @RickWinter - labelling it higher priority to help with the triaging.

**Comment by ahsonkhan** [comment]
Failed again here, from an unrelated PR: https://github.com/Azure/azure-sdk-for-cpp/pull/2132
https://dev.azure.com/azure-sdk/public/_build/results?buildId=848076&view=logs&j=fda9a6e2-14f0-5864-d894-5f56622f20fa&t=1c480a24-f5ee-59f2-3e43-433898827192
