### ISSUE TITLE
Move Pageable base class to core sdk

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2118]
and add docs

**Comment by Jinming-Hu** [comment]
Core sdk team should decide what to do if `MoveToNextPage` is called with `HasNextPage` being `false`.

**Comment by ahsonkhan** [comment]
@vhvb1989 please copy the `PagedResponse<T>` type into keyvault and try it out in some of its pageable APIs to validate the type works for your scenarios.

We'd want to do that before finalizing the design and moving it down to core.

https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-common/inc/azure/storage/common/paged_response.hpp#L14-L20

**Comment by ahsonkhan** [comment]
We also need to add targeted unit tests for `PagedResponse<T>`.
