### ISSUE TITLE
As a client library author releasing a first beta of a particular package, there needs to be a validation process and explicit approval of the package name chosen before releasing for the first time

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2126]
Similar to how the other primary languages have GA-gate on an explicit API review approval and to guard against breaking changes, any time a service is shipping its first beta package (for example, we are about to ship `azure-security-keyvault-common-cpp` and `azure-security-keyvault-keys-cpp`), there needs to be an explicit review and approval gate prior to a release to ensure the name is one we reviewed, agreed upon, and like.

**The detection could be:** A package with this name doesn't exist in the vcpkg package registry, and therefore it is a new package being introduced. Someone from a particular `<C++ reviewer alias>` needs to approve it before the release continues. 

For the client library author/owner, or the person triggering the first release, it is helpful to have tooling remind them of this requirement for review/approval rather than it being a manual, ad-hoc process (since that step might unintentionally go under the radar).

We want to avoid having to rename or delete packages once they are published to the vcpkg package registry. Though possible, the vcpkg team strongly discourages that since the old name becomes unusable.

Some of the package name factors to consider:
- Uniqueness
- SEO friendly
- How it compares to track 1 SDKs and other languages that have already shipped
- Is casing (i.e. kebab-case) applied correctly? Do we have terms like core or common in the name or is it too verbose?

cc @danieljurek

**Comment by kurtzeborn** [comment]
We did this.  Forgot to close the issue.
