### ISSUE TITLE
Instead of using friend classes, add client accepting ctors to PagedResponse-derived types.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2152]
Avoid unnecessarily using friend classes or forward declarations. Instead, all PagedResponse-derived types should have the necessary public ctor to create it from a client. This ensure single responsibility, and separation of concerns, and avoids having external classes setting private fields.

For example:
https://github.com/Azure/azure-sdk-for-cpp/blob/698e9965c56c47cf16d9350956e8d752031e5fe5/sdk/storage/azure-storage-blobs/src/blob_service_client.cpp#L137-L140

Follow-up from:
https://github.com/Azure/azure-sdk-for-cpp/pull/2116#discussion_r613322193
https://github.com/Azure/azure-sdk-for-cpp/pull/2116#discussion_r613225349
https://github.com/Azure/azure-sdk-for-cpp/pull/2116#discussion_r614429790

cc @JeffreyRichter, @Jinming-Hu

**Comment by Jinming-Hu** [comment]
This is not what https://github.com/Azure/azure-sdk-for-cpp/pull/2116#discussion_r613322193 is about.

**Comment by Jinming-Hu** [comment]
Personally I don't want to add such a constructor for PagedResponse-derived class. Because the ctor would only be used in one place, so it doesn't save many lines of code.

In addition, the ctor will have to be public, and it would mislead our customers into thinking they could call this constructor and construct a PagedResponse by themselves (rather than by calling List functions). But this is not what they're supposed to do and we don't guarantee it will always work.

**Comment by JeffreyRichter** [comment]
How about a compromise: add the ctor to the Pageable-derived class but make the ctor private. Then make the client a friend so it can call the ctor.
What's nice about this is that any fields added/modified to the pageable class will naturally require a change to the ctor which will cause compilation errors until the friends are fixed. But, the ctor is still not callable by customer code.

**Comment by Jinming-Hu** [comment]
> How about a compromise: add the ctor to the Pageable-derived class but make the ctor private. Then make the client a friend so it can call the ctor.
> What's nice about this is that any fields added/modified to the pageable class will naturally require a change to the ctor which will cause compilation errors until the friends are fixed. But, the ctor is still not callable by customer code.

Yeah, I'm okay with that.

It just doesn't resolve @ahsonkhan 's concern of `friend` classes.

**Comment by vhvb1989** [comment]
For KeyVault PagedResults, I basically did what @JeffreyRichter  is suggesting here with friend class:
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/list_keys_single_page_result.hpp#L33

I like this pattern and I think we should make it part of our guidelines.

**Comment by ahsonkhan** [comment]
> What's nice about this is that any fields added/modified to the pageable class will naturally require a change to the ctor which will cause compilation errors until the friends are fixed. 

+1

> It just doesn't resolve @ahsonkhan 's concern of `friend` classes.

It's a good step in the right direction, so if that's all we want to do today, for GA, I'll take it :)

Using friend class as a workaround, just because C++ doesn't have the concept of `internal`, introduces an implementation maintenance burden and I see this tight coupling to be problematic. We are introducing brittleness (and things like forward declaration to types in other packages) complicating the logic. When you come back to this code after some time, you'll have a hard time reasoning about it (I know I will). I really don't think adding a simple ctor that takes a client and options on `PagedResponse`-derived classes is much of a concern, because customers wouldn't be looking at that type as the entry point anyway. We always return the type from client APIs, which are the entry point, and callers use it.
