### ISSUE TITLE
Now that you have pageable all the `..SinglePage` apis should be removed.  SinglePage was only necessary before Pageable was available.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2155]
Now that you have pageable all the `..SinglePage` apis should be removed.  SinglePage was only necessary before Pageable was available.

_Originally posted by @RickWinter in https://github.com/Azure/azure-sdk-for-cpp/pull/2144#discussion_r620450386_

**Comment by RickWinter** [comment]
This needs to be done before GA.  It can happen in May release if time allows.
