### ISSUE TITLE
VCPKG breaks CI Fail

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2167]
Creating issue as I keep seeing this error once in a while, so, start tracking

Last occurence:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=866560&view=logs&j=32afe1f3-cae1-5682-187c-9a515535777f&t=eb790175-775e-5b46-331b-d42a59e01ffd

```
ApplicationInsightsTelemetrySender correlated 3 events with X-TFS-Session 4ce574e5-0478-46b5-bb42-e0ed966f3329
##[error]Chunks are not arriving in order or sizes are not matched up.
ERROR: Data Error : .\toolsrc\include\vcpkg\configurationdeserializer.h
--
Path = 
Type = tar
Code Page = UTF-8


Sub items Errors: 1

Archives with Errors: 1

Sub items Errors: 1
Finishing: Vcpkg Cache
```

**Comment by vhvb1989** [comment]
one more here:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=898687&view=logs&j=fda9a6e2-14f0-5864-d894-5f56622f20fa&t=64440416-7562-566c-4f50-84609d66d260

**Comment by vhvb1989** [comment]
One more time:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=924377&view=results

**Comment by vhvb1989** [comment]
One more:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=924517&view=results

**Comment by vhvb1989** [comment]
One more (in the Release pipeline :(  )
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=927627&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=70e13c24-1688-50ce-17e7-be375e71fa16

**Comment by davidcorrigan714** [comment]
@vhvb1989 We're seeing this same error message on the Cache task in our companies Azure DevOps instance. Have any insights on what's throwing the error or what might be causing it?

**Comment by vhvb1989** [comment]
@davidcorrigan714, I believed @danieljurek made a deeper analysis and classified the different issues.  @danieljurek  can you share your findings?

**Comment by vhvb1989** [comment]
One more:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1079660&view=logs&j=efb8e22a-57a5-5d01-2d97-95ae9b6a04dd&t=39c132e6-0088-5a0d-41cf-073a1cc4259f

**Comment by danieljurek** [comment]
This should no longer be an issue given we're not using the cache task for vcpkg anymore.
