### ISSUE TITLE
Create HTTP Body read strategy for unknown size

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#218]
Current implementation only supports HTTP Responses with Content-Length or Chunked response.

If response does not contain any of those, the stream Read operation should try to read until the connection is closed

**Comment by RickWinter** [comment]
@vhvb1989 please update comment linking to the PR and close

**Comment by vhvb1989** [comment]
PR: https://github.com/Azure/azure-sdk-for-cpp/pull/273
