### ISSUE TITLE
Rest Client needs to be updated for how it reads a Response Stream

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#219]
The current implementation in the Rest layer is expecting `Response->BodyStream->Read(buffer, size)` to fill the `buffer` up to `size`. And assumes that using a buffer as big as `Response->BodyStream->Length()` will require only one read() to have the entire body content in the buffer.

However the assumption is wrong. Since the BodyBuffer could be performing I/O, it could return less bytes than requested.
The implementation needs to loop until the Read operation returns 0.

Only the MemoryStramBody working on contiguous memory could warranty that one Read() operation could return the entire content.

So, the code that is implemented in Rest Client needs to be updated from
```cpp
        auto bodyStream = http_response.GetBodyStream();
        std::vector<uint8_t> bodyContent(static_cast<std::size_t>(bodyStream->Length()));
        bodyStream->Read(&bodyContent[0], bodyContent.size());
```  

to something like:

```cpp
        auto bodyStream = http_response.GetBodyStream();
        auto bodyContent = std::vector<uint8_t>();
        // Read 1k at at time or maybe 64k.  This can be changed
        {
          constexpr uint64_t fixedSize = 1024;
          uint8_t tempBuffer[fixedSize];
          auto readBytes = uint64_t();
          do
          {
            readBytes = bodyStream->Read(tempBuffer, fixedSize);
            bodyContent.insert(bodyContent.end(), tempBuffer, tempBuffer + readBytes);
          } while (readBytes != 0);
        }
```

or
```cpp
  std::vector<uint8_t> ReadBodyStream(std::unique_ptr<Azure::Core::Http::BodyStream>& stream)
  {
    auto s = stream->Length();
    std::vector<uint8_t> body(s, '\x00');
    // Read 64k at at time 8 388 608
    {
      constexpr uint64_t fixedSize = 1024 * 64;
      uint8_t tempBuffer[fixedSize];
      auto readBytes = uint64_t();
      auto offset = uint64_t();
      do
      {
        readBytes = stream->Read(tempBuffer, fixedSize);
        for (uint64_t index = 0; index != readBytes; index++)
        {
          body[offset + index] = tempBuffer[index];
        }
        offset += readBytes;
      } while (readBytes != 0);
    }

    return body;
  }

```

This issue is making storage CI tests:
2: [  FAILED  ] 5 tests, listed below:
2: [  FAILED  ] BlobServiceClientTest.ListContainers
2: [  FAILED  ] BlobContainerClientTest.ListBlobsFlat
2: [  FAILED  ] BlobContainerClientTest.ListBlobsHierarchy
2: [  FAILED  ] BlockBlobClientTest.StageBlock
2: [  FAILED  ] PageBlobClientTest.UploadClear

Because the Stream is not properly read to a buffer.
Functions to be fixed:
```cpp
static ListContainersSegment ListBlobContainersParseResponse(
          Azure::Core::Http::Response& http_response)

static UserDelegationKey GetUserDelegationKeyParseResponse(
          Azure::Core::Http::Response& http_response)

static BlobsFlatSegment ListBlobsParseResponse(
         Azure::Core::Http::Response& http_response)

static BlobBlockListInfo GetBlockListParseResponse(
        Azure::Core::Http::Response& http_response)

static PageRangesInfoInternal GetPageRangesParseResponse(
          Azure::Core::Http::Response& http_response)

```

**Comment by JinmingHu-MSFT** [comment]
@vhvb1989 A question suddenly came to my mind, what `CurlBodyStream::Length()` will return if it's a chunked HTTP response?

We may need to make clear the semantics of `BodyStream::Length` and `BodyStream::Read`.

**Comment by vhvb1989** [comment]
@JinmingHu-MSFT CurlBodyStream would return 0 for length when size is unknown.
BodyStream uses uint64_t for the length, so the option of returning -1 is not really an option.

This was one of the reasons I changed how the bodyStream is used on the protocol layer.  We can't always know the size of the body content to just make one read from the stream as:
```cpp
auto size = bodyStream.Length();
bodyStream.Read(buffer, size);
```
Because we might be dealing with a chunked or unknown body content size, we need to just keep pulling data from stream until it returns 0. At that point, only at that point we would know the size of the body content length.

@JeffreyRichter  @RickWinter  I would like to talk about this in out meeting.  I wonder if we can add `IsKnownSize()` to BodyStream contract?

**Comment by JinmingHu-MSFT** [comment]
> CurlBodyStream would return 0 for length when size is unknown.
> BodyStream uses uint64_t for the length, so the option of returning -1 is not really an option.

What if the body size is actually 0? How can our users differentiate these two situations?

**Comment by vhvb1989** [comment]
> > CurlBodyStream would return 0 for length when size is unknown.
> > BodyStream uses uint64_t for the length, so the option of returning -1 is not really an option.
> 
> What if the body size is actually 0? How can our users differentiate these two situations?

yeah, I've talked about this with Jeff. We will change utint64 to int64 and return -1 for unknown size.

**Comment by JinmingHu-MSFT** [comment]
Storage code all updated.
