### ISSUE TITLE
Add size baselines and gates to prevent growth

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#2192]
Size and speed are very important to C++ developers.  

- [ ] Add infrastructure to track sdk size on per package level
- [ ] Add gates to catch package size growth

**Comment by danieljurek** [comment]
When measuring the binary size with map files in C we had to create programs which use parts of the SDK. Parsing map files (whose formats differ between compilers) is domain-specific and should be owned by the language team. 

Do we want to measure the size of the produced static library file or do we want to measure the size of the library when incorporated into a program?
