### ISSUE TITLE
Open file handles should be in a holder at the point of initialization. 

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2199]
The handle should be in a holder at the point of initialization.  That way we don't need to setup a try/catch in this method.

_Originally posted by @RickWinter in https://github.com/Azure/azure-sdk-for-cpp/pull/2188#discussion_r626842699_

Previous discussion on the topic, where @JeffreyRichter recommended against using the holder pattern, since it was adding some machinery for not a lot of benefit: https://github.com/Azure/azure-sdk-for-cpp/pull/1830#discussion_r591891880

This commit shows an example of a FileHandleHolder:
https://github.com/Azure/azure-sdk-for-cpp/pull/1830/commits/9e3ec3a8cd838ec28566e8cede452cac9de7933a

See https://github.com/Azure/azure-sdk-for-cpp/blob/10d244e511dc62a527885c3d4eec09e5e267136e/sdk/core/azure-core/src/io/body_stream.cpp#L88-L126

**Comment by JeffreyRichter** [comment]
I think having the try/catch is better than having the holder because we know the file will be closed immediately and not when the holder gets destructed.
