### ISSUE TITLE
Figure out a way to keep spell check CI failures to 0 by either raising warning visibility or turning them into an error

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2222]
Follow up from https://github.com/Azure/azure-sdk-for-cpp/issues/1277#issuecomment-833959091

After the eng/common spelling errors have been fixed (outside this repo), we should figure out a way to keep the spell check errors from regressing. How do we remain "green" within the SDK? This PR fixed all the true errors: https://github.com/Azure/azure-sdk-for-cpp/pull/2209

**Comment by danieljurek** [comment]
An issue in `cspell` prevents this from closing. The issue is being addressed in https://github.com/Azure/azure-sdk-tools/pull/1946
