### ISSUE TITLE
Consolidate use of size_t vs int32_t in public surface area

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2226]
Are our guidelines correct that we are allowed to use `size_t` in public surface area or should we always use `int32_t`?https://azure.github.io/azure-sdk/cpp_implementation.html#integer-sizes

We use `size_t` in some places (for example Hash), but most other places use `int32_t` (for example BodyStream).

https://github.com/Azure/azure-sdk-for-cpp/blob/1a71c46cbd5fd7f54365ab8cd74e812b6f63a391/sdk/core/azure-core/inc/azure/core/cryptography/hash.hpp#L61
https://github.com/Azure/azure-sdk-for-cpp/blob/1a71c46cbd5fd7f54365ab8cd74e812b6f63a391/sdk/core/azure-core/inc/azure/core/io/body_stream.hpp#L98-L101

**Comment by ahsonkhan** [comment]
The guideline also recommends use of `int64_t` everywhere else, and not `int32_t`.

cc @BillyONeal as well since you helped us initially write these.

**Comment by Jinming-Hu** [comment]
C++ Working Group Meeting Notes 6/10

```
Topic: Choice of integer types
Conclusion:
File length are int64_t  (signed)
Array indexes should be size_t or ptrdiff_t (unsigned)
Numbers passed into or returned by client that are transmitted/received over the wire should be signed (int64_t, or if it's completely safe int32_t)
If client library returns some calculated number that is not going through or coming from the wire then the client should use whatever is appropriate
```

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/2285

Will open separate issues for the storage FileWriter change and private header/implementation fix-ups.
https://github.com/Azure/azure-sdk-for-cpp/issues/2315
https://github.com/Azure/azure-sdk-for-cpp/issues/2316
