### ISSUE TITLE
Verify there are no public APIs within azure core that are not used today and remove

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2227]
We found some unused methods via code inspection that we removed or hid:
https://github.com/Azure/azure-sdk-for-cpp/pull/2212
https://github.com/Azure/azure-sdk-for-cpp/pull/1998

From a quick glance (and previous API reviews), most of the other public APIs are used and intended to be visible. We may want a more structured, repeatable approach to increase our confidence.

**Comment by ahsonkhan** [comment]
@CaseyCarter, @BillyONeal do you know of any analysis tools we can use that can identify unused/unreferenced functions (i.e. APIs that are only used by unit tests)?

**Comment by BillyONeal** [comment]
I am unfamiliar with such tools; it's not clear what "reference" even means in the case of an SDK since there's no real difference between an API not otherwise used by your SDK but intended for your customers to use vs. an API that you have internally.
