### ISSUE TITLE
If a PR touches several files (100+), the spell check leg succeeds, incorrectly.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2228]
From https://github.com/Azure/azure-sdk-for-cpp/pull/2209#issuecomment-833889740

@danieljurek the spell checking CI leg doesn't work when we have a lot of files changed. It fails with `The command line is too long.`:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=879540&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=ccad100f-2904-5913-2083-c525ad929a03

```text
Starting: Check spelling (cspell)
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.180.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
Formatted command: . 'D:\a\_work\1\s\eng\common\scripts\check-spelling-in-changed-files.ps1' -TargetBranch "origin/$("master" -replace "refs/heads/")" -SourceBranch HEAD -CspellConfigPath ./.vscode/cspell.json
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_work\_temp\13887517-c5ce-4eab-b69e-ab169ca42783.ps1'"
git diff --diff-filter=d --name-only origin/master HEAD
Git Detected 364 changed file(s). Files checked by cspell may exclude files according to cspell.json
npx cspell --config ./.vscode/cspell.json D:\a\_work\1\s\samples\integration\cmake-fetch-content\src\main.cpp D:\a\_work\1\s\sdk\core\azure-core\inc\azure\core.hpp D:\a\_work\1\s\sdk\core\azure-core\inc\azure\core\base64.hpp D:\a\_work\1\s\sdk\core\azure-core\inc\azure\core\case_insensitive_containers.hpp 
...
D:\a\_work\1\s\sdk\template\azure-template\inc\azure\template\template_client.hpp D:\a\_work\1\s\sdk\template\azure-template\src\private\package_version.hpp D:\a\_work\1\s\sdk\template\azure-template\src\template_client.cpp D:\a\_work\1\s\sdk\template\azure-template\test\ut\macro_guard.cpp D:\a\_work\1\s\sdk\template\azure-template\test\ut\template_test.cpp
The command line is too long.
Finishing: Check spelling (cspell)
```

Looks like powershell has a max limit of 8191 characters.
https://docs.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation

cc @weshaggard - this probably impacts other repos too.

**Comment by weshaggard** [comment]
@danieljurek can we generate a cspell config file that lists these files and wraps the input config file?

**Comment by danieljurek** [comment]
Unfortunately not in this case. The cspell config supports exclusion lists. Cspell itself supports input from stdin but only in the form of raw text to check (not a list of files). The only way to supply file names to it is with command line parameters. This leaves a few options: 

1. npx is a `.cmd` file and the [upper limit for `cmd` command line is 8191 characters](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation). It might be possible to call node.exe (and npx) through PowerShell without having to go through `.cmd`... this could relieve us of the constraint of the upper limit of `cmd` length
2. Use a different shell (e.g. bash) which does not have these constraints (this has the drawback of involving another shell when trying to replicate the engineering system's procedures locally, as in a dev's inner loop) 
3. Divide up the list of files into segments whose overall command line length would be below the constraint, run cspell against each of these segments, and output the results
