### ISSUE TITLE
Add "x-ms-request-id" into logging default allow headers

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2240]
https://github.com/Azure/azure-sdk-for-cpp/blob/11d3a3f2863d1c2e647d307cea7c8d854ca9b68e/sdk/core/azure-core/src/http/log_policy.cpp#L132

**Comment by ahsonkhan** [comment]
@antkmsft can you please make sure this matches what other language SDKs do.

**Comment by Jinming-Hu** [comment]
`x-ms-request-id` is the most critical information to find server log for a client request. Our customers have to provide this information when they open a support ticket. It doesn't make any sense to redact this header from logging.

**Comment by ahsonkhan** [comment]
It sounds like we should enable this before GA then. Also seems relatively straightforward to do. @Jinming-Hu can you add a test for this please in storage?
