### ISSUE TITLE
let body out of the options and as an extra argument for Constructing the Request, just like is it now an extra arg for some other functions.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#225]
I would let body out of the options and as an extra argument for Constructing the Request, just like is it now an extra arg for some other functions.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/214_

**Comment by JinmingHu-MSFT** [comment]
Done for Storage Blobs service.

@katmsft will update Storage DataLake Service.

**Comment by katmsft** [comment]
Done for DataLake Service.
