### ISSUE TITLE
Both Azure Core SDK and Azure Storage SDK are supposed to be portable. So we cannot assume that on every platforms with all kinds of hardware configuration, the stack size is at least 16KB.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#226]
Both Azure Core SDK and Azure Storage SDK are supposed to be portable. So we cannot assume that on every platforms with all kinds of hardware configuration, the stack size is at least 16KB.

_Originally posted by @JinmingHu-MSFT in https://github.com/Azure/azure-sdk-for-cpp/pull/214_

**Comment by JinmingHu-MSFT** [comment]
(Change assignee)

This is in storage ut code, so it should be handled by storage team.

**Comment by JinmingHu-MSFT** [comment]
fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/213
