### ISSUE TITLE
Doxygen includes `{C++}` when including code snippets from .MD files.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2273]
Doxygen includes `{C++}` when including code snippets from .MD files. It should not be there.

See https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-core/1.0.0-beta.8/index.html (search the page for "{C++}").

**Comment by vhvb1989** [comment]
fixed by: https://github.com/Azure/azure-sdk-for-cpp/pull/2264/files#diff-b8dc45bc6fad5f70e59b49cda551e56ae6668c49fa0fd026c09b74537b9abed1R29
