### ISSUE TITLE
Some namespaces inside Storage include files do not align with directory structure

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2278]
For example, `/protocol/*.hpp`, `/*_sas_builder.hpp`. Some files (example:  `datalake_constants.hpp`, `datalake_utilities.hpp`) have only `_detail` namespace, but they don't live in `internal` directory.

**Comment by ahsonkhan** [comment]
cc @Jinming-Hu 

@antkmsft is any of the issues you listed related to public headers? If so, the move needs to happen before GA because it would be a breaking change otherwise.

**Comment by Jinming-Hu** [comment]
I noticed there's an `internal` directory and a `private` directory in core sdk. What's the difference? Should storage sdk put internal headers in `internal` or `private`?

**Comment by ahsonkhan** [comment]
Internal headers are for things meant for client libraries only, but not end customers, including things in the `_internal` namespace. We cannot make breaking changes to these.

Private headers usually are within the src directory, and are only private to the package, including things in the `_detail` namespace. No one outside the package should use it. We can make breaking changes to these.

**Comment by antkmsft** [comment]
PR #2381 may not be sufficient to close this work item.

It does move headers to internal, which is great, but, for example,
* A file that has `namespace Azure { namespace Storage { namespace Sas {` is located in `azure/storage/files/shares/` and not `azure/storage/sas/`.
* A file that has `namespace Azure { namespace Storage { namespace Files { namespace Shares { namespace Models {` lives in `azure/storage/files/shares/protocol/` and not `azure/storage/files/shares/models/`.

**Comment by Jinming-Hu** [comment]
> PR #2381 may not be sufficient to close this work item.
> 
> It does move headers to internal, which is great, but, for example,
> 
> * A file that has `namespace Azure { namespace Storage { namespace Sas {` is located in `azure/storage/files/shares/` and not `azure/storage/sas/`.
> * A file that has `namespace Azure { namespace Storage { namespace Files { namespace Shares { namespace Models {` lives in `azure/storage/files/shares/protocol/` and not `azure/storage/files/shares/models/`.

But we never established the rule that directory hierarchy has to be 1:1 mapping of namespace. What if one header file contains two namespaces?

**Comment by antkmsft** [comment]
I don't think we have cases where a file with multiple namespaces so far.
I am not against it, and we probably don't have a guideline for that. I just think if it will be discoverable for the SDK users, and directory-namespace mapping makes sense in that aspect. I think we follow it everywhere except here (an except `internal` directory), without any written rule. I'd say put the file where the users will be expecting it/searching for it. So if a file has 95% of stuff for namespace A, and only secondary stuff for namespace B, put it under `a/`. Or maybe split into two headers and include one from another if they are inter-connected.
So far I also can see the `namespace Models`/directory `protocol/` clear 1:1 mismatch, I think it is probably a clearer decision than `sas/`.
We could've discussed in the meeting, but we may not have enough time before the GA.
I'd say you are the Captain of the Storage ship, you make the call.
If this is not fixed before GA, close this work item, no much sense to keep it open, because we will never fix it after we ship, because it will be a breaking change.

**Comment by Jinming-Hu** [comment]
All right, I still don't want a rigid rule of directory being 1:1 mapping of namespace. But I agree a `sas/` subdirectory will help customers find the right header file more easily (when they only want to generate sas token while don't want to include `blobs.hpp` which has all blobs stuff). I'll create a PR to add `sas/` subdir. But other than this, everything we currently have looks good to me.

**Comment by Jinming-Hu** [comment]
I'll just close this one
