### ISSUE TITLE
`RequestFailedException` cannot be propagated across thread on Windows due to a defect of MSVC

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2281]
ref https://stackoverflow.com/questions/31766940/weird-behavior-with-exceptions-thrown-from-stdasync-in-msvc-2015

`RequestFailedException` is non-copiable and this causes a bug on Windows which blocks storage scenario of concurrent upload & download.

Proposed Fix:

1. Make the copy constructor of `RawResponse` private, as nobody else is supposed to call this method.
2. Make `RequestFailedException` friend class of `RawResponse`
3. Define a copy constructor for `RequestFailedException`, which makes a copy of unique pointer of raw response and everything else.

We can minimize impact to our customers via the method above. It also gives us a lot of flexibility because if in the future we decide to do something different, we don't have to make any breaking changes.

**Comment by vhvb1989** [comment]
It is fine to copy `RequestFailedException` ,  We just need to add the copy ctor.

There's no need to make the rawResponse private, as a rawResponse will never be returned to customers containing a bodyStream.

**Comment by Jinming-Hu** [comment]
> There's no need to make the rawResponse private, as a rawResponse will never be returned to customers containing a bodyStream.

I tend to make the copy constructor of raw response private, as I said, nobody is supposed to call that function.

If you insist, can we make a compromise by asserting the body is nullptr in the copy constructor?

**Comment by vhvb1989** [comment]
> the body is nullptr in the copy constructor?

Sure.  That's fine.

The fact that a rawResponse will never contain a bodyStream when the server's response comes with status code out of the success range (200's) is guaranteed by the transport policy in Core.  

Only if you, as a service, ever decide to manually create your pipeline and use your own transport policy, and manage to convince the arch board to use it, you would then need to worry.

**Comment by Jinming-Hu** [comment]
> The fact that a rawResponse will never contain a bodyStream when the server's response comes with status code out of the success range (200's) is guaranteed by the transport policy in Core.

Yeah, I totally get it. I just want to do something people call it defensive programming or to be future-proof, in case after years of evolvement, raw response and transport policy may have been dramatically changed and the fact that raw response never contains bodystream won't be true anymore. The assertion can help future developers find such an issue.
