### ISSUE TITLE
Based on guidelines, avoid using `int` within public header files, such as `Concurrency` within share_options

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2284]
Follow up from https://github.com/Azure/azure-sdk-for-cpp/pull/2276

We have the guideline to avoid it.
https://azure.github.io/azure-sdk/cpp_implementation.html#integer-sizes

![image](https://user-images.githubusercontent.com/6527137/118341184-00d52580-b4d3-11eb-8e96-937cb5899c92.png)

Going from int to int32_t isn't typically considered breaking, but we still want to make this happen before GA.

For example:
https://github.com/Azure/azure-sdk-for-cpp/blob/e4a18b5eb3b556fae7bde96c43444f27f2fcbdb8/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp#L638-L642

And:
https://github.com/Azure/azure-sdk-for-cpp/blob/e4a18b5eb3b556fae7bde96c43444f27f2fcbdb8/sdk/storage/azure-storage-blobs/src/private/package_version.hpp#L26-L32

We want to reduce use of `int` in source//cpp files as well, but that isn't critical for GA. Fixing the header files is more of a priority.

cc @Jinming-Hu

**Comment by Jinming-Hu** [comment]
This is a kind of controversial guideline. I think using `int` for concurrency and version is just fine.

I might be able to accpet using `int32_t` for version to keep alignment.

**Comment by ahsonkhan** [comment]
The guidelines haven't changed on this topic for quite a long time, the issue is primarily about making sure the source code is following it.

Do you want to discuss making an exception for these 1-2 specific fields? If so, care to provide a justification or reason, why it should be that way for these cases?

**Comment by Jinming-Hu** [comment]
All right, fine. It's not a big deal. totally not worth it. I'll just remove `int`s.
