### ISSUE TITLE
Avoid using unsigned ints in public surface area of the SDK - unix time should be signed

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2287]
https://github.com/Azure/azure-sdk-for-cpp/blob/e4a18b5eb3b556fae7bde96c43444f27f2fcbdb8/sdk/keyvault/azure-security-keyvault-common/inc/azure/keyvault/common/internal/unix_time_helper.hpp#L29

cc @vhvb1989

**Comment by vhvb1989** [comment]
unixTime comes and goes through the wire

**Comment by ahsonkhan** [comment]
And that dictates it be unsigned? How  come?

To be clear, the recommendation is to change this to int64_t.

Unix timestamp can be negative:
https://en.wikipedia.org/wiki/Unix_time#Encoding_time_as_a_number
> The Unix time number is zero at the Unix epoch, and increases by exactly 86400 per day since the epoch. Thus 2004-09-16T00:00:00Z, 12677 days after the epoch, is represented by the Unix time number 12677 × 86400 = 1095292800. This can be extended backwards from the epoch too, using negative numbers; thus 1957-10-04T00:00:00Z, 4472 days before the epoch, is represented by the Unix time number −4472 × 86400 = −386380800. This applies within days as well; the time number at any given time of a day is the number of seconds that has passed since the midnight starting that day added to the time number of that midnight.

https://www.nexcess.net/web-tools/unix-timestamp-converter/
> Many Linux systems store Unix time dates as a signed 32-bit integer.

Not being signed introduces the Jan 2038 problem.
