### ISSUE TITLE
Libcurl transport layer issue under high concurrency data transfer

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2289]
After running for a while, I keep getting `Failed to get a new connection for [host], couldn't resolve host name`, and the ingress and egress drop to zero.

![image](https://user-images.githubusercontent.com/52266153/118582794-8ce29800-b7c6-11eb-84b4-f4a71dcca7a1.png)

reproduce code

```C++
// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

#include <curl/curl.h>
#undef min
#undef max

#include <algorithm>
#include <atomic>
#include <chrono>
#include <iostream>
#include <mutex>
#include <random>
#include <thread>

#include <azure/core/http/curl_transport.hpp>
#include <azure/storage/blobs.hpp>

#include "samples_common.hpp"

SAMPLE(BlobsGettingStarted, BlobsGettingStarted)
void BlobsGettingStarted()
{
  curl_global_init(CURL_GLOBAL_ALL);

  using namespace Azure::Storage::Blobs;

  const std::string containerName = "sample-container";
  BlobClientOptions options;
  options.Transport.Transport = std::make_shared<Azure::Core::Http::CurlTransport>();
  auto containerClient = BlobContainerClient::CreateFromConnectionString(
      GetConnectionString(), containerName, options);
  containerClient.CreateIfNotExists();

  const std::string blobNamePrefix = "sample-blob-";

  std::vector<std::size_t> blobSizes;
  for (int i = 0; i < 100; ++i)
  {
    blobSizes.emplace_back(10);
    blobSizes.emplace_back(100);
    blobSizes.emplace_back(1024);
    blobSizes.emplace_back(8 * 1024);
    blobSizes.emplace_back(10 * 1024);
    blobSizes.emplace_back(12 * 1024);
    blobSizes.emplace_back(16 * 1024);
    blobSizes.emplace_back(32 * 1024);
    blobSizes.emplace_back(64 * 1024);
    blobSizes.emplace_back(128 * 1024);
  }
  for (int i = 0; i < 5; ++i)
  {
    blobSizes.emplace_back(2 * 1024 * 1024);
  }

  std::string blobContent;
  blobContent.resize(*std::max_element(blobSizes.begin(), blobSizes.end()));
  for (std::size_t i = 0; i < blobContent.size(); ++i)
    blobContent[i] = char(i + 0x123);

  auto upload_blob_func = [&](int i, int concurrency, bool init = false) {
    const std::string blobName = blobNamePrefix + std::to_string(i) + (init ? "" : "d");
    auto blobClient = containerClient.GetBlockBlobClient(blobName);
    const std::size_t blobSize = blobSizes[i];
    if (init)
    {
      try
      {
        if (static_cast<std::size_t>(blobClient.GetProperties().Value.BlobSize) == blobSize)
        {
          return;
        }
      }
      catch (Azure::Storage::StorageException&)
      {
      }
    }
    UploadBlockBlobFromOptions options;
    options.TransferOptions.SingleUploadThreshold = 1024;
    options.TransferOptions.Concurrency = concurrency;
    blobClient.UploadFrom(reinterpret_cast<const uint8_t*>(blobContent.data()), blobSize, options);
  };

  // init
  for (int i = 0; i < blobSizes.size(); ++i)
  {
    upload_blob_func(i, 16, true);
  }

  auto download_blob_func = [&](int i, int concurrency) {
    const std::string blobName = blobNamePrefix + std::to_string(i);
    auto blobClient = containerClient.GetBlockBlobClient(blobName);
    auto blobProperties = blobClient.GetProperties();
    const std::size_t blobSize = blobProperties.Value.BlobSize;
    std::string downloadBuffer;
    downloadBuffer.resize(blobSize);
    DownloadBlobToOptions options;
    options.TransferOptions.InitialChunkSize = 1024;
    options.TransferOptions.Concurrency = concurrency;
    blobClient.DownloadTo(
        reinterpret_cast<uint8_t*>(&downloadBuffer[0]), downloadBuffer.size(), options);
  };

  std::atomic<int> concurrency = 1;

  auto changeConcurrencyThreadHandle = std::thread([&concurrency]() {
    std::mt19937 eg(std::random_device{}());
    int currentConcurrency = 1;
    while (true)
    {
      int newConcurrency = std::uniform_int_distribution<int>(1, 512)(eg);
      concurrency.fetch_add(newConcurrency - currentConcurrency, std::memory_order_relaxed);
      currentConcurrency = newConcurrency;
      std::cout << "Change concurrency to " + std::to_string(currentConcurrency) + "\n"
                << std::flush;
      std::this_thread::sleep_for(std::chrono::minutes(10));
    }
  });

  auto taskSchedulerThreadHandle = std::thread([&]() {
    std::mt19937 eg(std::random_device{}());

    struct WorkerContext
    {
      std::atomic<std::time_t> startTime = 0;
      std::atomic<std::time_t> endTime = 0;
      std::thread threadHandle;
    };
    std::list<std::shared_ptr<WorkerContext>> workerContexts;
    while (true)
    {
      int c = std::uniform_int_distribution<int>(1, 16)(eg);
      int oldConcurrency = concurrency.fetch_sub(c, std::memory_order_relaxed);
      if (oldConcurrency < c)
      {
        // give back some
        concurrency.fetch_add(c - std::max(oldConcurrency, 0), std::memory_order_relaxed);
        c = std::max(oldConcurrency, 0);
      }
      if (c > 0)
      {
        int rd = std::uniform_int_distribution<int>(1, 100)(eg);
        int blobId = std::uniform_int_distribution<int>(0, int(blobSizes.size() - 1))(eg);
        std::function<void()> func;
        if (rd < 50)
        {
          func = [upload_blob_func, blobId, c, &concurrency]() {
            upload_blob_func(blobId, c);
          };
        }
        else
        {
          func = [download_blob_func, blobId, c, &concurrency]() {
            download_blob_func(blobId, c); 
          };
        }

        workerContexts.emplace_back(std::make_shared<WorkerContext>());
        auto context = workerContexts.back();
        context->threadHandle = std::thread([context, func, c, &concurrency]() {
          context->startTime.store(std::time(0), std::memory_order_release);
          try
          {
            func();
          }
          catch (Azure::Storage::StorageException& e)
          {
            std::cout << e.ErrorCode << " " << e.ErrorCode << std::endl;
          }
          catch (std::exception& e)
          {
            std::cout << e.what() << std::endl;
          }
          context->endTime.store(std::time(0), std::memory_order_release);
          concurrency.fetch_add(c, std::memory_order_relaxed);
        });
      }
      if (concurrency.load(std::memory_order_relaxed) > 0)
      {
        continue;
      }
      for (auto ite = workerContexts.begin(); ite != workerContexts.end();)
      {
        std::time_t startTime = (*ite)->startTime.load(std::memory_order_acquire);
        std::time_t endTime = (*ite)->endTime.load(std::memory_order_acquire);
        if (endTime != 0)
        {
          // means task finished
          (*ite)->threadHandle.join();
          ite = workerContexts.erase(ite);
        }
        else if (startTime != 0)
        {
          std::time_t delta = std::time(0) - startTime;
          if (delta > 1800)
          {
            std::cout << "task's been running for " + std::to_string(delta) + " seconds\n"
                      << std::flush;
          }
          ++ite;
        }
      }
      static std::time_t lastPrintTime = 0;
      std::time_t currentTime = time(0);
      if (currentTime - lastPrintTime > 60)
      {
        std::cout << "queue_size: " + std::to_string(workerContexts.size()) + "\n" << std::flush;
        lastPrintTime = currentTime;
      }
      std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
  });

  // run forever
  taskSchedulerThreadHandle.join();
  changeConcurrencyThreadHandle.join();
}
```

**Comment by Jinming-Hu** [comment]
This issue also exists on Linux, but with a different symptom.

```bash
$ ./azure-storage-sample BlobsGettingStarted
Change concurrency to 594
queue_size: 71
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)
```

**Comment by Jinming-Hu** [comment]
If the transport layer cannot handle too many concurrent connections, it should accept as many as connections as possible. Blocking all data transfer like on Windows or throwing `std::system_error` on Linux don't look like correct behavior.

**Comment by Jinming-Hu** [comment]
@vhvb1989

**Comment by vhvb1989** [comment]
Hey @Jinming-Hu , some questions:

- Can you mention the system details from where you are running?

- Can you describe what the code is doing in a brief?  For what I can tell, it starts 1005 threads just as part of the initializing. Each thread will then spawn 16 threads if the upload size is greater than 1024bytes (which are 705 items). So, the application is requesting to open ~705 000 connections in parallel.  Is that correct?   If yes, this type of application doesn't look right for one single computer. I would expect a cluster to take care of this kind of jobs.  

- Supposing we managed to get pass the initialize phase, then, the application is creating random numbers to choose the concurrency to create a new thread to either Download or Upload base on a 50% - 50% probability.  I don't fully understand if there is some way to control the max threads in the system at any given time or if it will just keep growing forever based on that randomization. Can you explain this part?

- What is what you are expecting to happen?  The SDK does not contain a request-scheduler, all request are directly sent to the OS as soon as they arrive.  If we would want the SDK to create a queue to keep eventually dispatching requests, we might want to talk about it.

- Is the track1 SDK supporting this?  What does it do?  

- Did you give a try using winHttp here?  

In general, I consider this a bad application design and I would like to understand the general problem (if this is a customer- common-scenario) to help recommending some other approaches (like a work balancer, or an operation-scheduler) which would provide all the benefits of a well known design-pattern-solution.

**Comment by Jinming-Hu** [comment]
> Hey @Jinming-Hu , some questions:
> 
> * Can you mention the system details from where you are running?

I tried on DS4 and DS14, and I can reproduce in both environment. So I assume it's not specific to any VM size.

> * Can you describe what the code is doing in a brief?  For what I can tell, it starts 1005 threads just as part of the initializing. Each thread will then spawn 16 threads if the upload size is greater than 1024bytes (which are 705 items). So, the application is requesting to open ~705 000 connections in parallel.  Is that correct?   If yes, this type of application doesn't look right for one single computer. I would expect a cluster to take care of this kind of jobs.

It creates 1000 blobs for test, in sequence, not in parallel. So the concurrency for initialization is just 16.

> * Supposing we managed to get pass the initialize phase, then, the application is creating random numbers to choose the concurrency to create a new thread to either Download or Upload base on a 50% - 50% probability.  I don't fully understand if there is some way to control the max threads in the system at any given time or if it will just keep growing forever based on that randomization. Can you explain this part?

The overall concurrency is controlled by atomic variable `concurrency`.

> * What is what you are expecting to happen?  The SDK does not contain a request-scheduler, all request are directly sent to the OS as soon as they arrive.  If we would want the SDK to create a queue to keep eventually dispatching requests, we might want to talk about it.
> * Is the track1 SDK supporting this?  What does it do?
> * Did you give a try using winHttp here?
> 
> In general, I consider this a bad application design and I would like to understand the general problem (if this is a customer- common-scenario) to help recommending some other approaches (like a work balancer, or an operation-scheduler) which would provide all the benefits of a well known design-pattern-solution.

All right. I get it.
Can you at lease help us understand why the application will crash on Linux when concurrency is high?
Do you think this is by-design behavior?

**Comment by vhvb1989** [comment]
You might want to try this:
https://ma.ttias.be/linux-increase-ip_local_port_range-tcp-port-range/#:~:text=%24%20sysctl%20net.ipv4.ip_local_port_range%20net.ipv4.ip_local_port_range%20%3D%2032768%2061000%20The,heavy%20traffic%20servers%20can%20easily%20reach%20this%20limit.

or 

https://access.redhat.com/solutions/41776

I am not Network expert, but from a quick re-search, I see that there could be a Max number of sockets in TIME_WAIT state allowed in the system for security reasons. 

You might want to look for Windows/Linux Network experts for more details about it.  If you do, please share any cool finding.

**Comment by vhvb1989** [comment]
For now, I will remove the blocking release and bug tags and remove the issue for the May release.  Let me know if you think we should still block on this otherwise.

**Comment by Jinming-Hu** [comment]
> You might want to try this:
> https://ma.ttias.be/linux-increase-ip_local_port_range-tcp-port-range/#:~:text=%24%20sysctl%20net.ipv4.ip_local_port_range%20net.ipv4.ip_local_port_range%20%3D%2032768%2061000%20The,heavy%20traffic%20servers%20can%20easily%20reach%20this%20limit.
> 
> or
> 
> https://access.redhat.com/solutions/41776
> 
> I am not Network expert, but from a quick re-search, I see that there could be a Max number of sockets in TIME_WAIT state allowed in the system for security reasons.
> 
> You might want to look for Windows/Linux Network experts for more details about it. If you do, please share any cool finding.

That doesn't make any sense. Connections are reused, so if the concurrency is 500. The number of connections is also ~500

**Comment by Jinming-Hu** [comment]
> For now, I will remove the blocking release and bug tags and remove the issue for the May release. Let me know if you think we should still block on this otherwise.

Fine, we also agree this is not GA-blocking. From storage team's experience of performing perf-test, usually we can get 30~40Gbps with 32~64 threads. So we agree ~500 concurrency is not a common scenario.

**Comment by Jinming-Hu** [comment]
BTW WinHttp transport layer doesn't have this problem.

**Comment by vhvb1989** [comment]
> BTW WinHttp transport layer doesn't have this problem.

I see.  This means that winHttp might have a queue to hold requests until resources are available from the OS.  I can try to design/implement something for the libcurl transport adapter for after GA.  I will check with Rick for planning/priority

**Comment by Jinming-Hu** [comment]
@vhvb1989 I think we need first to confirm it's a scheduling issue or queue issue of libcurl, before we make any changes.
