### ISSUE TITLE
Discussion: What's the correct way of waiting for multiple `std::future`s

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2292]
What's the correct way of waiting for multiple `std::future`s given each of them may have an exception thrown.

```C++
std::vector<std::future<void>> fts;
for (int i = 0; i < 3; ++i)
  fts.emplace_back(std::async(std::launch::async, some_func));
for (int i = 0; i < 3; ++I)
  fts[i].get()
```

Above is basically how storage code is doing it. But I feel it's problematic. If the first future has an exception, `.get()` will throw and unwind stack. `fts` then will be destructed. But according to the [API reference of ~future()](https://en.cppreference.com/w/cpp/thread/future/~future), the destructor will block. What will happen now if the other futures also throw exceptions?

@CaseyCarter @BillyONeal

**Comment by BillyONeal** [comment]
> What's the correct way of waiting for multiple `std::future`s given each of them may have an exception thrown.

There is no amazing way to handle that. The concurrency TS might have provided a solution but as far as I know nobody actually implements that.

> If the first future has an exception, .get() will throw and unwind stack.

Right, if multiple exceptions are possible you have to catch them all by wrapping the get() calls with a try/catch and doing something yourself.

> What will happen now if the other futures also throw exceptions?

Nothing, they're gone.

**Comment by Jinming-Hu** [comment]
> > What will happen now if the other futures also throw exceptions?

> Nothing, they're gone.

So those exceptions are just silently ignored, and won't crash the application, is that correct?

**Comment by BillyONeal** [comment]
I believe that is the intent but that functionality is certainly an area with extremely wide variation between implementations. I think expecting this block to ever happen is a recipe for deadlock and you probably want to collect / rethrow the exceptions instead or choose another error handling strategy for the result, or implement the exception transport yourself (with std::current_exception) rather than trying to rely on std::future.

**Comment by Jinming-Hu** [comment]
> I believe that is the intent but that functionality is certainly an area with extremely wide variation between implementations. I think expecting this block to ever happen is a recipe for deadlock and you probably want to collect / rethrow the exceptions instead or choose another error handling strategy for the result, or implement the exception transport yourself (with std::current_exception) rather than trying to rely on std::future.

This sounds like of complicated. I think I'll just wait until we get issues reported from customers.

Thanks @BillyONeal !
