### ISSUE TITLE
Review places where models and options use int32_t and consider changing them to int64_t.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2301]
Some exceptions are expected, but we seem to have quite a few places that use `int32_t` which might be better as `int64_t` for future proofing.

@JeffreyRichter can you please help review the usages.

https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp#L185
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L982
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L2785
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_responses.hpp#L730
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp#L353
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/protocol/share_rest_client.hpp#L699-L704

This one is interesting because other places use int64_t for this, so we should be consistent:
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L1318

cc @JeffreyRichter, @Jinming-Hu

**Comment by Jinming-Hu** [comment]
@JeffreyRichter Do you have any opinion on whether we should use `int32_t` or `int64_t` for above variables? I'm fine either way, although I believe none of those variables will exceed maximum of 32 bit integers.

**Comment by JeffreyRichter** [comment]
32-bit integers is fine for all of these

- Jeffrey Richter (see Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FRichterCloudApps&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TeBH6rge3q8VyFBwCrBXfSXND4oajfqayGLiZq1gmFo%3D&reserved=0> & Designing HTTP APIs<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9Ng00IlBCtw%26list%3DPL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65%26index%3D1&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nzunz4x55lMRzHb6qJVXuRkrlAAI03wXjPdexaPavzs%3D&reserved=0>)

________________________________

**Comment by ahsonkhan** [comment]
I didn't list them all, what about Timeout?

https://github.com/Azure/azure-sdk-for-cpp/blob/75d17550f26c05086cc429fac0bb96a34bd40009/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L2782

Are we sure things like `NumberOfSuccessfulFiles` are OK to be int32_t?

**Comment by ahsonkhan** [comment]
We should at least be consistent, right?

We use `int64_t` for CommittedBlockCount in 3/4 places.
https://github.com/Azure/azure-sdk-for-cpp/blob/75d17550f26c05086cc429fac0bb96a34bd40009/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L939
https://github.com/Azure/azure-sdk-for-cpp/blob/75d17550f26c05086cc429fac0bb96a34bd40009/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L1123
https://github.com/Azure/azure-sdk-for-cpp/blob/75d17550f26c05086cc429fac0bb96a34bd40009/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L1167

https://github.com/Azure/azure-sdk-for-cpp/blob/75d17550f26c05086cc429fac0bb96a34bd40009/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L1318

On an unrelated note, was it intentional that some of them are nullable and others are non-nullable?

**Comment by Jinming-Hu** [comment]
> 32-bit integers is fine for all of these

Yeah, I totally agree. I'll keep them as is.

**Comment by Jinming-Hu** [comment]
@ahsonkhan timeout is in seconds. `3^31` is almost 68 years. A timeout value that long doesn't make any sense.

Number of files is also unlikely to exceed `3^31`.

**Comment by Jinming-Hu** [comment]
> We should at least be consistent, right?

That's right. I'll change `int64_t` to `int32_t`.

**Comment by ahsonkhan** [comment]
It's up to you, but I thought the default stance was to use int64_t unless there is a good reason for it not to be.

> That's right. I'll change `int64_t` to `int32_t`.

Why not change one to `int64_t` instead?

**Comment by Jinming-Hu** [comment]
>> That's right. I'll change int64_t to int32_t.

> Why not change one to int64_t instead?

The maximum value for block count is only 50000 now.

**Comment by ahsonkhan** [comment]
> The maximum value for block count is only 50000 now.

Gotcha. Makes sense then. Thanks!
