### ISSUE TITLE
Make sure file names are consistently encoded as UTF-8 across all platforms, consistently

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2303]
There is a logical difference between windows store apps and others, `CreateFile` is not using the right encoding:
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-common/src/file_io.cpp#L37-L54

Consider using approaches like the one from winhttp:
https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp#L43

cc @Jinming-Hu, @JeffreyRichter 

@BillyONeal can you please share the docs that mention the  default is CP_ACP, because I could only find reference docs CreateFileA and W, but not CreateFile.

Add tests as well with custom encoded texts as filenames, similar to these (include invalid encoding and mismatched surrogates):
https://github.com/Azure/azure-sdk-for-cpp/blob/898a8aee84607bffe6116d5a08d7065608137aa5/sdk/core/azure-core/test/ut/transport_adapter_base.cpp#L447

**Comment by BillyONeal** [comment]
@BillyONeal can you please share the docs that mention the default is CP_ACP, because I could only find reference docs CreateFileA and W, but not CreateFile.

There is no "CreateFile" API. That's a macro that expands to CreateFileA or CreateFileW depending on whether you have UNICODE defined. (This pattern is the same for all A vs W Windows APIs)

**Comment by Jinming-Hu** [comment]
@antkmsft You're the original author of the code above. Can you help me understand why we need wide string for UWP apps while don't need it for non-uwp apps?

**Comment by BillyONeal** [comment]
> @antkmsft You're the original author of the code above. Can you help me understand why we need wide string for UWP apps while don't need it for non-uwp apps?

I can answer that part. `CreateFileA`/`CreateFileW` are "desktop apps only" APIs, so they don't exist on UWP.

**Comment by Jinming-Hu** [comment]
> > @antkmsft You're the original author of the code above. Can you help me understand why we need wide string for UWP apps while don't need it for non-uwp apps?
> 
> I can answer that part. `CreateFileA`/`CreateFileW` are "desktop apps only" APIs, so they don't exist on UWP.

So, on UWP, there are only wide string version APIs.

**Comment by BillyONeal** [comment]
> > > @antkmsft You're the original author of the code above. Can you help me understand why we need wide string for UWP apps while don't need it for non-uwp apps?
> > 
> > 
> > I can answer that part. `CreateFileA`/`CreateFileW` are "desktop apps only" APIs, so they don't exist on UWP.
> 
> So, on UWP, there are only wide string version APIs.

Correct. (And you need to use the wide versions anyway if you want the input to be interpreted as UTF-8)

**Comment by Jinming-Hu** [comment]
> > > > @antkmsft You're the original author of the code above. Can you help me understand why we need wide string for UWP apps while don't need it for non-uwp apps?
> > > 
> > > 
> > > I can answer that part. `CreateFileA`/`CreateFileW` are "desktop apps only" APIs, so they don't exist on UWP.
> > 
> > 
> > So, on UWP, there are only wide string version APIs.
> 
> Correct. (And you need to use the wide versions anyway if you want the input to be interpreted as UTF-8)

OK, I get it. So if I want to support UTF-8 path, I have to convert it to wstring and call W suffix APIs for desktop app.

One more question though, why cannot Windows handle encoding stuff like Linux? Why does Windows have narrow-string A APIs and wide-string W APIs, while Linux only has narrow string APIs?

UTF-8 characters can take up to 4 bytes. So even with W APIs on Windows, we still cannot put any UTF-8 characters into just one `wchar_t`. So how is W API better than A API in this sense?

**Comment by BillyONeal** [comment]
>One more question though, why cannot Windows handle encoding stuff like Linux? Why does Windows have narrow-string A APIs and wide-string W APIs, while Linux only has narrow string APIs?

Windows NT, Java, JavaScript, etc. all implemented Unicode when it was thought that 16 bits would be enough forever. At such time, Linux could not access Unicode anything. Later, in the mid 1990s, Unicode was changed to be 21 bits and UTF-8 was invented. Both UTF-8 (defacto Linux, network facing APIs, etc.) and UTF-16 (Java, JavaScript, NT, C#) environments are the way they are for legacy reasons at this point.

> UTF-8 characters can take up to 4 bytes. So even with W APIs on Windows, we still cannot put any UTF-8 characters into just one wchar_t. So how is W API better than A API in this sense?

The A APIs do not accept UTF-8 at all, so if there are code points you want to represent not in the currently active code page, you can't get at those files at all through the A APIs.

**Comment by Jinming-Hu** [comment]
I'm working on a fix of this issue. Since the input filename is a narrow `std::string`, do you think it's safe to always assume the input is UTF-8 encoded? (We already did so on UWP. We convert from UTF-8 to UTF-16.)

@ahsonkhan @BillyONeal @antkmsft

**Comment by BillyONeal** [comment]
> I'm working on a fix of this issue. Since the input filename is a narrow `std::string`, do you think it's safe to always assume the input is UTF-8 encoded? (We already did so on UWP. We convert from UTF-8 to UTF-16.)

It is not safe in C++ *in general* to make such an assumption but you can document that that's what you do so customers know that's your expectation.

It isn't what `main` or `fopen` or `std::path` do, for example. They are like `CreateFileA` and use the currently selected codepage.
