### ISSUE TITLE
Investigate and confirm storage perf is good when uploading/downloading files concurrently, since the expected flag isn't being used

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2305]
This might be a win32 api doc issue and not an issue with the SDK, but we should measure and make sure file upload is actually concurrent. The docs suggest we need to pass in FILE_FLAG_OVERLAPPED when creating the file handle.

https://github.com/Azure/azure-sdk-for-cpp/blob/d8214af143d92806b8364aa902b477997a9dc82f/sdk/storage/azure-storage-common/src/file_io.cpp#L37-L54

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea
![image](https://user-images.githubusercontent.com/6527137/118705081-a555b100-b7cc-11eb-866d-328118157549.png)

cc @JeffreyRichter, @Jinming-Hu, @BillyONeal

**Comment by Jinming-Hu** [comment]
We shouldn't use `FILE_FLAG_OVERLAPPED` here because we're expecting synchronous I/O operations.
But it's not documented in the API reference what the behavior is to use overlapped read/write without `FILE_FLAG_OVERLAPPED` flag when opening the file.

**Comment by JeffreyRichter** [comment]
Jinming is right. See this paragraph:

For an hFile that supports byte offsets, if you use this parameter you must specify a byte offset at which to start reading from the file or device. This offset is specified by setting the Offset and OffsetHigh members of the OVERLAPPED<https://docs.microsoft.com/en-us/windows/desktop/api/minwinbase/ns-minwinbase-overlapped> structure. For an hFile that does not support byte offsets, Offset and OffsetHigh are ignored.

From this page: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile

- Jeffrey Richter (see Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FRichterCloudApps&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TeBH6rge3q8VyFBwCrBXfSXND4oajfqayGLiZq1gmFo%3D&reserved=0> & Designing HTTP APIs<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9Ng00IlBCtw%26list%3DPL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65%26index%3D1&data=04%7C01%7C%7Cdc05b9290f9f445693ec08d8e1b30ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637507506469305857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nzunz4x55lMRzHb6qJVXuRkrlAAI03wXjPdexaPavzs%3D&reserved=0>)

________________________________

**Comment by BillyONeal** [comment]
>But it's not documented in the API reference what the behavior is to use overlapped read/write without FILE_FLAG_OVERLAPPED flag when opening the file.

It is documented: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew

FILE_FLAG_OVERLAPPED
0x40000000


[...]

If this flag is specified, the file can be used for simultaneous read and write operations.

If this flag is not specified, then I/O operations are serialized, even if the calls to the read and write functions specify an OVERLAPPED structure.



Billy3
________________________________

**Comment by Jinming-Hu** [comment]
All right, so the read/write is not concurrent.
We might be able to get some perf improvement with asynchronous I/O.

**Comment by ahsonkhan** [comment]
> All right, so the read/write is not concurrent.

How did you find out? What's the perf difference between this code path and the memory body stream one?

**Comment by Jinming-Hu** [comment]
> > All right, so the read/write is not concurrent.
> 
> How did you find out? What's the perf difference between this code path and the memory body stream one?

It says I/O operations are serialized in the document.
