### ISSUE TITLE
Make sure vcpkg port version is reset back to 0 in the package when released.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2306]
@antkmsft can you take this one - it is mainly a sanity check

**Comment by ahsonkhan** [comment]
We don't want the port-version in the final release of the package, especially for GA:
https://github.com/microsoft/vcpkg/blob/1dfba89852faa3bbe7aa6dbc9517fe3cf8712dc1/ports/azure-core-cpp/vcpkg.json#L4

cc @danieljurek

**Comment by antkmsft** [comment]
High chance no work is needed, we tested this with Daniel. The changes we publish, we are overwriting. I'll review the PR that gets published this release to make sure.

**Comment by ahsonkhan** [comment]
Looks like this issue is fixed:
https://github.com/microsoft/vcpkg/pull/18002

Anton, please close when ready :)
