### ISSUE TITLE
Change the static_assert in logging to use `atomic<Logger::Level>` to reduce uses of `int`.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2307]
https://github.com/Azure/azure-sdk-for-cpp/blob/92839dcc5681961946d093555f9b8b9dfc96d2e5/sdk/core/azure-core/inc/azure/core/internal/diagnostics/log.hpp#L17

To avoid use of `int` here, consider changing this to `atomic<Logger::Level>`.

Recommended by @BillyONeal 
> Yes it means that before C++17 you can't assert atomic<Logger::Level>::is_always_lock_free but the runtime assert() is probably OK

cc @antkmsft

**Comment by antkmsft** [comment]
Wait, I read this as the opposite - that before C++17, there is no way to be guaranteed that `atomic<Logger::Level>` is atomic, so we are limited to `int`, for which we can guarantee.

**Comment by BillyONeal** [comment]
> Wait, I read this as the opposite - that before C++17, there is no way to be guaranteed that `atomic<Logger::Level>` is atomic, so we are limited to `int`, for which we can guarantee.

That's right. `is_always_lock_free` was added in '17.

**Comment by antkmsft** [comment]
@ahsonkhan, so we don't need to "reduce the uses of `int`" then, the current implementation is the correct one.
