### ISSUE TITLE
FileWriter and other usages of buffer lengths within storage should use size_t instead of int64_t.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2315]
Follow up from https://github.com/Azure/azure-sdk-for-cpp/issues/2226

For example:
https://github.com/Azure/azure-sdk-for-cpp/pull/2310

cc @Jinming-Hu

**Comment by Jinming-Hu** [comment]
I changed the type for length parameter in FileWriter::Write() from size_t to length in this PR #2320

I think it's fine to cast return value of `ReadToCount` to `int64_t`. I'll leave it unchanged.

**Comment by Jinming-Hu** [comment]
Return this issue to core. If there's nothing else for storage team to do, feel free to close this PR.
