### ISSUE TITLE
unify the usage of `std::size_t` or `size_t`

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2319]
also `ptrdiff_t`

also functions like `memcpy` or `std::memcpy`

**Comment by antkmsft** [comment]
`int64_t` is also an `std::` - https://en.cppreference.com/w/cpp/header/cstdint.

**Comment by ahsonkhan** [comment]
Fixed most of the concerns here outside of storage, here: https://github.com/Azure/azure-sdk-for-cpp/pull/2415

Therefore, this issue can now be used to track storage fix-ups only.
