### ISSUE TITLE
The create release tag step is creating an extra version-less tag which needs to be cleaned-up

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2325]
For some reason the `Create release tag` step created an extra one, labeled `azure-core-cpp_`
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=902284&view=logs&j=7e3dcf18-0271-5969-bad2-2d563b59f0a3&t=7e72164f-f3ba-501f-4861-4640d54c1775
```text
Given the visible artifacts, github releases will be created for the following: 
azure-core_1.0.0-beta.9 
azure-core-cpp_ 
```
 
What happened there and can we clean that up? It is marked as Latest as well (instead of Pre-release), which gives customers the wrong impression:
https://github.com/Azure/azure-sdk-for-cpp/releases/tag/azure-core-cpp_

This issue is not specific to jus the core package, but impacted all the release pipelines, including identity and keyvault:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=902287&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=902288&view=results

cc @danieljurek, @weshaggard

**Comment by ahsonkhan** [comment]
And then we get this warning during doc publishing:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=902284&view=logs&j=cdf8120e-c355-5451-8b3d-cbe489ccbb18&t=e578cd36-c056-5561-6894-841cdc9312d3&l=22

That said, I do see the `beta.9` docs being published - probably link verification needs to be checked. I am not sure if the extra tag being introduced caused this downstream side effect:
https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-core/1.0.0-beta.9/index.html
```text
##[warning]Not able to do the default branch link replacement, since no release tag found for the release. Please manually check.
```

**Comment by ahsonkhan** [comment]
Just for posterity, after we clean the tags up, in case it is helpful for troubleshooting:
![image](https://user-images.githubusercontent.com/6527137/118867735-43627d80-b898-11eb-83eb-3cf9f6ef497f.png)

![image](https://user-images.githubusercontent.com/6527137/118867759-49585e80-b898-11eb-9372-5c9b4a3b99bf.png)

**Comment by weshaggard** [comment]
@danieljurek did you also need to clean-up some tags like https://github.com/Azure/azure-sdk-for-cpp/releases/tag/azure-core-cpp_?

**Comment by danieljurek** [comment]
Tags are cleaned up now

**Comment by ahsonkhan** [comment]
What, if anything, do we need to do about the docs publishing, given the warning about link replacement not working?
