### ISSUE TITLE
Make build variable coordination between package releases easier and more visible.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2329]
Right now, the build definition variable pipeline is sort of "tribal knowledge" and needs to be shared offline, or the person triggering the follow-up pipeline (to coordinate submitting them all in the same PR) needs to know where to look to find it.

For example:
![image](https://user-images.githubusercontent.com/6527137/118870143-0fd52280-b89b-11eb-8713-d18ab1837e8d.png)

Maybe this can be solved with a more visible/public doc describing where to look for the build variable. The solution space is a bit open ended.

cc @danieljurek

**Comment by ahsonkhan** [comment]
@Jinming-Hu, as one of the first SDK client library author who triggers the releases for storage, let me know if you have some ideas around this, that scales to future SDKs :)

**Comment by Jinming-Hu** [comment]
The current method works great for me. Just one small thing, is it possible to auto-generate the `VcpkgForkBranchName` rather than create it manually?

**Comment by kurtzeborn** [comment]
https://github.com/Azure/azure-sdk-for-cpp/issues/2321 is asking for effectively the same thing.  Closing this duplicate issue.  Please provide further comments on the other issue.
