### ISSUE TITLE
Add Track1 and Track2 Storage Blob Perf Tests

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-cpp#2340]
Please add the following Storage Blob perf tests:

1. Track2: Upload, ListBlobs
2. Track1: Download, Upload, ListBlobs

For reference, the .NET tests are here:
- Track2: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs/perf/Azure.Storage.Blobs.Perf
- Track1: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs/perf/Microsoft.Azure.Storage.Blob.Perf

There is also an alternative implementation of C++ Track1 and Track2 tests here: https://github.com/Jinming-Hu/azure-sdk-for-cpp-perf/tree/master/src

**Comment by Jinming-Hu** [comment]
it seems like Upload and List tests are already available for Track2.

https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-blobs/test/perf/inc/azure/storage/blobs/test/list_blob_test.hpp

https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-blobs/test/perf/inc/azure/storage/blobs/test/upload_blob_test.hpp
