### ISSUE TITLE
Beta11 release version doesnot compiles.

### ISSUE THREAD

**Issue by vivek-kumar-Niel** [Azure/azure-sdk-for-cpp#2346]
when tried to compile the beta11 release version however beta10 does compile successfully.

/data/azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11/sdk/keyvault/azure-security-keyvault-common/src/sha.cpp: In constructor ‘{anonymous}::SHAWithOpenSSL::SHAWithOpenSSL({anonymous}::SHASize)’:
/data/azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11/sdk/keyvault/azure-security-keyvault-common/src/sha.cpp:62:22: error: ‘EVP_MD_CTX_new’ was not declared in this scope; did you mean ‘EVP_MD_CTX_init’?
   62 |     if ((m_context = EVP_MD_CTX_new()) == NULL)
      |                      ^~~~~~~~~~~~~~
      |                      EVP_MD_CTX_init
/data/azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11/sdk/keyvault/azure-security-keyvault-common/src/sha.cpp: In destructor ‘virtual {anonymous}::SHAWithOpenSSL::~SHAWithOpenSSL()’:
/data/azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11/sdk/keyvault/azure-security-keyvault-common/src/sha.cpp:95:23: error: ‘EVP_MD_CTX_free’ was not declared in this scope; did you mean ‘EVP_MD_CTX_create’?
   95 |   ~SHAWithOpenSSL() { EVP_MD_CTX_free(m_context); }
      |                       ^~~~~~~~~~~~~~~

do we need to add any extra compile options to make it compile 

following are the compile options used

cmake -DCURL_LIBRARY=/CURLPATH/curl/lib/x86/Linux/libcurl.so  -DCURL_INCLUDE_DIR=/CURLPATH/curl/include -DBUILD_SHARED_LIBS=true  -DCMAKE_BUILD_TYPE=Release -DWARNINGS_AS_ERRORS=OFF ..

however DWARNINGS_AS_ERRORS should be set to off by default if we have warnings present in code , this warning is also occuring in Beta10 version.

In file included from /data/azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11/sdk/core/azure-core/src/base64.cpp:10:
/data/azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11/sdk/core/azure-core/src/base64.cpp: In static member function ‘static std::string Azure::Core::Convert::Base64Encode(const std::vector<unsigned char>&)’:
/data/azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11/sdk/core/azure-core/src/base64.cpp:69:27: warning: use of old-style cast to ‘char*’ [-Wold-style-cast]
   69 |     BIO_get_mem_ptr(bio, &bufferPtr);

 - OS: Oracle Enterprise Linux 7.6
 - Version : azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.11
 - Compiler : g++ version 9.3.1 20200408
 - C++ Version : 17

**Comment by Jinming-Hu** [comment]
Looks like it's caused by not including `<openssl/evp.h>`

**Comment by Jinming-Hu** [comment]
BTW I found some issues when I was looking through the impl of `SHAWithOpenSSL`.

For any classes that allocate resources in the constructor and deallocate resource in the destructor, we should properly define copy functions.
In the case of `SHAWithOpenSSL`, we should mark copy constructor and copy assignment operator as `deleted`.

**Comment by vivek-kumar-Niel** [comment]
thanks Jinming-Hu

yeah works now by including _OPENSSL_openssl_PREFIX , would be nice to have a find package for such dependencies.

is there any doc present for all dependencies ?

yeah agree with your other comment , i saw the code, need to handle copy constructor , assignment here

**Comment by vhvb1989** [comment]
Hello @vivek-kumar-Niel, bringing the dev-dependencies manually to CMake is less commonly expected than using VCPKG.  VCPKG takes care of bringing openSSL for libcurl.

I am curios, is there any reason why you prefer not using VCPKG in this case?

Also, after adding `_OPENSSL_openssl_PREFIX `, are you still seeing the warning?  or are you still disabling `fail on warning`?

**Comment by Jinming-Hu** [comment]
> bringing the dev-dependencies manually to CMake is less commonly expected than using VCPKG. VCPKG takes care of bringing openSSL for libcurl.

That's true on Windows, but not true on Linux. People tend to use built-in package manager, like `apt-get` on Ubuntu/debian and `yum` on RedHat.

Anyway, if customers choose to use their own package manager, it's their responsibility to take care of dependencies.

**Comment by Jinming-Hu** [comment]
@vhvb1989 If you look at the source code of `bio.h` of openssl, https://docs.huihoo.com/doxygen/openssl/1.0.1c/include_2openssl_2bio_8h_source.html, the warning should be caused by a C-style cast of the macro

```C
#define BIO_get_mem_ptr(b,pp)   BIO_ctrl(b,BIO_C_GET_BUF_MEM_PTR,0,(char *)pp)
```

I think we should suppress this warning in our code.

**Comment by vhvb1989** [comment]
>  If you look at the source code of bio.h of openssl,

Hoping we can drop support on openssl 1.0.x as it is not maintained any longer...
