### ISSUE TITLE
Why is this changed to reference again? It was just changed to unique_ptr several days ago.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#238]
Make the call about the BodyStream in HTTP Request/Response.

BodyStream* vs BodyStream& vs unique_ptr<BodyStream> vs shared_ptr<BodyStream>

**Comment by JinmingHu-MSFT** [comment]
@katmsft and I talked about this with @JeffreyRichter today, I think we're okay with this.
