### ISSUE TITLE
Headers containing the detail namespace that are only used by the package shouldn't be in public /inc/ folder, and not be in /internal/

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2410]
These two headers can most likely be labeled as _private and moved to the /src folder, since they are within the `_detail` namespace.

They certainly shouldn't be in the `/internal/` directory, unless I am missing something:

https://github.com/Azure/azure-sdk-for-cpp/blob/ecdadddc23ac2a3fcc2721315528a3be4de9d840/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/internal/datalake_constants.hpp#L6
https://github.com/Azure/azure-sdk-for-cpp/blob/ecdadddc23ac2a3fcc2721315528a3be4de9d840/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/internal/datalake_utilities.hpp#L13

If these headers are shared between packages, and must be `/internal/` for some reason, the namespace shouldn't be `_detail`. But, I don't see that to be the right fix.

cc @Jinming-Hu

**Comment by ahsonkhan** [comment]
Related to a recent fix of https://github.com/Azure/azure-sdk-for-cpp/issues/2278

**Comment by Jinming-Hu** [comment]
The code is also used in test code. So it has to be in header file.
