### ISSUE TITLE
Azure.Identity Improvements for C++ (July-December 2021)

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#2411]

**Comment by joshfree** [comment]
@RickWinter can you parent this under the zenhub epic https://github.com/Azure/azure-sdk/issues/2538?  You'll need to change the workspace / pipeline to Azure SDK Team in order for this to show up as an option.  I didn't want to change this on you and mess up any 'ADP Native Team' specific kanban boards
