### ISSUE TITLE
Intermittent failure when installing the code coverage tool on Linux: Tool 'dotnet-reportgenerator-globaltool' failed to install.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2417]
From an unrelated PR:
https://github.com/Azure/azure-sdk-for-cpp/pull/2415

https://dev.azure.com/azure-sdk/public/_build/results?buildId=930655&view=logs&j=fda9a6e2-14f0-5864-d894-5f56622f20fa&t=93773c86-710f-5ae6-99d4-de100c18d4b7&l=24

```text
Since you just installed the .NET SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: reportgenerator
Tool 'dotnet-reportgenerator-globaltool' (version '4.8.9') was successfully installed.
The tool package could not be restored.
Tool 'dotnet-reportgenerator-globaltool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

```

cc @danieljurek

**Comment by danieljurek** [comment]
Investigation of the logs found 4 such failures with the oldest being from 2021-04-29 and the most recent being 20921-08-20: 

Name | StartTime | EndTime | Duration | State | Result | Url | LogUrl
-- | -- | -- | -- | -- | -- | -- | --
Install coverage tools | 8/20/2021 22:43 | 8/20/2021 22:44 | 21 | completed | failed | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/1059778/Timeline/d201fa25-7a92-41fc-8ac4-aee32ca59f58 | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/1059778/logs/371
Install coverage tools | 4/29/2021 21:08 | 4/29/2021 21:09 | 50 | completed | failed | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/869435/Timeline/47b45b78-fded-4ead-903d-d996c360239b | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/869435/logs/436
Install coverage tools | 6/30/2021 21:38 | 6/30/2021 21:38 | 30 | completed | failed | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/975220/Timeline/461f4198-bb9e-4856-8ddc-3717e1b24ae9 | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/975220/logs/323
Install coverage tools | 8/6/2021 3:52 | 8/6/2021 3:53 | 26 | completed | failed | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/1035580/Timeline/83b81151-251d-4ac7-91e9-c89ac1191fef | https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/1035580/logs/217


These look like network failures

**Comment by ahsonkhan** [comment]
Failed again here, from https://github.com/Azure/azure-sdk-for-cpp/pull/3311:
[globaltool](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1344903&view=logs&j=ca6c228c-7ba2-55ec-3482-b320fca07ebb&t=d653138f-7ed9-5505-d349-895737f661f1&s=6884a131-87da-5381-61f3-d7acc3b91d76)
