### ISSUE TITLE
DateTime class supplied by Azure Core to support multiple format date time serializing/deserializing.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#242]
**Is your feature request related to a problem? Please describe.**
Currently, customers can only be using string to represent time, this is not convenient and kind of buggy.

**Describe the solution you'd like**
Add a DateTime class to support conversion for multiple time format parsing from or serialize to a string.

**Describe alternatives you've considered**
Introduce 3rd party dependencies or create guidelines of usage on std::chrono for time.

**Additional context**
Azure Storage needs two format:
RFC 1123
[ISO 8601](https://www.w3.org/TR/NOTE-datetime) (low priority)

**Comment by JinmingHu-MSFT** [comment]
ISO 8601 is not low priority. [This API](https://docs.microsoft.com/en-us/rest/api/storageservices/get-user-delegation-key) depends on it.

**Comment by RickWinter** [comment]
This seems a reasonable place to use `std::time`.  @BillyONeal @CaseyCarter is passing around time objects as dates anti-c++? 

@JeffreyRichter

**Comment by JinmingHu-MSFT** [comment]
Here's part of file properties of Storage File Service

```
x-ms-file-change-time: 2020-02-24T13:10:36.1522582Z
x-ms-file-last-write-time: 2020-02-24T13:10:36.1522582Z
x-ms-file-creation-time: 2020-02-24T13:10:36.1522582Z
```

`std::time` only provides second precision. Storage team needs at least 100-nanosecond level of precision.

**Comment by BillyONeal** [comment]
I strongly suggest just reusing the parsing bits from cpprestsdk here: https://github.com/microsoft/cpprestsdk/blob/7fbb08c491f9c8888cc0f3d86962acb3af672772/Release/src/utilities/asyncrt_utils.cpp#L621

cpprestsdk stores timestamps in (effectively) FILETIME. See https://github.com/microsoft/cpprestsdk/blob/7fbb08c491f9c8888cc0f3d86962acb3af672772/Release/include/cpprest/asyncrt_utils.h#L664

which is probably where the 100 nanos requirement for Storage originates.

Resolution beyond seconds is not in the C standard but platform specific APIs to get that (e.g. https://linux.die.net/man/2/clock_gettime ) exist.
