### ISSUE TITLE
Release scripts fails if no changelog is added for the release.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2439]
It should be OK to ship a beta or even GA without any breaking change or new features (only private changes maybe).

Right now, trying to release with empty changelog makes the pipeline fail

**Comment by danieljurek** [comment]
Changelog files are a required part of the release process - https://azure.github.io/azure-sdk/policies_releases.html#change-logs

In the case of no or very few changes, the guidance recommends making a note of the changes included between a relevant set of previous releases ([link](https://azure.github.io/azure-sdk/policies_releases.html#changelog-entries-for-ga-releases)): 

> Instead when doing a GA release it is recommended that we either squash all the beta notes into the GA changelog entry or add a comment similar to Includes all changes from X.Y.Z-beta.A to X.Y.Z.beta.B so that it is clear that all those changes are included.

**Comment by kurtzeborn** [comment]
Pushing back on this... For every release, we want to say *something* about why the release happened. As a policy, we actually want the release to fail if there's no explanation provided to customers about why we're releasing.

If you have a compelling scenario where we're going to be releasing often with empty changelogs, let's discuss further.  If this is just a rare thing, let's use the generic "bug fixes" or "version bump needed for <reason>".
