### ISSUE TITLE
[Storage Blobs Service] How to generate block id

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#246]
Currently, i'm using serial number(0,1,2,3,4...) as block id. @katmsft thinks we should do what we're doing in Track1 CPP sdk, which is to include a random uuid in block id. But I don't think it's necessary.

**Comment by RickWinter** [comment]
@JinmingHu-MSFT In track2 sdks the blockId is a Base64 encoded string
     * @param base64BlockId A Base64 encoded {@code String} that specifies the ID for this block. Note that all block
     * ids for a given blob must be the same length

**Comment by JinmingHu-MSFT** [comment]
@RickWinter We know the block ID should be Base64 encoded string. We're talking about what the string should be before being encoded.

**Comment by JinmingHu-MSFT** [comment]
The current implementation seems to be working fine. Let's reopen this issue if any problems comes up.
