### ISSUE TITLE
Key Vault Keys doesn't work on Alpine 3.x

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2460]
There's an error from the transport adapter when trying to use the Key Vault Keys SDK for C++ on Linux Alpine.

Notes:
 -  All the transport adapter tests from azure-core pass.
 - Tests from Azure Storage SDK pass.

For Key Vault, the SDK is able to generate the auth token just fine and send the request as expected.
Observed that the request is written to the wire as expected like:

```
POST /keys/name/create?api-version=X.X HTTP/1.1
accept: application/json
authorization: Bearer eyJ0e..........
content-length: 30
content-type: application/json
host: xxxxxxxx.vault.azure.net
user-agent: azsdk-cpp-KeyVault/X.X (Linux 5.4.72-microsoft-standard-WSL2 x86_64 #1 SMP Wed Oct 28 23:40:43 UTC 2020)
x-ms-client-request-id: e63686cc-1324-4ebf-664b-XXXXXXXXXX

{"attributes":null,"kty":"EC"}
```

The request is generated and sent the same way as on any other operating system.  Then, when trying to read the response from the server, the sdk uses:

readResult = curl_easy_recv(m_handle, buffer, bufferSize, &readBytes);

This call is returning 40 bytes read from the wire in `readBytes` but the content from `buffer` is not updated with the content comming from the wire. This makes the SDK to fail parsing the response.

This issue is currently only observed on Alpine Linux OS

**Comment by jxyang** [comment]
Possibly that the curl object was created without `CURLOPT_CONNECT_ONLY`? According to [libcurl](https://curl.se/libcurl/c/curl_easy_recv.html): 

> To establish the connection, set CURLOPT_CONNECT_ONLY option before calling curl_easy_perform or curl_multi_perform. Note that curl_easy_recv does not work on connections that were created without this option.
