### ISSUE TITLE
Transport Adapters: TLS support

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2497]
In order to implement Service Fabric support for Managed Identity Credential, we need to either add TLS validation support via callback, or disable certificate validation (JS and Python went that route).
But, we need some approach for this to be transport layer-agnostic in Core, plus both existing transports (Curl and WinHTTP need to support it).

**Comment by antkmsft** [comment]
Transport adapters had some related changes within the last two years, maybe it is already implemented.

**Comment by LarryOsterman** [comment]
The current HTTP transports have logic to disable certificate validation. They also have the ability to specify a specific certificate to be used when validating the connection.

**Comment by LarryOsterman** [comment]
It appears that this is already done.
