### ISSUE TITLE
azure/storage/blobs.hpp: No such file or directory

### ISSUE THREAD

**Issue by yellowhat** [Azure/azure-sdk-for-cpp#2499]
**Describe the bug**
Hi,
I would like to use `azure-sdk-for-cpp` on CentOS 8.4, but I am not able to compile.

**To Reproduce**
```
$ sudo dnf install -y "@Development Tools" cmake
$ git clone https://github.com/microsoft/vcpkg
$ ./vcpkg/bootstrap-vcpkg.sh
$ ./vcpkg/vcpkg install azure-storage-blobs-cpp
$ mkdir proj && cd proj
$ cat >CMakeLists.txt <<EOF
cmake_minimum_required(VERSION 3.18)
project(myproj LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED True)

find_package(azure-storage-blobs-cpp CONFIG REQUIRED)

add_executable(myproj myproj.cpp)
target_link_libraries(myproj PRIVATE azure-storage-blobs)
EOF
$ cat >myproj.cpp <<EOF
#include <stdlib.h>
#include <iostream>
#include <azure/storage/blobs.hpp>

int main()
{
    std::cout << "Test" << std::endl;
    return 0;
}
EOF
$ cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake
$ cmake --build build
Scanning dependencies of target myproj
[ 50%] Building CXX object CMakeFiles/myproj.dir/myproj.cpp.o
/home/vasco/proj/myproj.cpp:3:10: fatal error: azure/storage/blobs.hpp: No such file or directory
 #include <azure/storage/blobs.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/myproj.dir/build.make:82: CMakeFiles/myproj.dir/myproj.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/myproj.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2

```
Am I missing something?

Thanks

**Setup (please complete the following information):**
- OS: CentOS 8.4
- IDE : [e.g. IntelliJ]
- Version of the Library used:
  - azure-core-cpp[core,curl,http]:x64-linux -> 1.0.0
  - azure-storage-blobs-cpp[core]:x64-linux -> 12.0.0
  - azure-storage-common-cpp[core]:x64-linux -> 12.0.0
  - curl[core,non-http,openssl,ssl]:x64-linux -> 7.74.0#7
  - libiconv[core]:x64-linux -> 1.16#8
  - liblzma[core]:x64-linux -> 5.2.5#2
  - libxml2[core]:x64-linux -> 2.9.10#7
  - openssl[core]:x64-linux -> 1.1.1k#5
  - vcpkg-cmake[core]:x64-linux -> 2021-02-28#3
  - vcpkg-cmake-config[core]:x64-linux -> 2021-05-22
  - zlib[core]:x64-linux -> 1.2.11#10

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Jinming-Hu** [comment]
```CMake
target_link_libraries(myproj PRIVATE Azure::azure-storage-blobs)
```

**Comment by yellowhat** [comment]
@Jinming-Hu Thanks for the suggestion. It is working now.

**Comment by CaseyCarter** [comment]
Best guess (I'm no CMake expert) is this bit of code that generates the CMake import files for our SDKs:

https://github.com/Azure/azure-sdk-for-cpp/blob/e105bcdca303e12872e3a3a2e7033d75002a38d5/cmake-modules/AzureVcpkg.cmake#L105-L111

(this is a file that describes the library and it's various properties and dependencies). CMake's `find_package` command loads these files to get access to libraries. The presence of `NAMESPACE Azure::` in the `install` command prepends `Azure::` to the target names.

**Comment by yellowhat** [comment]
Thanks for the explanantion.
