### ISSUE TITLE
How retry mechanism is going to work when network interruption occurs during customer reading response body?

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#250]

**Comment by JeffreyRichter** [comment]
We wrap the response BodyStream with a ReliableBodyStream and the customer actually reads from this. If, while reading, the underlying body stream throws an exception, then it can issue a new HTTP GET request to continue reading from where the first stream left off. We have examples in other languages and we should just port that code to C++

**Comment by vhvb1989** [comment]
ReliableStream is already implemented.
@JinmingHu-MSFT  I am closing this issue.  Please feel free to re-open if there's still anything pending for this.
