### ISSUE TITLE
Base64Url encode is not unique to KeyVault and should be in Azure Core

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2501]
Base64Url encoding and decoding operation is a very common transformation API. It should be in Azure Core since we know future services will need it.

It is currently internal within KeyVault Common. If we are happy with the design, we should consider making it public and moving it to core.

https://github.com/Azure/azure-sdk-for-cpp/blob/0874e1c1c9047b9ccf6caac5057f67c9b92144a7/sdk/keyvault/azure-security-keyvault-common/inc/azure/keyvault/common/internal/base64url.hpp#L16-L22

https://github.com/Azure/azure-sdk-for-cpp/blob/0874e1c1c9047b9ccf6caac5057f67c9b92144a7/sdk/core/azure-core/inc/azure/core/base64.hpp#L15-L21

https://github.com/Azure/azure-sdk-for-net/search?q=base64url
WebPubSub, Attestation, ContainerRegistry, ACS, etc.

cc @JeffreyRichter, @RickWinter, @vhvb1989

**Comment by JeffreyRichter** [comment]
As always making things public comes with a huge cost (making it general purpose [not just for our specific needs], documentation, samples, support in perpetuity). So, we should avoid this unless there is real customer benefit.

**Comment by ahsonkhan** [comment]
Leave it internal, but move it to core.
