### ISSUE TITLE
Why do we have single_page.hpp in KeyVault common, and why is it internal?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2505]
It is only used in KeyVault Keys. Can it be moved there?

https://github.com/Azure/azure-sdk-for-cpp/blob/0874e1c1c9047b9ccf6caac5057f67c9b92144a7/sdk/keyvault/azure-security-keyvault-common/inc/azure/keyvault/common/internal/single_page.hpp#L15-L16

Same with this public header:
https://github.com/Azure/azure-sdk-for-cpp/blob/fda88bf7b8389575b9d973821efc604442e10493/sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/list_keys_single_page_result.hpp

https://github.com/Azure/azure-sdk-for-cpp/search?q=GetPageResultOptions

Such types should be using the `PagedResponse<T>` approach, similar to things like Storge's `ListSharesPagedResponse`
https://github.com/Azure/azure-sdk-for-cpp/blob/0874e1c1c9047b9ccf6caac5057f67c9b92144a7/sdk/core/azure-core/inc/azure/core/paged_response.hpp#L18-L29

https://github.com/Azure/azure-sdk-for-cpp/blob/fda88bf7b8389575b9d973821efc604442e10493/sdk/storage/azure-storage-files-shares/src/share_responses.cpp#L64-L68

cc @vhvb1989, @RickWinter, @JeffreyRichter

**Comment by vhvb1989** [comment]
single_page defines `GetPageResultOptions` which is a base class to define the options for getting a page from Key Vault. Not only `Keys` contains APIs with Paged responses.

Any API from either Keys, Secrets or Certificates that produces Pages, would take options for the API.
For example, `GetDeletedKeys` API takes `GetDeletedKeysOptions` as an optional argument.  All options types will derive from `GetPageResultOptions` and can eventually add unique options for the API.

I can rename the header name, if `single_page` is confusing here

**Comment by vhvb1989** [comment]
It is internal because KeyVault Common exposes this component only to be used by KeyVault packages
