### ISSUE TITLE
Is it worth it to have keyvault common just for a small subset of types like `KeyVaultPipeline`?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2506]
Right now KeyVault Common in C++ has:
- SHA Hashing APIs (probably should be moved to core)
- Base64 Url (should be moved to core)
- KeyVaultException (should be removed)
- Unix Time helper (should be moved to core)
- Single Page (should use `PagedResponse<T>` and removed)

If the only piece leftover in KeyVault common is `KeyVaultPipeline`, do we need that package at all or can we move it to `azure-security-keyvault-keys` as a private implementation detail/shared header in `/src`?

https://github.com/Azure/azure-sdk-for-cpp/blob/0874e1c1c9047b9ccf6caac5057f67c9b92144a7/sdk/keyvault/azure-security-keyvault-common/inc/azure/keyvault/common/internal/keyvault_pipeline.hpp#L24-L30

.NET has it in `Azure.Security.KeyVault.Keys`:
https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyVaultPipeline.cs#L8-L14

But it also has some source sharing (though still in the `Azure.Security.KeyVault` namespace):
https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/keyvault/Azure.Security.KeyVault.Shared/src/KeyVaultPipeline.cs#L10-L12

cc @heaths, @tg-msft, @JeffreyRichter, @RickWinter, @vhvb1989

**Comment by vhvb1989** [comment]
Its the structure foundation for certificates and secrets packages.

**Comment by heaths** [comment]
For .NET, the pipeline had functionality that predates much of the shared code in Azure.Core. In fact, much of that code was copied and modified minimally. But I see no reason to remove it from .NET because the methods also give me consistent control over what is classified as errors and better support for our pseudo-LROs. If C++ wants to do it for the same reasons and uses source sharing, I don't see any harm. Is there some reason to otherwise duplicate code across the different packages here?

**Comment by vhvb1989** [comment]
we can't do shared-code in cpp the way it works on .NET
We prefer shipping and maintaining a common package for all the packages from a service.
This common package should be transparent for consumers (similar to the shared-source from .NET).

>  Is there some reason to otherwise duplicate code across the different packages here?

Not cool.  That would bring pain and chaos to keep all copies in sync and avoid issues.

**Comment by heaths** [comment]
It was a pointed question in response to this from the OP:

> If the only piece leftover in KeyVault common is KeyVaultPipeline, do we need that package at all or can we move it to azure-security-keyvault-keys as a private implementation detail/shared header in /src?

If you remove the shared pipeline, you'd have to duplicate code or - as you stated - have a shared package. I just know that for all other languages, we've explicitly avoided shared packages. IIRC, Python and JS effectively dup shared code during generation such that, while it's duped, it's done from a single source and the duped source is treated like generated source i.e., don't modify it (so like your _details namespace, I imagine).
