### ISSUE TITLE
Rename KeyOperation to KeyOperationType to avoid confusion with LRO `Operation<T>` types

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2507]
From https://apiview.dev/Assemblies/Review/2b96c2a3509844fcaf0106f1af1d43f1#002e5a4dd371402b875d3e7124a79b9a

cc @vhvb1989, @RickWinter

**Comment by gearama** [comment]
After long and intense debates the decision was reached by the stakeholders to remain with the current name of KeyOperation ( singular) thus this issue is not needed anymore.
