### ISSUE TITLE
Remove Sha256 from storage code

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2513]
https://github.com/Azure/azure-sdk-for-cpp/blob/fda88bf7b8389575b9d973821efc604442e10493/sdk/storage/azure-storage-common/inc/azure/storage/common/crypt.hpp#L40

**Comment by Jinming-Hu** [comment]
blocked by https://github.com/Azure/azure-sdk-for-cpp/issues/2500

**Comment by ahsonkhan** [comment]
> blocked by #2500

@Jinming-Hu what do you mean by this? Is removing Sha256 from storage not feasible yet?

**Comment by Jinming-Hu** [comment]
> > blocked by #2500
> 
> @Jinming-Hu what do you mean by this? Is removing Sha256 from storage not feasible yet?

It's being used in storage test code.

I'd have to move the implementation of `Sha256` from storage common package to test code. Then after you guys move `Sha256` from keyvault to core (as we talked this morning in the working group meeting), I'd remove `Sha256()` from storage test code and use the one in core package. That sounds like a lot of hassle.

Why not wait until you've moved SHA-256 to core package, then I can use the it in storage test code and remove the one in storage common package.

**Comment by ahsonkhan** [comment]
Before we do this, let's make sure we validate that a test dependency change from storage to core doesn't require storage vcpkg package to take a dependency on a higher azure-core version (and cause a vcpkg CI failure).

It might be worth moving the storage impl to the tests for now, or wait until after the next release, so we have enough time to validate this.

**Comment by Jinming-Hu** [comment]
I'd prefer waiting.

**Comment by ahsonkhan** [comment]
> Before we do this, let's make sure we validate that a test dependency change from storage to core doesn't require storage vcpkg package to take a dependency on a higher azure-core version (and cause a vcpkg CI failure).

@Jinming-Hu were you able to verify this?

**Comment by Jinming-Hu** [comment]
This sha256 function is only used in test code, and `vcpkg install` won't build test code at all. So I think it should be fine.
