### ISSUE TITLE
Consider skipping tests according to runtime conditions

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#2520]
Today we evaluate whether to run live tests using a template condition. This has at least two downsides: 

* Duplicate condition logic for whether the Release stages should depend on LiveTest 
* (UI) live tests don't show up in Unified Pipelines where there are not live tests. Better to have the tests and show that they were skipped for consistency and more obvious transparency.

**Comment by benbp** [comment]
Are you alluding to the general runtime variables that the other language release pipelines use?
