### ISSUE TITLE
Is it idiomatic to C++ to default initialize containers like vectors using `= {}` in API parameters?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2533]
The `additionalAuthenticationData` vector parameter in KeyVault APIs is defaulted as an empty vector, using the `initializer_list` ctor. This is in an attempt to mirror the semantics of other languages like .NET:
https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.cryptography.encryptparameters.a192gcmparameters?view=azure-dotnet#Azure_Security_KeyVault_Keys_Cryptography_EncryptParameters_A192GcmParameters_System_Byte___System_Byte___

https://github.com/Azure/azure-sdk-for-cpp/blob/0874e1c1c9047b9ccf6caac5057f67c9b92144a7/sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/cryptography/encrypt_parameters.hpp#L156-L158

@CaseyCarter follow up on our offline conversation, how out-of-the-norm is having containers be defaulted in C++? Should we have a guideline recommending against it?

- Should we leave it as is, defaulted, like .NET? If it is an optional parameter, should it be part of an optional struct where we can add more field later?
- Should we change it to be a required parameter? If we mark the client SDK parameter as required today and make it optional tomorrow, is that considered a breaking change? I imagine that is fine to do.

The feedback on APIview was to make it defaulted (which it already currently is):
https://apiview.dev/Assemblies/Review/2b96c2a3509844fcaf0106f1af1d43f1#4ac1f1a3d46441b094b6f6cbbf9beb66

cc @JeffreyRichter, @vhvb1989

**Comment by CaseyCarter** [comment]
> @CaseyCarter follow up on our offline conversation, how out-of-the-norm is having containers be defaulted in C++? Should we have a guideline recommending against it?

Only slightly non-normal. I'd be concerned about inefficiency if the default arguments were not empty vectors, but these seem fine to me.

> * Should we leave it as is, defaulted, like .NET? If it is an optional parameter, should it be part of an optional struct where we can add more field later?

I wouldn't go out of my way to change these.

> * Should we change it to be a required parameter? If we mark the client SDK parameter as required today and make it optional tomorrow, is that considered a breaking change? I imagine that is fine to do.

Adding a default argument is non-breaking.

**Comment by ahsonkhan** [comment]
We decided to match what other languages are doing. It is OK to have defaulted parameters that are of C++ container types. 
The semantics of passing an empty vector and no parameter is identical (we only add the value to the request if the size of the vector is non-zero).
