### ISSUE TITLE
Rename the message param to `what_arg` on RFE following the std::runtime_error base class ctor

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2542]
https://github.com/Azure/azure-sdk-for-cpp/blob/d0ca42643f4c81261ecaa8ba0d75ceb7d3127a48/sdk/core/azure-core/inc/azure/core/exception.hpp#L75

This is a non-breaking change

- `what()` from the base class should work as is
- The semantics of Message field: only returned from the service, and it is not set to the `what_arg`

**Comment by ahsonkhan** [comment]
@antkmsft I don't think this issue got fixed fully.

This aspect still remains, I believe:
> - The semantics of Message field: only returned from the service, and it is not set to the `what_arg`

https://github.com/Azure/azure-sdk-for-cpp/blob/3aee1859f0e74514bf75440dca43b07b0d8c3358/sdk/core/azure-core/src/exception.cpp#L18-L31

**Comment by antkmsft** [comment]
@ahsonkhan, and it's not set to the `what_arg`: https://github.com/Azure/azure-sdk-for-cpp/blob/3e2e5a6dfc54fa0f4c5fdfa9de379147f43cd20d/sdk/core/azure-core/inc/azure/core/exception.hpp#L78
