### ISSUE TITLE
Cognitive Speech Keyword Recognition - Silence duration after keyword detection

### ISSUE THREAD

**Issue by lrodorigo** [Azure/azure-sdk-for-cpp#2576]
**Describe the bug**
After the keyword is detected, the user has no time to give commands. In detail the speech to text operation is terminated in a very short time after the keyword detection. Is there a way to set the duration of the silence between the keyword and the following commands?  
The current maximum delay is really short and is difficult fot the user to understand a "keyword spotted feedback" (e.g. a led whitch turns on) and then continue speaking without hitting the silence threshold timeout between the keyword and the following commands.

I tried the solutions reported in the following posts, with no success:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/131#issuecomment-450928482 
and 
```
auto config = SpeechConfig::FromSubscription("<<KEY>>", "eastus");
config->SetProperty(PropertyId::SpeechServiceConnection_EndSilenceTimeoutMs, "10000");
```
**Expected behavior**
We expect that setting the `SpeechServiceConnection_EndSilenceTimeoutMs` property also affects the delay between the keyword and the successive utterances (or we expect an alternative way to configure this delay). 

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - Azure CPP SDK v 1.17.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by RickWinter** [comment]
Closing this issue as its tracked in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1170
