### ISSUE TITLE
The Speech::KeywordRecognizer::RecognizeOnceAsync method is blocking if the result value is not used

### ISSUE THREAD

**Issue by lrodorigo** [Azure/azure-sdk-for-cpp#2589]
**Describe the bug**
` Speech::KeywordRecognizer::RecognizeOnceAsync ` becomes a blocking method if its result value is not used. 
I think that this happens because, if the result value is not used, the returned `std::future<std::shared_ptr<KeywordRecognitionResult>>` is destroyed (due to the ref. counting that goes to zero), and then a self-join is invoked on the calling thread.

**To Reproduce**
***Code Snippet***
Try the following example:
https://gist.github.com/lrodorigo/6934bc025a81b7695e697b0c1ef97f86

**Expected behavior**
I expect that an "async" method is actually non-blocking, even is the result value is not used (moreover because Recognized/Canceled callback are also exposed) 

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - v 1.17.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by trrwilson** [comment]
Hello, @lrodorigo! Like the question around silence configuration, could you please ask this over in the cognitive-services-speech-sdk project? https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues

The team actively monitors that issue list and we haven't yet set up a process for migrating the issues automatically. Thanks for the understanding!

(In the meantime, I'll raise this with the team to see if your suspicion about the future is what's causing it)

**Comment by RickWinter** [comment]
Closing, this issue is in the Azure-Samples.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues
