### ISSUE TITLE
API Reference doc link links to .NET reference docs 

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-cpp#2598]
API Reference link in [readme](https://github.com/Azure/azure-sdk-for-cpp/tree/azure-security-keyvault-keys_4.0.0-beta.3/sdk/keyvault/azure-security-keyvault-keys#azure-key-vault-key-client-library-for-c) links to .NET reference docs on docs.microsoft: https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys?view=azure-dotnet

**Comment by ahsonkhan** [comment]
Thanks for finding and reporting it @lilyjma! 

cc @vhvb1989 - we may want to do a scrub of other potential links that might need updating
