### ISSUE TITLE
Update documentation for using MSI

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#2604]
Need to add conceptual code snippets for MSI support to docs.

https://docs.microsoft.com/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token
https://docs.microsoft.com/azure/cloud-shell/msi-authorization
https://docs.microsoft.com/azure/azure-arc/servers/managed-identity-authentication

**Comment by antkmsft** [comment]
The docs above do not have code samples from language SDKs.
They send a HTTP request and parse JSON from a response.
If there are `docs.microsoft.com` that use Azure SDK in their samples, with multiple tabs for Java, C#, and so on, C++ should be there as well. I extracted that purpose to #2706.
