### ISSUE TITLE
Investigate refactoring of KeyClient API implementation to avoid the inversion of control flow

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2614]
Rather than a `SendRequest` method with a callback which both creates and sends the request (generically), have a sequential flow, as follows:
```text
  request = createrequest();
  response = pipeline.Send(request);
  Validate(response.status);
  model = deserialize();
  return model;
```

This applies to all such APIs:
https://github.com/Azure/azure-sdk-for-cpp/blob/c16ce55b184e24c608e0788096510ea539e6052c/sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp#L304-L318

cc @JeffreyRichter, @vhvb1989

**Comment by RickWinter** [comment]
@vhvb1989 Do you know what problem this design is solving?

**Comment by vhvb1989** [comment]
@RickWinter this is not to solve any issue.  This would be a way to simplify too much the client implementation so the protocol layer would be directly implemented in the convivence layer. I am against this change :) , since one only template method is easier to maintain than (N times APIs)
