### ISSUE TITLE
Intermittent CI failure due to task cancelled/timeout

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2616]
https://github.com/Azure/azure-sdk-for-cpp/runs/3025686697

![image](https://user-images.githubusercontent.com/52266153/125547164-7452e42a-5fd7-481a-b016-ffe9b8121686.png)

**Comment by benbp** [comment]
@danieljurek this seems like vcpkg download timeouts. Do you think it would make sense to do some directory caching on the VM agents in these cases? I don't have enough knowledge of what's being downloaded.

**Comment by danieljurek** [comment]
The cache task in DevOps has been noticeably less reliable of late. I'm working on a classifier for Pipeline Witness so we can get more data on what is causing these failures.
