### ISSUE TITLE
Review header name inc/azure/keyvault/keys/key_vault_key.hpp

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#2627]
KeyVault is the service.  It is odd to use `key_vault_keys.hpp`.  `keyvault_keys.hpp` is more appropriate.

**Comment by vhvb1989** [comment]
`Key Vault` is the name of the service. The name comes with one space and it is advertised like that in readMe and docs. When it comes to code, it becomes either:
keyVault -> cammel
KeyVault -> pascal
key_vault -> snake

We should never consider it as one-word.  This was one of the earliest comments from @heaths for the naming pattern for the SDK.

**Comment by ahsonkhan** [comment]
We need to be consistent, we aren't currently.
https://github.com/Azure/azure-sdk-for-cpp/blob/e69f6e182a31daafd95ed7b9fc6219da3910995e/sdk/keyvault/azure-security-keyvault-keys/src/private/keyvault_protocol.hpp
https://github.com/Azure/azure-sdk-for-cpp/blob/e69f6e182a31daafd95ed7b9fc6219da3910995e/sdk/keyvault/azure-security-keyvault-keys/src/private/keyvault_constants.hpp
https://github.com/Azure/azure-sdk-for-cpp/blob/e69f6e182a31daafd95ed7b9fc6219da3910995e/sdk/keyvault/azure-security-keyvault-keys/test/ut/azure_security_keyvault_keys_test.cpp

@heaths, the simplified header that we expect customers to include today, is called `key_vault_keys.hpp`.
The package name and the directory paths are all `keyvault`. Are we sure we don't want the filename to be `keyvault_keys.hpp`?

**Comment by heaths** [comment]
@JeffreyRichter, myself, and the v-team had this discussion recently for the unofficial Azure SDK for Rust and it should be "keyvault" - one word. Same for "eventgrid", etc. While the marketing name is "Key Vault", the component segments across our SDKs use "KeyVault" or "keyvault" already e.g., "Azure.Security.KeyVault.Secrets".

**Comment by ahsonkhan** [comment]
Alright, great, so let's make the change here in C++ as well to use `keyvault`, which is what most of the existing headers are doing already.
