### ISSUE TITLE
Support for overwriting x-ms-client-request-id

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2655]
https://github.com/Azure/azure-sdk-for-cpp/blob/1839061e0d2ebeee44a2ed563bfe642f5b6796cd/sdk/core/azure-core/inc/azure/core/internal/http/pipeline.hpp#L104

Can we move `RequestIdPolicy` to between service-specific per-call policies and client-options per-call policies? So that the `x-ms-client-request-id` header is visible to customers, and they can overwrite it or log it.

**Comment by RickWinter** [comment]
Seems reasonable to do all our internal per-call policies before the client's per-call.  @Jinming-Hu was this a request from a customer?

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu was this a request from a customer?

Yes

**Comment by RickWinter** [comment]
@Jinming-Hu Can you elaborate on what is being done to the user agent string.  I'd like to understand why they want to modify the value as the contents of the user agent string are only meaningful to the service

cc @JeffreyRichter

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu Can you elaborate on what is being done to the user agent string. I'd like to understand why they want to modify the value as the contents of the user agent string are only meaningful to the service
> 
> cc @JeffreyRichter

The customer only asked for accessing client request id. But there's no harm to give them access to user agent.
