### ISSUE TITLE
Auto-generated release PRs in vcpkg should be assigned or cc'd to the C++ dev team to help land it sooner

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2658]
@DanielJurek - can we please update the PR generation to auto-tag/cc the Azure SDK C++ dev team, so we can get notified and follow-up on such feedback and releases?

_Originally posted by @ahsonkhan in https://github.com/microsoft/vcpkg/issues/19028#issuecomment-884383053_

**Comment by kurtzeborn** [comment]
@danieljurek, @ahsonkhan if the VCPKG folks will allow us to add entries to the CODEOWNERS file in that repo, this is solved pretty easily with that.
