### ISSUE TITLE
Modify the path parameter to be by-value instead of a const reference.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2659]
> Moreover, since we're going to make a copy of this parameter at Line 38 anyway, I think a by-value parameter is better than const reference.

> A by-value parameter along with changing line 38 to a move assignment, yes.

_Originally posted by @CaseyCarter in https://github.com/Azure/azure-sdk-for-cpp/pull/2595#discussion_r671440673_

https://github.com/Azure/azure-sdk-for-cpp/blob/d90d5c761e90d9ff986dd434a3bddba06c9881e9/sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp#L53-L58

cc @Jinming-Hu

**Comment by ahsonkhan** [comment]
@CaseyCarter I am assuming you mean:
`const std::vector<std::string>&& defaultPath` -> `const std::vector<std::string> defaultPath`

And:
`request.Path = defaultPath;` -> `request.Path = std::move(defaultPath);`

**Comment by CaseyCarter** [comment]
> @CaseyCarter I am assuming you mean:
> `const std::vector<std::string>&& defaultPath` -> `const std::vector<std::string> defaultPath`

Almost! We need to remove the `const` here for the `move` below to have a useful effect: attempting to move from a `const` object generally results in a copy, and we can avoid that copy since we use this vector only to initialize `request.Path`.
 
> And:
> `request.Path = defaultPath;` -> `request.Path = std::move(defaultPath);`
