### ISSUE TITLE
Add MSDocs for Azure SDK for C++ and link it to azure.github.io/azure-sdk

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2665]
There should be a link from https://azure.github.io/azure-sdk/releases/latest/#c to the MSDocs, but the link is not showing up as there are not MSDocs for the Azure SDK for C++.

**Comment by kyle-patterson** [comment]
@vhvb1989 @RickWinter We have a reference listing on docs now (https://docs.microsoft.com/azure/storage/blobs/reference#c-client-libraries), which directs to https://azure.github.io/azure-sdk-for-cpp/index.html for the API reference.

Do you want to link to the docs page, or directly to azure.github.io?

**Comment by vhvb1989** [comment]
> @vhvb1989 @RickWinter We have a reference listing on docs now (https://docs.microsoft.com/azure/storage/blobs/reference#c-client-libraries), which directs to https://azure.github.io/azure-sdk-for-cpp/index.html for the API reference.
> 
> Do you want to link to the docs page, or directly to azure.github.io?

The link in docs is too short IMO.  And the docs from github.io is for preview releases AFAIK.

I was hoping if we could have something like the other languages have (see python: https://docs.microsoft.com/en-us/azure/developer/python/?view=azure-python)  where there's plenty official docs for the GA versions

**Comment by kyle-patterson** [comment]
The github.io page shows 12.0.1 for storage (and every other release), so I think in terms of API reference it's the best candidate.

As far as the developer page, #1598 is tracking that - it's on the radar, but will need more time. For now, we should focus efforts on getting an API ref back on the releases page...

**Comment by kyle-patterson** [comment]
Quick update, the PR was completed and docs links (github.io) are now appearing in the aka.ms/azsdk table. Thank you @vhvb1989 ! I will work with related service owners to address #1598

![image](https://user-images.githubusercontent.com/57923303/131702170-10ecce56-37d1-4f35-a682-bc1a412a8f86.png)
