### ISSUE TITLE
Yes, all XxxClient types should have a GetURL method on them. This is required to get the URL and pass it to another client (with different pipeline options or credentials) or pass it to another machine so it operate on the resource.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2701]
Yes, all XxxClient types should have a GetURL method on them. This is required to get the URL and pass it to another client (with different pipeline options or credentials) or pass it to another machine so it operate on the resource.

_Originally posted by @JeffreyRichter in https://github.com/Azure/azure-sdk-for-cpp/pull/2671#r681185381_

**Comment by Jinming-Hu** [comment]
nothing needs to be done by storage team. Assign back.

**Comment by RickWinter** [comment]
@vhvb1989 We should add this to the guidelines and add checks into APIView to validate
