### ISSUE TITLE
Put more version requirements in vcpkg manifest files

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2702]
👍 Let's also update the corresponding `find_package`/`find_dependency`/`version>=` for the KeyVault then.

_Originally posted by @antkmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/2678#discussion_r677912845_

**Comment by antkmsft** [comment]
Since KeyVault can't work on top of Core 1.0 GA, let's put the version requirements the same way the new Identity version will.

**Comment by RickWinter** [comment]
@antkmsft Please make this fix and review all other packages for similar requirements
