### ISSUE TITLE
Storage Blob Batch

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2712]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by kshcherbatov** [comment]
@Jinming-Hu 
> We still have some different opinions about the interface design.

Let me put my two cents in...

You already expose 
```
namespace Azure { namespace Storage { namespace Blobs {
Azure::Response<Models::DeleteBlobResult> BlobContainerClient::DeleteBlob(const std::string& blobName, ...)
```
so there could be BlobContainerClient::DeleteBlobs(.... ??? .... )

I think general-purpose input iterator [begin_it, end_it) pointing std::string would be a great choice:
```
template< class InputIt, class T >
Azure::Response<Models::DeleteBlobsResult>BlobContainerClient::DeleteBlobs(InputIt first, InputIt last, ...)
```
like in https://en.cppreference.com/w/cpp/algorithm/find

Thus, callers can store std::string in any container they like....

If too many objects are passed for deletion, this is not the SDK problem. 
Say, in AWS S3 CPP SDK you just pass a vector to the request-constructor:
```
Aws::S3::Model::DeleteObjectsRequest delete_objects_request;
delete_objects_request.WithBucket(bucket_name).
      WithDelete(Aws::S3::Model::Delete().
      WithObjects(std::move(objects_to_delete_)).
      WithQuiet(true));
.....
inline Delete& WithObjects(Aws::Vector<ObjectIdentifier>&& value) { SetObjects(std::move(value)); return *this;}
inline void SetObjects(Aws::Vector<ObjectIdentifier>&& value) { m_objectsHasBeenSet = true; m_objects = std::move(value); }
...
DeleteObjectsAsync(std::move(delete_objects_request), async_cb, context);
```

**Comment by gab-david** [comment]
Hello,
I'm also interested with this feature.
My use case is to handle big files up to 50 000 parts * 4000 MiB as given by azure limits.
At the end of the concatenation, I would like to make one single (or a limited number of) HTTP request to delete all blob parts instead of 50000 requests.
Is the feature still planned ?
Regards

**Comment by Jinming-Hu** [comment]
Now blob batch is available in 12.5.0.beta2. We'll ship a stable release next month.

**Comment by Jinming-Hu** [comment]
> Hello, I'm also interested with this feature. My use case is to handle big files up to 50 000 parts * 4000 MiB as given by azure limits. At the end of the concatenation, I would like to make one single (or a limited number of) HTTP request to delete all blob parts instead of 50000 requests. Is the feature still planned ? Regards

Hi @gab-david , are 50000 parts in one blob or there are 50000 blobs? If there're 50000 blobs, then this feature won't help.

**Comment by kshcherbatov** [comment]
Thank you very much @Jinming-Hu,
Just tried the feature and it works for me perfectly. I am looking forward for the stable release.

Side notes:
- Batch exposes DeleteBlob method which I uses with DeleteIfExists semantics; I've experimentally assured, that one missing object (which I added on purpose) doesn't fail the sequence what is perfectly fine for me; I could have some misses in my set.
- Apparently, I shouldn't schedule more than 255 requests pro batch; That wasn't clear from SDK API
https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch
