### ISSUE TITLE
Identity: apply Jeff's concurrent token refresh logic

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#272]
We currently have one, but Jeff's invention is better.
Also, we wanted to extract identity into a module, this might be a good task to combine with.

**Comment by RickWinter** [comment]
@antkmsft Can you elaborate on this item.  Is this work necessary now that we have token caching?

**Comment by antkmsft** [comment]
@RickWinter, this have been so long ago. We've made multiple improvements since then. We are good in terms of concurrency, and identity has been extracted into a separate module long ago. We should close this item, it is completed.
