### ISSUE TITLE
Delete keyvault-common from the source tree

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2720]
"Keyvault-common is abandoned"
_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/2718#r685417878_

So, should we delete it from the source tree then?

**Comment by vhvb1989** [comment]
`keyvault-common` as a package was removed from the repo some time ago.  I added `azure-security-keyvault-shared` folder, but it's not a package, but only code that gets compiled into packages directly
