### ISSUE TITLE
Review doxygen for KeyVault libraries (both KeyVault Keys and Secrets libs)

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2732]
Make sure the principles and decisions from #2260 are applied to KeyVault docs.
Generate the docs, review if everything looks right.

The general structure is:
the root README from the repo ./README should link to each Service's README ( ./sdk/keyvault/README
then, each service's README should link to each package's README ( ./sdk/keyvault/azure-security-secrets/README )
then, each package's README should link to the sample's docs ( ./sdk/keyvault/azure-security-secrets/samples/docs... )
then, each sample's docs should link to the sample source code.

**Comment by gearama** [comment]
Incomplet
Azure/azure-sdk-for-cpp: This repository is for active development of the Azure SDK for C++. For consumers of the SDK we recommend visiting our versioned developer docs at https://azure.github.io/azure-sdk-for-cpp.

https://azure.github.io/azure-sdk-for-cpp/index.html#vcpkg
_____________________________________


Circular link 
our developer docs.

From <https://azure.github.io/azure-sdk-for-cpp/> 
________________________________________


https://azure.github.io/azure-sdk-for-cpp/#getting-started 
, go to Azure SDK for C++ Developer Docs.

From <https://azure.github.io/azure-sdk-for-cpp/#getting-started> 

Circular refference 
_____________________________________

Find a pretty name 
, visit https://cla.microsoft.com.

From <https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-security-keyvault-certificates/4.0.0-beta.1/index.html> 
______________________________________
Keyvaulkt keys samples links

Don't work 

________________________
Keys 

 [soft-delete][soft_delete]

From <https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-security-keyvault-keys/4.2.0/index.html#delete-a-key> 

__________________________
Keys 

## Troubleshooting
### General

From <https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-security-keyvault-keys/4.2.0/index.html#delete-a-key> 

++_______________________
Keys 

```cpp try 

From <https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-security-keyvault-keys/4.2.0/index.html#delete-a-key> 

_________________________________
Ssecrets 

Ensure first segment the same in all 
________________________________
Secrets 

Link to code samples code base
