### ISSUE TITLE
Vcpkg manifests: re-add version constraints

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2735]
Re-add `builtin-baseline` and `version>=`.

We had to remove them because vcpkg found a bug in that functionality, so they had to remove them from our manifests (https://github.com/microsoft/vcpkg/pull/19299) until the proper fix is in place - https://github.com/microsoft/vcpkg-tool/pull/151 (plus, confirm with Robert Schumacher that we are good to go).

**Comment by ras0219-msft** [comment]
Note that in addition to waiting for https://github.com/microsoft/vcpkg-tool/pull/151 to merge the new tool version needs to roll out (typically 1-2 weeks unless a critical issue forces an earlier deployment).
