### ISSUE TITLE
Fix azure-storage-queues vcpkg build

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2739]
Queues lib was never released, and I understand it is in early stages of development, but it would be good to fix the vcpkg build for it. Because it fails our vcpkg daily verification PR (https://github.com/microsoft/vcpkg/pull/17119), making it harder to distinguish between signal and noise.

I don't think it will take much time to fix. I can take a look.
It could be 0.5-4 hours for all. 8 hours in the unlikely worst case.

Other possible workaround would be to disable the vcpkg manifest generation in the Queues' cmakefile, and it should prevent vcpkg package from being pushed for daily validation.

I think it is best to get our daily vcpkg validation PR green at least one week before the next release.

**Comment by Jinming-Hu** [comment]
Will this PR https://github.com/Azure/azure-sdk-for-cpp/pull/2749 fix the problem?
