### ISSUE TITLE
Storage Queues lib: add doxygen comments for public API

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2740]
> * We require all public headers to be fully documented before merging. Please add Doxygen.

I want to get API view done first because according to our experience in blob/file services, API review usually takes longer time. I'll make up the docs in another PR.

> * We require a changelog

Ok

_Originally posted by @Jinming-Hu in https://github.com/Azure/azure-sdk-for-cpp/issues/2671#issuecomment-890449855_

**Comment by antkmsft** [comment]
See also https://github.com/Azure/azure-sdk-for-cpp/pull/2671/files#r680119473, that should not be be happening either, when this is done.

**Comment by antkmsft** [comment]
I think Jinming might actually fix this in #2671.

**Comment by RickWinter** [comment]
We require doxygen comments on all public APIs which are checked into main.

**Comment by Jinming-Hu** [comment]
done in #2671
