### ISSUE TITLE
Installing latest Keyvault-Keys library through vcpkg results in linker errors to credential classes

### ISSUE THREAD

**Issue by kyle-patterson** [Azure/azure-sdk-for-cpp#2741]
**Describe the bug**
When installing keyvault-keys 4.0.0 through vcpkg, the linker will not find ClientSecretCredential or ManagedIdentityCredential.

***Exception or Stack Trace***
Exception when building: 

unresolved external symbol "const Azure::Identity::ClientSecretCredential::`vftable'" (??_7ClientSecretCredential@Identity@Azure@@6B@) referenced in function "public: __cdecl Azure::Identity::ClientSecretCredential::ClientSecretCredential(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct Azure::Core::Credentials::TokenCredentialOptions const &)" (??0ClientSecretCredential@Identity@Azure@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00AEBUTokenCredentialOptions@Credentials@Core@2@@Z)

Error LNK2019	unresolved external symbol "public: __cdecl Azure::Identity::ManagedIdentityCredential::ManagedIdentityCredential(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct Azure::Core::Credentials::TokenCredentialOptions const &)" (??0ManagedIdentityCredential@Identity@Azure@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUTokenCredentialOptions@Credentials@Core@2@@Z) referenced in function "void __cdecl std::_Construct_in_place<class Azure::Identity::ManagedIdentityCredential,char * &>(class Azure::Identity::ManagedIdentityCredential &,char * &)" (??$_Construct_in_place@VManagedIdentityCredential@Identity@Azure@@AEAPEAD@std@@YAXAEAVManagedIdentityCredential@Identity@Azure@@AEAPEAD@Z)

**To Reproduce**
1. install package: `vcpkg install azure-security-keyvault-keys-cpp (any triplet)`
2. In cmakelists:
```
add find_package(azure-security-keyvault-keys-cpp CONFIG REQUIRED)
target_link_libraries(main PRIVATE Azure::azure-security-keyvault-keys)
```
3. Generate cache and build

**Setup (please complete the following information):**
 - OS: Windows 10, 64-bit
 - IDE : Visual Studio 2019
 - Version of the Library used: keys 4.0.0, identity 1.1.0, core 1.2.0

**Additional context**
Building from latest main resolves the issue, it seems to only be when installing through vcpkg. Additionally, explicitly linking to azure-identity (ie, target_link_libraries(main PRIVATE Azure::azure-identity)) will resolve ManagedIdentityCredential, but not ClientSecretCredential.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by vhvb1989** [comment]
Make sure azure-identity is also installed.

The linker is complaining about it can’t find the ClientSecretCredential which comes from azure-identity.

Identity is not a dependency of any other package (for building the library). 

Identity becomes a dependency of the application where some service (like keyvault or storage) is used together with an specific credential.

**Comment by vhvb1989** [comment]
See how Key Vault samples are linking Identity as well like:

target_link_libraries(sample1-hello-world PRIVATE azure-security-keyvault-keys azure-identity)

**Comment by kyle-patterson** [comment]
The CMakeLists in question is already doing that:

```
#------in the root CMakeLists.txt

cmake_minimum_required (VERSION 3.8)

project ("azure-test")

find_package(azure-security-keyvault-keys-cpp CONFIG REQUIRED)
find_package(azure-identity-cpp CONFIG REQUIRED)

# Include sub-projects.
add_subdirectory ("azure-test")
```
```
#-------in the azure-test subdirectory CMakeLists.txt
add_executable (azure-test "azure-test.cpp" "azure-test.h")
target_link_libraries(azure-test PRIVATE Azure::azure-security-keyvault-keys Azure::azure-identity)
```

This helps when trying to link `ManagedIdentityCredential`, but I still get the `ClientSecretCredential` error

**Comment by vhvb1989** [comment]
Can you share the azure-test.cpp as well?

**Comment by vhvb1989** [comment]
And can you also share the output of running `vcpkg.exe list` from within the Vcpkg folder.  I want to see what libraries are installed in there

**Comment by vhvb1989** [comment]
Removing KeyVault code from the sample and trying to just creating a Azure::Identity::ClientSecretCredential as:

auto credential = make_shared<Azure::Identity::ClientSecretCredential>("a", "b", "c");

Failes.

I suspect about the change from PR: https://github.com/Azure/azure-sdk-for-cpp/pull/2448/files#diff-a30072fc7e8ef9f53bd6750f874a751d4b0d2d9ef2df45c41c9571250deff3caR99   moving `_detail::g_aadGlobalAuthority`.

**Comment by antkmsft** [comment]
`g_aadGlobalAuthority` is declared and defined exactly the same way. Let me to look.

**Comment by antkmsft** [comment]
@kyle-patterson, would writing the CMakeFile like this unblock you? -
```
cmake_minimum_required (VERSION 3.15)
project (vcpkg-test LANGUAGES CXX)

add_executable(vcpkg-test "main.cpp")
set_property(TARGET vcpkg-test PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreadedDebug")

set(VCPKG_TARGET_TRIPLET "x64-windows-static")
# install as this:
# vcpkg install azure-identity-cpp:x64-windows-static azure-security-keyvault-keys-cpp:x64-windows-static
find_package(azure-identity-cpp "1.1.0" CONFIG REQUIRED)
find_package(azure-security-keyvault-keys-cpp "4.0.0" CONFIG REQUIRED)

target_link_libraries(vcpkg-test PRIVATE Azure::azure-identity Azure::azure-security-keyvault-keys)
```

I need to take a further look into whether the Azure SDK is consumable at all when built as DLL. It could be not, it could be that I can't configure cmake to explain it what I want to do.

**Comment by kyle-patterson** [comment]
@antkmsft That did the trick, I'm able to compile with that cmakefile

**Comment by antkmsft** [comment]
I more or less isolated the problem - https://github.com/Azure/azure-sdk-for-cpp/issues/2771
I have a solution how to fix, but ideally that fix would not be necessary, and I'd prefer not to fix it that way. But we need to unblock our customers, so we may do it - at least temporary, if there is no other fix.
And I am even more fine with the fix, but what is hard to accept is that there is this inconsistent and unexpected MSVC behavior with no clear boundary, and so far we don't even know why, even though we know how to fix (the straightforward fix is super simple).

**Comment by CorreyL** [comment]
@antkmsft Has the recommendation by @Jinming-Hu here:

https://github.com/Azure/azure-sdk-for-cpp/issues/2771#issuecomment-916655025

Been implemented in the latest release of `azure-security-keyvault-keys-cpp`? I seem to be encountering this issue still on the `4.2.0` release, and I'm not using `CMake` (hence I'm not sure if your workaround [here](https://github.com/Azure/azure-sdk-for-cpp/issues/2741#issuecomment-898064884) would apply to me), though I can try to move to it if absolutely needed.

Here's the linker error I'm seeing in `Visual Studio 2019`:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "const Azure::Identity::ClientSecretCredential::`vftable'" (??_7ClientSecretCredential@Identity@Azure@@6B@) referenced in function "public: __thiscall Azure::Identity::ClientSecretCredential::ClientSecretCredential(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct Azure::Core::Credentials::TokenCredentialOptions const &)" (??0ClientSecretCredential@Identity@Azure@@QAE@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00ABUTokenCredentialOptions@Credentials@Core@2@@Z)	AzureKeyVaultHSM	C:\Users\Correy\source\repos\AzureKeyVaultHSM\AzureKeyVaultHSM.obj	1	
```

Some ancillary information if it helps:

### My `main.cpp` (using Visual Studio 2019)

Worth noting I'm not usually a C++ developer, so admittedly there might be some redundant lines of code here:

```cpp
#include <iostream>
#include <fstream>
#include <json/json.h>

#include <azure/keyvault/keyvault_keys.hpp>
#include <azure/keyvault/keys/key_client.hpp>
#include <azure/keyvault/keys/key_client_models.hpp>
#include <azure/keyvault/keys/key_client_options.hpp>
#include <azure/keyvault/keys/cryptography/cryptography_client.hpp>
#include <azure/core.hpp>
#include <azure/core/credentials/token_credential_options.hpp>
#include <azure/identity/dll_import_export.hpp>
#include <azure/identity/client_secret_credential.hpp>
#include <azure/identity/environment_credential.hpp>
#include <azure/identity/managed_identity_credential.hpp>

using namespace Azure::Core::Credentials;
using namespace Azure::Identity;
using namespace Azure::Security::KeyVault::Keys;
using namespace Azure::Security::KeyVault::Keys::Cryptography;

int main()
{
    AzureSecrets azureSecrets;
    std::string tenantId = azureSecrets.GetTenantId();
    std::string clientId = azureSecrets.GetClientId();
    std::string clientSecret = azureSecrets.GetClientSecret();
    std::string azureKeyvaultUrl = azureSecrets.GetAzureKeyVaultUrl();

    auto credential = std::make_shared<ClientSecretCredential>(tenantId, clientId, clientSecret);
    // KeyClient client(azureKeyvaultUrl, credential);

    return 0;
}
```

It's worth noting that if I instantiate `credential` as an instance of the `EnvironmentCredential` class like so (i.e. from the same `azure/identity` namespace), no errors occur:

![image](https://user-images.githubusercontent.com/16601729/143078242-887f707a-c9ef-47a0-8b44-444d6752871d.png)

### `$ vcpkg list`

```sh
azure-core-cpp:x86-windows                         1.3.1            Microsoft Azure Core SDK for C++
azure-core-cpp[curl]:x86-windows                                    Libcurl HTTP transport implementation
azure-core-cpp[http]:x86-windows                                    All HTTP transport implementations available on ...
azure-core-cpp[winhttp]:x86-windows                                 WinHTTP HTTP transport implementation
azure-identity-cpp:x86-windows                     1.1.0            Microsoft Azure Identity SDK for C++
azure-security-keyvault-certificates-cpp:x86-wi... 4.0.0-beta.1     Microsoft Azure Key Vault Certificates SDK for C++
azure-security-keyvault-common-cpp:x86-windows     4.0.0-beta.3     Microsoft Azure Common Key Vault SDK for C++
azure-security-keyvault-keys-cpp:x86-windows       4.2.0            Microsoft Azure Key Vault Keys SDK for C++
azure-security-keyvault-secrets-cpp:x86-windows    4.0.0-beta.1     Microsoft Azure Key Vault Secrets SDK for C++
curl:x86-windows                                   7.80.0           A library for transferring data with URLs
curl[non-http]:x86-windows                                          Enables protocols beyond HTTP/HTTPS/HTTP2
curl[schannel]:x86-windows                                          SSL support (Secure Channel)
curl[ssl]:x86-windows                                               Default SSL backend
curl[sspi]:x86-windows                                              SSPI support
jsoncpp:x86-windows                                1.9.5            jsoncpp is an implementation of a JSON reader an...
vcpkg-cmake-config:x64-windows                     2021-11-01
vcpkg-cmake:x64-windows                            2021-09-13
zlib:x86-windows                                   1.2.11#13        A compression library
```

Feel free to let me know if I can provide any further details.
