### ISSUE TITLE
azure-security-keyvault-keys doesn't support getting access token for Azure Managed HSM

### ISSUE THREAD

**Issue by qinxgit** [Azure/azure-sdk-for-cpp#2750]
**Describe the bug**
I created a simple project just use the azure-security-keyvault-keys sdk to communicate with Azure Key Vault Managed HSM service. I got error message:
`
Found token with aud=https://vault.azure.net, but expected aud=https://managedhsm.azure.net (Activity ID: 72559188-fe3c-11eb-ab04-6045bd6f6bfb)
`

***Exception or Stack Trace***
>	azure-identity.dll!Azure::Identity::EnvironmentCredential::GetToken(const Azure::Core::Credentials::TokenRequestContext & tokenRequestContext, const Azure::Core::Context & context) Line 72	C++
 	azure-core.dll!Azure::Core::Http::Policies::_internal::BearerTokenAuthenticationPolicy::Send(Azure::Core::Http::Request & request, Azure::Core::Http::Policies::NextHttpPolicy nextPolicy, const Azure::Core::Context & context) Line 24	C++
 	azure-core.dll!Azure::Core::Http::Policies::NextHttpPolicy::Send(Azure::Core::Http::Request & request, const Azure::Core::Context & context) Line 21	C++
 	azure-core.dll!Azure::Core::Http::Policies::_internal::RetryPolicy::Send(Azure::Core::Http::Request & request, Azure::Core::Http::Policies::NextHttpPolicy nextPolicy, const Azure::Core::Context & context) Line 129	C++
 	azure-core.dll!Azure::Core::Http::Policies::NextHttpPolicy::Send(Azure::Core::Http::Request & request, const Azure::Core::Context & context) Line 21	C++
 	azure-core.dll!Azure::Core::Http::Policies::_internal::TelemetryPolicy::Send(Azure::Core::Http::Request & request, Azure::Core::Http::Policies::NextHttpPolicy nextPolicy, const Azure::Core::Context & context) Line 166	C++
 	azure-core.dll!Azure::Core::Http::Policies::NextHttpPolicy::Send(Azure::Core::Http::Request & request, const Azure::Core::Context & context) Line 21	C++
 	azure-security-keyvault-keys.dll!Azure::Core::Http::Policies::_internal::RequestIdPolicy::Send(Azure::Core::Http::Request & request, Azure::Core::Http::Policies::NextHttpPolicy nextPolicy, const Azure::Core::Context & context) Line 373	C++
 	azure-security-keyvault-keys.dll!Azure::Core::Http::_internal::HttpPipeline::Send(Azure::Core::Http::Request & request, const Azure::Core::Context & context) Line 186	C++
 	azure-security-keyvault-keys.dll!Azure::Security::KeyVault::_detail::KeyVaultKeysCommonRequest::SendRequest(const Azure::Core::Http::_internal::HttpPipeline & pipeline, Azure::Core::Http::Request & request, const Azure::Core::Context & context) Line 20	C++
 	azure-security-keyvault-keys.dll!Azure::Security::KeyVault::Keys::KeyClient::SendRequest(Azure::Core::Http::Request & request, const Azure::Core::Context & context) Line 36	C++
 	azure-security-keyvault-keys.dll!Azure::Security::KeyVault::Keys::KeyClient::CreateKey(const std::string & name, Azure::Security::KeyVault::Keys::KeyVaultKeyType keyType, const Azure::Security::KeyVault::Keys::CreateKeyOptions & options, const Azure::Core::Context & context) Line 127	C++
 	AKVClientSample.exe!main() Line 28	C++

**To Reproduce**
Follow the document at https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/keyvault/azure-security-keyvault-keys and run the below code against a Azure Key Vault Managed HSM resource.

***Code Snippet***
```
// AKVClientSample.cpp : Defines the entry point for the application.
//

#include "AKVClientSample.h"
#include <azure/keyvault/keyvault_keys.hpp>
#include <azure/identity.hpp>
#include <string>

using namespace std;
using namespace Azure::Core;
using namespace Azure::Security::KeyVault::Keys;
using namespace Azure::Identity;

int main()
{
    cout << "Hello Azure Key Vault." << endl;
    const string AZURE_KEYVAULT_URL = "https://<your hsm pool>.managedhsm.azure.net";

    // Create a new key client using the default credential from Azure Identity using environment variables previously set,
    // including AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, and AZURE_TENANT_ID.
    
    auto credential = make_shared<EnvironmentCredential>();  
    KeyClient client(AZURE_KEYVAULT_URL, credential);

    try
    {
        // Create a new key using the key client.
        client.CreateKey("key-name", KeyVaultKeyType::Rsa);

        // Retrieve a key using the key client.
        auto key = client.GetKey("key-name");
        cout << "Key " << key.Value.Name() << " id: " << key.Value.Id() << " " << key.Value.Properties.Version << endl;
    }
    catch (const RequestFailedException& ex)
    {
        cout << "Exception: " << ex.Message << endl;
        return 1;
    }
    return 0;
}

```

**Expected behavior**
The code should output a key's properties.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10 
 - IDE : Visual Studio
 - Version of the Library used: 4.0.0

**Additional context**
I believe the scope "https://managedhsm.azure.net" should also be added into the TokenRequestContext.Scopes in key_client.cpp.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vhvb1989** [comment]
@qinxgit the current implementation comes with a hardcoded scope for public cloud as you noticed.

I have created a PR to calculate the scope to be used from the provided Url which is used to create the Key Vault client.

Thank you.

**Comment by qinxgit** [comment]
> @qinxgit the current implementation comes with a hardcoded scope for public cloud as you noticed.
> 
> I have created a PR to calculate the scope to be used from the provided Url which is used to create the Key Vault client.
> 
> Thank you.

Thanks!
