### ISSUE TITLE
Add GCC-8 and GCC-9 to CI checks

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#276]
Current CI tests uses GCC 7 on linux ( GNU 7.5.0 )

We recently had a bug for building on GCC 8.  https://github.com/Azure/azure-sdk-for-cpp/issues/266

We should have CI tests for GCC 8 and GCC 9. (compile only. No need to run tests).

**Comment by danieljurek** [comment]
Swagging this as 3 right now because some other investigation into containers for C revealed that the YAML needed to support containers and not containers in the same build requires duplicating a lot of the YAML syntax and will need to see if there are reasonable ways to DRY it up.
