### ISSUE TITLE
Request for comment by MSVC team: linker error for inline function

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2771]
1. Install Azure-Identity vcpackage built as DLL: `vcpkg install azure-identity-cpp:x64-windows`

2. Create a project that will consume it:
**CMakeLists.txt**:
```
cmake_minimum_required (VERSION 3.15)
project (vcpkg-test LANGUAGES CXX)

add_executable(vcpkg-test "main.cpp")
set_property(TARGET vcpkg-test PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreadedDebugDLL")

set(VCPKG_TARGET_TRIPLET "x64-windows")
find_package(azure-identity-cpp "1.1.0" CONFIG REQUIRED)

target_link_libraries(vcpkg-test PRIVATE Azure::azure-identity)
```
**main.cpp**:
```
#include <azure/identity/client_secret_credential.hpp>

int main()
{
    Azure::Identity::ClientSecretCredential csc("a", "b", "c");
}
```

3. Build:
```
main.cpp.obj : error LNK2019: unresolved external symbol "const Azure::Identity::ClientSecretCredential::`vftable'"
(??_7ClientSecretCredential@Identity@Azure@@6B@) referenced in function
"public: __cdecl Azure::Identity::ClientSecretCredential::ClientSecretCredential(
class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,
class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,
class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,
struct Azure::Core::Credentials::TokenCredentialOptions const &)"
(??0ClientSecretCredential@Identity@Azure@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00AEBUTokenCredentialOptions@Credentials@Core@2@@Z)
vcpkg-test.exe : fatal error LNK1120: 1 unresolved externals
  ninja: build stopped: subcommand failed.

Build All failed.
```

4. Press F12 on `#include <azure/identity/client_secret_credential.hpp>` - edit the header:
Add `AZ_IDENTITY_DLLEXPORT` for the `ClientSecretCredential` class:
```
class AZ_IDENTITY_DLLEXPORT ClientSecretCredential final : public Core::Credentials::TokenCredential {
```

5. Build again - build and link succeeds.

6. But adding `AZ_IDENTITY_DLLEXPORT` should not be required, because we use `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`: https://github.com/Azure/azure-sdk-for-cpp/blob/31dc284164611a2f81feda3abaa7275a17e64fa1/sdk/identity/azure-identity/CMakeLists.txt#L9

7. But why then it works in exact same situation for Azure-Core? Replace .cpp code with this:
```
#include <azure/core/datetime.hpp>

int main()
{
    Azure::DateTime dt(2021);
}
```

8. Build succeeds, no linker errors.

Questions:
1. Is this a MSVC bug?
How is it possible that there is a linker error for an inline function? And it's not that the non-inline function was not dllexported - we can edit the header without SDK recompilation, and it links, so SDK was built correctly.

2. What is the best way to fix it? We could add `AZ_IDENTITY_DLLEXPORT` attribute for Azure-Identity classes, but then how do we know which classes/libraries do need it, and which are not? Other libs do no seem to need it so far, but we wouldn't know for sure until we try to use every inline function. Plus, that attribute affects code readability. Ideally, if it worked without that. But if this is a bug, I guess we'll have to, so that it works on older versions?

More context:
The linker error is because an inline SDK function calls a non-inline SDK function:
https://github.com/Azure/azure-sdk-for-cpp/blob/3f5c5ae66476f7c77a0ffc0bf1d50f17192166b3/sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp#L89-L102
https://github.com/Azure/azure-sdk-for-cpp/blob/3f5c5ae66476f7c77a0ffc0bf1d50f17192166b3/sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp#L56-L61

So, if we call a non-inline SDK function directly from the code (I tried with `GetToken()`), then there is no linker error.
But if we call an inline SDK function which calls a non-inline SDK function, there is a linker error.

The Azure-Core counter-example does the same, and there is never a linker error:
https://github.com/Azure/azure-sdk-for-cpp/blob/3f5c5ae66476f7c77a0ffc0bf1d50f17192166b3/sdk/core/azure-core/inc/azure/core/datetime.hpp#L105-L114
https://github.com/Azure/azure-sdk-for-cpp/blob/3f5c5ae66476f7c77a0ffc0bf1d50f17192166b3/sdk/core/azure-core/inc/azure/core/datetime.hpp#L59-L70

**Comment by Jinming-Hu** [comment]
Hi @antkmsft I finally find a way to get around this issue.
Move the definitions of constructor `ClientSecretCredential()` into .cpp file.

**Comment by RickWinter** [comment]
Closing per Jinming finding a valid fix.

**Comment by CaseyCarter** [comment]
From the initial error message: "error LNK2019: unresolved external symbol `const Azure::Identity::ClientSecretCredential::`vftable'`
(`??_7ClientSecretCredential@Identity@Azure@@6B@`) referenced in function ..." the problematic symbol isn't a function, it's the virtual function table. Polymorphic types in C++ are usually implemented with a "secret" pointer at the beginning of the object representation that points at a table of pointers-to-function that are implementations of the type's `virtual` functions. "virtual function table" == "vftable". The vftable pointer is set in each constructor (and destructor) to track the objects dynamic type as it changes during construction / teardown.

Some implementations (at least those targeting the MSFT ABI and the SYSV ABI that linuxen use) have a handy trick where they avoid emitting a copy of the vtable and implementations of all virtual functions of every type in every TU by emitting that info for a given type only in the first TU that defines a non-inline non-virtual function for that type. The definition of `ClientSecretCredential` looks like:

```c++
  class ClientSecretCredential final : public Core::Credentials::TokenCredential {
  private:
    // non-static data members

    ClientSecretCredential(/* arguments */); // non-inline, non-virtual constructor

  public:
    explicit ClientSecretCredential(/* arguments */)
        : ClientSecretCredential(/* stuff */)
    {} // inline, non-virtual (delegating constructor)

    explicit ClientSecretCredential(/* different arguments */)
        : ClientSecretCredential(/* other stuff */)
    {} // inline, non-virtual (delegating constructor)

    // other non-static member functions
};
```

**WIP: saving this despite not being finished yet**
