### ISSUE TITLE
Build perf improvements

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#2774]
@antkmsft mentioned during standup that we should consider targeting builds to a package and its dependencies instead of building the entire SDK on each build leg. 

For example, this build of `core` is also building `storage` -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1057225&view=logs&j=0fa9045b-9773-5caa-2289-e9e87f13f3cb&t=697f019e-e841-5045-da00-e6ee974c7d15

Since this is domain specific to C++ the C++ team should own how this is done.

**Comment by antkmsft** [comment]
Another thing would be to review and possibly shorten/improve the build matrix.

**Comment by RickWinter** [comment]
> Another thing would be to review and possibly shorten/improve the build matrix.

Lets track that in another issue.  We need this separation of builds for Cognitive dependency as well.

**Comment by antkmsft** [comment]
All credit to @danieljurek, I now see when I only change core, only core gets built. The same for identity. And we also generate build matrix now.
