### ISSUE TITLE
Content-Length response header is disregarded

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#278]
**Describe the bug**
In this PR https://github.com/Azure/azure-sdk-for-cpp/pull/270, all HTTP headers are changed to lowercase,  but you're still trying to read `Content-Length` with uppercase letters [here](https://github.com/Azure/azure-sdk-for-cpp/blob/57bdc0f6d6e485e3946e5f97872a7a4fe3387f60/sdk/core/azure-core/src/http/curl/curl.cpp#L335). Also [here](https://github.com/Azure/azure-sdk-for-cpp/blob/57bdc0f6d6e485e3946e5f97872a7a4fe3387f60/sdk/core/azure-core/src/http/curl/curl.cpp#L344)

***Exception or Stack Trace***
N/A

**To Reproduce**
N/A

***Code Snippet***
```
 auto isContentLengthHeaderInResponse = headers.find("Content-Length");
  if (isContentLengthHeaderInResponse != headers.end())
  {
    this->m_contentLength
        = static_cast<int64_t>(std::stoull(isContentLengthHeaderInResponse->second.data()));
    return;
  }
```

**Expected behavior**
`Content-Length` should not be disregarded.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Any
 - IDE : N/A
 - Version of the Library used: Latest master

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by JinmingHu-MSFT** [comment]
This is blocking Storage team, please fix it ASAP. @vhvb1989 

BTW, it's always necessary to run some basic tests before creating a PR.

**Comment by vhvb1989** [comment]
@JinmingHu-MSFT https://github.com/Azure/azure-sdk-for-cpp/pull/279

Couldn't run storage CI tests because this is a breaking change. So it was expected so see them fail.  Please approve this PR so I can merge.

**Comment by JinmingHu-MSFT** [comment]
@vhvb1989 I didn't mean storage CI tests. Azure core has its own test cases. This is a simple bug. It should've been caught by azure core test cases.
