### ISSUE TITLE
[CORE] Azure core is not building on g++ 5

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2785]
g++ 5 is used in CI legs from cognitive lib.

base64.cpp is currently failing due to an ignored returned value.

Tasks:
- [x] Fix the build on g++ 5
- [x] Add g++ 5 to the CI/CD matrix

**Comment by RickWinter** [comment]
@vhvb1989 As part of this work we need to add G++ 5 to the CI/CD matrix

**Comment by vhvb1989** [comment]
> @vhvb1989 As part of this work we need to add G++ 5 to the CI/CD matrix

Done.
