### ISSUE TITLE
BodyStream::ReadToEnd doesn't work anymore

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#280]
**Describe the bug**
`BodyStream::ReadToEnd` returns partial result for chunked response

***Exception or Stack Trace***
N/A

**To Reproduce**
Run the following sample

***Code Snippet***
```
// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

#include "http/pipeline.hpp"

#include <array>
#include <http/curl/curl.hpp>
#include <http/http.hpp>
#include <iostream>
#include <memory>
#include <vector>

using namespace Azure::Core;
using namespace Azure::Core::Http;
using namespace std;

int main()
{

  // Create the Transport
  std::shared_ptr<HttpTransport> transport = std::make_unique<CurlTransport>();

  std::vector<std::unique_ptr<HttpPolicy>> policies;

  // Add the transport policy
  policies.push_back(std::make_unique<TransportPolicy>(std::move(transport)));

  auto httpPipeline = Http::HttpPipeline(policies);

  auto context = Context();

  string host("http://anglesharp.azurewebsites.net/Chunked");

  auto request = Http::Request(Http::HttpMethod::Get, host);

  auto response = httpPipeline.Send(context, request);
  auto response_bodystream = response->GetBodyStream();
  auto response_body = BodyStream::ReadToEnd(context, *response_bodystream);

  cout << response_body.data() << endl;

  return 0;
}
```

**Expected behavior**
```
Chunked transfer encoding test
This is a chunked response after 100 ms.
This is a chunked response after 1 second. The server should not close the stream before all chunks are sent to a client.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/52266153/87385951-f788dd00-c5d1-11ea-957c-ceb6445129fe.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : N/A
 - Version of the Library used: latest master branch

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by vhvb1989** [comment]
will be Fixed by https://github.com/Azure/azure-sdk-for-cpp/pull/273
