### ISSUE TITLE
C++: quickstart/blob-storage example crashing on Raspberry Pi 3

### ISSUE THREAD

**Issue by dhavalkaneria** [Azure/azure-sdk-for-cpp#2835]
**Query/Question**
Hello I have tried to compile Azure c++ sdk for blob storage and keyvault on raspberry pi 3 . From time to time, the application crashes. Sometimes it prints "corrupted size vs. prev_size", sometimes I get a "Segmentation fault".  So my question is Azure C+= SDK is supporting 32bit Raspberry Pi OS Lite version?

The operating system is Raspberry Pi OS Lite 32-bit (release December 2nd 2020).

During Compile time I have added -mcpu=native flag into CMakeLists.txt without this flag, it won't allow me to compile as other compiler errors.

***Why is this not a Bug or a Feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: Raspberry Pi OS Lite 32-bit 
 - IDE : vim
 - Azure SDK latest Release
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by Jinming-Hu** [comment]
@RickWinter Do we support or plan to support Respberry Pi?

**Comment by vhvb1989** [comment]
Raspberry Pi OS comes from Debian which we do support but only for 64bit.  We don't support Linux 32bits.
https://azure.github.io/azure-sdk/cpp_implementation.html#supported-platforms
