### ISSUE TITLE
Azure C++ sdk for Secret related operation (Like GetSecret() )not working on Ubunut 20.04 but same code working on ubuntu18.04

### ISSUE THREAD

**Issue by dhavalkaneria** [Azure/azure-sdk-for-cpp#2848]
**Query/Question**
Azure C++ sdk for Secret related operation (Like GetSecret() )not working on Ubunut 20.04 but same code working on ubuntu 18.04.
I am getting KeyVault Client Exception on Ubuntu 20.04 VM system. Also not printing any reason phrase. same code working properly with Ubuntu 18.04 VM.  

uname -a  for Ubuntu 20.04 [ Linux dhaval-VirtualBox 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux]

for Ubuntu 18.04 [Linux dhaval-VirtualBox 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux]
Is there anything I need to take care to install any library?
Azure c++ SDK supported higher version like Ubuntu 20.04 ?

Code:
         SecretClient secretClient(keyVaultURL, credential);
        std::cout << "after constructor" << std::endl;
        // just a response, with a secret
        auto response = secretClient.SetSecret("Test1","Test2");
Errors Message:

Access Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL3ZhdWx0LmF6dXJlLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzU4MjBhMjM2LTdiNDktNDgxZC1iYWRlLWQ5MDVlNWEzNzg3NS8iLCJpYXQiOjE2MzExMDYzNjIsIm5iZiI6MTYzMTEwNjM2MiwiZXhwIjoxNjMxMTEwMjYyLCJhaW8iOiJFMlpnWUpqdTZzS2hrVkM4OFBvQnBXVjdmMjY2QndBPSIsImFwcGlkIjoiNzIwNjk1YTctMmM3Mi00NzU2LTk2YTgtZmNlNTY4NDI3MjFlIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNTgyMGEyMzYtN2I0OS00ODFkLWJhZGUtZDkwNWU1YTM3ODc1LyIsIm9pZCI6IjA2NjU1NzlhLTVlYWMtNDIxMy05ZGY4LTE1NzdiMDdhMTU4YSIsInJoIjoiMC5BVG9BTnFJZ1dFbDdIVWk2M3RrRjVhTjRkYWVWQm5KeUxGWkhscWo4NVdoQ2NoNDZBQUEuIiwic3ViIjoiMDY2NTU3OWEtNWVhYy00MjEzLTlkZjgtMTU3N2IwN2ExNThhIiwidGlkIjoiNTgyMGEyMzYtN2I0OS00ODFkLWJhZGUtZDkwNWU1YTM3ODc1IiwidXRpIjoiTDdsd1BKb194MEd2ZWpXTW5NaldBQSIsInZlciI6IjEuMCJ9.MvMoPY6C-8ep1Ivk6KGNNDB7njbbfi9e8iPhGF1snTrCUlnDrPDUUiiUZZJk3V7mKe_pj3Bgrqt8pMjDK591vkBObCNz3wq6KPMTUTYE_b-vm1KSLBhr29iG41I8g63K8i9zWuoJE5zK_89ClwGwKbbxe_7Q_m-Fz28OYLmRr_Y1gGLyPVmizIOrQPW109LUhGN8kr1mhIeokcS45GjdXcMHd0Mpbq_wiisxCnO_aErVLyVCMSm7AcxCdK9PJbe-CljtetjSrJt5tUm6cM3dmxHEbckBqnbNXHpPyDghYne_oFI67XjoiOOClrISC55XfKRUfwvkxI9REjNqSIOpnQ
Status Code: 0, Reason Phrase: 
KeyVault Client Exception error:

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 20.04 and Ubuntu 18.04
 - IDE : Visual Code
 - latest release
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [* ] Query Added
- [ *] Setup information Added

**Comment by gearama** [comment]
Hello, 

At first look there shouldn't be any diffrence in behavior between ubuntu 20 and 18 regarding the secrets sdk. 
That being said, i'll do some investigation and keep this issue updated. 

Thank you for the report.

**Comment by gearama** [comment]
Just to make sure all is proper , can you point me to the code creating the client ? 
keyvaultURL and credential , how are they initialized before being passed  to the client
SecretClient secretClient(keyVaultURL, credential);

**Comment by gearama** [comment]
Also how are you using our code ? using vcpkg ? copy the code locally etc ?

**Comment by dhavalkaneria** [comment]
@gearama Thank you for the response. My code looks like this.

try
    {
        std::cout << tenantId << clientId << clientSecret << keyVaultURL << keyName << std::endl;
        auto credential = std::make_shared<Azure::Identity::ClientSecretCredential>(tenantId, clientId, clientSecret);
        SecretClient secretClient(keyVaultURL, credential);
        std::cout << "after constructor" << std::endl;
        // just a response, with a secret
        auto response = secretClient.SetSecret("Test1","Test2");
        std::cout << "Set Done" << std::endl;
        response = secretClient.GetSecret(keyName);
        std::cout << "SECRETKEYNAME: "<< keyName << " SECRETKEYVALUE: " << response.Value.Value << std::endl;
        retValue = 0;
    }
    catch (const Azure::Core::Credentials::AuthenticationException &exception)
    {
        // (invalid credential parameters, insufficient permissions).
        std::cout << "KeyVault Authentication error: " << exception.what() << std::endl;
        return retValue;
    }
    catch (Azure::Core::RequestFailedException const& e)
    {
        std::cout << "Status Code: " << static_cast<int>(e.StatusCode)
              << ", Reason Phrase: " << e.ReasonPhrase << e.ErrorCode << std::endl;
        std::cout << "KeyVault Client Exception error:" << std::endl << e.Message << std::endl;
        return retValue;
    }
    catch (std::exception const& e)
    {
        std::cout << "Exception error:" << std::endl << e.what() << std::endl;
        return retValue;
    }

-->I am using C++ SDK on local and building and compiling using the CMake tool. after that, I am using the necessary static libraries for my project. code looks like above.
--> same steps I used in ubuntu 18.04 and code giving me some secret value based on the secret name but not on ubuntu 20.04.
--> One more thing is the same steps I followed on the Raspberry Pi 64bit OS device (buster Debian Linux) here also I am getting the same exception as Ubuntu 20.04. So If I correlated both things then I believe the Issue coming with a higher Linux kernel version...

**Comment by dhavalkaneria** [comment]
One more thing I want to add is I am also Using Blob Storage Library with this key vault library. It was working fine with Ubuntu 20.04, Raspberry 64bit OS, and Ubuntu 18.04. this is a little strange for me.

**Comment by dhavalkaneria** [comment]
@gearama  Hey more thing I got news from other issues which I raised #2835.  They are saying https://azure.github.io/azure-sdk/cpp_implementation.html#supported-platforms only this much-supported version. 

Again 2 questions arise:
1) only supported in Ubuntu 18.04 but also storage library working on Ubuntu 20.04 also but not key vault library.
2) Debian 9+ supported but still key vault related Library not working properly.  

Sorry For the more comments. It was just my thought to clear your thought.

**Comment by gearama** [comment]
Thank you for the info, looking into it

**Comment by gearama** [comment]
Hello, 

After investigating the issue , the conclusion is that the default version of CURL on the system is out of date, please use vcpkg to get curl, or install version 7.78 of curl . 

Thank you, 
George Arama

**Comment by dhavalkaneria** [comment]
@gearama  Any update on this? did you found anything?

**Comment by dhavalkaneria** [comment]
I also upgrade curl version 7.79.0

dhaval@dhaval-VirtualBox:~/Documents/OCT_Acquisition_Device/source/KeplerDeviceCloud/build/bin$ curl --version
curl 7.79.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2021-09-15
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
WARNING: curl and libcurl versions do not match. Functionality may be affected.


------------------------------------------------------------------------------------------------------

Still getSecret not working and getting client exception

**Comment by gearama** [comment]
Hello @dhavalkaneria  we are still investigating the issue , preliminarily you can use the vcpkg version of curl, and libcurl. 
In the previous message you get a warning regarding impacted functionality due to mismatching versions. 
We are testing multiple combinations to try and determine what the underlying issue is.
