### ISSUE TITLE
Add support for multi-tenant authentication to Key Vault

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-cpp#2902]
Support for multi-tenant authentication may have been added to your language's version of Azure.Core. Since support for multi-tenant authentication has been a frequent customer ask in some languages, let's add support in all languages where possible.

See https://github.com/Azure/azure-sdk-for-net/issues/18359 for more information and help for how to conceptually implement it.

**Comment by gearama** [comment]
this item is composed of 3 main pillars 

- [ ] Add handling of challenges in azure core bearer_token_authentication_policy ( send non auth request , obtain challenge out of 401 response header, cache)

- [ ] Add handling of challenges to keyvault(identity client_secret_credentials) by determining which fields are used from the challenge response and send an auth request using the data from the challenge

- [ ] Once the first two are in place we can add multi tenant auth by using challange information about what / where to send

https://microsoft-my.sharepoint.com/:v:/p/gearama/EWRAw7ujQ7BCpVBAvmvGaMIBZ-dw5I03UUv_1t4X0CURfg

**Comment by gearama** [comment]
I am apparently unable to get this item done, someone else will have to figure out this multi tenant magic.

**Comment by gearama** [comment]
i'm unable to get this working. i had to abbandon the PR . someone who has better understanding of auth should handle it. the PR i had , while functional had to be closed due to the level of comments and changes requested
