### ISSUE TITLE
Uploading a blob fails when connecting to a storage account on Ubuntu 20.04

### ISSUE THREAD

**Issue by kyle-patterson** [Azure/azure-sdk-for-cpp#2916]
**Describe the bug**
When trying to UploadFrom with a connection established using a connection string from a linux (Ubuntu 20.04) environment, an exception is hit that Core is not able to connect. The same code built for windows-x64 (static) will run without issue.

***Exception or Stack Trace***
```
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Fail to get a new connection for: httpscppstudy.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)
```

**To Reproduce**
Build and execute the below code snippet on Ubuntu 20.04

***Code Snippet***
```
auto serviceClient = BlobServiceClient::CreateFromConnectionString(connStr);
auto containerClient = serviceClient.GetBlobContainerClient(containerName);
auto blobClient = containerClient.GetBlockBlobClient(blobName);

std::vector<uint8_t> buffer(blobContent.begin(), blobContent.end());
blobClient.UploadFrom(buffer.data(), buffer.size());
```

**Expected behavior**
Behavior should be identical with windows 10 executable, which uploads the blob content to a container

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE : CMAKE & vim
 - Version of the Library used: Storage 12.2.0, Core 1.2.1, (x64-linux)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by vhvb1989** [comment]
@kyle-patterson  can you tell how are you consuming the Azure SDK client?   Is it from VCPKG?  or are you cloning source, building and installing with cmake and then consuming?   or are you using the source samples to build and run?

Also, can you tell how are you installing/setting the Azure SDK dependencies?  ( libcurl, openssl, etc? )  Are you installing the packages with apt-get install?  or are you using vcpkg?   
Are you able to share the dependency versions for libcurl and openssl?

thank you
