### ISSUE TITLE
[Cognitive] - Remove/Replace HTTP layer

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2925]
Target headers:
- azure_c_shared_utility_http_proxy_io_wrapper:  Proxy
- azure_c_shared_utility_httpapi_wrapper:  Http abstraction
- azure_c_shared_utility_httpapiex_wrapper: Http retry
- azure_c_shared_utility_httpheaders_wrapper:  Http headers support (add, find, remove)

These features can be replaced by the Http functionality from Azure SDK Core

**Comment by RickWinter** [comment]
@LarryOsterman this is marked done in the project but is still open.  Should this be closed?
