### ISSUE TITLE
[Cognitive] - Replace `azure_c_shared_utility_sha_wrapper`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2929]
Speech SDK requires `SHA1`.

The c shared utility lib provides multiple SHA implementations (SHA1, SHA-224, SHA-256, SHA-384, SHA-512)
*Own implementation.

Azure SDK Core provides only Sha256Hash, Sha384Hash and Sha512Hash.
Azure SDK Core uses openSSL to implement the SHA hashing

Options to replace/update:
- Make Azure SDK Core to support `SHA1` (using openSSL)
- Make Azure SDK Core to support `SHA` (internal impl for no extra dependency)
- Update Speech SDK to use `SHA256` or greater instead of SHA1.

**Comment by LarryOsterman** [comment]
Work needed:

1. Create `Azure::Core::Cryptography::_internal::Sha224`, and `Azure::Core::Cryptography::_internal::Sha1` for both bcrypt and openssl.
2. Move `Azure::Core::Cryptography::_internal::Sha*` types to public API surface
3. Update existing uses of the `_internal::Sha*` types to use the public Sha* types.

Publish an SDK update defining the new APIs so cognitive can consume it.

**Comment by LarryOsterman** [comment]
I don't believe this cognitive request is still open.
