### ISSUE TITLE
[Cognitive] - Remove `azure_c_shared_utility_string_token_wrapper`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2932]
Speech SDK requires the `string_token.h` header as utility to handle string tokens:

- StringToken_GetFirst(const char* source, size_t length, const char** delimiters, size_t n_delims)
- StringToken_GetDelimiter(STRING_TOKEN_HANDLE token)
- StringToken_GetValue(STRING_TOKEN_HANDLE token)
- StringToken_GetLength(STRING_TOKEN_HANDLE token)
- StringToken_GetNext(STRING_TOKEN_HANDLE token, const char** delimiters, size_t n_delims)
- StringToken_Destroy(STRING_TOKEN_HANDLE token)

The  Speech SDK is using these API to parse URL.  The implementation can be replaced/updated to use the Azure SDK URL from CORE

**Comment by vhvb1989** [comment]
in feature branch

**Comment by LarryOsterman** [comment]
QQ: If this is in the feature branch, should this issue still remain open?
