### ISSUE TITLE
[Cognitive] - Remove `azure_c_shared_utility_xlogging_wrapper`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2936]
Replace/Update the logging layer using the Azure SDK core log support.

**Comment by LarryOsterman** [comment]
Functional gaps in Azure logging:
1) Azure Logging only has Log::Write(Level, std::string), it does not have:
    1) printf style logging support,
    1) LogBinary - logs binary data in same fashion as windbg.
    1) LogLastError (and LogErrorWinHTTPWithGetLastErrorAsString - we have this somewhat in the HTTP exception handler)
    1) Logging with call stack traces.

It's not clear which of these (if any) are required by Cognitive Services.

**Comment by LarryOsterman** [comment]
Closing for now because it's not clear this will be an issue moving forward.
