### ISSUE TITLE
ARM UWP build fails -- message : see reference to function template instantiation 'std::_Tree_node<std::pair

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#2945]
Repro steps: 

```pwsh 
$env:VCPKG_DEFAULT_TRIPLET = 'arm-uwp'
$env:CMAKE_GENERATOR = 'Visual Studio 16 2019'
$env:CMAKE_GENERATOR_PLATFORM = 'arm'
$env:CMAKE_SYSTEM_NAME = 'WindowsStore'
$env:CMAKE_SYSTEM_VERSION = '10.0'

cmake .. -DBUILD_TRANSPORT_WINHTTP=ON
cmake --build . --parallel 8
```

Sample output: 

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\ostream(284,1): error C2220: the following warning is treated as an error [D:\code\azure-sdk-for-cpp\build\sdk\template\azure-template\test\azure-template-test.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\ostream(269): message : while compiling class template member function 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(
int)' [D:\code\azure-sdk-for-cpp\build\sdk\template\azure-template\test\azure-template-test.vcxproj]
D:\code\azure-sdk-for-cpp\build\_deps\googletest-src\googletest\include\gtest/internal/gtest-internal.h(534): message : see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<
(int)' being compiled [D:\code\azure-sdk-for-cpp\build\sdk\template\azure-template\test\azure-template-test.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\ostream(641): message : see reference to class template instantiation 'std::basic_ostream<char,std::char_traits<char>>' being compiled [D:\code\azure-sdk-for-cpp\build\sdk\template\a
zure-template\test\azure-template-test.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\ostream(284,1): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [D:\code\azure-sdk-for-cpp\build\sdk\template\azure-template\test\azure
-template-test.vcxproj]
D:\code\azure-sdk-for-cpp\sdk\core\azure-core\src\http\curl\curl.cpp(591,9): error C2220: the following warning is treated as an error [D:\code\azure-sdk-for-cpp\build\sdk\core\azure-core\azure-core.vcxproj]
D:\code\azure-sdk-for-cpp\sdk\core\azure-core\src\http\curl\curl.cpp(591,9): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [D:\code\azure-sdk-for-cpp\build\sdk\core\azure-core\azure-core.vcxproj]
  win_http_transport.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xtree(1673,1): error C2220: the following warning is treated as an error [D:\code\azure-sdk-for-cpp\build\sdk\core\azure-core\azure-core.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xtree(1632): message : see reference to function template instantiation 'std::_Tree_node<std::pair<const std::string,std::string>,std::_Default_allocator_traits<_Alloc>::void_pointer
> *std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::_Copy_nodes<_Moveit>(std::_Tree_node<std::pair<const std::string,std::string>,std::_Default_allocator_traits<_Alloc>::void_pointer> *,std::_Tree_node<std::pair<const std::string,std::string>,std::_Default_allocator_tra
its<_Alloc>::void_pointer> *,_Moveit)' being compiled [D:\code\azure-sdk-for-cpp\build\sdk\core\azure-core\azure-core.vcxproj]
          with
          [
              _Alloc=std::allocator<std::pair<const std::string,std::string>>,
              _Kty=std::string,
              _Ty=std::string,
              _Pr=std::less<std::string>,
              _Moveit=std::_Tree<std::_Tmap_traits<std::string,std::string,std::less<std::string>,std::allocator<std::pair<const std::string,std::string>>,false>>::_Copy_tag
          ]
```

**Comment by vhvb1989** [comment]
@danieljurek  please provide more info about how to reproduce.
I have tried on Windows, setting the env variables you mentioned but I can't reproduce this.  I can't even make CMake to generate for arm-uwp.  Can you describe the entire setup?

what extensions do I need to install for VS?  I am using the MSCV build tools

**Comment by danieljurek** [comment]
Following up from our discussion yesterday: THis is failing because cmake isn't detecting the appropriate ARM compiler. There is also another problem: cmake doesn't treat the `CMAKE_SYSTEM_NAME` and `CMAKE_SYSTEM_VERSION` environment variables as configurations. Those need to be supplied to the cmake command line in a form similar to `-DCMAKE_SYSTEM_NAME`

**Comment by dg0yt** [comment]
vpckg + uwp?
https://github.com/microsoft/vcpkg/pull/16111
https://github.com/microsoft/vcpkg/pull/21857

**Comment by RickWinter** [comment]
@vhvb1989 @gearama This configuration should be added to our matrix.

@danieljurek do we have arm and arm64 hardware to run tests on in the pipeline?

**Comment by danieljurek** [comment]
We do not have ARM or ARM64 hardware in our hosted pipelines at this time.

**Comment by gearama** [comment]
i do not have an ARM machine, if we are provided with hardware then we can test this arch , otherwise our hands are tied. @RickWinter  does out admin provide such machines ? ARM laptop , or desktop ? 
i found this https://www.microsoft.com/en-us/d/surface-pro-x/8xtmb6c575md?activetab=pivot:techspecstab not sure it would work if i can install stuff on it for development though.

**Comment by danieljurek** [comment]
@gearama and I sync'd offline to help reproduce the build issues. @antkmsft is also working on some compile scenarios today as well.

**Comment by gearama** [comment]
@RickWinter is it worth wasting time on UWP in general:  https://www.techradar.com/news/microsoft-is-finally-dropping-uwp-app-support-windows-app-sdk-heres-why 
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/migrate-to-windows-app-sdk-ovw 

Microsoft is dropping UWP and asking devs to migrate to windows 11 SDK , i have a suspicion we won't see much interest in UWP , i'm suprised there is any now given the lack of future for this dead feature

**Comment by RickWinter** [comment]
We should look at usage data.  The backward compatibility for App SDK only goes to Windows 10.

cc: @kyle-patterson , @LarryOsterman

**Comment by LarryOsterman** [comment]
UWP is really ambiguous as a term of art. It could be "something which uses WinRT APIs", it could be "a packaged app", it could be "a packaged app which runs in an appcontainer", it could be "an app which uses Xaml for it's UI". It could be any combination of these.

What does "UWP" mean in the context of this build pipeline? Most of the "recommending people move away from UWP" articles are somewhat ambiguous.
