### ISSUE TITLE
Blob upload fails with socket timeout on AKS

### ISSUE THREAD

**Issue by lordgamez** [Azure/azure-sdk-for-cpp#2977]
**Query/Question**
Hi Team! Currently I am using Azure SDK for C++ in my application for uploading blobs to an Azure Storage account. The application seems to be working on a local machine and even on an Azure VM using managed identity credentials or any other credentials like SAS token. A problem occurs when the application is being run inside a kubernetes pod on AKS. The upload fails with the following message: `Timeout waiting for socket to read.`

This seems to originate from sdk/core/azure-core/src/http/curl/curl.cpp:948

The strange thing is that in a locally ran container the application uploads the blob successfully and even on AKS in the same pod the upload process fails, a blob upload succeeds by using Azure CLI to upload a blob after `az login` with a command like `az storage blob upload --account-name myaccount --container-name data --file test.log --name xyz.log`

Do you have any idea what could be wrong, what could be different on an AKS cluster that needs to be modified, or anything the SDK needs to be configured differently?

***Why is this not a Bug or a feature Request?***
I am not sure if this is a bug or a configuration issue.

**Setup (please complete the following information if applicable):**
 - OS: ubuntu18.04 running on Azure
 - IDE: vscode
 - Version of the Library used: 12.2.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by lordgamez** [comment]
The request that seems to be timing out is the following:
```
INFO  : HTTP Request : GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED
metadata : REDACTED
user-agent : azsdk-cpp-identity/1.2.0-beta.1 (Linux 5.4.0-1059-azure x86_64 #62~18.04.1-Ubuntu SMP Tue Sep 14 17:53:18 UTC 2021
x-ms-client-request-id : c1891a54-0b92-41b8-7172-edda1097c8ed
DEBUG : [CURL Transport Adapter]: Creating a new session
DEBUG : [CURL Transport Adapter]: No Host in request headers. Adding it
DEBUG : [CURL Transport Adapter]: No content-length in headers. Adding it
DEBUG : [CURL Transport Adapter]: Send request without payload
DEBUG : [CURL Transport Adapter]: Parse server response                                   │
WARN  : HTTP Transport error: Timeout waiting for socket to read
INFO  : HTTP Retry attempt #1 will be made in 4094ms
INFO  : HTTP Request : GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED
metadata : REDACTED
user-agent : azsdk-cpp-identity/1.2.0-beta.1 (Linux 5.4.0-1059-azure x86_64 #62~18.04.1-Ubuntu SMP Tue Sep 14 17:53:18 UTC 2021
x-ms-client-request-id : c1891a54-0b92-41b8-7172-edda1097c8ed
```

**Comment by vhvb1989** [comment]
@lordgamez did you create the AKS using `--enable-managed-identity` ??

See: https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by vhvb1989** [comment]
@lordgamez somehow I missed the last comment XD ahaha,,  Thank you!
