### ISSUE TITLE
Feature request: Core SDK should support HTTP request with request body and non-buffered(stream) response

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3000]
Currently we have three [constructor overloads](https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/core/azure-core/inc/azure/core/http/http.hpp#L240):

1. with request body, buffered response
2. without request body, non-buffered response
3. without request body, buffered response

Storage SDK needs HTTP request with request body and non-buffered(stream) response to implement [Query Blob Content](https://docs.microsoft.com/en-us/rest/api/storageservices/query-blob-contents)

**Comment by Jinming-Hu** [comment]
reopen since it was reverted in https://github.com/Azure/azure-sdk-for-cpp/pull/3033

**Comment by Jinming-Hu** [comment]
@vhvb1989 Can you share a timeline for fixing this issue?

**Comment by vhvb1989** [comment]
> @vhvb1989 Can you share a timeline for fixing this issue?

I did in the past with: https://github.com/Azure/azure-sdk-for-cpp/pull/3002

However, I reverted it as it was not yet required from storage. So, feel free to re-apply the changes from that PR together with the Storage feature that it requires it.

**Comment by Jinming-Hu** [comment]
OK, that works for me.
