### ISSUE TITLE
Installing Azure SDK for C++ in a docker container

### ISSUE THREAD

**Issue by WilfredDube** [Azure/azure-sdk-for-cpp#3005]
**Query/Question**

I would like to know how I may install azure c++ sdk in a docker container. I need it for a C++ services that downloads and processes files in Azure blob storage. **Will the container not become too large?** Also the installation is kind of complex compare to the popular:

```
...    
RUN git clone https://github.com/blah/bla.git \
    && cd blah && mkdir -p build \
    && cd build \
    && cmake .. \
    && cmake --build . --target install 
...
```
**Why is the no cmake installation?**

I have read the installation guide but after following the whole installation procedure in my development environment (Centos 8), cmake fails to find the `azure-storage-blobs-cpp` even after adding the `-DCMAKE_TOOLCHAIN_FILE=[path to vcpkg repo]/scripts/buildsystems/vcpkg.cmake` flag correctly.

After running the `./vcpkg integrate ...` command there is still no header files inside the /usr/local/include or /usr/include and no libraries in the lib or lib64 folder.

Is there an alternative or straight forward way like in the above snippet for installing the SDK in my development environment and then in a Linux based container for deployment?

***Why is this not a Bug or a feature Request?***
Its just an installation problem

**Setup (please complete the following information if applicable):**
 - OS: Centos development environment and Ubuntu docker container
 - IDE : VS Code
 - Version of the Library used: latest
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Query Added
- [*] Setup information Added

**Comment by Jinming-Hu** [comment]
Hi @WilfredDube , can you try `make install`?

@RickWinter This customer is looking for a way to install sdk headers/libs to system path, this is not storage-specific. I think it should be handled by eng-sys or core team.

**Comment by WilfredDube** [comment]
> Hi @WilfredDube , can you try `make install`?
> 
> @RickWinter This customer is looking for a way to install sdk headers/libs to system path, this is not storage-specific. I think it should be handled by eng-sys or core team.

`make && make install` are ok I just need a standard  installation procedure

**Comment by gearama** [comment]
use vcpkg, also in the repo there are several docker container samples that install the sdk 
https://github.com/Azure/azure-sdk-for-cpp/tree/main/.devcontainer
https://github.com/Azure/azure-sdk-for-cpp/blob/main/Dockerfile
https://github.com/Azure/azure-sdk-for-cpp/blob/main/Dockerfile.src
