### ISSUE TITLE
Include the regular cmake installation method

### ISSUE THREAD

**Issue by WilfredDube** [Azure/azure-sdk-for-cpp#3006]
**Is your feature request related to a problem? Please describe.**
I got frustrated when I tried to install the SDK because the installation procedure is different from the popular cmake method of installing C/C++ libraries and SDK's especially in the Linux environment. I would like to use the SDK in my development environment CentOS 8 and then deploy the application in a docker container. The challenge is that the method in the documentation doesn't install objects (header files and library files) in a global `/usr/ ` folder so that its is accessible from anywhere on the computer.
The SDK also depends too much on external dependencies such as `boost` which makes it easy to have version conflicts. and an increase in the size of the installation (e.g in a docker container)
In addition the documentation is very poor, containing snippets of code and documentation of some configurations assumes that the IDE used is VS. 

**Describe the solution you'd like**
There are a couple of solutions I would like to suggest
1. Incorporate two methods of installation i.e. using vcpkg and cmake
2. Reduce the many external library dependencies especially boost, etc (will cause version conflicts with what the developer's application already depends on.
3. Reduce the size of the SDK i.e. for  docker containers
4. Document, document, document. We need complete guides, books, videos and more examples dedicated for each language.

**Describe alternatives you've considered**
This is the easiest method to install especially in a docker container:
```
git clone https://github.com/blah/bla.git \
&& git  submodule update --init
&& cd blah && mkdir -p build \
&& cd build \
&& cmake .. \
&& cmake --build . --target install 
```

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [1 ] Description Added
- [ 1] Expected solution specified

**Comment by ahsonkhan** [comment]
Thanks for adopting the SDK and filing the detailed issue and request to make it better!

> The SDK also depends too much on external dependencies such as `boost` which makes it easy to have version conflicts. and an increase in the size of the installation (e.g in a docker container)

Regarding this, @WilfredDube, the C++ SDK doesn't take a dependency on boost. Can you please clarify and expand on where you end up seeing this being pulled in for you?

**Comment by WilfredDube** [comment]
When I ran:

`./vcpkg/vcpkg install azure-storage-cpp`

and the size of the buildtree folder got to 1.7GB where 1.1 GB of it is from the boost library

**Comment by RickWinter** [comment]
> When I ran:
> 
> `./vcpkg/vcpkg install azure-storage-cpp`

@WilfredDube That package is the previous release of storage SDK.  The latest storage C++ package is **azure-storage-blobs-cpp** available with
`.\vcpkg install azure-storage-blobs-cpp`
