### ISSUE TITLE
Assert on no owner property returned in ListPaths call

### ISSUE THREAD

**Issue by shawncao** [Azure/azure-sdk-for-cpp#3037]
**Describe the bug**
DataLakeFileSystems ListPaths assert on file to have owner property in its return, but in my test case, it doesn't return "owner"

***Exception or Stack Trace***
```
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x000000010148e350 NebulaServer`Azure::Core::Json::_internal::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, Azure::Core::Json::_internal::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const& Azure::Core::Json::_internal::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, Azure::Core::Json::_internal::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >::operator[]<char const>(this=0x0000600000018160, key="owner") const at json.hpp:19460:9
   19457              // at only works for objects
   19458              if (_az_JSON_HEDLEY_LIKELY(is_object()))
   19459              {
-> 19460                assert(m_value.object->find(key) != m_value.object->end());
   19461                return m_value.object->find(key)->second;
   19462              }
   19463
Target 0: (NebulaServer) stopped.
```

**To Reproduce**
N/A

***Code Snippet***
```
  std::vector<FileInfo> fileInfos;
  auto dirClient = std::make_shared<DataLakeDirectoryClient>(
    client_->GetDirectoryClient(path));

  // azure datalake will throw if the path not exists
  // different behavior from S3/GCS, wish there is a quick method like `Exists`
  try {
    // opts may contain continuation token since azure return maximum 5K results per request
    ListPathsOptions opts;
    while (true) {
      auto res = dirClient->ListPaths(false, opts);
     ...
```

**Expected behavior**
clear requirement or not assert, after all, we don't need "owner" info anyways

**Screenshots**

**Setup (please complete the following information):**
"GIT_TAG azure-storage-files-datalake_12.2.0"

**Additional context**
should be straightforward, not sure why "owner" is not returned though.

```
    frame #5: 0x000000010148ea24 NebulaServer`Azure::Storage::Files::DataLake::_detail::DataLakeRestClient::FileSystem::PathItemFromJson(node=0x0000600000018160) at datalake_rest_client.hpp:716:26
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by shawncao** [comment]
FYI. I used this simple change to unblock Nebula integration with Azure, but if you think it's worth to merge this PR let me know, otherwise, I'll drop it. https://github.com/Azure/azure-sdk-for-cpp/pull/3038

**Comment by Jinming-Hu** [comment]
Hi @shawncao , are you running your application against Azure Storage service? I don't understand why the "owner" field was not returned.

**Comment by shawncao** [comment]
Hey @Jinming-Hu thanks for looking into this issue. 
FYI. the code where we use azure SDK is here https://github.com/varchar-io/nebula/blob/master/src/storage/azure/DataLake.cpp#L94-L132

The storage we're using is DataLake Gen2, not sure how much we can share since it may contain company data. I think it's safe to share the endpoint which is https://testnebula.dfs.core.windows.net/, like usually, just create a container, upload a file, and use above code to list the folder. I don't think we did anything special.

+ @ritvik-statsig

**Comment by Jinming-Hu** [comment]
Please check if you have enabled HNS for your storage account

![Screenshot 2021-11-04 123809](https://user-images.githubusercontent.com/52266153/140258905-c745bd90-47b4-4e46-b0d3-85f1f6b3811e.png)

**Comment by shawncao** [comment]
it is disabled.

**Comment by Jinming-Hu** [comment]
DataLake clients only work for storage accounts with HNS enabled. Please use blob clients instead
