### ISSUE TITLE
[Storage Blob Service] Bearer challenge Support in storage SDK

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#304]

**Comment by vhvb1989** [comment]
is this for getting Bearer token?  @antkmsft  isn't that the secret credential?

**Comment by JinmingHu-MSFT** [comment]
I don't know what this feature involves either. It's just a feature in storage team's backlog that i'm going to work on in the future.

**Comment by JinmingHu-MSFT** [comment]
> is this for getting Bearer token? @antkmsft isn't that the secret credential?

No, it's different.

**Comment by JinmingHu-MSFT** [comment]
This feature needs to be implemented in Azure.Identity first, and then Storage is going to integrate the new TokenPolicy.

**Comment by Jinming-Hu** [comment]
Hi @XiaoningLiu since you're the feature owner, can you elaborate what needs to be done in Identity sdk and what needs to be done in storage sdk?

**Comment by Jinming-Hu** [comment]
relevant to https://github.com/Azure/azure-sdk-for-cpp/issues/304

**Comment by RickWinter** [comment]
@Jinming-Hu @XiaoningLiu What is the timelime for this work?  What is the priority for this ask?

**Comment by katmsft** [comment]
Confirmed by @XiaoningLiu that JS currently does not have it supported. However, @RickWinter you might want to follow up with Ashish regarding the priority instead.

**Comment by antkmsft** [comment]
Part of, and basically is largely #1601
