### ISSUE TITLE
Leverage the record and playback framework to improve unit test coverage of storage libraries

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3051]
@gearama can help fill in the details since we followed this approach to improve e2e coverage for the KeyVault certificates library, without having to only rely on nightly live tests.

Examples:
https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings

https://github.com/Azure/azure-sdk-for-cpp/blob/4614b80d2214f28e3613f20c9ff3a3c79225c43f/sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.CreateCertificate.json#L1-L6

This will help us improve code coverage on regular runs as well.

@vhvb1989 can provide guidance on the framework itself. For reference:
- https://github.com/Azure/azure-sdk-for-cpp/issues/1386
- https://github.com/Azure/azure-sdk-for-cpp/pull/2685

**Comment by vhvb1989** [comment]
This is already done
