### ISSUE TITLE
Enable test coverage checks for storage libraries

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3052]
https://github.com/Azure/azure-sdk-for-cpp/blob/4614b80d2214f28e3613f20c9ff3a3c79225c43f/sdk/storage/ci.yml#L40

For example look at others:
https://github.com/Azure/azure-sdk-for-cpp/blob/4614b80d2214f28e3613f20c9ff3a3c79225c43f/sdk/identity/ci.yml#L36-L37

Related testing issue:
https://github.com/Azure/azure-sdk-for-cpp/issues/3051

Follow-up from https://github.com/Azure/azure-sdk-for-cpp/pull/2992

cc @Jinming-Hu, @danieljurek

**Comment by RickWinter** [comment]
Issue has been addressed
