### ISSUE TITLE
Intermittent error during "Install dependencies from apt" step on Ubuntu18_gpp5

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3055]
From https://github.com/Azure/azure-sdk-for-cpp/pull/3049/checks?check_run_id=4110362871

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1179776&view=logs&j=ec4a1e72-3a6c-5a5c-62dd-ba3b2af5e922&t=33a4ea97-58a7-53d7-9020-d9e09cd8df0a

```text
Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
##[error]PowerShell exited with code '1'.
```

Looks like this is a first occurrence of such an error (at least that I have seen), might want to keep an eye on repeated errors to help prioritize.

cc @danieljurek

**Comment by ahsonkhan** [comment]
@antkmsft, @vhvb1989, @gearama have any of you seen such build errors before in PR CI runs?

**Comment by danieljurek** [comment]
I've seen 2 instances of this happening in the last 100 days. 

* https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/1179776/logs/215
* https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/1156800/logs/268

This looks like a problem with a race condition within the OS or tools. The solution here would be to wait for the lock file (for up to _n_ seconds) and then run the `apt` commands.
