### ISSUE TITLE
Intermittent request timeout during the `Publish test results` step on mac, for certain legs.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3067]
During `Publish test results`  step on `Validate macOS11_release`, from https://github.com/Azure/azure-sdk-for-cpp/runs/4111371465

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1180062&view=logs&j=e109b754-e5a4-58aa-96d5-f28daf32bc3c&t=7114d34e-4489-5091-4ca1-a79515325428&l=13

```text
/usr/local/bin/dotnet --version
5.0.402
Async Command Start: Publish test results
Async Command End: Publish test results
##[error]The HTTP request timed out after 00:00:30.
Finishing: Publish test results
```

cc @danieljurek

**Comment by kurtzeborn** [comment]
We're just using the vanilla DevOps tasks, so there's not a lot we can do here.  If C++ has excessively large test result files that might be a cause, but in the example above, it only took 30 seconds to upload (or rather fail).

Now that we have @hallipr's Kusto log querying for our DevOps pipelines, it should be pretty easy to figure out if we're seeing this anywhere else.
