### ISSUE TITLE
Remove HTTP header `Content-Length` for GET requests

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#307]

**Comment by vhvb1989** [comment]
Can you add more description about this?
Will you expect transport layer to add the content-length header?  or how are you removing this?

**Comment by JinmingHu-MSFT** [comment]
For other HTTP clients, we don't need to set `Content-Length` header for GET or HEAD requests. @katmsft and I are thinking if we need to be consistent with other HTTP clients.

**Comment by vhvb1989** [comment]
yeah, you can remove it from GET/HEAD

**Comment by JinmingHu-MSFT** [comment]
done in https://github.com/Azure/azure-sdk-for-cpp/pull/312
