### ISSUE TITLE
CI gate fail: GenerateReleaseArtifacts -> Prevent changes to eng/common outside of azure-sdk-tools repo

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#3091]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1187010&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=9610202e-2967-5c36-f0d3-91fb4b691a2b&l=25

**Comment by ahsonkhan** [comment]
For context: https://github.com/Azure/azure-sdk-for-cpp/pull/3090#issuecomment-964663029

**Comment by chidozieononiwu** [comment]
Looks like this is the same issue as https://github.com/Azure/azure-sdk-tools/issues/1236
