### ISSUE TITLE
Fix artifact reposting problem

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#3096]
Use [publish-artifact.yml](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/publish-artifact.yml) 

Build -- https://dev.azure.com/azure-sdk/public/_build/results?buildId=1187010&view=logs&j=a6128be7-2ff2-5efb-d1b0-5709ac892010&t=f173abd7-365c-5e77-6bfe-905b7faa3229

PR where this came up -- https://github.com/Azure/azure-sdk-for-cpp/pull/3090

**Comment by RickWinter** [comment]
Failed in pipeline:
[https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2210562&view=logs&j=4c653870-7574-5bce-127e-cb8dfa6c88eb&t=50521935-f168-5148-939c-e9b899e33351&l=30](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2Finternal%2F_build%2Fresults%3FbuildId%3D2210562%26view%3Dlogs%26j%3D4c653870-7574-5bce-127e-cb8dfa6c88eb%26t%3D50521935-f168-5148-939c-e9b899e33351%26l%3D30&data=05%7C01%7CRick.Winter%40microsoft.com%7C5c3811bc730348aa219808db19c63e8a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638132111465218558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8OUj6D1joLv6dOUDGTad6xsx%2BRXrWgUiUOIU4sQoy50%3D&reserved=0)
