### ISSUE TITLE
ListBlobsByHierarchy does not yield folders

### ISSUE THREAD

**Issue by janbernloehr** [Azure/azure-sdk-for-cpp#3103]
**Describe the bug**
Suppose we have the blobs in a container

foo1.txt
foo2.txt
bar/readme.bd

We would expect that `ListBlobsByHierarchy("/")` yields `["foo1.txt", "foo2.txt", "bar"]` - as was the case with `list_blobs_segmented` in azure-storage-cpplite. However, `bar` is missing from the returned results.

***Exception or Stack Trace***
-

**To Reproduce**
-

***Code Snippet***
```
for (auto response = blob_container_client->ListBlobsByHierarchy("/");  response.HasPage(); response.MoveToNextPage()) {
	for (auto const& list_blob_item : response.Blobs)
    {
           std::cout << "item: " << list_blob_item.Name << "\n";
    }
}
```

**Expected behavior**
`ListBlobsByHierarchy("/")` yields `["foo1.txt", "foo2.txt", "bar"]

**Screenshots**
-

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE : VSCode
 - ec9cb17cab24e940895eb2249c096f500f69383edfa66b20cb6456414767ce99

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
Hi @janbernloehr , in Track2 SDK, we decided to split blobs and blob prefixes into two containers, so you should write

```C++
  for (auto response = containerClient.ListBlobsByHierarchy("/"); response.HasPage();
       response.MoveToNextPage())
  {
    for (auto const& blob_item : response.Blobs)
    {
      std::cout << "item: " << blob_item.Name << "\n";
    }
    for (const auto& directory_item : response.BlobPrefixes)
    {
      std::cout << "directory: " << directory_item << "\n";
    }
  }
```
