### ISSUE TITLE
Remove azure-template releases and tags

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#3115]
It is harder even for me to find 1.0 GA tag, because it is on 5th page.
The same must be for the customers - lots of noise in Releases/Tags: https://github.com/Azure/azure-sdk-for-cpp/releases

**Comment by RickWinter** [comment]
@danieljurek  @weshaggard I'm not sure what the practice is for all languages.  Should these be kept if the package isn't published all the way through to vcpkg?

Note, @antkmsft I agree there are lots of entries for template.  However at some point they'll be just as many for all the packages and it becomes just as hard.  Take a cruise through python, .net, java, js, go.  Even if you removed their template packages you'd be hard pressed to find the release b/c there are so many.

**Comment by weshaggard** [comment]
As you mention there are tons of tags in most of our repos and we don't treat template special in those cases as the tags all exist. 

Unfortunately the github UI for tags is not very good but I think the thing to do here to teach folks how to find tags they are interested via commands like `git tag -l azure-identity*` that will list just the tags matching the pattern. Assuming they care about the tag at all. They can also use things like our package index at https://azure.github.io/azure-sdk/releases/latest/cpp.html to find the latest.

**Comment by kurtzeborn** [comment]
Our intention is that these template packages follow all the same patterns and rules as other packages.  Any special cases we introduce make them less of a template and therefore less useful when setting up new packages.

Please reactivate if you disagree with this reasoning.
