### ISSUE TITLE
Can `UpdateReadMe` branch be deleted?

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#3118]
If it is no longer used?

Created by Ahson last updated 9 months ago.

https://github.com/Azure/azure-sdk-for-cpp/branches/all

**Comment by antkmsft** [comment]
There is now also `ahsonkhan-patch-1` branch.

**Comment by ahsonkhan** [comment]
That's from this PR which will be auto-deleted once merged:
https://github.com/Azure/azure-sdk-for-cpp/pull/3154

**Comment by ahsonkhan** [comment]
Compared the contents of the README from the branch and main, and looks like most of it made it in already and is up-to-date (from https://raw.githubusercontent.com/Azure/azure-sdk-for-cpp/a8c79cb8c05fe197192f3f9607d42bba0b8b8140/README.md).

As part of: https://github.com/Azure/azure-sdk-for-cpp/pull/1723

![image](https://user-images.githubusercontent.com/6527137/145130423-7c352a4c-38d9-4b4a-a873-ff84037eb817.png)

https://www.diffchecker.com/yymNn7im

So, we can safely remove that branch :)
