### ISSUE TITLE
Add the package README.md file as index.html content

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#3121]
Currently opening the package on the doxygen lands on an empty index page.  That should instead be information for the the package.

Doxygen supports adding addition content to the index.  We should leverage this feature and insert the README.md for each package into this content.

https://www.doxygen.nl/manual/config.html#cfg_use_mdfile_as_mainpage

> USE_MDFILE_AS_MAINPAGE
> If the USE_MDFILE_AS_MAINPAGE tag refers to the name of a markdown file that is part of the input, its contents will be placed on the main page (index.html). This can be useful if you have a project on for instance GitHub and want to reuse the introduction page also for the doxygen output.

**Comment by gearama** [comment]
https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-security-keyvault-certificates/4.0.0-beta.1/index.html It seems to have been already added , i can see the flag set in the cmake file
