### ISSUE TITLE
Build/test matrix should include more Linux and GCC configurations

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#313]
We've discovered errors in various Linux distributions that aren't caught by the current matrix of distributions. The supported matrix is here: https://azure.github.io/azure-sdk/cpp_implementation.html#linux

Explore using containers to add entries which aren't available as Azure DevOps hosts. 

A subset of the matrix can run during CI builds, a more complete matrix should run during nightly builds

**Comment by kurtzeborn** [comment]
May be a duplicate of #276.

**Comment by danieljurek** [comment]
Closing as dup of #276
