### ISSUE TITLE
Unable to connect to a container using CreateFromConnectionString

### ISSUE THREAD

**Issue by ekansh-hash** [Azure/azure-sdk-for-cpp#3140]
I am not able to connect to an azure container when I use CreateFromConnectionString. I followed the example to download a blob using the connection string but an exception is thrown when the function CreateFromConnectionString is called.
![image](https://user-images.githubusercontent.com/15551914/143182402-a60891e6-04ad-47fc-b9f8-7a77c2702709.png)

 I tried to debug the code and it takes me to xtree .

![image](https://user-images.githubusercontent.com/15551914/143182883-26825b26-4f9c-4fa7-b937-231404966c6b.png)

I have not been able to figure out what the issue is and I don't see anything in the example that I have missed. I should mention that the connection string indeed does have the correct value.

 - OS: Windows 10
 - IDE : Visual Studio

**Comment by ahsonkhan** [comment]
cc @Jinming-Hu

**Comment by Jinming-Hu** [comment]
Hi @ekansh-hash, can you paste the stack trace of the exception?
