### ISSUE TITLE
ci pipelines need step building with cmake 3.13

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#3192]

**Comment by gearama** [comment]
our cpp - keyvault - ci build steps use cmake 3.22 we need some steps using 3.13 to make sure we don't accidentally introduce features from higher versions

**Comment by ahsonkhan** [comment]
cc @danieljurek

**Comment by ahsonkhan** [comment]
Corresponding Embedded C issue:
https://github.com/Azure/azure-sdk-for-c/issues/2054
