### ISSUE TITLE
Retry policy doesn't work for DNS failure and connection failure

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#320]
This is actually caused by this https://github.com/Azure/azure-sdk-for-cpp/issues/317 issue. Since we're throwing exception pointer (which is really unusual) on dns failure or network failure, but trying to catch them by reference (see [here](https://github.com/Azure/azure-sdk-for-cpp/blob/204c025d095e2b1a74f0f1ded806e4205dd554f0/sdk/core/azure-core/src/http/retry_policy.cpp#L143)), we'll never be able to actually catch the exception. So the retry mechanism won't work.

**Comment by RickWinter** [comment]
Fixed
