### ISSUE TITLE
Setup a process to ensure all client libraries depend on latest release of Azure Core

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3214]

**Comment by ahsonkhan** [comment]
cc @danieljurek in case you have some ideas on the best way to incorporate this to the release process (similar to the version increment auto-PRs)

**Comment by ahsonkhan** [comment]
We still want to do this. Currently this is a manual process:
https://github.com/Azure/azure-sdk-for-cpp/pull/5405

**Comment by LarryOsterman** [comment]
> We still want to do this. Currently this is a manual process: #5405

Does this imply that an Azure Core release will trigger a re-release of all other packages?
