### ISSUE TITLE
Azure Storage Missing doxygen packages documentation

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#3218]
**Describe the bug**
https://azure.github.io/azure-sdk-for-cpp/storage.html missing content for the sub packages, e.g. https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-security-keyvault-keys/4.2.0/index.html 
![image](https://user-images.githubusercontent.com/50641385/148450094-dd95b5a2-375f-478f-a96a-b22b4e6bc92a.png)

||
V
![image](https://user-images.githubusercontent.com/50641385/148450186-659f4c19-3276-40f1-8c65-d840ec1b07bc.png)

**Expected behavior**
when visiting the links there should be content on the package level.
![image](https://user-images.githubusercontent.com/50641385/148450317-f4a1e574-566b-4975-a2fb-aa751d0c57ed.png)

The issue is that in the code there are no readme.md files missing from the storage subfolders of /sdk/storage folder
 azure-storage-blobs             
 azure-storage-common            
 azure-storage-files-datalake    
 azure-storage-files-shares      
 azure-storage-queues            

in order for content to show up in the web view we need README.md files created in each of this subfolders not just under the /sdk/storage file.

**Comment by gearama** [comment]
@danieljurek has more information regarding retrofitting previous releases.

**Comment by ahsonkhan** [comment]
cc @Jinming-Hu - we need getting started doc content for storage libraries as README.md for each service

**Comment by danieljurek** [comment]
One way to back-fill older versions would be to check out the repo at the release tag for each released package's version, copy a README.md file into the appropriate location, re-run the doc generation steps, then upload the results to the appropriate location in storage. 

The content of each README.md file would have to match what's available in each version of the documentation. For example, don't advertise new features that are available in `azure-storage-blobs@12.2.1` but not available in `azure-storage-blobs@12.0.0` in the README.md file for `azure-storage-blobs@12.0.0`. This could mean one `README.md` file for each version of each package we want to document.

**Comment by Jinming-Hu** [comment]
related to https://github.com/Azure/azure-sdk-for-cpp/issues/691

**Comment by Jinming-Hu** [comment]
This issue has been fixed in the recent releases.
