### ISSUE TITLE
Invalid Shared Access Signatures

### ISSUE THREAD

**Issue by jankrassnigg** [Azure/azure-sdk-for-cpp#3222]
**Describe the bug**
I'm attempting to migrate from the old storage SDK to this one, but I fail to get access to file's with an SAS generated with AccountSasBuilder.

I basically do this:
```cpp
AccountSasBuilder sb;
sb.Protocol = SasProtocol::HttpsAndHttp;
sb.ExpiresOn = Azure::DateTime(std::chrono::system_clock::now() + std::chrono::minutes(60 * 24));
sb.ResourceTypes = AccountSasResource::All;
sb.Services = AccountSasServices::All;
sb.SetPermissions(AccountSasPermissions::All);
std::string sas = sb.GenerateSasToken(credentials);
```

The SAS that comes out looks like this:

?se=2022-01-06T18:45:42Z&sig=Y7FZbR5mRNJAQZxzywHDrdxhj8bui2OeWcWhbcaKzCkw%3D&sp=rwdxlacuptf&spr=https,http&srt=sco&ss=bqf&sv=2020-02-10

When I put this into the service where I want to use it to download a file, it doesn't work. It does work with an SAS generated with the older storage SDK, though, so I compared a working one with a none working one, and I see some differences that make me wonder whether this builder is correct / finished.

1. It has a ? at the start, which is superfluous in some cases, it should omit that.
2. It doesn't escape colons, the colons in the time should be escaped by "%3A" (at least that's what the old SDK did)
3. It doesn't escape commas, the comma in "https,http" should be escaped by "%2C" (the old SDK did that)
4. The old SDK appended a "sr=c", no idea what that stands for and whether that is needed ?

Also, the old SDK used "sv=2017-04-17", I guess that's a version for the signature? This one uses "sv=2020-02-10" and the "sig" parts are also different. Is that expected? 

After fixing the general URL escaping errors myself, I'm getting the error message "Access to the input blob container was denied. Invalid access rights or invalid shared access signature."

And thus finally the big question: 

**Does a service need to be upgraded to support the SAS generated by this SDK?**

***Exception or Stack Trace***
none

**To Reproduce**
see above

***Code Snippet***
see above

**Expected behavior**
The generated SAS should be valid.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS2019
 - Version of the Library used: 12.2.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jankrassnigg** [comment]
I should also mention that previously I used azure::storage::cloud_blob_container::get_shared_access_signature(), so this was done on a container. In the new SDK I only see code to generate an SAS for the account. I assume there is no difference, since I gave it the AccountSasResource::Container flag, right?

**Comment by RickWinter** [comment]
> Also, the old SDK used "sv=2017-04-17", I guess that's a version for the signature? This one uses "sv=2020-02-10" and the "sig" parts are also different. Is that expected?

The sv=???????? is defining the service version the SDK uses.  As we release SDKs we update the SDKs to talk the latest versions of the service.  There is no action required on your part.  When there is we consider it a breaking change the major version of the SDK would rev.

**Comment by Jinming-Hu** [comment]
@jankrassnigg I tried your code snippet, it works for me. Here is the code I used for testing.

```C++
int main()
{
  using namespace Azure::Storage::Sas;
  using namespace Azure::Storage::Files::Shares;

  const std::string shareName = "sample-share";
  const std::string fileName = "sample-file";
  const std::string fileContent = "Hello Azure!";

  auto shareClient = ShareClient::CreateFromConnectionString(GetConnectionString(), shareName);
  shareClient.CreateIfNotExists();

  ShareFileClient fileClient = shareClient.GetRootDirectoryClient().GetFileClient(fileName);

  std::vector<uint8_t> buffer(fileContent.begin(), fileContent.end());
  fileClient.UploadFrom(buffer.data(), buffer.size());

  Azure::Storage::StorageSharedKeyCredential credentials("YOUR_ACCOUNT_NAME", "YOUR_ACCOUNT_KEY");
  
  AccountSasBuilder sb;
  sb.Protocol = SasProtocol::HttpsAndHttp;
  sb.ExpiresOn = Azure::DateTime(std::chrono::system_clock::now() + std::chrono::minutes(60 * 24));
  sb.ResourceTypes = AccountSasResource::All;
  sb.Services = AccountSasServices::All;
  sb.SetPermissions(AccountSasPermissions::All);
  std::string sas = sb.GenerateSasToken(credentials);

  auto fileClientWithSas = ShareFileClient(fileClient.GetUrl() + sas);

  fileClientWithSas.DownloadTo(buffer.data(), buffer.size());

  std::cout << std::string(buffer.begin(), buffer.end()) << std::endl;

  return 0;
}
```

**Comment by Jinming-Hu** [comment]
Now answer your questions:

> It has a ? at the start, which is superfluous in some cases, it should omit that.

This is just for customers' convenience, so that they can write `url + sas_token`. Otherwise they'd have to write `url + "?" + sas_token`.

> It doesn't escape colons, the colons in the time should be escaped by "%3A" (at least that's what the old SDK did)
> It doesn't escape commas, the comma in "https,http" should be escaped by "%2C" (the old SDK did that)

Colons or commas don't have to be encoded according to RFC.

> The old SDK appended a "sr=c", no idea what that stands for and whether that is needed ?

`sr` stands for signed resource. It's only available in service SAS. See [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview#types-of-shared-access-signatures) for the differences of three kinds of SAS.

To create a file service SAS, you should use [ShareSasBuilder](https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_sas_builder.hpp)

**Comment by jankrassnigg** [comment]
> To create a file service SAS, you should use ShareSasBuilder

Ha, THAT pointed me into the right direction! I had to use BlobSasBuilder, which for some reason I didn't find before.

Thanks for the help guys, it's working now :)
