### ISSUE TITLE
Sample code for making a REST call

### ISSUE THREAD

**Issue by jankrassnigg** [Azure/azure-sdk-for-cpp#3233]
As far as I can tell, the documentation for this project is pretty awful. And I'm not the only one who stumbled across this: https://devblogs.microsoft.com/azure-sdk/cppintro/#comment-26

So, if you want to improve your product, I really suggest to add more samples and fix the documentation to not just go round in circles. Or, if such documentation already exists somewhere, make it easier to discover.

Anyway, I'd like to use the Azure Core SDK to do a simple REST call (using https), to replace my usage of [cpprest](https://github.com/microsoft/cpprestsdk) with this library. However, I have no idea how to even start with that. Could someone post some sample code, how to do that?

**Comment by RickWinter** [comment]
We hear you on the documentation and are working to make that experience better.  If you have specific places that you ended up going in circles, please help point us to those places and we will work to remedy.

Azure::Core is not a direct replacement for cpprest.  Azure::Core is intended to be consumed by Azure client SDK libraries for communication with Azure.  Although it's possible to use it standalone to communicate with Azure, that is not an officially supported scenario.

**Comment by jankrassnigg** [comment]
Regarding the documentation, this is your main page:
https://azure.github.io/azure-sdk-for-cpp/

It explains the basics to get up and running, that is fine, but then you need a sample how to do this or that, but the page doesn't have that, so you go to the "Need help" section and there are two promising links. But the first link literally links to the same page and the second page links to something that doesn't seem to have any resources regarding this SDK. That's the point where I felt like somebody was making fun of me.

Regarding cpprest, on it's main page it says "cpprestsdk is in maintenance mode and we do not recommend its use in new projects. We will continue to fix critical bugs and address security issues."

That's it, it doesn't say what to use instead. So IS there anything else one could use? I thought that since the Azure SDKs do REST calls all the time, this would should be possible to use for me as well.
