### ISSUE TITLE
WinHTTP HTTP Pipeline does not set WINHTTP_OPTION_CLIENT_CERT_CONTEXT to WINHTTP_NO_CLIENT_CERT_CONTEXT by default

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-for-cpp#3235]
**Describe the bug**
When an HTTPS server is configured to optionally request client certificates, WinHTTP will refuse to connect to the server if the WIHTTP_OPTION_CLIENT_CERT_CONTEXT is not set to WINHTTP_NO_CLIENT_CERT_CONTEXT:

```
  if (!WinHttpSetOption(handleManager->m_requestHandle, WINHTTP_OPTION_CLIENT_CERT_CONTEXT, WINHTTP_NO_CLIENT_CERT_CONTEXT, 0))
  {
    GetErrorAndThrow("Error while setting client cert context to ignore..");
  }
```

That means that the WinHTTP stack cannot connect to Azure servers that optionally require client certificates. The CURL stack does not have this issue.

**To Reproduce**
Ask LarryO for a reproduction. A simple version is to use the HTTP pipeline to navigate to:

`curl.exe https://sharedwus.wus.attest.azure.net/.well-known/openid-configuration`

The service at this URL optionally accepts a client certificate and returns a JSON structure with information about the attestation instance.

***Code Snippet***
See the above. The 3 lines of code above are required to make this work. I do not know how this interacts with other client certificate usage however.

**Expected behavior**
I expect the WinHTTP pipeline to behave the same as the CURL HTTP Pipeline when retrieving from the URL above.

**Setup (please complete the following information):**
 - OS: Windows.
 - IDE : Any
 - Version of the Library used

**Comment by ahsonkhan** [comment]
Interesting catch @LarryOsterman. I wasn't aware that setting this option was required:
https://docs.microsoft.com/en-us/windows/win32/winhttp/option-flags

**Comment by LarryOsterman** [comment]
It's not clear to me that this is "required" - it 100% is required if you're attempting to connect to a service which optionally requires TLS client authentication however.  And as I understand it, TLS client authentication is required for ARM support. It's possible that other services aren't affected in the same way because they have separate management and dataplane service roots - for whatever reason, MAA shares a service root between dataplane and management.

I also don't know how setting this would interfere with azure services that require TLS authentication.

**Comment by ahsonkhan** [comment]
Moving this out until we have a scenario (and an SDK we are ready to ship) where we need this investigated and fixed. Feel free to pull back in to the appropriate milestone when necessary :)

**Comment by LarryOsterman** [comment]
Moved to 2022 March because the CI pipeline for Attestation is failing due to this issue.
