### ISSUE TITLE
BOM file creation failing on UWP

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#3254]
The BOM file step is failing on UWP builds

**Comment by scbedd** [comment]
[Example Build Failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1308436&view=logs&j=e71eac3d-89c8-52e0-61cd-202dc96cdaa6&t=d24da1d2-1d8e-597f-9a37-150adf4c20ab)
