### ISSUE TITLE
Static checks in the GenerateReleaseArtifacts Job

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#3289]
* clang-format for clang 11 (currently running in Ubuntu 20) -- may need to [configure]( https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#custom_llvm_toolset) cmake, project files, or the machine to use clang 11
* MSVC code analysis using environment variable [AZURE_ENABLE_STATIC_ANALYSIS](https://github.com/Azure/azure-sdk-for-cpp/blob/fda88bf7b8389575b9d973821efc604442e10493/cmake-modules/AzureGlobalCompileOptions.cmake#L19) -- Does this need to run on multiple configurations or is a single configuration sufficient? If it needs to run on multiple configurations it might make more sense to keep ti in the nightly runs where we benefit from parallel execution.

**Comment by kurtzeborn** [comment]
We do already do clang formatting, but possibly not the version(s) you want.  The EngSys team is not going to get to this any time soon.  If the language team wants changes here, go ahead and do them.  We're happy to assist/review.
