### ISSUE TITLE
Make it obvious if a build is simply building or running tests

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#3290]
A couple approaches: 

* Change job names to reflect Build or Build & Test
* If there are no tests compiled skip the ctest step... While the absence of tests is not a failure in itself it would be better if we skipped the test step in build-only jobs. 

Also: Call out which build job is uploading the coverage information

**Comment by kurtzeborn** [comment]
It's been over a year.  Not getting to this any time soon.
