### ISSUE TITLE
Distributed Tracing - Enable tracing for REST-based libraries

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-cpp#3293]
Support [distributed tracing](https://azure.github.io/azure-sdk/general_implementation.html) with OpenTelemetry in C++ REST-based SDKs.

**Comment by ronniegeraghty** [comment]
@LarryOsterman, it says this issue is in progress, but the issue hasn't been updated in a while and the issue falls under the "stale" category, before I leave this comment updating it. Are there any updates on this issue?

**Comment by LarryOsterman** [comment]
The Azure organization has gone "All-In" on distributed tracing.

That means adding some code to wrap service methods to enable tracing in the SDK clients.

This work item is an envelope for the work for updating *all* the service clients.

**Comment by ronniegeraghty** [comment]
Looks like we have issues open for [Storage](https://github.com/Azure/azure-sdk-for-cpp/issues/3556) and [Key Vault](https://github.com/Azure/azure-sdk-for-cpp/issues/3557) for this. Are these the last two parts for this envelope issue?
