### ISSUE TITLE
Add credscan

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#3294]
Similar [to how this is done in .NET](https://github.com/Azure/azure-sdk-for-net/blob/0eeac2c4bac280cea01e208938ee5d1db5fc3697/eng/pipelines/aggregate-reports.yml#L151)

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-cpp/pull/3382

The PR includes the enable codes and the link in comments have all errors detected from the tool.

**Comment by sima-zhu** [comment]
@danieljurek Could you please take a look at the errors reported in the pipeline and ask someone help with suppression?

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-cpp/issues/3568

**Comment by danieljurek** [comment]
This was fixed and credscan was added in https://github.com/Azure/azure-sdk-for-cpp/pull/4328
