### ISSUE TITLE
❓Survey: Your experience in this repo

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-cpp#3313]
Whether you're a frequent visitor or a relatively new visitor of the repo, please tell us about your experience with our issue support and/or PR contribution process. The survey should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8QTQTGJ?Source=azure-sdk-for-cpp

**Comment by DBJDBJ** [comment]
This is important repo for native C++ projects. It is abandoned for almost two years. In particular, I need concrete advice on sending to Azure Log Insight's. Not that I cannot see how I might do it myself from C++, but for a official and recommended future safe way of doing it.

Kind regards ...

**Comment by lilyjma** [comment]
Thank you for your interest in the experience survey. The survey has now been closed.
If you didn't get a chance to provide feedback this time, please look out for future surveys.

**Comment by RickWinter** [comment]
> This is important repo for native C++ projects. It is abandoned for almost two years. In particular, I need concrete advice on sending to Azure Log Insight's. Not that I cannot see how I might do it myself from C++, but for a official and recommended future safe way of doing it.
> 
> Kind regards ...

Can you elaborate on the repo that is abandoned?  This repo, Azure/azure-sdk-for-cpp, is in active development.

**Comment by DBJDBJ** [comment]
@RickWinter Ah, I must have been in a hurry? Let me check...
