### ISSUE TITLE
Update conditions to include live-tests stage to internal pipelines

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#3349]
The current condition requires `LiveTestCtestRegex` to be set, however, we can now remove the test regex concept to separate the live and non-live test and use the regex from `CtestRegex` for public and internal pipelines

**Comment by kurtzeborn** [comment]
Not sure what's being asked for.  Possible it's already been dealt with.  The EngSys team won't be getting to this any time soon.  If this is a priority for the language team, please go ahead and fix/address this.
