### ISSUE TITLE
Engineering system for C++ should have support for snippet creation

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-for-cpp#3368]
# Statement of problem

Most of the other SDK solutions have a mechanism to allow SDK authors to create samples and snippets which are reflected in .md files and doxygen comments. This allows documentation for the SDK to be maintained in sync with samples/snippets and thus is more likely to be accurate.

# Possible solutions

For C#, the team went with syntax like:
```C# Snippet:HelloCreateKeyVaultBackupClient
KeyVaultBackupClient client = new KeyVaultBackupClient(new Uri(keyVaultUrl), new DefaultAzureCredential());
```

Source implementation is at 

For Java, the team went with syntax like
```java readme-sample-getSigningCertificates
List<AttestationSigner> certs = client.listAttestationSigners();

certs.forEach(cert -> {
    System.out.println("Found certificate.");
    if (cert.getKeyId() != null) {
        System.out.println("    Certificate Key ID: " + cert.getKeyId());
    } else {
        System.out.println("    Signer does not have a Key ID");
    }
    cert.getCertificates().forEach(chainElement -> {
        System.out.println("        Cert Subject: " + chainElement.getSubjectDN().getName());
        System.out.println("        Cert Issuer: " + chainElement.getIssuerDN().getName());
    });
});
```

Each of the other languages has similar mechanisms. 

# Preferred Solution
Something that gives the ability to update both markdown and C++ source files.

**Comment by danieljurek** [comment]
This may be domain specific work to build (and possibly test) the snippets and extract the relevant bits for insertion into documentation.

**Comment by kurtzeborn** [comment]
The EngSys team is not going to get to this any time soon.  If the langauge team feels this is important, they should follow up.
