### ISSUE TITLE
azure-security-attestation build failed on VS2019

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3376]
```
3>opensslcert.cpp
3>C:\Users\user\Desktop\azure-sdk-for-cpp\sdk\attestation\azure-security-attestation\src\private\crypto\openssl\opensslcert.cpp(426,24): error C3861: 'timegm': identifier not found
```

https://github.com/Azure/azure-sdk-for-cpp/blob/ddc9eb355f48cbeb0159bc49cc6937ea885d3677/sdk/attestation/azure-security-attestation/src/private/crypto/openssl/opensslcert.cpp#L423

This is because `_WINDOWS` isn't defined.

Environment:

Windows 10 Enterprise 21H2 19044.1526
Microsoft Visual Studio Community 2019 Version 16.11.10

**Comment by LarryOsterman** [comment]
Missed this case - replace _WINDOWS with `defined(AZ_PLATFORM_WINDOWS)` and you should be good. The fix will be included in my next PR.
