### ISSUE TITLE
Azure Identity Iron Semester for C++

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-cpp#341]
The Azure Identity library provides Azure Active Directory token authentication support across the Azure SDK. It provides a set of TokenCredential implementations which can be used to construct Azure SDK clients which support AAD token authentication.

This issue tracks the new features, reliability improvements, and the release of minor updates to Azure.Identity for the C++ programming language during September - December 2020

**Comment by antkmsft** [comment]
#5, #18, #76, #77, #78, #79, #80, #81, #82

**Comment by katmsft** [comment]
@RickWinter Should this be in November milestone so that we have this before GA?
