### ISSUE TITLE
After Upgrade azure-storage-files-shares_12.1.0  to azure-identity_1.1.1 for blob upload then upload average speed decresed.

### ISSUE THREAD

**Issue by dhavalkaneria** [Azure/azure-sdk-for-cpp#3414]
**Query/Question**
I am using Azure c++ sdk for blob upload. Previously I was using azure-storage-files-shares_12.1.0 release version. After a few months I upgraded the azure c++ version azure-identity_1.1.1. Now my average upload speed of blob reduced to around 10 seconds. Is there any major change that are affecting to reduce the speed for upload. ? I am gone through all ChnageLog between this 2 branch but not found major related to blob upload.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: Linux 18.04 on VirtualBox
 - IDE :Visual Studio Code.
 - Version of the Library used 
 - azure-storage-files-shares_12.1.0 ->>> avg. upload time for 64Mb file --->39 sec.
 - azure-identity_1.1.1 ->>> avg. upload time for 64Mb file --->49 sec.
 
-I am using API auto res = blobClient.UploadFrom(blobName) into my Application.

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by dhavalkaneria** [comment]
What is the default protocol we are using for HTTP? HTTP/2 or HTTP/1.1?  I found one change is https://github.com/Azure/azure-sdk-for-cpp/issues/2848. I am not sure whether it is limiting our speed for upload as it uses hard-coded HTTP/1.1 version instead of HTTP/2.

In azure-storage-files-shares_12.1.0 release above bug was not introduced so taking by default HTTP/2 and increasing speed of Upload? that is the reason? this just guess....

**Comment by dhavalkaneria** [comment]
Any Update?

**Comment by antkmsft** [comment]
I have tried uploading a 3GiB blob in 3 different combinations:
* Identity 1.1.0 + storage 12.1.0: ~210 seconds.
* Identity 1.1.1 + storage 12.2.1: ~210 seconds.
* Identity 1.1.1 + storage 12.1.0: ~210 seconds.
* (latest as of now) Identity 1.2.0 + storage 12.3.0: ~235 seconds.

At all times, uploading with Token Credential is up to 2 seconds slower than when using SAS token, but both numbers do change consistently, so I can't say that any specific identity version performs worse or better relative to SAS auth.

Here is the code that I used to test:
```cpp
#include <chrono>
#include <cstdlib>
#include <vector>
#include <iostream>

#include <azure/identity/environment_credential.hpp>
#include <azure/storage/blobs/block_blob_client.hpp>

int main()
{
	auto blobUrl = std::getenv("AZURE_STORAGE_BLOB_URL");
	if (blobUrl == nullptr)
	{
		std::cerr << "AZURE_STORAGE_BLOB_URL not defined.\n";
		return 1;
	}

	auto blobSasUrl = std::getenv("AZURE_STORAGE_BLOB_SAS_URL");
	if (blobSasUrl == nullptr)
	{
		std::cerr << "AZURE_STORAGE_BLOB_SAS_URL not defined.\n";
		return 1;
	}

	try {
		std::cerr << "Creating vector...";
		std::vector<uint8_t> vec;
		for (auto i = 0; i < ((1024 * 1024 * 1024) / 16); ++i)
		{
			for (uint8_t c = '0'; c <= '9'; ++c)
			{
				vec.push_back(c);
			}

			for (uint8_t c = 'A'; c <= 'F'; ++c)
			{
				vec.push_back(c);
			}
		}
		std::cerr << " Done.\n";

		{
			auto credential = std::make_shared<Azure::Identity::EnvironmentCredential>();
			Azure::Storage::Blobs::BlockBlobClient blockBlobClient(blobUrl, credential);

			std::cerr << "Starting upload using TokenCredential...";
			{
				const auto started = std::chrono::system_clock::now();
				blockBlobClient.UploadFrom(vec.data(), vec.size());
				const auto ended = std::chrono::system_clock::now();

				auto const duration = ended - started;
				std::cerr << " Done.\n";
				std::cout << "Upload using TokenCredential: " << std::chrono::duration_cast<std::chrono::seconds>(duration).count() << "s.\n";
			}
		}

		{
			Azure::Storage::Blobs::BlockBlobClient blockBlobClient(blobSasUrl);

			std::cerr << "Starting upload using SAS...";
			{
				const auto started = std::chrono::system_clock::now();
				blockBlobClient.UploadFrom(vec.data(), vec.size());
				const auto ended = std::chrono::system_clock::now();

				auto const duration = ended - started;
				std::cerr << " Done.\n";
				std::cout << "Upload using SAS: " << std::chrono::duration_cast<std::chrono::seconds>(duration).count() << "s.\n";
			}
		}
	}
	catch (const std::exception& ex)
	{
		std::cerr << "\nException: " << ex.what();
		return 2;
	}
	catch (...)
	{
		std::cerr << "\nUnknown exception.";
		return 2;
	}

	return 0;
}
```

@dhavalkaneria, is there anything wrong with the repro code I have? Can you produce the same kind of numbers? (Blob size can be diferent)

Given that I currently see no inconsistent perf difference between SAS auth and token auth, I don't think at this point it is likely that perf is related to identity, and I think you should follow up with @Jinming-Hu from the Storage team.

If I can help in any way, please let me know, I will be glad to.

**Comment by Jinming-Hu** [comment]
@dhavalkaneria `blobClient` is from package `azure-storage-blobs`. Upgrading  `azure-storage-files-shares` should not affect blob clients.

Can you check if you upgraded `azure-storage-blobs` when this issue happened?

**Comment by vhvb1989** [comment]
> What is the default protocol we are using for HTTP? HTTP/2 or HTTP/1.1? I found one change is #2848. I am not sure whether it is limiting our speed for upload as it uses hard-coded HTTP/1.1 version instead of HTTP/2.
> 
> In azure-storage-files-shares_12.1.0 release above bug was not introduced so taking by default HTTP/2 and increasing speed of Upload? that is the reason? this just guess....

We are using HTTP1.1 for the libcurl transport adapter since it does not support HTTP2.0.  
However, Azure Storage uses version 1.1 as well.  The adapter would fail for any HTTP2.0 response

**Comment by vhvb1989** [comment]
@dhavalkaneria , Can you set env var `AZURE_LOG_LEVEL=1` while you run your test?  

It might be possible that your upload request is failing from some network issue and it is re-try by the client after some seconds, generating the delay you are observing.

Please turn logging on and share the log you get from console if possible

**Comment by Jinming-Hu** [comment]
I noticed this issue was opened in early March. I assume this is the same issue as https://github.com/Azure/azure-sdk-for-cpp/issues/3548.

**Comment by vhvb1989** [comment]
> I noticed this issue was opened in early March. I assume this is the same issue as #3548.

This is Linux...
