### ISSUE TITLE
Move to latest App Services MSI API version

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-cpp#344]
- Move Azure.Identity to the latest App Services MSI API version.
- Update /sdk/e2e Azure Functions date parsing tests

**Comment by RickWinter** [comment]
@antkmsft Please address this as part of the MSI feature.

**Comment by antkmsft** [comment]
We're on all the same versions that .NET and Java SDKs are:
AppService: "2017-09-01"
AzureArc: "2019-11-01"
Imds: "2018-02-01"

More info:
All of the versions above are release versions.

We also support Cloud Shell authentication the same way .NET does.
.NET does not pass `api-version` for Cloud Shell. We have the very same creation logic, we send the same HTTP headers, and so on.

We don't support Service Fabric at the moment.
.NET and Java use `2019-07-01-preview` for Service Fabric. I've been told they have it for a reason that newer version is not yet deployed to all the environments/regions/OSes.
If we were to implement Service Fabric Managed Identity Credential today, I would argue we still use the same as Tier1 languages, and upgrade in coordination with them.

We are not behind Tier1 languages on API version for supported Managed Identity sources - we use the same versions as both Java and .NET.
