### ISSUE TITLE
Support for Blob Immutability Policies in the SDK

### ISSUE THREAD

**Issue by ajs97** [Azure/azure-sdk-for-cpp#3461]
**Query/Question**
I have a use case where I need to use the blob immutability policies, where we set the policy to specific blob versions, and not at the container level. Going through the `azure-storage-blobs` changelog, I see that `BlobClient::SetImmutabilityPolicy(), BlobClient::DeleteImmutabilityPolicy(), BlobClient::SetLegalHold()` APIs were added in the 12.4.0-beta.1 version. Had a few questions regarding this:
1. We want to integrate this SDK into our codebase, and we are a bit skeptical about using the beta version of the SDK. How stable is the beta version? Would you recommend using the beta in a production environment, or should we wait for a stable release, i.e, 12.4.0.
2. When will you be releasing the 12.4.0 version? 

***Why is this not a Bug or a feature Request?***
This is regarding APIs added in the 12.4.0-beta1, and the dates regarding the new release.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 18.04
 - IDE : VSCode, but not applicable here. 
 - Version of the Library used: 12.4.0-beta1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by RickWinter** [comment]
Although we aim for stability in every build, we do not recommend using Beta releases in production.
