### ISSUE TITLE
Avoid static initialization

### ISSUE THREAD

**Issue by RobinGeffroy** [Azure/azure-sdk-for-cpp#3479]
**Describe the bug**
Azure SDK is auto-initialized in curl_connection_pool_private.hpp. The CurlConnectionPool class initialize curl in its constructor, and call the cleanup in its destructor.
However, in our environment, we initialize openssl *without* the atexit() cleanup (openssl flag OPENSSL_INIT_NO_ATEXIT) and we call the OPENSSL_cleanup() manually. We end up in error due to this destructor being called upon exit.
It would be nice to have global initialize / cleanup functions for Azure SDK.

I don't know if this is a bug or a feature request though, sorry if made a mistake.

**To Reproduce**
Activate OpenSSL with OPENSSL_INIT_NO_ATEXIT. Might need to be done in CURL (because it also initialize openssl).

**Information Checklist**
We work with azure-identity-1.1.1

**Comment by JeffreyRichter** [comment]
We could add a function that allows explicit cleanup and then the destructor would turn into a no-op. This could be done in a non-breaking way. @vhvb1989 / @LarryOsterman

**Comment by vhvb1989** [comment]
Well, I am curious about how you are using Openssl @RobinGeffroy.  

What OpenSSL version are you using?  version  >= 1.1.0 doesn't require calling init/free unless there's something special you want to init (out of the defaults)

Are you working on Linux?  What's the error you are getting?  Is it a signal error?  

Libraries should not be calling `OPENSSL_cleanup`.  We would need to inspect if libcurl is doing it, but I would suspect that what it might be happening is that libcurl is making openSSL to be init with default behavior (before your call to OpenSSL initialize), which includes using the atexit() callback to call free()

On your call to initialize OpenSSL, have you tried to first call `OPENSSL_cleanup` and then initialize again with the `OPENSSL_INIT_NO_ATEXIT` option?  That might help.

**Comment by RobinGeffroy** [comment]
Hello,
I indeed want something special, for instance avoid a configuration file.

The original issue was due to a bug within our code (some decade-old code for signal handling using `exit()` instead of `_exit()`, as a result the `atexit()` cleanup was called even if the process was killed with a SIGTERM, and ended up in a segmentation fault in another library).
It was hard to narrow down the issue, but we're now fine :-)

However, on an unrelated note (no issue nor bug), I find it nice to have explicit functions if the users wants to, to make initialization / cleanup.
In our context, we have a single process that can do multiple transfer types (Google Cloud Storage, Azure, Amazon, etc), according to configuration. It would be nice to avoid initializing Azure if we don't need it.

**Comment by vhvb1989** [comment]
> It would be nice to avoid initializing Azure if we don't need it.

Have you considered dynamically Loading/unloading libraries on your application?  (dlopen / windows dll loader)

**Comment by RobinGeffroy** [comment]
Well, using dlopen() might be a little heavy for this, because it implies a lot of modifications.
I just suggest the idea of having a clean initialization instead of an implicit one, as done per Amazon SDK or Google Cloud Storage API for instance.

**Comment by vhvb1989** [comment]
@RobinGeffroy , thank you for suggesting adding the `init` method.

The Azure SDK for C++ does not use init/clean functions by design. Most of the global/static components are not created until they are required (wrapped under a `get` function which would create the singleton object).

The Libcurl transport adapter is one special case.  Similar to the other transport adapter we ship in Azure-core (winHTTP), it is a replaceable implementation.  You can create a transport adapter implementation on your application and use it instead. In that case, you can handle the life-time of the adapter depending on your needs.
