### ISSUE TITLE
Template client is out-dated and needs to be updated, removing or updating `ClientVersion`

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3508]
SDK authors start with the template client and might incorrectly assume we want a ClientVersion() method.

This is not what we want for SDKs, and hence the template client needs to be updated to reflect the correct pattern here.

https://github.com/Azure/azure-sdk-for-cpp/blob/487c7ce5425cbb44c68d0250c799fe0388b00f47/sdk/template/azure-template/inc/azure/template/template_client.hpp#L12

cc @LarryOsterman, @RickWinter 

It showed up in Attestation APIView because it started off as a template client:
https://github.com/Azure/azure-sdk-for-cpp/blob/af7281ef1a273404abb9c79f4de775b5b32f089b/sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client.hpp#L163

https://apiview.dev/Assemblies/Review/5b2efd771af642728e4796813564404b#Azure::Security::Attestation::AttestationAdministrationClient

![image](https://user-images.githubusercontent.com/6527137/162083239-73c7af61-244a-46fa-bda7-32b315cfd036.png)

**Comment by LarryOsterman** [comment]
Removing ClientVersion from Template as a part of updating Template to match service requirements.
