### ISSUE TITLE
Azure::Core::Context::IsCancelled is marked as noexcept, but it calls Azure::Core::Context::GetDeadline which may throw

### ISSUE THREAD

**Issue by bnmaa** [Azure/azure-sdk-for-cpp#3567]
**Describe the bug**
https://github.com/Azure/azure-sdk-for-cpp/blob/201d588b6d344cfb72350e53ec38c649d8b94344/sdk/core/azure-core/inc/azure/core/context.hpp#L236
Is marked as `noexcept`, while it calls
https://github.com/Azure/azure-sdk-for-cpp/blob/fda88bf7b8389575b9d973821efc604442e10493/sdk/core/azure-core/inc/azure/core/context.hpp#L178
which is not `noexcept`, which violates the contract.

**To Reproduce**
Run static code analysis with `noexcept` calling chain detection against azure-sdk-for-cpp
e.g. OACR

**Expected behavior**
In general, every `noexcept` function should not call non-`noexcept`.
Please help mark `GetDeadline()` as `noexcept` if it won't throw.

**Setup (please complete the following information):**
 - OS: Windows 11 (but the issue itself is platform-independent)
 - IDE : Visual Studio 2019
 - Version of the Library used: 1.0.0-beta.2 (b16ff00d98a3fa2ad7c0966462ee44068f847b0d)

**Additional context**
Our build pipeline detects this violation, it means, if `GetDeadline()` ever throws at runtime, the program would crash.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vhvb1989** [comment]
@JeffreyRichter @CaseyCarter  is this by design?  Are we trying to make `IsCancelled()` unrecoverable by all means? 

Related: https://github.com/Azure/azure-sdk-for-cpp/pull/2033
Related: https://github.com/Azure/azure-sdk-for-cpp/pull/2197

It might be fine to make to add `noexcept` , as it is not a breaking change. 

On the other hand, if `IsCanelled()` ever throw, it shouldn't be possible to recover from that.

**Comment by JeffreyRichter** [comment]
IsCancelled should never throw.

-- Jeffrey Richter
________________________________
