### ISSUE TITLE
Lower log level for " HTTP status code 200 won't be retried."

### ISSUE THREAD

**Issue by bzhou-sw** [Azure/azure-sdk-for-cpp#3581]
**Is your feature request related to a problem? Please describe.**
We set log level to `log_level_warning`, and we see a lot of log messages:
```
HTTP status code 200 won't be retried.
```
It caused so many unnecessary warnings in log file. 
IMHO `2xx status code won't be retried` is expected behavior and should not be treated as warning.

**Describe the solution you'd like**
Better to make such log level as info or verbose.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by RickWinter** [comment]
Thank you for the feedback on this.  We will consider this change for a future release.
