### ISSUE TITLE
[Bug] Overwriting `Azure::Core::Http::Details::c_GetStreamForBody` to false in Context for chunked response does not work.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#360]
When I call:
```
context = context.WithValue(Azure::Core::Http::Details::c_GetStreamForBody, false);
```
before a request is sent that's returning a chunked response with the context, the response will contain no response body, resulting in `RawResponse::GetBody()` returning empty buffer.

**Comment by JinmingHu-MSFT** [comment]
this is because we didn't check the bool value here. https://github.com/Azure/azure-sdk-for-cpp/blob/ef0c530ee0250ed879cb68c37ca11c2b2ad7e249/sdk/core/azure-core/src/http/transport_policy.cpp#L19

**Comment by vhvb1989** [comment]
No need to be fixed.
Context is not used any longer to set DownloadViaStream. 
Instead, HTTP Request is used to set this setting.
