### ISSUE TITLE
Context timeout exceeded when appending to an AppendBlob

### ISSUE THREAD

**Issue by sherriiiliu** [Azure/azure-sdk-for-cpp#3651]
**Question**
I am using C++ Azure Blob Storage SDK 12.4.0 to call `AppendBlock` to append block to an AppendBlock. I am also leveraging `Azure::Core::Context::WithDeadline(DateTime const & deadline)` to enforce a 100ms timeout on client side. What I expected is all write operations longer than 100ms will be cancelled and throw an `OperationCancelledException`, but what I truly observed is that some operations still last long and client side got a response after 100ms, even 1s. My question is, is context timeout not a hard timeout for client? Thanks.

**Setup**
 - OS: Windows Server 2019
 - SDK Version: 12.4.0

**Comment by Jinming-Hu** [comment]
As far as I know, context cancellation only tries best to cancel the operation. There's no guarantee it always works. Especially when the thread is trying to read data from wire, there's no way to cancel the blocking read operation until socket returns some data.

Core sdk team may know more about the implementation.

**Comment by RickWinter** [comment]
The context timeout only guarantees to never cancel early.

**Comment by sherriiiliu** [comment]
> The context timeout only guarantees to never cancel early.

Thanks for clarifying. Another question about the data written to blob storage after cancellation. If some data has been written to a blob successfully on server but not returned to client yet, after cancellation, will this part data be reverted? Or just leave in storage as garbage data?

**Comment by RickWinter** [comment]
The data written to the server will be complete for that particular request.  The cancellation token does not send a cancel request to the service.

**Comment by Jinming-Hu** [comment]
Rick is correct. Nothing will be reverted.
