### ISSUE TITLE
Audit and fix-up places where methods are marked as noexcept too liberally

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3674]
https://github.com/Azure/azure-sdk-for-cpp/search?l=C%2B%2B&q=noexcept

The string extension methods shouldn't be marked noexcept. Audit other instances, like the ones in DateTime.

Use of it in places like `Nullable<T>` is expected and OK. Ignore instances in 3rd party libraries like nlohmann json.

**Comment by ahsonkhan** [comment]
The relevant instances that need another look are in core.

cc @antkmsft, @LarryOsterman

**Comment by antkmsft** [comment]
When 4 of the linked PRs above, we should no longer have places where `noexcept` is used too liberally.
