### ISSUE TITLE
[Key Vault] Add error logging for when downloading an HSM's security domain fails.

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-cpp#3690]
Downloading an HSM's Security domain sometimes fails for our live tests without us logging a possible error message from the Powershell cmdlet. We can leverage [.NET](https://github.com/Azure/azure-sdk-for-net/blob/79fddcfff8d895a19cbea334ccea6d1a20cc918a/sdk/keyvault/test-resources-post.ps1#L99)'s approach to alleviate this in our `test-resources-post.ps1` script. [Here's a PR](https://github.com/Azure/azure-sdk-for-java/pull/29175) where Java added this change.

**Comment by gearama** [comment]
i'll look into it

**Comment by gearama** [comment]
we had this fix in our code
