### ISSUE TITLE
Can't generate project with samples

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#3723]
There's an issue trying to add a cmake target from identity samples:

-- Found Threads: TRUE  
CMake Error at build/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:606 (_add_library):
  _add_library INTERFACE library requires no source arguments.
Call Stack (most recent call first):
  samples/helpers/service/CMakeLists.txt:11 (add_library)

CMake Error at samples/helpers/service/CMakeLists.txt:17 (target_include_directories):
  Cannot specify include directories for target "service" which is not built
  by this project.

-- Check if compiler accepts -pthread

To repro, run:

cmake -DBUILD_TESTING=ON -DBUILD_SAMPLES=ON  ..

**Comment by ahsonkhan** [comment]
@vhvb1989 do we know *why* it broke now (or was it never building)?

**Comment by vhvb1989** [comment]
> @vhvb1989 do we know **why** it broke now (or was it never building)?

I didn't go deep enough to understand it. Since it works on Windows, I believe we are using Windows on CI to build samples and we don't have a gate to build samples for non-Windows. 

That's my guess.

I am also not sure why it works on Windows.  It could be related to the dynamic/static stuff or about how VSProjects are generated.  I am sure @antkmsft  would know better about the technical details :)

I just went straight forward with some fix to re-enable samples
