### ISSUE TITLE
Improve targeting

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#373]
Current builds include all targets. Targets should be scoped. 

This needs: 
* A way to list targets of a specific service (e.g. `azure-core*`) 
* A way to specify those targets to the build `cmake --build . --targets ...`

**Comment by danieljurek** [comment]
Moving this out of GA, we need to do work to split out the builds and figure out package/source dependencies before this work can be done. Was not listed as high pri for this cycle.

**Comment by RickWinter** [comment]
@danieljurek Are you planning to do more optimization in the package pipelines this semester?
