### ISSUE TITLE
Document the guideline exception: `TracerProvider` returns `_internal::Tracer` from a public method

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3741]
We’ve a scenario where we’d want to create an exception to the guideline that public method signatures and types shouldn’t expose `_internal` types. C++ doesn’t have a notion of internal, so we enforce it by convention, using the `_internal` namespace.

https://github.com/Azure/azure-sdk-for-cpp/blob/de6ed1da385a45e9e26afaae01e09a9671324bec/sdk/core/azure-core/inc/azure/core/tracing/tracing.hpp#L294-L310

**There’s no great way to strictly adhere to the guideline, in this case, so we'd want to document the exception that captures such a scenario.**

- We need the `TracerProvider` type to be public, since the end customer needs to instantiate it.
- We need packages outside of `Azure.Core` (i.e. `Azure.Core.Tracing.OpenTelemetry`) to implement the `CreateTracer` virtual method on that type. We have no way to mark a method on a public type as internal.
- We don’t want the `Tracer` types to be public, since the customer doesn’t need it. So, it is marked as `_internal`, even though it is returned from a public method.

https://github.com/Azure/azure-sdk-for-cpp/blob/f391e45bc144ce23488949aff9475f0ebfd199ba/sdk/core/azure-core-tracing-opentelemetry/README.md#enabling-tracing-using-opentelemetry

cc @LarryOsterman, @JeffreyRichter

**Comment by LarryOsterman** [comment]
Would you mind linking to the C++ guidelines that describe how to manage `_internal` types? I did a quick scan through the guidelines and did not find guidance related to internal types.

It would be helpful to understand the guidance which is being updated.

**Comment by JeffreyRichter** [comment]
If a customer calls the CreateTracer method above, they might want to assign the result to a variable that they declare as a SharedPtr<Tracer> (instead of auto) and therefore, Tracer should NOT be internal; it should be public.

**Comment by ahsonkhan** [comment]
From what I understand, the `CreateTracer` method is not intended to be called by the customer at all, and is only meant for the SDK. That is why the goal is to try and hide as much of the unnecessary details as possible, within the internal namespace, leading to this exceptional case. Only instantiating the `TracerProvider` type is needed by the customer.

Following through with making `Tracer` public would end up requiring a few other types like `Span`/etc. to be marked as public too, none of which the customer needs. We wanted to avoid exposing such types, similar to how .Net keeps its `DiagnosticScope` and factory types internal:
https://github.com/Azure/azure-sdk-for-net/blob/ac2497255f274d294d4f4f16497c11db8f2de148/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L18
