### ISSUE TITLE
Feature request: Add all C++ standard library keywords/functions to cSpell whitelist

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3743]
cSpell complains about word `stoul`, which is a function in C++ standard library https://en.cppreference.com/w/cpp/string/basic_string/stoul.

We could use cSpell directive to disable this warning, but that is less ideal. 

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1649730&view=logs&jobId=898e4637-1718-5730-45ee-bcd3f73a618c&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=ccad100f-2904-5913-2083-c525ad929a03

**Comment by danieljurek** [comment]
Looks like there's a dictionary called `cpp-refined` that contains the word... 

https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/cpp/src/stdlib-cpp.txt#L130

When upgrading the cspell version we should add in this dictionary.
