### ISSUE TITLE
Clean up cpp credscan errors

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-cpp#3837]
This is a pre-requisite step before enable the credscan in PR validation.

Setup a testing scan against the entire repo. 
Here is the error report: [CredScan result analysis](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1715661&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=9036d097-2774-5136-505e-b4dc0a37f42d)

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/48036328/179572041-3d2345b0-7ac0-4a4a-94bb-918af9b807a3.png">

**Comment by RickWinter** [comment]
@sima-zhu Can you provide an updated link.  The link for issues does not work.

**Comment by danieljurek** [comment]
This was fixed and credscan was added in https://github.com/Azure/azure-sdk-for-cpp/pull/4328
