### ISSUE TITLE
Empty file created if blob not found

### ISSUE THREAD

**Issue by mmarko1010** [Azure/azure-sdk-for-cpp#3847]
https://github.com/Azure/azure-sdk-for-cpp/blob/6c74e576f212f8e7c249200f827712be01558310/sdk/storage/azure-storage-blobs/src/blob_client.cpp#L422

shouldn't we [try to] download `firstChunk` before creating `fileWriter`?
The current implementation leaves behind an empty file (created in FileWriter) if the blob doesn't exist.

**Comment by Jinming-Hu** [comment]
This makes sense, will fix it sometime.
