### ISSUE TITLE
Newbie question: How to build shared libraries without modifying CMakeLists?

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-sdk-for-cpp#3849]
Is there a way to build Shared libraries instead of the static libraries straight from the source?

thanks,

Yang

**Comment by Jinming-Hu** [comment]
I always have the same problem. I remember building dll worked some time ago, then some day it didn't work anymore. @RickWinter Can you have somebody take a look?

**Comment by Jinming-Hu** [comment]
Hi @yxiang92128 , I just tested on ubuntu 20. I built with command `cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON`. It works.

Can you share your env and the command you used?

**Comment by steve-madden** [comment]
When targeting windows, static linkage for opentelemetry-cpp is required as the sdk is header-only. See https://github.com/open-telemetry/opentelemetry-cpp/issues/1105

This is enforced in the vcpkg port.  (see https://github.com/microsoft/vcpkg/blob/master/ports/opentelemetry-cpp/portfile.cmake)

Attempting to build the default cmake target fails:

```
C:\Users\smadden\dev\Azure\azure-sdk-for-cpp\build❯ cmake ..
No transport adapter was selected, using WinHTTP as the default option for Windows.
-- Running vcpkg install
Error: opentelemetry-cpp:x64-windows@1.3.0 is only supported on '!(windows & !static)'

-- Running vcpkg install - failed
CMake Error at build/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:850 (message):
  vcpkg install failed.  See logs for more information:
  C:\Users\smadden\dev\Azure\azure-sdk-for-cpp\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:26 (project)
```

**Comment by Jinming-Hu** [comment]
@steve-madden Yes, I am aware of this problem. But @yxiang92128 is working on Linux, so I assume he's referring to a different problem.

@steve-madden Do you mind opening a separate issue to track the one caused by opentelemetry?
