### ISSUE TITLE
Add vector const * const to http request to avoid copying while uploading

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#386]
Make http request to support having a const pointer to a vector for the payload to be uploaded.

This will avoid making a copy of data while pulling from bodyStream to upload data.  This is an improvement when uploading from a contiguous memory address.

**Comment by JinmingHu-MSFT** [comment]
Do we really need it? MemoryBodyStream can also do that.

**Comment by vhvb1989** [comment]
> 
> 
> Do we really need it? MemoryBodyStream can also do that.

MemoryBodyStream abstraction would be broken because it would need to provide it's buffer start (somehow).
We would need to assume MemoryBodyStream is always on contiguous memory as well.

The alternative is to document that a MemoryBodyStream is always on contiguous memory, then we need to add a method to BodyStream::GetType() which MemoryStream would override to return "MemoryBodyBufferType". This type would mean that we can get the buffer start pointer address from the stream.  However, this introduce the feature to all bodyStream to able to support unique features for it's own type.

We could bring it to our weekly meeting.  @JeffreyRichter  @RickWinter

**Comment by JinmingHu-MSFT** [comment]
@vhvb1989 okay, I see what you're trying to do.

So you want to add a constructor that accepts `const std::vector<uint8_t>*` as parameter, why not just `const uint8_t*`? it's simpler.

**Comment by JinmingHu-MSFT** [comment]
@vhvb1989 Also I don't think it's useful. Because we already decided that Storage API accepts `BodyStream`, not a vector or data pointer.

**Comment by vhvb1989** [comment]
Talked to Jeff about this.
We don't need to add this to Request.
The perf improvement won't be worth it.  We will use stream only for Request
