### ISSUE TITLE
Performance Testing for C++

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#387]
Work Remaining

- [x] Pipeline – 1 per language * service -- storage first  [[1 week]] – requires automation changes to support CPP
- [x] Integrate with the existing dashboard that  includes all languages – 2 days most work on Vinay

Other perf related bugs 
 #4060
 #4059
 #4058
 #4056
 #4057
 #4061

**Comment by gearama** [comment]
https://msit.powerbi.com/groups/me/reports/8d364b6d-89bd-4664-920d-d272d842f769/ReportSection4cb69395f87f6a0ae561?experience=power-bi
