### ISSUE TITLE
SAS Token compatibility across SDKs versions (v7.5 - v12)

### ISSUE THREAD

**Issue by lemon-guy** [Azure/azure-sdk-for-cpp#3870]
**Query/Question**
Is SAS Token generated with AzureSDK v7.5 compatible with AzureSDK v12?

In my case, I have server that generates SAS tokens and sends them to clients (separate VMs). 
Those clients use it to instantiate Azure::Storage::Blobs::BlockBlobClient and manipulate blobs later on.
Server is Debian, clients are Windows and Centos.

When both server and clients were running AzureSDK v7.5 everything was working as expected.
We are transitioning to v12 and started upgrade with clients, so we ended up in situation when:
server is v7.5, client is v12. And in this case requests end up with this error:

```
Azure threw storage exception...: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b7dc6f3a-101e-006e-4bf5-a84804000000
Time:2022-08-05T18:00:59.8131776Z
Request ID: b7dc6f3a-101e-006e-4bf5-a84804000000
        Extended Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b7dc6f3a-101e-006e-4bf5-a84804000000
Time:2022-08-05T18:00:59.8131776Z
```

To test if this is SAS Token version issue, I generated one in portal.azure.com and hardcoded it in client. I authenticated and requests worked.

I would like to maintain compatibility between older server and newer clients and I don't understand why old token wouldn't work with new SDK. Old SDK works with it just fine, so it's not like they were deprecated. 
Perhaps there is a bug when Azure SDK parses older version of token?

Here is v7.5 SAS token:
`?sv=2019-12-12&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtYFC%2BIoSk53P2Yw%3D&spr=https&se=2022-08-05T18%3A02%3A58Z&sp=racwdl&sr=c`
sig is 50 characters

Here is v12 SAS token:
`?sv=2021-06-08&ss=b&srt=sco&sp=rwdlaciyx&se=2022-08-06T05:45:00Z&st=2022-08-05T17:30:00Z&spr=https&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvvW2zupRfRt0cRc%3D`
sig is 48 characters

That's how I create Azure::Storage::Blobs::BlockBlobClient	and do requests:
```
std::string connection_string = "BlobEndpoint=https://" + accountName + ".blob.core.windows.net/;SharedAccessSignature=" + sasToken;
auto blobServiceClient = Azure::Storage::Blobs::BlobServiceClient::CreateFromConnectionString(connection_string);
Azure::Response<Azure::Storage::Blobs::Models::AccountInfo> response = blobServiceClient.GetAccountInfo();
```

Btw. By doing blobServiceClient.GetAccountInfo I check, if it was initialized properly. If there is better (official) way please let me know.
In 7.5 I was doing this:
```
auto storageAccount = azure::storage::cloud_storage_account::parse(connection_string);
if ( storageAccount.is_initialized() )
auto blobClient = storageAccount.create_cloud_blob_client();
```
but I didn't see counterpart for v12 :(

Thanks,
Michal

***Why is this not a Bug or a feature Request?***
It may be a bug, but perhaps I'm not using the SDK correctly?

**Setup (please complete the following information if applicable):**
 - OS: Windows10/Centos7
 - IDE : Visual Studio 2019
 - Azure Core 1.6.0
 - Azure Storage Common 12.2.4
 - Azure Storage Blobs 12.4.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [👍] Query Added
- [👍] Setup information Added

**Comment by Jinming-Hu** [comment]
Hi @lemon-guy , the SAS token you shared generated with v7.5 is service SAS token. The one generated by v12 is account SAS token. (See [this link](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview#service-sas) for the difference)

GetAccountInfo operation can only be authorized with account SAS token. That's why it failed with 403 when you used SAS token generated by v7.5 SDK to authorize such a request.

**Comment by lemon-guy** [comment]
@Jinming-Hu You are right, after removing GetAccountInfo and just straight up doing blob manipulation it worked. Thanks! 😄
