### ISSUE TITLE
Test failure azure-security-keyvault-keys.KeyVaultKeyClient.CreateKeyWithReleasePolicyOptions

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#3894]
Test is failing in pipeline

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1788075&view=logs&j=e4f25df5-be68-54ba-1772-d4de18f1aa91&t=9db41257-08f5-5ca9-db3b-46e639f68a82

**Comment by antkmsft** [comment]
It failed due to a timeout. Passed on rerun.
