### ISSUE TITLE
How to clear uncommitted blocks using StageBlock?

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-sdk-for-cpp#3911]
**Query/Question**
How do I undo "uncommitted blocks"?  meaning to clear the uncommitted block and start from scratch?

The only workaround I can think of is to delete the blob in its entirety. 

***Why is this not a Bug or a feature Request?***
Will need a way to back up uncommitted blocks for a blob.

**Setup (please complete the following information if applicable):**
 - OS: SLES15SP4
 - IDE : [e.g. IntelliJ]
 - Version of the Library used - latest
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
1. Delete blob
2. If you don't want to delete the blob, call GetBlockList, then CommitBlockList.

**Comment by yxiang92128** [comment]
> 1. Delete blob
> 
>     2. If you don't want to delete the blob, call GetBlockList, then CommitBlockList.

For option 2,  I just don't see how it might work.  How do you get CommitBlockList to wipe out the UncommittedBlocks? CommitBlock takes a list of blockIds you want to commit; so if you give a zero length vector, it will do nothing? and the UncommittedBlocks would still be there?  I am not sure how it might actually work.

thanks.

**Comment by yxiang92128** [comment]
A unrelated question:
I am trying to stage a block and then retrieve the Uncommitted List afterwards.  Shall I expect Uncommit list size to be 1? It somehow printed size to be 0 after this block of code.   I don't know what went wrong.  I thought if I call StageBlock with a buffer and a size, it will get accumulated into the Uncommitted blocks until I call CommitBlockList?

    ```
auto block_id = encode_block_id(context->block_id);
    const std::vector<uint8_t> dataPart1(static_cast<size_t>(128), 'a');
    fprintf(stderr, "staging: %s\n", block_id.c_str());
    fflush(stderr);

    auto blockContent = Azure::Core::IO::MemoryBodyStream(dataPart1.data(), dataPart1.size());

    blockBlobClient.StageBlock(block_id, blockContent);

    auto current_blocks_res  = blockBlobClient.GetBlockList(options, aContext);

    fprintf(stderr, "UncommitBlock size: %d\n", current_blocks_res.Value.UncommittedBlocks.size());
    fflush(stderr);


```

**Comment by yxiang92128** [comment]
unrelated question:
BlobServiceClient, BlobContainerClient and BlobClient
For any of these client handles above which are created from CreateFromConnectionString, how do I save them to a member variable because it does not seem to be a default constructor for them?

I intend to reuse the client later on for another operation such as Download or List.

thanks

**Comment by Jinming-Hu** [comment]
> > 1. Delete blob
> >    
> >    2. If you don't want to delete the blob, call GetBlockList, then CommitBlockList.
> 
> For option 2, I just don't see how it might work. How do you get CommitBlockList to wipe out the UncommittedBlocks? CommitBlock takes a list of blockIds you want to commit; so if you give a zero length vector, it will do nothing? and the UncommittedBlocks would still be there? I am not sure how it might actually work.
> 
> thanks.

`CommitBlockList` will clear all blocks that are not in the list. 
If you call GetBlockList to get current blocks, then call CommitBlockList with the same blocks, the blob content will keep unchanged.

**Comment by Jinming-Hu** [comment]
> 



> unrelated question: BlobServiceClient, BlobContainerClient and BlobClient For any of these client handles above which are created from CreateFromConnectionString, how do I save them to a member variable because it does not seem to be a default constructor for them?
> 
> I intend to reuse the client later on for another operation such as Download or List.
> 
> thanks

Do pointers work for you in this case? like `std::unique_ptr<SomeClient>` or `std::shared_ptr<SomeClient>`?
