### ISSUE TITLE
How to set encryption algorithm/key/checksum in track2? Customer Provided Key

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-sdk-for-cpp#3926]
**Query/Question**
In legacy sdk, we used to do this as a workaround to encrypt the object with a customer provided key and also the chosen algorithm by the customer along with a checksum.

```
azure::storage::operation_context context;
context.user_headers().add(_XPLATSTR("x-ms-encryption-algorithm"), _XPLATSTR(sseinfo->getSSEAlgo()));
context.user_headers().add(_XPLATSTR("x-ms-encryption-key"), _XPLATSTR(sseinfo->getCPEKKey()));
context.user_headers().add(_XPLATSTR("x-ms-encryption-key-sha256"), _XPLATSTR(sseinfo->getCPEKChecksum()));


```

Do we have a more direct API options to set those now in track2?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] SLES15SP4
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 latest

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
Hi @yxiang92128 , there a field `CustomerProvidedKey` in [BlobClientOptions](https://github.com/Azure/azure-sdk-for-cpp/blob/009fe81672801ca7ef193a4e91cd800121eb5e5c/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp#L141). You set this field and create a client with it, all requests sent from this client will have these headers applied.


@microzchang Can you share a code sample for this scenario?

**Comment by microzchang** [comment]
Hi @yxiang92128 , Here is a code sample for this scenario, FYI.

```
    // create container client with CPK
    Blobs::EncryptionKey key; // CPK
    Blobs::BlobClientOptions options;
    options.CustomerProvidedKey = key;
    auto containerClient = Azure::Storage::Blobs::BlobContainerClient::CreateFromConnectionString(
        StandardStorageConnectionString(), m_containerName, options);
    containerClient.GetProperties();

    //create blob using CPK
    std::vector<uint8_t> blobContent(512);
    Azure::Core::IO::MemoryBodyStream bodyStream(blobContent.data(), blobContent.size());
    std::string blockBlobName = "test1" ;
    auto blockBlobClient = containerClient.GetBlockBlobClient(blockBlobName);
    bodyStream.Rewind();
    blockBlobClient.Upload(bodyStream);
    std::string blockId1 = Base64EncodeText("1");
    blockBlobClient.CommitBlockList({blockId1});
```

**Comment by Jinming-Hu** [comment]
There are three fields in [EncryptionKey](https://github.com/Azure/azure-sdk-for-cpp/blob/93991ab122a5d8ec757445476ac01916b0d1ca6f/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp#L115), corresponding to those HTTP headers.
Currently only AES-256 is supported.

**Comment by yxiang92128** [comment]
I wonder why this EncryptionKey is being set at ClientOption level for the BlobContainerClient.  If I were to reuse the client, the encryption key will stay in effect throughout its lifetime; however if there are certain object(s) I don't want to apply the CPEK on, I don't see a workaround but to create a new client.  I think it might be more appropriate to apply the CPEK at the context level just as the legacy SDK does.  Can you guys comment?

**Comment by Jinming-Hu** [comment]
@yxiang92128  this is by-design in Track2 SDK. You want to use a new CPEK, you'll have to create a new client.

Note that you don't have to create BlobContainerClient then all the way down to a blob client. [BlobClient](https://github.com/Azure/azure-sdk-for-cpp/blob/009fe81672801ca7ef193a4e91cd800121eb5e5c/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp#L56) also takes ClientOptions as parameter.

**Comment by yxiang92128** [comment]
Can you add an API to update the CustomerProvidedKey (internal field m_customerProvidedKey) for the Client?   Our application creates and uses a BlobContainerClient handle to create blob on the go and each blob could be supplied with different keys.

**Comment by Jinming-Hu** [comment]
> Can you add an API to update the CustomerProvidedKey (internal field m_customerProvidedKey) for the Client? Our application creates and uses a BlobContainerClient handle to create blob on the go and each blob could be supplied with different keys. A significant rewrite of our code is required if we need to create a BlobClient on each request; I am not sure about the performance impact either.

Adding a new API would be challenging. Unlike legacy SDK, v12 SDK has consistent API interface across all language storage SDKs. If .Net v12 SDK or java/python/js v12 SDK doesn't have such an API, it's hard to justify it in C++.

Can you elaborate on why creating a new blob client from constructor for each blob doesn't work for your scenario?
