### ISSUE TITLE
Optimizing performance issue for http client

### ISSUE THREAD

**Issue by JasonYang-MSFT** [Azure/azure-sdk-for-cpp#395]
**Describe the bug**
The default http client has extremally low performance.

In a single stage block operation with 8MB payload, it costs **_32.771 seconds_** to finish. 32.769 of them are spent in **_curl_easy_send_** here: https://github.com/Azure/azure-sdk-for-cpp/blob/9563d9dd3c3c6b10d02befc3baa974fa16572fad/sdk/core/azure-core/src/http/curl/curl.cpp#L224

On the other hand, directly using curl's **_curl_easy_perform_** to stage a block with 8MB payload in the same environment only costs **_3.676 seconds_** which is 8x faster.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.
**1** SingleThreadPerf here used default http client to upload blocks. https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/test/blobs/performance_benchmark.cpp#L12
**2** Below code is directly using curl to upload a block.
void CurlEasyTest()
{
  char* buffer = new char[8 * 1024 * 1024];

  std::string url = "xxx";
  CURL* easy_handle = curl_easy_init();

  curl_easy_setopt(easy_handle, CURLOPT_UPLOAD, 1L);
  curl_easy_setopt(easy_handle, CURLOPT_PUT, 1L);

  curl_easy_setopt(easy_handle, CURLOPT_URL, url.data());

  struct curl_slist* chunk = NULL;
  chunk = curl_slist_append(chunk, "x-ms-version: 2019-02-02");
  chunk = curl_slist_append(chunk, "Content-Length: 8388608");
  curl_easy_setopt(easy_handle, CURLOPT_HTTPHEADER, chunk);

  curl_easy_setopt(easy_handle, CURLOPT_READFUNCTION, read_callback);
  curl_easy_setopt(easy_handle, CURLOPT_READDATA, (void*)buffer);
  curl_easy_setopt(easy_handle, CURLOPT_BUFFERSIZE, 8388608);
  curl_easy_setopt(easy_handle, CURLOPT_INFILESIZE_LARGE, (curl_off_t)8388608);

  clock_t begin = clock();
  curl_easy_perform(easy_handle);
  clock_t end = clock();

  std::cout << "Size" << total << std::endl;
  std::cout << (end - begin) * 1000 / CLOCKS_PER_SEC << "ms" << std::endl;

  delete[] buffer;
}
**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by vhvb1989** [comment]
The provided test program has a weird behavior.  `clock()` function returns a bigger `clock_t` for the end_time when using Azure Core Transport Adapter. Even when it takes lees time to complete a PUT upload operation.  

                I changed the way time is recorded for `std::chrono::steady_clock::now();` and I see the values I was expecting:

// Time result using Azure Core Transport Adapter:
Size: 8388608     // payload size to upload
Time difference = 869[ms]

// Time result using the program provided by Storage team (using libcurl only)
Size: 8388608    // payload size to upload
Time difference = 60071[ms]


I believe `time_t` gets some kind of overflow at some point and the value it is giving you is not accurate.

Can you update the way the measurements are taken to use chrono library and share the results with it?

Here is a simple PR with the tests I created.
https://github.com/Azure/azure-sdk-for-cpp/pull/396

**Comment by JasonYang-MSFT** [comment]
clock() returns “The number of clock ticks elapsed since an epoch related to the particular program execution.”. So the value itself, instead of the difference between two values, shouldn’t be used to compare two test programs or one test program but in two different runs. 

I have run those three test programs. It shows exactly the opposite of what you concluded.

Azure core transport test costs 39 ~ 40 seconds while curl only test costs 10~11 seconds. 

![perfAzureCore](https://user-images.githubusercontent.com/18202333/89422804-5de3c400-d768-11ea-939b-3455660c097b.PNG)
![perfAzureHttpPipeLine](https://user-images.githubusercontent.com/18202333/89422809-5fad8780-d768-11ea-8d83-94e08c481ccb.PNG)
![perfCurlOnlyTest](https://user-images.githubusercontent.com/18202333/89422814-60461e00-d768-11ea-86b8-6673fc387217.PNG)

**Comment by vhvb1989** [comment]
@JasonYang-MSFT  thanks for the data.
I noticed the results are from Windows.
I got my results from Linux, so, we might be fine on Linux.

For Windows, can you mention if you are using the default curl[winssl] from vcpkg?  
I noticed that time gets improved if the tests are done to the HTTP version of the server instead of the HTTPS.

I am trying to run on Windows with openssl  (the way we do on Linux) and see the numbers.
I will share my results later

**Comment by JasonYang-MSFT** [comment]
It is curl[winssl]. I was following the instructions here: https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests

**Comment by RickWinter** [comment]
@vhvb1989 Can you update the issue with the work items and add an estimate value

**Comment by vhvb1989** [comment]
hi @JasonYang-MSFT 

Can you try latest master to see if this is resolved?
Latest master contains the implementation for keep-alive and the fix for waitForSocket function. 
So this issue should be already fixed by those commits.

Let me know if you still see any issue

**Comment by vhvb1989** [comment]
Closing issue for now.
Please reopen if you still see perf issue
