### ISSUE TITLE
KeyVault: Settings API

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#3988]

**Comment by gearama** [comment]
ey folks, here is [the Settings work](https://github.com/Azure/azure-sdk-for-java/pull/31705) I've got going so far for Java. A few things are subject to change, most likely when it comes to the KeyVaultSetting class and how we store it's value property, but in general the shape of the APIs should remain the same. Here's an [APIView link](https://apiview.dev/Assemblies/Review/32098eb4e57c45638a66927947e2c2d8/dd77ff7105f5421a83c86d36fb0123ab?diffRevisionId=e046238ead884119b3c3acc0fe65d21a&doc=False&diffOnly=True) if you want to take a look at the APIs only.
