### ISSUE TITLE
Code Generation

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#4]
**Protocol Layer Patterns**
- [ ] Parameter design
   - [ ] Optional vs Required parameters
- [ ] Naming patterns

**Code Generation**
- [ ] Prototype Code Generation tooling for AutoRest 
   - [ ] Spit out structures
   - [ ] Spit out serialization code
   - [ ] Storage Protocol Layer Produced

**Comment by RickWinter** [comment]
Tracked in CodeGen
