### ISSUE TITLE
Object versioning and object immutability support in the Azure blob storage CPP SDK

### ISSUE THREAD

**Issue by adhitya97** [Azure/azure-sdk-for-cpp#4019]
Hello,

I am unable to find any documentation in the CPP SDK regarding setting/getting object retention and list object versions that are present in a versioning enabled container. 

Is there a plan to add provisions to perform immutability operations using the CPP SDK?

Thanks in advance.

**Comment by microzchang** [comment]
Hello,
Now there are APIs related to immutability operations that can be used, you can refer to the following code:

- getting object retention:
    API `Azure::Storage::Blobs::BlobClient::GetProperties()` can get the properties of the blob, and you can get the object retention info from `ImmutabilityPolicy` filed like below:
https://github.com/Azure/azure-sdk-for-cpp/blob/083a88e8849d54be50aa50434995f480b67d1274/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp#L1637
- setting object retention:
   API `Azure::Storage::Blobs::BlobClient::SetImmutabilityPolicy()` can set the Immutability Policy of the blob.
https://github.com/Azure/azure-sdk-for-cpp/blob/083a88e8849d54be50aa50434995f480b67d1274/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp#L379
- list object versions:
  API `Azure::Storage::Blobs::BlobContainerClient::ListBlobsByHierarchy()` can list object versions.
https://github.com/Azure/azure-sdk-for-cpp/blob/083a88e8849d54be50aa50434995f480b67d1274/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp#L227
 And set `options.Include = Versions` like below code can list object versions :
```
    Azure::Storage::Blobs::ListBlobsOptions options;
    options.Include = Blobs::Models::ListBlobsIncludeFlags::Versions;
```

Also, you can view [https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api](url) for more information.
