### ISSUE TITLE
Make the SDK to build using simple instructions

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#4025]
Cleanup the build instructions to provide simple instructions for:

- Building from source
- Building with vcpkg

**Comment by Jinming-Hu** [comment]
Not all the main branch commits in our repo are in release state.

If you clone the repo right now, it may contain some code that's supposed to be released next month. The code may be broken (cannot compile, containing a bug, waiting for arch board approval etc.). User-Agent is not correctly set either.

We need to solve this problem first if you plan to support building from main branch.
