### ISSUE TITLE
Individual status codes in batch request available after exception

### ISSUE THREAD

**Issue by Essyer** [Azure/azure-sdk-for-cpp#4048]
**Is your feature request related to a problem? Please describe.**
Following guide for [.net](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs.Batch/samples/Sample03b_BatchingAsync.cs) FineGrainedBatchingAsync I am trying to get response codes for each sub request of batch request for both, blob deletions and tier change. Example below is for tier change requests, m_workingContainer is BlobContainerClient.
```
auto batch = std::make_shared<Azure::Storage::Blobs::BlobContainerBatch>(m_workingContainer.CreateBatch());
std::vector<std::pair<std::string, std::shared_ptr<Azure::Storage::DeferredResponse<Azure::Storage::Blobs::Models::SetBlobAccessTierResult>>>> tierChangeResults;
...
for(auto &item : items)
{
  auto tierChangeResult = batch->SetBlobAccessTier(item.blobName, Azure::Storage::Blobs::Models::AccessTier::Cool);
  auto tierChangeResultP = make_shared<Azure::Storage::DeferredResponse<Azure::Storage::Blobs::Models::SetBlobAccessTierResult>>(std::move(tierChangeResult));
  tierChangeResults.push_back(std::make_pair(std::move(item.blobName), std::move(tierChangeResultP)));
}
...
try { 
  auto batchRes = m_workingContainer.SubmitBatch(*batch);
  for(auto &res : tierChangeResults)
  {
	  auto batchResponseCode = static_cast<int>(res.second->GetResponse().RawResponse.get()->GetStatusCode());
          std::cout << "Blob " << res.first << " status " << batchResponseCode << std::endl;
  }
}
catch (const Azure::Storage::StorageException& e)
{
...
}

```
If all blobs exist, the batch request returns without exception and I can iterate over all sub requests and get status 200 for each one. If I remove one of blobs before tier change request is sent, SubmitBatch throws exception:
```
if (httpStatusCode != Core::Http::HttpStatusCode::Accepted)
{
  throw StorageException::CreateFromResponse(std::move(pRawResponse));
}
```
When pRawResponse is moved to exception constructor, it is no longer available in DeferredResponse. If any sub request fails, even though all other blobs will be moved to cool tier I do not know about it because whole batch fails and I cannot get response codes. How can I get sub request status after the exception?

**Describe the solution you'd like**
pRawResponse copy to exception constructor

**Describe alternatives you've considered**
StorageException API that returns list of blob names and status codes

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Jinming-Hu** [comment]
@Essyer  How about this:


```C++
try { 
  auto batchRes = m_workingContainer.SubmitBatch(*batch);
} catch (StorageException& e) {
  // batch request fail, none of the subrequests were executed
}

for(auto &res : tierChangeResults) {
  try {
    auto batchResponseCode = static_cast<int>(res.second->GetResponse().RawResponse.get()->GetStatusCode());
    // subrequest successful
  }
  catch (StorageException& e) {
    // subrequest fail
  }
}
````

**Comment by Essyer** [comment]
@Jinming-Hu Thank you very much, with your example I get all information I need.
