### ISSUE TITLE
LNK2005 errors occur when attempting to build Azure C++ code into C++/CLR library via native static library

### ISSUE THREAD

**Issue by kwende** [Azure/azure-sdk-for-cpp#4049]
**Describe the bug**
A working example can be found here: https://github.com/kwende/AzureCPPTestingGrounds. Our solution consists of a number of native static libraries that link into a C++/CLR library that ultimately gets consumed by a C# application. We need to use the Azure C++ code from one of the static libraries. Once included in the static library, the C++/CLR library no longer builds because of linker errors. The linker errors are due to the fact CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS is used when building the Azure libraries, which exposes all symbols (including CRT symbols) causing multiple definitions to occur and thereby break our build process. 

For more details, see my post I added to the wrong repo here: https://github.com/Azure/azure-storage-cpp/issues/415

***Exception or Stack Trace***
1>MSVCRTD.lib(throw_bad_alloc.obj) : error LNK2005: "public: __cdecl std::bad_alloc::bad_alloc(class std::bad_alloc const &)" (??0bad_alloc@std@@QEAA@AEBV01@@Z) already defined in staticlibrary.lib(azure-core.dll)
1>MSVCRTD.lib(throw_bad_alloc.obj) : error LNK2005: "public: __cdecl std::bad_array_new_length::bad_array_new_length(class std::bad_array_new_length const &)" (??0bad_array_new_length@std@@QEAA@AEBV01@@Z) already defined in staticlibrary.lib(azure-core.dll)
1>MSVCRTD.lib(throw_bad_alloc.obj) : error LNK2005: "public: __cdecl std::exception::exception(class std::exception const &)" (??0exception@std@@QEAA@AEBV01@@Z) already defined in staticlibrary.lib(azure-core.dll)
1>MSVCRTD.lib(throw_bad_alloc.obj) : error LNK2005: "public: virtual __cdecl std::bad_array_new_length::~bad_array_new_length(void)" (??1bad_array_new_length@std@@UEAA@XZ) already defined in staticlibrary.lib(azure-core.dll)
1>MSVCRTD.lib(throw_bad_alloc.obj) : error LNK2005: "public: virtual char const * __cdecl std::exception::what(void)const " (?what@exception@std@@UEBAPEBDXZ) already defined in staticlibrary.lib(azure-core.dll)
1>ManagedLibrary.obj : error LNK2028: unresolved token (0A0001C9) "unsigned __int64 __cdecl DoIt(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?DoIt@@$$FYA_KV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z) referenced in function "public: unsigned __int64 __clrcall ManagedLibrary::AzureFile::GetFileSize(void)" (?GetFileSize@AzureFile@ManagedLibrary@@$$FQE$AAM_KXZ)
1>ManagedLibrary.obj : error LNK2019: unresolved external symbol "unsigned __int64 __cdecl DoIt(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?DoIt@@$$FYA_KV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z) referenced in function "public: unsigned __int64 __clrcall ManagedLibrary::AzureFile::GetFileSize(void)" (?GetFileSize@AzureFile@ManagedLibrary@@$$FQE$AAM_KXZ)
1>C:\repos\AzureCPPTestingGrounds\ExampeBuildError\x64\Debug\ManagedLibrary.dll : fatal error LNK1120: 2 unresolved externals
1

**To Reproduce**

It's laid out in the README for the repo I showed above giving a working example. But here is the copy/paste of that: 

Git pull VCPKG from here: https://github.com/microsoft/vcpkg
Run .\bootstrap-vcpkg.bat from the VCPKG repo.
Now install the Azure C++ SDK: ./vcpkg.exe install azure-storage-blobs-cpp:x64-windows azure-storage-files-datalake-cpp:x64-windows azure-storage-files-shares-cpp:x64-windows.
We don't use CMAKE for anything, so we're going to just grab the DLL/LIB files directly. We notice the .LIB files generated to: C:\repos\vcpkg\installed\x64-windows\lib. Likewise, we notice the include files located at C:\repos\vcpkg\installed\x64-windows\include.
We create a new solution (the solution in this repo) that consists of three components: a native static library, a C++/CLR library, and a C# console application.
We copy the LIB and INCLUDE files from where we found them in Step 4 to an EXTERNALS folder in our solution. Since all we're concerned with at this time is building, we leave out the DLLs.
We reference the LIB and INCLUDE files from the static library. We then take add code to the static library inspired from https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-blobs/samples/blob_getting_started.cpp.
We build this library and notice it builds.
We then reference this static library from the C++/CLR library. We attempt to use it, but notice it doesn't build because of LNK2005 errors regarding the C runtime.

***Code Snippet***
It's a linker error, no snippet is available. 

**Expected behavior**
I expect the C runtime functions to not be exposed and so my C++/CLR DLL should build w/ the static library. 

**Screenshots**
![image](https://user-images.githubusercontent.com/526471/197573517-9b137e7e-4229-4873-b6eb-86560141cd96.png)

**Setup (please complete the following information):**
 - OS: [e.g. iOS] OS Name	Microsoft Windows 11 Pro, Version	10.0.22621 Build 22621
 - IDE : [e.g. IntelliJ] Visual Studio
 - Version of the Library used: 
 
 Microsoft Visual Studio Professional 2022 (64-bit) - Current, Version 17.3.6, 
Microsoft Visual Studio Professional 2022
Version 17.3.6
VisualStudio.17.Release/17.3.6+32929.385
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA252
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22179.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.32708
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.22179.3
Profiling support for Python projects.

Python with Pylance   17.0.22179.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.32708
Visual C++ for Linux Development

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [ x] Setup information Added

**Comment by RickWinter** [comment]
The code has significantly changed since this issue was filed. We are interested to learn more about your scenario. Please feel free to open a new issue if this problem is still affecting your builds.
