### ISSUE TITLE
[Perf] Cannot detect runtime package versions for storage-blobs tests

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-cpp#4052]
The storage-blobs perf tests currently have two issues preventing full detection of runtime package versions:

1. The version of `azure-storage-blobs` is printed with the incorrect case, which prevents it from being detected.  The tools code expects the version to be printed `UPPER-CASE`, but the storage-blob test prints `Mixed-case`:

```
var packageMatch = Regex.Match(result.StandardOutput, @$"{key.ToUpper()} VERSION ?.*");
```
https://github.com/Azure/azure-sdk-tools/blob/dd39b04ec076e35e5f52a65b7b12638b27fff6a9/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs#L80

```
[07:00:07.277] Azure-storage-blobs VERSION source
```
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1940429&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=49e32a0b-4245-531b-0723-9d45113ffbd3&l=653

2. The test only prints the version of `azure-storage-blobs`, but not `azure-core`.  We want to track the version of all `azure-*` packages, to ensure we are testing the correct versions.  Specifically, we typically want to test both storage and core as packages, compared to both storage and core from source.

**Comment by Jinming-Hu** [comment]
@mikeharder Is this still an issue? Do you know which piece of code prints the version?
