### ISSUE TITLE
[Perf] Perf tests appear to use sources when they claim to be using packages

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-cpp#4062]
PR https://github.com/Azure/azure-sdk-for-cpp/pull/4012 adds a perf test which calls `Core::Convert::Base64Encode()`, and also adds a 100ms sleep in the `Base64Encode()` method in source.

The goal is to verify that the perf pipeline is correctly using packages and sources as expected.  Specifically, when testing the source version of `azure-core-cpp`, throughput should be around 10 ops/sec, due to the 100ms sleep.  But when testing the package version of `azure-core-cpp`, throughput should be much higher.

Here is a pipeline run before the 100ms sleep was added.  Both `1.7.2` and `source` are around 25M ops/sec:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1941892&view=logs&j=eb9934df-ce1d-5189-09d1-97b6d9cd110c&t=0e80b947-56f8-55fe-4bce-23cb00c0ba0a&l=12

Here is a pipeline run after the 100ms sleep was added.  `source` is around 10 ops/sec as expected, but `1.7.2` is also around 10 ops/sec, which implies that sources were used instead of the package:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1941917&view=logs&j=eb9934df-ce1d-5189-09d1-97b6d9cd110c&t=0e80b947-56f8-55fe-4bce-23cb00c0ba0a&l=12

**Comment by gearama** [comment]
this should have been fixed a while back
