### ISSUE TITLE
[Azure Core] URL encoding problems

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#407]
1. In `Url::AddQueryParameter`, are we supposed to pass encoded query parameters or unencoded query parameters?
2. `Request::GetEncodedUrl` doesn't encode the URL at all, neither path nor query parameters.
3. Storage code requires access to unencoded query parameters to sign the request.

**Comment by vhvb1989** [comment]
1. ->  Unencoded.
2. ->  I want to move the url-encoding responsibility to the transport adapter.  This would mean that HTTP Request in Azure Core will never know anything about encoding.  Convenience layer wouldn't also require to encode a url or query parameters.

In the initial design, however, we are expecting the HTTP Request to be able to make the url-encoding. (Not implemented yet)
I will talk to @JeffreyRichter about it

**Comment by JinmingHu-MSFT** [comment]
> 1. ->  Unencoded.
> 2. ->  I want to move the url-encoding responsibility to the transport adapter.  This would mean that HTTP Request in Azure Core will never know anything about encoding.  Convenience layer wouldn't also require to encode a url or query parameters.
> 
> In the initial design, however, we are expecting the HTTP Request to be able to make the url-encoding. (Not implemented yet)
> I will talk to @JeffreyRichter about it

I want to share requests from storage side, before you redesign and rewrite this `Request` thing.

1. constructor of `Request` should be able to accept an encoded URL. Whether or not it can handle unencoded URL is totally up to you, storage side doesn't care.
2. Storage needs to be able to access **encoded** path to sign the request.
3. Storage needs to be able to access **decoded** query parameters to sign the request.

**Comment by vhvb1989** [comment]
The expected design I am planning to implement is:
1.  Merging URLBuilder class from storage and URL class from Core
	-  Same features from Storage to be keep
2.  Update HTTP Request to be constructed with a URL class instead of an std::string
	-  Anyone creating a Request (convenience/protocol layer) would need to create a URL object first to create a Request.
       -  Http Request would create a copy of the URL, so the URL object used to init the Request can change/be gone/etc, but HTTP request will keep a copy.
3.  Remove getPath() and getHost() from HTTP Request. 
	-  Adding getURL() instead to return a copy of the URL object that can be used to get path, host, query, etc
4.  Add an static method static std::string url-encode(std::string source) to URL class that can be used by the transport adapter to encode url before sending it

**Comment by vhvb1989** [comment]
@JinmingHu-MSFT , I have a question about the first requeriment:

>1. constructor of Request should be able to accept an encoded URL. Whether or not it can handle unencoded URL is totally >up to you, storage side doesn't care.`

I was looking to the storage code here:
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/src/common/storage_credential.cpp#L10

I noticed that the URL is not passed encoded:
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/src/common/storage_credential.cpp#L62

Then I saw on URLBuilder there is a comment about url must be url-encoded
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/inc/common/storage_uri_builder.hpp#L16

Does it only means that the URI builder will not encode it?   Like it does with other methods like appendPath()?

**Comment by JinmingHu-MSFT** [comment]
> I was looking to the storage code here:
> https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/src/common/storage_credential.cpp#L10
> 
> I noticed that the URL is not passed encoded:
> https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/src/common/storage_credential.cpp#L62
> 
> Then I saw on URLBuilder there is a comment about url must be url-encoded
> https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/inc/common/storage_uri_builder.hpp#L16
> 
> Does it only means that the URI builder will not encode it? Like it does with other methods like appendPath()?

Because in connection string, the URL always only contains ascii characters. They are totally the same before and after encodinng.

**Comment by JinmingHu-MSFT** [comment]
> 4\. Add an static method static std::string url-encode(std::string source) to URL class that can be used by the transport adapter to encode url before sending it

Do we need to make it static method? What if it's just a member method?
