### ISSUE TITLE
Create a template project

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#411]
In other monorepos we have a `template` project which serves as both a starting point for creating packages the repo and as a means of testing publishing mechanisms without affecting packages published for other services. 

* [.NET](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/template)
* [Java](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/template)
* [JS](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/template)
* [Python](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/template) 

The package's code should be very simple ([example](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/template/azure-template/azure/template/template_code.py)). 

We do sometimes release the template package to package managers ([example](https://www.nuget.org/packages/Azure.Template/1.0.2-preview.17)). For vcpkg I imagine that we should close all automatically opened PRs for template before releasing.

**Comment by RickWinter** [comment]
Examples for this are in other languages such as .NET
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/template

The package needs to show how tests run, how packages are built, how docs are built.
The template package lets other services know what is needed to start working.  It also allows the EngSys team to validate changes they are making.
