### ISSUE TITLE
Instructions to build only sdk/storage/azure-storage-blobs and it's dependencies

### ISSUE THREAD

**Issue by nishanth-hon** [Azure/azure-sdk-for-cpp#4139]
**Query/Question**
I am planning to use azure sdk for cpp in a resource constrained device. I only want azure storage blob upload feature.
I do not want azure keyvault or azure-storage-queues or any other module. What options should I pass while build to achieve this? 

***Why is this not a Bug or a feature Request?***
This is merely a request for instructions to serve a specific use case

**Setup (please complete the following information if applicable):**
Doesn't seem applicable. I feel this can apply to all setups/ build environments.

For Example  azure-iot-sdk-c (https://github.com/Azure/azure-iot-sdk-c/blob/LTS_07_2022_Ref02/CMakeLists.txt)
provides options to only compile specific modules that are required.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Jinming-Hu** [comment]
@nishanth-hon Do you build from source or install via vcpkg?
