### ISSUE TITLE
Create Identity e2e tests for running in Azure Functions

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-cpp#414]
Tracking item to create new /sdk/e2e Azure.Identity smoke tests for running in Azure Functions hosted environment.

1. Add new /sdk/e2e tests for Azure Functions
2. Update Parent issue https://github.com/Azure/azure-sdk/issues/899 with instructions for Test team

/cc @danieljurek

**Comment by antkmsft** [comment]
// NOTE: Azure Functions is Managed Identity Credential, and we do have an E2E test written for ManagedIdentityCredential: https://github.com/Azure/azure-sdk-for-cpp/blob/b54d509c72fb76598832bcf1fcd5c4a89b245782/sdk/identity/azure-identity/test/e2e/azure_identity_e2e_test.cpp
