### ISSUE TITLE
SAS token working in previous version (v7.5) but not on current version (v12)

### ISSUE THREAD

**Issue by giseliramos** [Azure/azure-sdk-for-cpp#4140]
**Query/Question**
When using the lib `azure::storage_lite`, version 7.5, with a SAS token generated at the container level, I was able to create a blob client with the following:
```
auto creds = std::make_shared<azure::storage_lite::shared_access_signature_credential>(sasToken);
auto account = std::make_shared<azure::storage_lite::storage_account>(nameAccount, creds, useHttps, blobEndpoint);
blob_client = azure::storage_lite::blob_client(account, maxConc);
```

For the new version (this library, version 12), with the same SAS token and with the following code, I´m unable to create the blob client:
```
const auto sasTokenUrl = fmt::format("https://{}/{}?{}", blobEndpoint, containerName, sasToken);
blobClient = Azure::Storage::Blobs::BlobContainerClient(sasTokenUrl);
```
It gives a 403 error. Is there any missing steps to successfully authenticate with the same SAS token? I´m sure that the token is not expired. I also checked the migration guide, it states that I need the complete url, so I´m formatting to generate the complete url.

Any clarification on this auth migration guide would be useful.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 20.04
 - IDE : VS code
 - Version of the Library used: azure-storage-blobs 12.6.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Jinming-Hu** [comment]
@giseliramos 

The code snippet looks good to me.

Can you share the error message? There is a RequestId in it. I can check from server side why the request failed.

**Comment by giseliramos** [comment]
Hi @Jinming-Hu, after I use `blobContainerClient.CreateIfNotExists()`, I have the following error and request id:
```
This request is not authorized to perform this operation.
RequestId:1ea4e224-d01e-000e-02bb-040820000000
Time:2022-11-30T12:56:54.3917782Z
```
I´ve noticed that if I generate a SAS token at container level, even with all the permissions, I´m not able to use the functions `CreateIfNotExists()` and `GetProperties()`. It works only if I use a SAS token at account level, is that correct?

**Comment by Jinming-Hu** [comment]
@giseliramos You cannot create or delete container with container sas. You have to use account sas to do that. This is by-design

Take a look at below links for sas permissions

https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specify-the-signed-resource-blob-storage-only
https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specify-the-account-sas-parameters
