### ISSUE TITLE
LIVEONLY tests in Storage 

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4147]
There are some issues with test proxy behavior and some of the storage tests in a few cases there are errors around json deserialization "expected string received null", which suggest that the deserailization of the incoming json might not handle nulls properly. 
The followin g tests i swiched to _LIVEONLY_ 
         
 
	 37 - azure-storage-blobs.BlobContainerClientTest.Lease (Failed)
	 
	114 - azure-storage-blobs.PageBlobClientTest.Lease (Failed)
	
	420 - azure-storage-files-shares.FileShareClientTest.Lease (Failed)
	421 - azure-storage-files-shares.FileShareClientTest.SnapshotLease (Failed)
	
	447 - azure-storage-files-shares.FileShareFileClientTest.LeaseRelated (Failed)

TEST_F(BlobBatchClientTest, DISABLED_SubmitDeleteBatch) 
 TEST_F(BlobBatchClientTest, DISABLED_SnapshotVersion
 TEST_F(BlobBatchClientTest, DISABLED_TokenAuthorization)
TEST_F(QueueClientTest, PeekMessage_LIVEONLY_)

[testlogs.zip](https://github.com/Azure/azure-sdk-for-cpp/files/10135304/testlogs.zip)
[AppendBlobClientTest.ContentHash.zip](https://github.com/Azure/azure-sdk-for-cpp/files/10157180/AppendBlobClientTest.ContentHash.zip)

**Comment by gearama** [comment]
https://github.com/Azure/azure-sdk-tools/issues/4853

**Comment by Jinming-Hu** [comment]
@gearama 

Do you want storage team to look into this or you want to assign this to yourself just for tracking?

**Comment by Jinming-Hu** [comment]
Hi @gearama , 

I found some secrets were not properly redacted when fetching tokens. 
In the below recorded request, tenant ID, client ID, client secret were in plaintext. Not sure if the cookie should be redacted.

![image](https://user-images.githubusercontent.com/52266153/211984065-a1cb0309-f94d-4d19-8d63-82421ff8d25d.png)

**Comment by Jinming-Hu** [comment]
Hi @gearama , have you got a chance to look at the above issue?

What is the correct way to record/playback token-fetching/refreshing requests anyway? Is it by-design to now record such requests?
