### ISSUE TITLE
Azure Tables SDK

### ISSUE THREAD

**Issue by ahojnnes** [Azure/azure-sdk-for-cpp#4149]
The legacy https://github.com/Azure/azure-storage-cpp SDK supports Azure Table storage.

Is there a plan to support Azure Table storage through this modernized SDK?
```[tasklist]
### API Surface Area
- [x] SetTableServiceProperties
- [x] GetTableServiceProperties
- [x] Preflight Table Check
- [x] GetService Stat
- [x] CreateTable
- [x] DeleteTable
- [x] QueryTable
- [x] GetTableACL
- [x] SetTableACL
- [x] QueryEntities
- [x] InsertEntity
- [x] UpdateEntity
- [x] MergeEntity
- [x] DeleteEntity
- [x] Insert/Merge Entity
- [x] Insert/Replace Entity
- [x] EntityGroup Transactions
- [x] Swtich to Tables/azure-data-tables
```

```[tasklist]
### Clients
- [x] Token Client
- [x] Connection String Client
- [x] SaS Client
```

```[tasklist]
### Additional Work
- [x] Stress
- [x] Samples
- [x] Docs
- [x] API Review
- [x] Perf
- [x] Api Review Feedback
```

**Comment by RickWinter** [comment]
Thank you for taking the time to open this request.  We are building out services in this new format.  I can't comment on when Tables will be available but can say it is a service we plan to provide.

**Comment by ronniegeraghty** [comment]
Hi @ahojnnes, 
We've released the first beta of our [Azure Tables library for C++](https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-data-tables/1.0.0-beta.1/index.html)!
Please take a look and let us know what you think.
