### ISSUE TITLE
Can we update DateTime::Parse(string, DateFormat::Rfc3339) to allow space in place of T?

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#4171]
So far, it is the only known input that has space in it instead of "T". If we have more, we can add (internally first, I think) another parse format support. It is easy to modify the parser to allow space there.
But, I would check with Jeffrey first to ask if he thinks it is safe to update the parser, and whether that still can be called `DateFormat::Rfc3339`.

RFC 3339 itself says:
"_NOTE: ISO 8601 defines date and time separated by "T". Applications using this syntax may choose, for the sake of readability, to specify a full-date and full-time separated by (say) a space character._"
https://www.rfc-editor.org/rfc/rfc3339

_Originally posted by @antkmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/4167#discussion_r1042897351_
      
FWIW, .NET's DateTime.Parse() would parse `"2021-02-03 12:34:56"`, ours would not.

**Comment by JeffreyRichter** [comment]
Do we have a need to allow the space instead of T? If so, what is the use case?

**Comment by antkmsft** [comment]
It is only needed by `AzureCliCredential`, in one place. Currently, we do search-for-space-and-replace-with-T there: https://github.com/Azure/azure-sdk-for-cpp/blob/456a8e9fb9154d223f07b7d01df890a1a17b714e/sdk/identity/azure-identity/src/token_credential_impl.cpp#L184-L194

Should we leave it only at that one place, or is it ok to update the `DateTime` parser?

**Comment by JeffreyRichter** [comment]
Leave it for now. This shouldn't happen often, so we hopefully won't need to change our DateTime parser.

**Comment by antkmsft** [comment]
Thanks Jeffrey!
cc @ahsonkhan

**Comment by ahsonkhan** [comment]
What format does the DateTime in `AzureCliCredential` adhere to? Is the datetime format they use documented somewhere?

Our Rfc3339 datetime format seems to be too strict. Rfc3339 is a profile of ISO8601 but allows some more flexibility beyond what ISO 8601 states. Given the enum name is Rfc3339 and not ISO8601, we may want to be less strict.

> Separating date and time parts with other characters such as space is not allowed in ISO 8601, but allowed in its profile RFC 3339.

**Comment by antkmsft** [comment]
`AzureCliCredential` has to work with what `az account get-access-token --output json ...` command gives it. And that is apparently, a string, as you'd expect from a datetime, but with a space instead of T. I think it ultimately comes from MSAL for Pyhton library. I don't think it is explicitly documented. Even if they fix it, we'd still have to support older versions.

I agree, adding support for space is probably the least problematic things we can add support for - it is widely used. Even .NET's `DateTime.Parse()` supports it. But the fact that up to this moment no one has ran into this limitation, does also indicate that it is not used very frequently in the SDK space. And that argument has some strength for us, as our `DateTime` is not a general purpose DateTime, but the one that is used for communications with Azure services. If we add it, we won't be able to take it back, and will have to support it, although realistically it won't cost us much.

I understand Jeffrey's decision here, not adding it yet leaves us with more potential options for the future and limits the scope we have to support. I'd say, let's see if more places need support for space in datetimes, or if customer would want it, and then we can add it, and we'll update the place in the token parser where we replace space with `'T'` before giving it to DateTime parser. I don't think it is "never", I think it is "maybe later".

**Comment by ahsonkhan** [comment]
> is not a general purpose DateTime, but the one that is used for communications with Azure services

We **do** need it for communication with Azure services, here. Azure Cli Credential bares that out. Rather than having custom string find-replace logic (which we are needing to do anyway), the appropriate fix would be to have the `DateTime::Parse` method be accurate to what it is documented as doing. I am not saying we should support every single test case, but allowing `T` OR `<space>` seems reasonable.

Change this line:
https://github.com/Azure/azure-sdk-for-cpp/blob/3fe9c27c412fcb46d0399f27b900a45e7fbee1c6/sdk/core/azure-core/src/datetime.cpp#L607

```diff
- if (cursor < DateTimeLength && (dateTime[cursor] == 'T' || dateTime[cursor] == 't'))
+ // Unlike ISO 8601, RFC 3339 allows for a space character, and that's needed by Azure Cli Credential
+ if (cursor < DateTimeLength && (dateTime[cursor] == 'T' || dateTime[cursor] == 't' || dateTime[cursor] == ' '))
```


https://github.com/Azure/azure-sdk-for-cpp/blob/3fe9c27c412fcb46d0399f27b900a45e7fbee1c6/sdk/core/azure-core/inc/azure/core/datetime.hpp#L171-L182

Also, we have a `DateFormat` which explicitly says parse this date according to Rfc 3339 and then we are rejecting an input that is valid according to the RFC. I would consider that something worth fixing.

https://medium.easyread.co/understanding-about-rfc-3339-for-datetime-formatting-in-software-engineering-940aa5d5f68a

https://ijmacd.github.io/rfc3339-iso8601/

**Comment by antkmsft** [comment]
@ahsonkhan, both your and @JeffreyRichter arguments make sense to me. Jeffrey's from a practical point of view, yours from the theoretical and from specification purity point of view. My instinct is more with Jeffrey, since once released, we have less options to change it in the future. Although in this case, it makes good sense, and it is not likely it is going to be problematic for us in the future, plus I like mimicking the .NET behavior. But in the end, I do not have that strong of an opinion. Either is fine with me - as I said, I kind of agree with you both. So far, I am fine with find-and-replace on that one instance in the code. Plus it makes Identity backwards-compatible for a few more versions.
It looks like you are more passionate about this, and I respect that. If you can come to an agreement with Jeffrey about this, and make sure we are really not missing anything and won't run into any unforeseen problems, I will be happy to change it. Just do that and tell me the conclusion, and I'll make a PR that adds `' '` where `'T'` is allowed and a few updates to unit test.

**Comment by antkmsft** [comment]
Space it is. I'll make a PR.
