### ISSUE TITLE
Does Listblob have similiar option for SetStartAfter?

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-sdk-for-cpp#4194]
**Query/Question**
AWS S3 has the following
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ListObjectsV2Request.html#setStartAfter-java.lang.String-

I wonder if I need to accomplish the similar functionality in Azure blobs. What should I do? 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
No, it doesn't have such an option.
