### ISSUE TITLE
Generating SAS token requires usage of "_internal" methods

### ISSUE THREAD

**Issue by ahojnnes** [Azure/azure-sdk-for-cpp#4204]
Using the current interfaces for blob storage, the only available interface to produce a SAS token from a connection string looks as follows (unless I missed something):
```
const auto connectionStringParts = Azure::Storage::_internal::ParseConnectionString(connectionString);
std::string sasToken = sasBuilder.GenerateSasToken(Azure::Storage::StorageSharedKeyCredential(
    connectionStringParts.AccountName, connectionStringParts.AccountKey));
```
It could be convenient to have a `Azure::Storage::StorageSharedKeyCredential::CreateFromConnectionString()` or be able to create a SAS token from a BlobServiceClient or similar without accessing internal methods.

**Comment by Jinming-Hu** [comment]
Hi @ahojnnes thanks for your feedback.

The problem for `Azure::Storage::StorageSharedKeyCredential::CreateFromConnectionString()` is that not all connection strings have account name or account key. The connection strings you get from Azure Portal is the most common one, but there are other kinds out there. Some connection strings consist of URLs and SAS tokens. In this case, you cannot create a shared key credential from this kind of connection strings.

**Comment by Jinming-Hu** [comment]
We don't support generating SAS from service client or other clients because some SAS tokens require blob container name or blob path. But we cannot always extract these two fields from url.

**Comment by ahojnnes** [comment]
I guess `Azure::Storage::StorageSharedKeyCredential::CreateFromConnectionString` could throw an appropriate exception, if the given connection string does not contain an account name and key?
