### ISSUE TITLE
TransportAdapterOptions.MultipleCrlOperations unit test fails on Linux

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#4237]
I think it is an issue with the connection pool, not the example.com.
Maybe there is a newer Libcur version that started behaving differently on Linux.
But it repros consistently in CI now.

I compiled with Curl transport on Windows, it does not repro.
On Linux, it also fails with `_LIVEONLY_`.

CI failure logs:
first,
```
[  INFO ] /mnt/vss/_work/1/s/sdk/core/azure-core/test/ut/transport_policy_options.cpp:549:: Test https://www.example.com/
231: [2023-01-10T19:34:34.6835347Z] DEBUG : [CURL Transport Adapter]: Creating a new session.
231: [2023-01-10T19:34:34.6835697Z] DEBUG : [CURL Transport Adapter]: Spawn new connection.
231: [2023-01-10T19:35:38.7378656Z] DEBUG : [CURL Transport Adapter]: No Host in request headers. Adding it
231: [2023-01-10T19:35:38.7379044Z] DEBUG : [CURL Transport Adapter]: No content-length in headers. Adding it
231: [2023-01-10T19:35:38.7379310Z] DEBUG : [CURL Transport Adapter]: Send request without payload
231: [2023-01-10T19:35:38.7384886Z] DEBUG : [CURL Transport Adapter]: Parse server response
231: [2023-01-10T19:35:38.7459252Z] DEBUG : [CURL Transport Adapter]: Request completed. Moving response out of session and session to response.
231: [2023-01-10T19:35:38.7459741Z] DEBUG : Moving connection to pool...
231: [2023-01-10T19:35:38.7460087Z] DEBUG : Clean thread running. Won't start a new one.
```

then,
```
231:   Actual: it throws Azure::Core::Http::TransportException with description "Fail to get a new connection for: https://www.example.com. Timeout was reached".
```

Place in the test code where it fails:
https://github.com/Azure/azure-sdk-for-cpp/blob/01af6783b1ffa4be1717fd8d413e874dcee5620d/sdk/core/azure-core/test/ut/transport_policy_options.cpp#L578-L579

Log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2105545&view=logs&j=ca6c228c-7ba2-55ec-3482-b320fca07ebb&t=58b93069-ce09-5d02-79f9-e17c70ed0a5d

**Comment by antkmsft** [comment]
Ok, so I ran it on my local Gentoo machine - the test passes. So, something must be wrong with the CI machine, unless it is Ubuntu-specific. Good news, I think, is that it is not likely a bug in the code, either our SDK or libcurl, probably a setup issue. I think it could be related with some connection restrictions for CI machines.

@danieljurek, does this ring any bells? One of the unit tests started to fail about 2 days ago, that test is trying to reach some https endpoints (example.com, amazon.com, google.com) while doing something special with certificates (@LarryOsterman probably has more context). Could it be some firewall or proxy setting? Do you know if maybe some security setting got changed for Ubuntu machines recently?

**Comment by antkmsft** [comment]
@danieljurek, it is the machine pool:
* Run in`azsdk-pool-mms-ubuntu-*-general` pool + `MMSUbuntu*` images - fails on Ubuntu: https://github.com/Azure/azure-sdk-for-cpp/pull/4238/checks?check_run_id=10590166919
* Run in `Azure Pipelines` pool + `ubuntu-*` images - passes on Ubuntu: https://github.com/Azure/azure-sdk-for-cpp/pull/4238/checks?check_run_id=10591118292

So, what do we do now? Can I check in the change that changes the pool to Azure Pipelines?

Bad news: about an hour ago, it stated to fail on Mac machines. Whichever firewall changes getting applied to machine pools seem to be breaking our tests. This one with Linux pool started at the end of the last week or early this week.

cc @LarryOsterman

**Comment by antkmsft** [comment]
@LarryOsterman, and I am not sure if "example.com" is the only one that fails, or is it just the first one. But maybe "google.com" and "amazon.com" are in the 1ES firewall's allow list, but "example.com" is not, and that's why we're seeing problems with it.

**Comment by danieljurek** [comment]
@mikeharder -- Looks like there's a firewall rule impacting some CI tests for the C++ SDK. 

@antkmsft -- Could you try using `microsoft.com` or a storage account (e.g. `cppvcpkgcache.blob.core.windows.net`)?

**Comment by LarryOsterman** [comment]
> If I understand that test correctly, it wanted domains that are signed with different types of certificates/different root authorities, and the domains that are being used have that mix. I'll clarify with Larry, he knows more.

That is exactly what the test is doing. It also attempts to verify it multiple times to exercise the CRL cache in CURL.

**Comment by antkmsft** [comment]
How important is it for the test to talk to amazon.com, google.com, example.com instead of, let's say, microsoft.com, azure.com, xbox.com, github.com, office.com, etc? If it makes no difference, maybe we can use these domains, and the 1ES team would feel a little better about moving these domains to allow-list?
Does the fact that amazon, google, and example.com are using TLS certificates with different authorities, maybe even slightly different certificate types, matters at all?

**Comment by LarryOsterman** [comment]
> How important is it for the test to talk to amazon.com, google.com, example.com instead of, let's say, microsoft.com, azure.com, xbox.com, github.com, office.com, etc? If it makes no difference, maybe we can use these domains, and the 1ES team would feel a little better about moving these domains to allow-list?
Does the fact that amazon, google, and example.com are using TLS certificates with different authorities, maybe even slightly different certificate types, matters at all?

The entire purpose of this test is to use non-microsoft assets. Every Microsoft asset uses the same CA, one owned by Microsoft.

If we believe that the HttpTransport is intended to work with arbitrary HTTP servers, then IMHO it's important to test against servers that have certificates issued by different CAs, and with different CRL/OCSP rules.

If, on the other hand, we believe that the HttpTransport in the "Azure C++ SDK" is only intended to communicate with Azure/Microsoft resources, then we can drop the checks for non-Microsoft CA based sites.

And to be clear: Both of these interpretations are completely accurate.
