### ISSUE TITLE
Warning C4100 for unreferenced formal parameter in the OpenTelemetry installed dependency, when building the tests in the repo via command line.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4250]
I get this build warning coming from the installed vcpkg dependency, when building the repo from the command line (on Windows):
```text
mkdir build
cd build
cmake ..
cmake --build .
```

```text 
opentelemetry.cpp
  azure-core-tracing-opentelemetry.vcxproj -> E:\GitHub\Fork\azure-sdk-for-cpp\build\sdk\core\azure-core-tracing-opente
  lemetry\Debug\azure-core-tracing-opentelemetry.lib
  azure_core_otel_test.cpp
  service_support_test.cpp
E:\GitHub\Fork\azure-sdk-for-cpp\build\vcpkg_installed\x64-windows-static\include\opentelemetry/sdk/trace/simple_proces
sor.h(44,57): error C2220: the following warning is treated as an error [E:\GitHub\Fork\azure-sdk-for-cpp\build\sdk\cor
e\azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
E:\GitHub\Fork\azure-sdk-for-cpp\build\vcpkg_installed\x64-windows-static\include\opentelemetry/sdk/trace/simple_proces
sor.h(44,57): warning C4100: 'parent_context': unreferenced formal parameter [E:\GitHub\Fork\azure-sdk-for-cpp\build\sd
k\core\azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
E:\GitHub\Fork\azure-sdk-for-cpp\build\vcpkg_installed\x64-windows-static\include\opentelemetry/sdk/trace/simple_proces
sor.h(43,28): warning C4100: 'span': unreferenced formal parameter [E:\GitHub\Fork\azure-sdk-for-cpp\build\sdk\core\azu
re-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
E:\GitHub\Fork\azure-sdk-for-cpp\build\vcpkg_installed\x64-windows-static\include\opentelemetry/sdk/trace/simple_proces
sor.h(59,33): warning C4100: 'timeout': unreferenced formal parameter [E:\GitHub\Fork\azure-sdk-for-cpp\build\sdk\core\
azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
  Generating Code...
```

Here's the corresponding code:
https://github.com/open-telemetry/opentelemetry-cpp/blob/46b16ec3cf6ce622c0e074a0f2bbe73cf269798d/sdk/include/opentelemetry/sdk/trace/simple_processor.h#L43-L45

https://github.com/open-telemetry/opentelemetry-cpp/blob/46b16ec3cf6ce622c0e074a0f2bbe73cf269798d/sdk/include/opentelemetry/sdk/trace/simple_processor.h#L58

@LarryOsterman Should we opt-out of these warnings (but only from our dependency), from tests, like we do here?
https://github.com/Azure/azure-sdk-for-cpp/blob/868ad80ca2b4d23413f46eddaefaac1f09705179/sdk/core/azure-core-tracing-opentelemetry/src/opentelemetry.cpp#L10-L23

**Comment by ahsonkhan** [comment]
We have the following pragma around the headers in one of the test files, but not the other:
https://github.com/Azure/azure-sdk-for-cpp/blob/868ad80ca2b4d23413f46eddaefaac1f09705179/sdk/core/azure-core-tracing-opentelemetry/test/ut/azure_core_otel_test.cpp#L9-L27

https://github.com/Azure/azure-sdk-for-cpp/blob/868ad80ca2b4d23413f46eddaefaac1f09705179/sdk/core/azure-core-tracing-opentelemetry/test/ut/service_support_test.cpp#L18

**Comment by antkmsft** [comment]
I think we should disable any warning coming from 3rd party headers, not only here but in all occurrences - current and future ones - if we can't do anything about it, so they are de-facto unactionable and they clutter the error logs.
And I think we already do this ion other places.
So, I'd disable not only 4100 in your PR, but also 4244 and 6323. If there is pragma to disable all, without providing individual numbers, I'd use that before the block of 3rd party library includes, and restore right afterwards.
