### ISSUE TITLE
Create API Review step is failing in pipeline runs due to linker command failed with exit code 1107

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4275]
Recent CI and nightly runs are failing with warnings and errors more frequently than before. One contributing factor is APIView related errors and warnings.

> PowerShell exited with code '1'.
Build • Create API Review for azure-core • Create API Review for azure-core

For example:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2139473&view=logs&j=a5b8631f-d2a8-5bf4-c5b7-ed5dd46e146c&t=e1b0a0cf-6330-5d90-93da-5076ba54d894
> clang++: error: linker command failed with exit code 1107 (use -v to see invocation)
> Exception details: StatusCode: 413, ReasonPhrase: 'Payload Too Large', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:

This isn't unique to Core. We see other errors for service SDKs, like Attestation:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2139476&view=logs&j=a5b8631f-d2a8-5bf4-c5b7-ed5dd46e146c&t=e1b0a0cf-6330-5d90-93da-5076ba54d894&l=51
> clang++ D:\a\_work\1\s\sdk\attestation\azure-security-attestation\inc\ApiViewSettings.json D:\a\_work\1\s\sdk\attestation\azure-...
clang++: error: linker command failed with exit code 1107 (use -v to see invocation)
> Exception details: StatusCode: 524, ReasonPhrase: '', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:

It would be useful to output more diagnostic information to the console to debug reasons for such error conditions.

There is another warning in the `Dump Package properties` step:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2140048&view=logs&j=a5b8631f-d2a8-5bf4-c5b7-ed5dd46e146c&t=d7f7b61a-6ffa-5531-6b02-f2d4db7c9f77&l=15
> ##[warning]Failed to retrieve package version for 'core/perf'. No version file found.

Here are the recent public and internal `cpp - core` pipelines.

https://dev.azure.com/azure-sdk/public/_build?definitionId=1614&_a=summary

![image](https://user-images.githubusercontent.com/6527137/214728056-83631e2c-0e19-408c-8f1f-33451aa32bc0.png)

https://dev.azure.com/azure-sdk/internal/_build?definitionId=1615&_a=summary

![image](https://user-images.githubusercontent.com/6527137/214727951-72ca9ca6-6c14-4204-9970-1c8ca980b60b.png)

@LarryOsterman, @danieljurek, @RickWinter

**Comment by RickWinter** [comment]
@ahsonkhan I have not seen this failure recently.  Is this still an issue or can this be closed?

/cc: @LarryOsterman

**Comment by ahsonkhan** [comment]
Yeah, seems like it has been fixed, looking at recent runs like these:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2819764&view=logs&j=35d7e651-8a8e-56d5-4b64-d16694245812&t=faf6fff4-92e8-51af-9fb2-08b78942373f

I am not sure what fixed it though, maybe https://github.com/Azure/azure-sdk-for-cpp/pull/4521?
