### ISSUE TITLE
The test-proxy.log should show up in artifacts during CI runs to help debuggability

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4285]
From @LarryOsterman: This way, if something fails during a test proxy run, we have information from the logs that can help diagnose the issue.

cc @scbedd

**Comment by scbedd** [comment]
[This is actually present now](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2211377&view=logs&j=eab3bf07-e4a8-5feb-e258-dcdff3614a8b&t=eeffb5bb-8a0a-5f42-8ecf-bc8d13dbef8f)
