### ISSUE TITLE
QoL improvements: PRs only modifying markdown files in the repo (such as docs) should still have link verification, cspell, and other CI checks run

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4287]
Currently, whenever a PR modifies just the markdown files in the repo, the CI leg is stuck at `checkenforcer` and none of the verification legs that are part of `GenerateReleaseArtifacts` run. These are important to catch link verification and spelling errors.

Otherwise, errors slip through, causing other PRs to be impacted and builds fail (like in here https://github.com/Azure/azure-sdk-for-cpp/pull/4273, https://github.com/Azure/azure-sdk-for-cpp/issues/4286).

For example, look at this PR which highlights the unwanted behavior:
https://github.com/Azure/azure-sdk-for-cpp/pull/4283

![image](https://user-images.githubusercontent.com/6527137/214970660-19bd832b-432c-409a-8ecf-31b5c15963bd.png)

For the appropriate checks and CI pipelines to run, I had to cosmetically modify other files, such as the `CMakeLists.txt` file. Otherwise, no CI legs run. Only then do we see things like:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2142299&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=ccad100f-2904-5913-2083-c525ad929a03

![image](https://user-images.githubusercontent.com/6527137/214970797-a0c2f995-cbe2-4419-aa23-ab6eae302bc2.png)

This has the other unfortunate side effect of the PR not being mergeable, since it can't be green.

cc @weshaggard, @danieljurek, @RickWinter, @LarryOsterman

**Comment by LarryOsterman** [comment]
One option to consider is to change sdk\core\ci.yml to add the "doc" tree to the list of paths which should be included. That should cause the core pipeline to be triggered whenever we modify any of our documents.

**Comment by ahsonkhan** [comment]
That's a good idea!

How do we handle and merge doc changes at the root of the repo, like the README.md or the contributing guide?

**Comment by weshaggard** [comment]
@ahsonkhan you could add a path trigger for the root of the repo to trigger the core pipeline as well.

**Comment by LarryOsterman** [comment]
Wes, wouldn't the path trigger on the root mean that the core pipeline is triggered on every change to the repo, not just file changes in the root of the repo?

**Comment by weshaggard** [comment]
Yes if you do the full path but you can do wildcards based on what I'm reading at https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#paths. Perhaps `*.md` would work to only trigger on those files.

**Comment by ahsonkhan** [comment]
Partially fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/4296
