### ISSUE TITLE
Repo-wide cleanup of mention and artifacts after test recordings were moved out

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4293]
With the test recording json file clean-up and move effort (done in https://github.com/Azure/azure-sdk-for-cpp/pull/4118), there are remnants of a few files/artifacts related to test recordings that can be cleaned-up now.

This isn't an exhaustive list, but it is start of what to fix:
1) Do we still need `AZURE_TEST_RECORDING_DIR`?
For example, see:
https://github.com/Azure/azure-sdk-for-cpp/blob/efee11268ec3e0dcf98dea8d3c5f2abc5c529f41/sdk/keyvault/azure-security-keyvault-administration/test/ut/CMakeLists.txt#L12-L13
2) We can remove the opt-out for cspell since those directories don't exist:
https://github.com/Azure/azure-sdk-for-cpp/blob/efee11268ec3e0dcf98dea8d3c5f2abc5c529f41/.vscode/cspell.json#L28
3) The contributing guide still mentions the use of a `/recordings` folder:
https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#test-mode
> All the AZURE service network responses are recorded in a json file within the /recordings folder from the /test/ut directory.

**Comment by gearama** [comment]
AZURE_TEST_RECORDING_DIR is actually used to determine the path where the test proxy stores the recordings, to give it the relative path where to  recording is stored, so we actually need it. 

2. and 3. addressed
