### ISSUE TITLE
Perf Pipline for storage failing 

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4353]
[2/10 5:15 PM] Mike Harder
Hey George.  It looks like the C++ blob perf pipeline has an issue where it sometimes fails.

[2/10 5:15 PM] Mike Harder
These two builds were of the same commit but one failed

[2/10 5:16 PM] Mike Harder
The one that failed broke during 10KB upload using "source" versions

[2/10 5:17 PM] Mike Harder
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2178390&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=49e32a0b-4245-531b-0723-9d45113ffbd3&l=9290

"Parallel":8,"Port":null,"Rate":null,"TestProxies":"N/A","Warmup":60}=== Test Options ==={"Size":"1073741824"}=== Global Setup ====== Test Setup ===Standard Error:   at Azure.Sdk.Tools.PerfAutomation.Util.RunAsync(String filename, String arguments, String workingDirectory, IDictionary`2 environmentVariables, StringBuilder outputBuilder, StringBuilder errorBuilder, Boolean throwOnError) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Util.cs:line 84

I'm guessing the C++ process crashed without writing anything to console
**Describe the bug**

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
```
Azure.Sdk.Tools.PerfAutomation.ProcessResultException: Command '/mnt/vss/_work/1/s/build/sdk/storage/azure-storage-blobs/test/perf/azure-storage-blobs-perf DownloadBlob --size 1073741824 --parallel 8 --warmup 60 --duration 60 --sync' failed with exit code 137
```

I think the process was killed due to OOM. @mikeharder did you make any changes to the perf test recently that could possibly increase the memory usage?

**Comment by gearama** [comment]
done
