### ISSUE TITLE
blobClient.UploadFromBuffer() hangs uploading to Premium BlockBlobStorage

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-cpp#437]
## Repro Steps
1. Build storage samples
   * `cmake -DBUILD_CURL_TRANSPORT=ON -DBUILD_TESTING=ON -DBUILD_STORAGE_SAMPLES=ON ..`
   * `make -j 8`
2. Set `AZURE_STORAGE_CONNECTION_STRING` to a storage account of kind `Standard/Hot - StorageV2 (general purpose v2)`.
3. `./sdk/storage/sample/azure-storage-sample BlobsGettingStarted`
    * Sample works fine
4. Set `AZURE_STORAGE_CONNECTION_STRING` to a storage account of kind `Premium - BlockBlobStorage`.
5. `./sdk/storage/sample/azure-storage-sample BlobsGettingStarted`
    * Sample creates container successfully, but `blobClient.UploadFromBuffer` hangs indefinitely.

**Comment by JinmingHu-MSFT** [comment]
maybe it's a storage bug, i'm going to look into it.

**Comment by JinmingHu-MSFT** [comment]
@mikeharder that's because Premium storage account only supports page blob, while we're demonstrating how to upload a block blob in the sample.

But it shouldn't hang indefinitely, did you handle the exception?

**Comment by mikeharder** [comment]
@JinmingHu-MSFT: Are you sure Premium only supports page blob?  The account kind is "BlockBlobStorage" so I'm pretty sure it supports block blob:

![image](https://user-images.githubusercontent.com/9459391/90066204-4b0a4b80-dca2-11ea-8c53-beba841b0b00.png)

The documentation also states that Premium supports block blobs: https://azure.microsoft.com/en-us/pricing/details/storage/blobs/

**Comment by JinmingHu-MSFT** [comment]
@mikeharder oh, i was trying premium standard storage v2 
![image](https://user-images.githubusercontent.com/52266153/90083237-8e1cfb00-dd44-11ea-99a5-0fa6727d8692.png)

**Comment by JinmingHu-MSFT** [comment]
confirmed as a bug in Core HTTP client, cannot handle chunked response with 0 length.

Raw response:
```
HTTP/1.1 201 Created
Transfer-Encoding: chunked
Content-MD5: Pz8543xut4RVSbb2g52Mww==
Last-Modified: Thu, 13 Aug 2020 01:16:27 GMT
ETag: "0x8D83F2681038358"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 924441bd-501e-0027-7e0f-716e1b000000
x-ms-client-request-id: 47a74d7e-7805-49ad-725d-06b1c4d7927d
x-ms-version: 2019-12-12
x-ms-content-crc64: DtjZpL9/o8c=
x-ms-request-server-encrypted: true
Date: Thu, 13 Aug 2020 01:16:27 GMT

0

```

**Comment by JinmingHu-MSFT** [comment]
@vhvb1989 please fix this one.

**Comment by katmsft** [comment]
I have also encountered this issue in File service when creating permission.
Request:
```
PUT https://tankstdcppt.file.core.windows.net/yczmdnu3rf?comp=filepermission&restype=share HTTP/1.1
authorization: SharedKey tankstdcppt:xxxxxxxxxxxxxxxxxx=
content-length: 206
host: tankstdcppt.file.core.windows.net
user-agent: azsdk-cpp-storagefile/1.0.0-private.beta.1 (Windows 10 Enterprise 6.3 18363 18362.1.amd64fre.19h1_release.190318-1202)
x-ms-date: Thu, 13 Aug 2020 07:35:27 GMT
x-ms-version: 2019-12-12

{"permission":"O:S-1-5-21-2127521184-1604012920-1887927527-21560751G:S-1-5-21-2127521184-1604012920-1887927527-513D:AI(A;;FA;;;SY)(A;;FA;;;BA)(A;;0x1200a9;;;S-1-5-21-397955417-626881126-188441444-3053964)"}
```
Response:
```
HTTP/1.1 201 Created
Server: Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: d783c4eb-d01a-000a-5144-71fb7e000000
x-ms-version: 2019-12-12
x-ms-file-permission-key: 12575217961520350054*667635224076228247
Date: Thu, 13 Aug 2020 07:35:27 GMT
Content-Length: 0
```
