### ISSUE TITLE
sdk\core\azure-core\test\libcurl-stress-test pulls the incorrect vcpkg version.

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-for-cpp#4370]
**Describe the bug**
The dockerfile in libcurl-stress-test\Dockerfile has the following code:

```dockerfile
RUN wget -O vcpkg.tar.gz https://github.com/microsoft/vcpkg/archive/master.tar.gz
RUN mkdir /opt/vcpkg
RUN tar xf vcpkg.tar.gz --strip-components=1 -C /opt/vcpkg
RUN /opt/vcpkg/bootstrap-vcpkg.sh
RUN ln -s /opt/vcpkg/vcpkg /usr/local/bin/vcpkg

```

This code pulls what is in the current vcpkg release. But the Azure SDK is built and tested with a specific vcpkg commit (currently 94ce0dab56f4d8ba6bd631ba59ed682b02d45c46). By pulling the current baseline instead of the commit against which the packages are built, the SDK built for the Dockerfile is being built against an untested set of downstream dependencies.

**Expected behavior**

The dockerfile should pull the vcpkg repository at the vcpkg commit which was used to test the Azure SDK - we have had challenges when we build and test against newer vcpkg binaries.

**Comment by gearama** [comment]
VCPKG here runs in Manifest mode, thus it will use that version of the packages that vcpkg will use will be at that glorious SHA. E.G. when building the build logs:
Vcpkg integrate step.
CMAKE_TOOLCHAIN_FILE is not defined. Define it for the user.
AZURE_SDK_DISABLE_AUTO_VCPKG is not defined. Fetch a local copy of vcpkg.
Vcpkg commit string used: 94ce0dab56f4d8ba6bd631ba59ed682b02d45c46
-- Bootstrapping vcpkg before install

**Comment by gearama** [comment]
reope to use for PR update
