### ISSUE TITLE
Build failure on aarch64

### ISSUE THREAD

**Issue by hqho** [Azure/azure-sdk-for-cpp#4371]
**Query/Question**
I am not able to build the SDK on ARM64.  Is the SDK supported for ARM?

***Why is this not a Bug or a feature Request?***
Build failures on ARM.

tdbn-sles-1764:/home/jenkins/azure-sdk-for-cpp/build.release # cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/home/jenkins/local
No transport adapter was selected, using libcurl as the default option for POSIX.
Vcpkg integrate step.
-- Bootstrapping vcpkg before install
-- Bootstrapping vcpkg before install - failed
CMake Error at build.release/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:868 (message):
  vcpkg install failed.  See logs for more information:
  /home/jenkins/azure-sdk-for-cpp/build.release/vcpkg-bootstrap.log
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:26 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Setup (please complete the following information if applicable):**
 - OS: [SLES15SP4]
 - Version of the Library used: 12.5.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
```
CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

I think it's because `make` or `g++` is not installed in your environment.

**Comment by hqho** [comment]
I do have both installed

tdbn-sles-1764:~ # which make
/usr/bin/make
tdbn-sles-1764:~ # which g++
/usr/bin/g++

**Comment by nrgiii** [comment]
I have hit this same bug when attempting to build azure on Ubuntu 20 on aarch64. 
Are there plans to support azure on aarch64? A little guidance would be helpful.
```

/usr/bin/cmake  -DENABLE_TESTING:BOOL=OFF --log-level=DEBUG -DCMAKE_INSTALL_PREFIX:PATH=/hudson2/users/normg/gs370/slow52/azure/install52 -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -DCMAKE_PREFIX_PATH:PATH=/hudson2/users/normg/gs370/slow52/azure/install52 -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_CXX_FLAGS:STRING="-mabi=lp64 -fcommon -pipe -fPIC -D_REENTRANT -fno-strict-aliasing -pthread -g " -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_C_FLAGS:STRING="-mabi=lp64 -fcommon -pipe -fPIC -D_REENTRANT -fno-strict-aliasing -pthread -g" -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF -DOPENSSL_ROOT_DIR:PATH="/hudson2/users/normg/gs370/slow52/openssl/install52" -DOPENSSL_USE_STATIC_LIBS:BOOL=TRUE -DLibCrypto_LIBRARY:FILEPATH="/hudson2/users/normg/gs370/slow52/openssl/install52/lib/libcrypto.so" -DLibCrypto_INCLUDE_DIR:PATH="/hudson2/users/normg/gs370/slow52/openssl/install52/include" /hudson2/users/normg/gs370/externals/azure
No transport adapter was selected, using libcurl as the default option for POSIX.
Vcpkg integrate step.
CMAKE_TOOLCHAIN_FILE is not defined. Define it for the user.
AZURE_SDK_DISABLE_AUTO_VCPKG is not defined. Fetch a local copy of vcpkg.
Vcpkg commit string used: 94ce0dab56f4d8ba6bd631ba59ed682b02d45c46
-- Bootstrapping vcpkg before install
-- Bootstrapping vcpkg before install - failed
CMake Error at /hudson2/users/normg/gs370/slow52/azure/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:868 (message):
  vcpkg install failed.  See logs for more information:
  /hudson2/users/normg/gs370/slow52/azure/vcpkg-bootstrap.log
Call Stack (most recent call first):
  /usr/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:26 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
cmake failed


normg@hudson>cmake --version
cmake version 3.20.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by Jinming-Hu** [comment]
@microzchang can you take a look?

**Comment by nrgiii** [comment]
Thank you, I will give it a try.
