### ISSUE TITLE
ShareClient::GetStatistics fail with invalid map<K, T> key

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#4377]
```
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: application/xml
< Server: Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: c4c25aeb-701a-0052-0966-46250e000000
< x-ms-version: 2021-12-02
< Date: Wed, 22 Feb 2023 02:38:35 GMT
<
﻿<?xml version="1.0" encoding="utf-8"?><ShareStats><ShareUsageBytes>0</ShareUsageBytes></ShareStats>* Connection #0 to host premiumfileut.file.core.windows.net left intact
```

**Comment by Jinming-Hu** [comment]
https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-files-shares/src/rest_client.cpp#L1655-L1657

**Comment by microzchang** [comment]
Should we make them nullable or remove them? Both of these are breaking changes. But I think the first is less affected.

**Comment by Jinming-Hu** [comment]
> Should we make them nullable or remove them? Both of these are breaking changes. But I think the first is less affected.

Let's make them optional when parsing response, but keep the API interface unchanged. It's non-breaking this way.

You may refer to this link https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-blobs/swagger/README.md?plain=1#L541~L544 for how to do that.

**Comment by microzchang** [comment]
Yeah, I found the way to do this without breaking change yet. So I deleted the message.

**Comment by ahsonkhan** [comment]
> https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-files-shares/src/rest_client.cpp#L1655-L1657
> 
> REST API doesn't return ETag or Last-Modified at all.

@Jinming-Hu is that something we should fix in the code gen logic (or update the swagger)? Why does it generate code which expected ETag when the swagger doesn't?

**Comment by Jinming-Hu** [comment]
@ahsonkhan These headers are present on both public REST API reference and swagger. I tend to think it's a server-side bug.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/data-plane/Microsoft.FileStorage/preview/2022-11-02/file.json#L1777~L1785

https://learn.microsoft.com/en-us/rest/api/storageservices/get-share-stats#response-headers
