### ISSUE TITLE
CI: vcpkg verification PR should include all packages at all times, and unconditionally run daily

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#4422]
Note: I am talking about the verification PR and not the release process.

Issue 1: https://github.com/microsoft/vcpkg/pull/17119 has different packages depending on the time of day.
**It should push all packages at all times.**

Issue 2: It won't update the package if daily live test run fails.
**It should push packages regardless whether live test is failing or not.**
Live tests could be affected by timeouts, CI issues. Could be valid bugs.
But if the change was good enough for the CI that ran non-live tests, it is good for vcpkg validation as well.
It may discover useful issues that can be fixed independently of live test issues - for example, if sonething does not compile on ARM or UWP.
Also, given that we only update vcpkg PR once daily, we are missing the window to validate changes too often. We should be able to open that PR at any time and see whether all packages do build as of the last <=24 hours.

**Comment by danieljurek** [comment]
For Issue 1... Does this mean every merge to `main` updates the packages?

**Comment by antkmsft** [comment]
I was going to answer with a question if we could make it to run on a schedule, once or several times daily, but I actually like the idea of running every time we push to `main` - I hope it is not too often for the vcpkg's CI to handle. We don't seem to have that many daily commits, so I hope it is ok.

**Comment by danieljurek** [comment]
Resolved: Let's do 1x/day validation and then if we need more frequent, we can do that.
