### ISSUE TITLE
Possible concurrency issue in storage queues

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4436]
valgrind --tool=drd ./azure-storage-queues-test &> ~/queues_thread.txt

[queues_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946700/queues_thread.log)

**Comment by Jinming-Hu** [comment]
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435
