### ISSUE TITLE
Possible concurency issue in storage shares

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4437]
valgrind --tool=drd ./azure-storage-files-shares-test &> ~/shares_thread.txt

[shares_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946717/shares_thread.log)

Log incomplete , run died due to taking too long

**Comment by Jinming-Hu** [comment]
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435
