### ISSUE TITLE
Possible concurency issues in storage datalake

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4438]
valgrind --tool=drd ./azure-storage-files-datalake-test &> ~/datalake_thread.txt

[datalake_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946724/datalake_thread.log)

**Comment by Jinming-Hu** [comment]
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435
