### ISSUE TITLE
Possible concurrency issues in storage blobs

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4439]
valgrind --tool=dr^C./azure-storage-blobs-test &> ~/blobs_thread.txt

[blobs_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946731/blobs_thread.log)

**Comment by Jinming-Hu** [comment]
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435
