### ISSUE TITLE
Add support for 100-continue in Azure Core

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-cpp#4444]
https://github.com/Azure/azure-sdk/issues/5787

**Comment by Jinming-Hu** [comment]
We have two transports, libcurl and WinHTTP.

Libcurl already works in the way described in https://github.com/Azure/azure-sdk/issues/5787.
WinHTTP doesn't. I don't know if WinHTTP is able to do that.

**Comment by LarryOsterman** [comment]
Duplicate of #3501
