### ISSUE TITLE
HTTP Client CPU usage optimization

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#447]
single-thread upload/download throughput is fine. But consumes significantly more CPU than libcurl.

high cpu usage greatly impacts overall performance when downloading in high concurrency.

**Comment by vhvb1989** [comment]
I can see a high CPU usage when running without the fix from this issue: https://github.com/Azure/azure-sdk-for-cpp/issues/445

CPU Profiling without the fix #445 
Download:
![image](https://user-images.githubusercontent.com/24213737/90574942-12b9b000-e16f-11ea-996e-b21a8fccfcb3.png)


Upload:
![image](https://user-images.githubusercontent.com/24213737/90574762-99ba5880-e16e-11ea-9ca0-97a5e246f872.png)


CPU usage after the fix (current master):
Download:
![image](https://user-images.githubusercontent.com/24213737/90575048-5ca29600-e16f-11ea-986d-170fb942b798.png)


Upload:
![image](https://user-images.githubusercontent.com/24213737/90575016-4a285c80-e16f-11ea-843e-2e865f6904d8.png)

**Comment by vhvb1989** [comment]
@JinmingHu-MSFT  can we consider this one as fixed by #445  and close?

**Comment by JinmingHu-MSFT** [comment]
@vhvb1989 let me try it out first. i'll close this one if it works.

**Comment by JinmingHu-MSFT** [comment]
close it for now, will re-evaluate after HTTP connection keep-alive https://github.com/Azure/azure-sdk-for-cpp/issues/446 is available.
