### ISSUE TITLE
Enable proactive renewal of Managed Identity tokens

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-cpp#4474]
**Intro:**
Refreshing the tokens with half lifetime would improve resiliency for clients if there's an ESTS outage while fetching a token. 

**Acceptance Criteria:**
All MSI tokens are refreshed at least half lifetime token request is made after half lifetime

MSI has token lifetime of 24 hours. Refresh the tokens if `refresh_in` is passed from ESTS or at half lifetime if `refresh_in` isn't passed. For tokens which have lifetime of less than 2 hours, there are no changes to be made.

**Comment by joshfree** [comment]
This item is actionable for C++.  @billwert could you please share the PR from Java?

**Comment by billwert** [comment]
the first part: https://github.com/Azure/azure-sdk-for-java/pull/33766

the bug fix I had to make :) https://github.com/Azure/azure-sdk-for-java/pull/33970

**Comment by antkmsft** [comment]
// NOTE: To person who might be fixing this, look at `TokenRequestContext::MinimumExpiration` maybe utilizing it would help.

**Comment by antkmsft** [comment]
Or, maybe in GetToken(), simply cut the expiration in half when it is >24 hours, see the other SDKs for inspiration.
