### ISSUE TITLE
cpp github-event-processor repository setup and enablement

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-cpp#4479]
Repository specific issue to track setup for AZ CLI and enablement of github-event-processor

Parent issue: https://github.com/Azure/azure-sdk-tools/issues/5789

**Comment by RickWinter** [comment]
@JimSuplizio What does the github-event-processor do?

**Comment by JimSuplizio** [comment]
> @JimSuplizio What does the github-event-processor do?

@RickWinter it's the FabricBot replacement we're going to be rolling out that uses GitHub Actions.
