### ISSUE TITLE
Implement Queued Send in MessageSender API.

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-for-cpp#4510]
There are two models for send supported in uAMQP: Synchronous and asynchronous.

Asynchronous sends are queued locally before being transmitted to the sender, synchronous sends are sent and block until the client has received a disposition frame for the send.

The amount of time required to wait for the disposition response may be significant and thus a reliable asynchronous send mechanism is needed to handle this case.

**Comment by antkmsft** [comment]
We probably have this implemented as of today?

**Comment by LarryOsterman** [comment]
FWIW, we don't. But it's also not needed because EventHubs queues internally.
