### ISSUE TITLE
Add unit test for zero chunk size response

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#452]
it requires mock or finding some server to return a zero chunk data.
I tested it based on the issue reported with a premium storage account.
I will create a new issue to do not forget about adding unit tests for this once we have a way to mock network responses

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/451/review_comment/create_

**Comment by JinmingHu-MSFT** [comment]
well, I guess we don't need to add test if it involves too much effort. Target testing should be enough.

**Comment by vhvb1989** [comment]
blocked for now until we have test live/record framework.
Moving this to backlog

**Comment by vhvb1989** [comment]
fixed by https://github.com/Azure/azure-sdk-for-cpp/pull/881
