### ISSUE TITLE
Add `DefaultAzureCredentialOptions` with `AdditionallyAllowedTenants` and `AuthorityHost`.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#4565]
This came up during identity architect review.

**Comment by RickWinter** [comment]
Does this make sense since we don't allow configuration of DefaultAzureCredential?  Its a slippery slop if we start allowing customizations of the DefaultAzureCredential behavior.

**Comment by ahsonkhan** [comment]
`DefaultAzureCredential` will not have behavioral customizations or options in C++. This is a by-design choice. Customizations are possible in `ChainedTokenCredential` or if you use the specific credential explicitly.
