### ISSUE TITLE
sdk/core/azure-core/src/http/curl/curl.cpp compile error

### ISSUE THREAD

**Issue by bzhou-sw** [Azure/azure-sdk-for-cpp#4598]
**Query/Question**
Tried to build with latest SDK (head https://github.com/Azure/azure-sdk-for-cpp/commit/2cce17d6910a9f34376fcaa88d78710566d91eae) but compilation failed:

```
/opt/project/sdk/core/azure-core/src/http/curl/curl.cpp: In constructor 'Azure::Core::Http::CurlConnection::CurlConnection(Azure::Core::Http::Request&, const Azure::Core::Http::CurlTransportOptions&, const string&, const string&)':
/opt/project/sdk/core/azure-core/src/http/curl/curl.cpp:2312:5: error: 'curl_blob' was not declared in this scope
 2312 |     curl_blob rootCertBlob
      |     ^~~~~~~~~
/opt/project/sdk/core/azure-core/src/http/curl/curl.cpp:2317:37: error: 'CURLOPT_CAINFO_BLOB' was not declared in this scope; did you mean 'CURLOPT_CAINFO'?
 2317 |     if (!SetLibcurlOption(m_handle, CURLOPT_CAINFO_BLOB, &rootCertBlob, &result))
      |                                     ^~~~~~~~~~~~~~~~~~~
      |                                     CURLOPT_CAINFO
/opt/project/sdk/core/azure-core/src/http/curl/curl.cpp:2317:59: error: 'rootCertBlob' was not declared in this scope
 2317 |     if (!SetLibcurlOption(m_handle, CURLOPT_CAINFO_BLOB, &rootCertBlob, &result))
      |                                                           ^~~~~~~~~~~~
make[2]: *** [sdk/core/azure-core/CMakeFiles/azure-core.dir/build.make:63: sdk/core/azure-core/CMakeFiles/azure-core.dir/src/http/curl/curl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:298: sdk/core/azure-core/CMakeFiles/azure-core.dir/all] Error 2
```

***Why is this not a Bug or a feature Request?***
First want to check if I missed some build env changes.

**Setup (please complete the following information if applicable):**
 - OS: `ubuntu:focal-20230412`
 - IDE : Linux cmake
 - Version of the Library used: libcurl is `libcurl4-openssl-dev:amd64 7.68.0-1ubuntu2.18`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by LarryOsterman** [comment]
The Azure SDK for C++ has an undeclared dependency on CURL 7.77, which was released in May 2021 (our vcpkg baseline is from 2022 so we didn't notice that we had taken a dependency on version 7.77).

Do you have the ability to move to a more recent version of CURL? The version you're targeting is from Jan 2020 and there are several security vulnerabilities that have been fixed since then (including at least one marked High).

**Comment by bzhou-sw** [comment]
Thanks for the info. So there is no way to use latest SDK with 7.68?  We are using Ubuntu 20.04 and latest libcurl distribution for that is 7.68. 
If no solution on your side, then we will seek other solutions like compile from more recent libcurl source.

**Comment by ahsonkhan** [comment]
@bzhou-sw how do you acquire the `azure-sdk-for-cpp` libraries? Do you use vcpkg to install this SDK as part of your application? Or do you use some other approach?

**Comment by bzhou-sw** [comment]
We don't use vcpkg. We clone the git repo and only build modules we need as `.so` inside container.
We will move our dev env from Ubuntu 20.04 to 22.04, and libcurl issue should be solved since 22.04 has `libcurl 7.81`, that will work for the SDK, right?

**Comment by bzhou-sw** [comment]
Build SDK with ubuntu 22.04 successfully.

**Comment by RickWinter** [comment]
We are tracking the 7.77 dependency work in #4792
