### ISSUE TITLE
Track Pr comments

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4609]
- [x] #1 https://github.com/Azure/azure-sdk-for-cpp/pull/4596/files#r1184438940 
- [x] #2 https://github.com/Azure/azure-sdk-for-cpp/pull/4596/files#r1184441345
- [x] #3 https://github.com/Azure/azure-sdk-for-cpp/pull/4596/files#r1184442480
- [x] #4 https://github.com/Azure/azure-sdk-for-cpp/pull/4596/files#r1184477429
- [x] #5 https://github.com/Azure/azure-sdk-for-cpp/pull/4596/files#r1184444207
- [x] #6 https://github.com/Azure/azure-sdk-for-cpp/pull/4596#discussion_r1185431843

**Comment by ahsonkhan** [comment]
FWIW, it is difficult to link to a comment under the "files changed" view of a large PR. Try clicking it and see where it takes you (if it even takes you to the right place). I had better luck from the conversations tab.

For example, a link like this, under "conversation" works better (even if the comment was resolved):
https://github.com/Azure/azure-sdk-for-cpp/pull/4596#discussion_r1184477429

**Comment by gearama** [comment]
all issues closed
