### ISSUE TITLE
Implementation of parallel upload/download functions

### ISSUE THREAD

**Issue by youennL-cs** [Azure/azure-sdk-for-cpp#4623]
**Is your feature request related to a problem? Please describe.**
We would like to upload blocks in parallel in a blob storage and I'm frustrated to not having the `CommitBlockListAsync` function implemented while it is already available in `azure-sdk-for-net`, for example. 
We also need a function to download in parallel.

**Describe the solution you'd like**
The implementation for parallel upload/download in a blob storage.

**Describe alternatives you've considered**
We don't see another alternative.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Jinming-Hu** [comment]
@youennL-cs 

We have concurrent upload and download in blob SDK.

for example, with [BlobClinet::DownloadTo](https://github.com/Azure/azure-sdk-for-cpp/blob/d693099d44c4f965cde6ff06d6f3cd0358ef01a8/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp#L277), you can download a blob to a file or memory buffer with multiple threads, the concurrency is configurable with `DownloadBlobToOptions`.

**Comment by youennL-cs** [comment]
I saw this function but can I consider Async as [DownloadToFileParallelAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblob.downloadtofileparallelasync?view=azure-dotnet) available for .NET ? 
And I can't see anything for upload/commit.

The current `CommitBlockList` (which is not Async) as no concurrency parameter in the option (`CommitBlockListOptions`) and so it doesn't look like having a way to parallelise the commit.

**Comment by Jinming-Hu** [comment]
C++ SDK doesn't support async functions. You can call sync methods from multiple threads to accomplish parallelism.
