### ISSUE TITLE
Does this SDK support ADL Gen1?

### ISSUE THREAD

**Issue by jiafanou** [Azure/azure-sdk-for-cpp#4631]
**Query/Question**
It seems cpp SDK is quite different than dotnet version. Does it support ADL Gen1?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Linux/Windows
 - IDE : [e.g. IntelliJ] 
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
No. Currently we support blob SDK and Datalake Gen2.
