### ISSUE TITLE
Client-side timeout for BlockBlobClient's method (e.g. Upload)

### ISSUE THREAD

**Issue by phoebusm** [Azure/azure-sdk-for-cpp#4641]
**Is your feature request related to a problem? Please describe.**
This is to give a faster response if there is any error in connecting to the data center. Usually the connection can be made very shortly. The default timeout is more than enough. 

**Describe the solution you'd like**
A customizable timeout option added in BlobClientOptions or ClientOptions. 

**Describe alternatives you've considered**
Switching to a third-party thin client. This will greatly increase the implementation cost for connecting to Azure.

**Additional context**
-

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by microzchang** [comment]
Hi,[phoebusm](https://github.com/phoebusm).
There is actually a timeout option you can use in `Azure::Core::Context`, the following is an example:
```C++
Azure::Storage::Blobs::BlobClient blobClient = Azure::Storage::Blobs::BlobClient::CreateFromConnectionString("<connection_string>", "container_name", "blob_name"); // create client through connection string
try
{
    Azure::Core::Context requestContext;
    requestContext = requestContext.WithDeadline(std::chrono::system_clock::now() + std::chrono::milliseconds(60000L));
    Azure::Storage::Blobs::ListBlobsOptions requestOptions;
    {
      //... Set download options.
    }
    auto result = blobClient .Download(requestOptions, requestContext);
}
catch (Azure::Core::OperationCancelledException& ex)
{
    // If timeout, will through OperationCancelledException.
    // Handle OperationCancelledException;
}

```

**Comment by phoebusm** [comment]
Thank you for the quick reply and example. Will try it out.
