### ISSUE TITLE
Potential memory corruption in shutdown due to multiple call curl_easy_cleanup()

### ISSUE THREAD

**Issue by adamhan-hitachi** [Azure/azure-sdk-for-cpp#4643]
**Query/Question**
In Curl transport layer, is it possible to have multiple instances of CurlConnection? 

The reason to ask is that I captured back trace for memory corruption during application shutdown as attached. The stack shows that was corrupted in curl_easy_cleanup(), which is called by CurlConnection's destructor. Hence, it could explain that if there are multiple CurlConnection instances in CurlConnectionPool. 

Otherwise, I need to explore other reason. 

***Why is this not a Bug or a feature Request?***
It may be a bug. But I haven't reproduce it in unit test. It would be easies to check from design perspective. 

**Setup (please complete the following information if applicable):**
 - OS: Debian 11
 - IDE : Self build by Bazel / CMake
 - Version of the Library used: https://github.com/Azure/azure-sdk-for-cpp/releases/tag/azure-security-attestation_1.1.0
 - libcurl/7.88.1 OpenSSL/1.1.1n 
 -
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

![image](https://github.com/Azure/azure-sdk-for-cpp/assets/120096360/f8a280b8-e91b-498b-883b-c4bb4106e1b4)

**Comment by kysucix** [comment]
Could you try is this pr is fixing your memory leak? https://github.com/ClickHouse/azure-sdk-for-cpp/pull/7

**Comment by adamhan-hitachi** [comment]
> Could you try is this pr is fixing your memory leak? [ClickHouse#7](https://github.com/ClickHouse/azure-sdk-for-cpp/pull/7)

Thanks for the suggestion. I checked my version, it seems already changed to use unique pointer to manage Curl handle, as shown in the code snippet below - 
   m_handle = Azure::Core::_internal::UniqueHandle<CURL>(curl_easy_init());

In my version,  to release unique pointer above will call curl_easy_cleanup() as shown in following snippet - 
    template <> struct UniqueHandleHelper<CURL>
    {
      using type = BasicUniqueHandle<CURL, curl_easy_cleanup>;
    }

But it won't call curl_easy_cleanup() in your changes. I can't easily merge your changes. 

Could I ask if you think it would be a problem to call curl_easy_cleanup() in this way (multiple times I guess)?

**Comment by kysucix** [comment]
I think in the pr I mentioned it's different. The `unique_ptr` is created passing `curl_easy_cleanup()` as a `Deleter.`
