### ISSUE TITLE
Is vcpkg required for building Azure SDK?

### ISSUE THREAD

**Issue by GuanLuo** [Azure/azure-sdk-for-cpp#4649]
**Query/Question**
We are moving from `azure-storage-cpplite` to `azure-sdk-for-cpp` as the prior is marked as deprecating. After experimenting around the build instruction, it appears that `vcpkg` is implicitly used to install other dependencies (including Azure SDK with CMake `ExternalProject_Add`). As I noticed that `vcpkg` will pull dependencies that already used in other part of my project, is it possible to compile the Azure SDK in pure CMake, in this way, I can make sure the same depending libraries are used without looking further into how to integrate with `vcpkg`?

***Why is this not a Bug or a feature Request?***
This is general question regarding the build system.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 20.04
 - IDE : N/A
 - Version of the Library used: azure-storage-blobs_12.7.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Jinming-Hu** [comment]
Hi @RickWinter , although the customer is trying to build storage sdk, but I assume this could be a more general question: can C++ SDK be added as a CMake dependency and built without vcpkg?

I was checking our code base and I found `AZURE_SDK_DISABLE_AUTO_VCPKG` and `FETCH_SOURCE_DEPS` macros, so I assume the answer could be yes.

I created a CMake project for testing with below content as `CMakeLists.txt` and built with command `AZURE_SDK_DISABLE_AUTO_VCPKG=ON cmake -DFETCH_SOURCE_DEPS=ON -B build`

```CMake
cmake_minimum_required(VERSION 3.11)
set(CMAKE_CXX_STANDARD 14)

project(azure-storage-test-proj)

find_package(Git REQUIRED)
include(FetchContent)

FetchContent_Declare(
  azure-storage-blobs
  GIT_REPOSITORY https://github.com/Azure/azure-sdk-for-cpp.git
  GIT_TAG azure-storage-blobs_12.7.0)

FetchContent_GetProperties(azure-storage-blobs)
if(NOT azure-storage-blobs_POPULATED)
  FetchContent_Populate(azure-storage-blobs)
  add_subdirectory(
    ${azure-storage-blobs_SOURCE_DIR}/sdk/storage/azure-storage-blobs
    ${azure-storage-blobs_BINARY_DIR})
endif()

add_executable(az-test src/test.cc)

if(WIN32)
  target_compile_definitions(az-test PRIVATE NOMINMAX)
endif()

if(MSVC)
  target_compile_options(az-test PUBLIC /W4 /WX /MP)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL
                                                "GNU")
  target_compile_options(az-test PUBLIC -Wall -Wextra -Werror -pedantic)
  target_compile_options(az-test PRIVATE -O3)
endif()

find_package(azure-storage-blobs-cpp CONFIG REQUIRED)
target_link_libraries(
  az-test
  Azure::azure-storage-blobs)
```

it failed with below error message

```
Vcpkg integrate step.
CMAKE_TOOLCHAIN_FILE is not defined. Define it for the user.
No transport adapter was selected, using libcurl as the default option for POSIX.
setting up compile options for STORAGE_BLOBS
project found STORAGE_BLOBS
FLAG VALUE : ON
Downloading version 1.8.0 of azure-core
Downloading version 12.3.1 of azure-storage-common
add folder build/sdk/core
CMake Error at build/_deps/azure-storage-blobs-src/sdk/storage/azure-storage-blobs/CMakeLists.txt:32 (add_subdirectory):
  add_subdirectory given source "build/sdk/core" which is not an existing
  directory.


add folder build/sdk/storage/azure-storage-common
CMake Error at build/_deps/azure-storage-blobs-src/sdk/storage/azure-storage-blobs/CMakeLists.txt:32 (add_subdirectory):
  add_subdirectory given source "build/sdk/storage/azure-storage-common"
  which is not an existing directory.


-- Retrieving version from /home/jamis/test/build/_deps/azure-storage-blobs-src/sdk/storage/azure-storage-blobs/src/private/package_version.hpp
-- VERSION_MAJOR 12
-- VERSION_MINOR 7
-- VERSION_PATCH 0
-- VERSION_PRERELEASE 
-- AZ_LIBRARY_VERSION 
CMake Error at /usr/local/share/cmake-3.26/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
  By not providing "Findazure-storage-common-cpp.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "azure-storage-common-cpp", but CMake did not find one.

  Could not find a package configuration file provided by
  "azure-storage-common-cpp" (requested version 12.3.1) with any of the
  following names:

    azure-storage-common-cppConfig.cmake
    azure-storage-common-cpp-config.cmake

  Add the installation prefix of "azure-storage-common-cpp" to
  CMAKE_PREFIX_PATH or set "azure-storage-common-cpp_DIR" to a directory
  containing one of the above files.  If "azure-storage-common-cpp" provides
  a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  build/_deps/azure-storage-blobs-build/azure-storage-blobs-cppConfig.cmake:31 (find_dependency)
  CMakeLists.txt:36 (find_package)


-- Configuring incomplete, errors occurred!
````

I couldn't figure out the problem, can your team take a look?


cc @LarryOsterman @gearama @antkmsft @ahsonkhan

**Comment by LarryOsterman** [comment]
As of today, vcpkg is required for installing the Azure SDK (more accurately: the only scenarios the team tests require the use of vcpkg).

I have a commitment for the next milestone to investigate alternate acquisition mechanisms, including using FetchContent from github directly.

**Comment by Jinming-Hu** [comment]
@LarryOsterman Thanks for your response. I take it to mean that installing without vcpkg is not supported as of now.

**Comment by RickWinter** [comment]
> @LarryOsterman Thanks for your response. I take it to mean that installing without vcpkg is not supported as of now.

Correct, It can be made to work with customizations by the user.  We do NOT support it out of the box at this time.  We are looking into it and may add support in the future.
