### ISSUE TITLE
Azure::Core::Operation<T>::GetRawResponseInternal() is never used

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#4662]
This is a pure virtual method. Every derived class needs to implement it, from what I can see, all derived classes have the same implementation with only 1-line code `return *m_rawResponse;`. But this method is not used anywhere, can we just delete it?

I found this problem when working on improving storage test coverage, this line of code can never be reached.

![image](https://github.com/Azure/azure-sdk-for-cpp/assets/52266153/e4358367-6d6a-4801-9396-e3ffb867e8c6)

**Comment by antkmsft** [comment]
See also #4749
