### ISSUE TITLE
listBlobs() not listing all blobs in container

### ISSUE THREAD

**Issue by JonKirkland** [Azure/azure-sdk-for-cpp#4677]
**Describe the bug**
Hello, I've found that using listBlobs() is not listing blobs that are in virtual directories, it was working a few days ago so I don't know what happened. I have used vcpkg to install the latest x64 sdk.

**To Reproduce**
Try using listBlobs() in a container. Example in code snippet below. 

***Code Snippet***
    
```
BlobContainerClient containerClient = BlobContainerClient::CreateFromConnectionString(connectionString, containerName);
std::cout << "Listing blobs...\n";
auto listBlobsResponse = containerClient.ListBlobs();
for (auto blobItem : listBlobsResponse.Blobs) {
    std::cout<<blobItem.Name<<std::endl;
}    

```
**Expected behavior**
I expected all blobs within the container to be listed, even the ones within virtual directories. Instead, only the blobs not in virtual containers are listed. 
For example, the blob contains 2 files: test.txt, folder/test2.txt.
Only test.txt would be listed, I would expect both to be listed.

**Setup (please complete the following information):**
 - OS: Windows 11 Pro, Version: 10.0.22621, Build 22621
 - IDE : Visual Studio 2022 Community Edition
 - Version of the Library used: azure-core-cpp:x64-windows 1.8.1 Microsoft Azure Core SDK for C++

**Additional context**
It is really strange that this was working a couple days ago, projects I haven't touched suddenly are not functioning properly, without me even updating the SDK. I also tried using ListBlobsByHierarchy() with "/" as a delimiter, but still same problem.

**Comment by Jinming-Hu** [comment]
Hi @JonKirkland this sample shows the correct usage of list operation.

https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-blobs/samples/blob_list_operation.cpp#L62-L71

**Comment by JonKirkland** [comment]
Thanks a lot.
