### ISSUE TITLE
Azure Pipeline Validation failed with "The signing feature is not available for your organization yet." at step "Generate BOM"

### ISSUE THREAD

**Issue by microzchang** [Azure/azure-sdk-for-cpp#4680]
**Describe the bug**
Pipeline Validation failed with "The signing feature is not available for your organization yet." at step "Generate BOM".
I have retried for several times and get the same failure.

***Exception or Stack Trace***
You can get the detail failure in this PR: https://github.com/Azure/azure-sdk-for-cpp/pull/4664
And the failed pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2815063&view=logs&jobId=7c6ba154-1dd3-507d-6d24-8db90b0372c9&j=7c6ba154-1dd3-507d-6d24-8db90b0372c9&t=01245f84-53cd-51f5-7f46-ca8f9eb2dd03

![image](https://github.com/Azure/azure-sdk-for-cpp/assets/110015819/0c54c570-05bf-4308-b474-a9bf892706d7)

**Comment by microzchang** [comment]
@RickWinter @danieljurek  I'm not sure if azure-core or  engsys team should be assigned this issue.

**Comment by LarryOsterman** [comment]
Assigning to @danieljurek, but I suspect that this may end up somewhere in 1ES.

**Comment by danieljurek** [comment]
From a chat in the EngSys channel, it looks like SBOM is not interesting for PRs. To that end, I think we can exclude SBOM work during PRs.
