### ISSUE TITLE
Reconsider the discouragement of `DefaultAzureCredential` in production.

### ISSUE THREAD

**Issue by teo-tsirpanis** [Azure/azure-sdk-for-cpp#4682]
**Is your feature request related to a problem? Please describe.**

https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-identity/1.5.0/index.html says that "`DefaultAzureCredential` is […] not recommended to use in production".

This comes in contrast with the [.NET SDK's documentation](https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication?tabs=command-line#defaultazurecredential) which says that "[t]he use of `DefaultAzureCredential` should be preferred over manually coding conditional logic or feature flags to use different authentication methods in different environments".

Which of the two is wrong? I hope we are.

**Describe the solution you'd like**
I would like the documentation of `DefaultAzureCredential` to be amended to stop mentioning that the class is not recommended to use in production, and the following lines to be removed from its constructor:

https://github.com/Azure/azure-sdk-for-cpp/blob/72cdbaa0fed2ba847607a0a5f372d70f83c41f2d/sdk/identity/azure-identity/src/default_azure_credential.cpp#L25-L36

**Describe alternatives you've considered**

* Use `DefaultAzureCredential` nevertheless.
* Manually create a `CainedTokenCredential`.

**Additional context**

[Other cloud platforms like Google Cloud openly embrace automatic authentication schemes.](https://cloud.google.com/docs/authentication/application-default-credentials)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by RickWinter** [comment]
The C++ SDK has an evolved approach to the `DefaultAzureCredential`.  The C++ SDK recommends only enabling in production those credentials which your application knows it will use.  Thus our recommendation of using specific authentication or a ChainedTokenCredential with the specific credentials you intend to support.
