### ISSUE TITLE
KeyVaultSecret type is missing doxygen docs in comments

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4691]
https://github.com/Azure/azure-sdk-for-cpp/blob/e05c92c48463d43a41dc433c31d4061817b20aa7/sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_secret.hpp#L13

See the docs:
https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-security-keyvault-secrets/4.2.0/annotated.html

![image](https://github.com/Azure/azure-sdk-for-cpp/assets/6527137/f38015f0-4bdf-4dee-8c7a-8cd1f6c8da24)

cc @ronniegeraghty

**Comment by gearama** [comment]
is there is 4.2.1


![Image](https://github.com/Azure/azure-sdk-for-cpp/assets/50641385/a6323536-bc4c-4797-951e-85493f30101a)

**Comment by ahsonkhan** [comment]
Yep, it was fixed here: https://github.com/Azure/azure-sdk-for-cpp/pull/4715#discussion_r1532936390
