### ISSUE TITLE
Support falling back to anonymous authentication in token credentials.

### ISSUE THREAD

**Issue by teo-tsirpanis** [Azure/azure-sdk-for-cpp#4705]
Support falling back to anonymous authentication if all components of a chained token credential fail.

**Is your feature request related to a problem? Please describe.**
I'm working on a library that supports connecting to Azure Blob Storage. We currently support authentication using Shared Keys and SAS Tokens, and want to add support for Active Directory authentication.

To make it as frictionless as possible and guide users to the most secure authentication option, I am thinking of making it opt to AD authentication (through `DefaultAzureCredential`, see also #4682) by default, if the user is connected to an HTTPS endpoint and has not configured a shared key or a SAS token.

However, if the user is not authenticated, [the SDK would throw that it failed to get a token](https://github.com/Azure/azure-sdk-for-cpp/blob/0516518265c7606477fa5e54c2cdc117efcc4a89/sdk/identity/azure-identity/src/chained_token_credential.cpp#L99), preventing connecting to Azure anonymously, in the rare case the user wants to.

**Describe the solution you'd like**
What I propose to do is to change the implementation of `BearerTokenAuthenticationPolicy` to skip setting the authorization header if the `AccessToken::Token` string is empty.

Then on my code I will create an `AnonymousCredential` class that will always return an empty string and be valid forever (to prevent trying again), and chain it after `DefaultAzureCredential`.

**Describe alternatives you've considered**
My first thought is to add a `bool` parameter to `DefaultAzureCredential` and `ChainedTokenCredential`

The other option I will do for now but would prefer not to in the long term, is to just add a config option in my library to disable AD authentication.

**Additional context**
If approved, I have a branch ready and can open a PR.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by RickWinter** [comment]
The `DefaultAzureCredential` is an ease of use getting started credential which we recommend not using in production.  We do not plan to add any customizations to control turning off the credentials within its flow.  If you want that level of control then the credential you'll want to use is the `ChainedTokenCredential`.

**Comment by teo-tsirpanis** [comment]
Thanks for the quick response @RickWinter. Maybe I was not clear enough. My question is how to say from a `TokenCredential` "you know what, I changed my mind, I don't want an `Authorize` header to the request". The existing code sets the header always:

https://github.com/Azure/azure-sdk-for-cpp/blob/c45dff4c9ff6b38b5d7fe471de1cae35e4ab9a7a/sdk/core/azure-core/src/http/bearer_token_authentication_policy.cpp#L80

And I propose to change it to this:

```cpp
  if (!m_accessToken.Token.empty())
  {
    request.SetHeader("authorization", "Bearer " + m_accessToken.Token);
  }
```

**Comment by RickWinter** [comment]
Storage strongly advises against public access to blobs unless the scenario must have it.  See this article, https://learn.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-overview

Changing BearerTokenTypes to accept anonymous values goes against what the BearerTokenTypes are for.  BearerToken auth is for services that require authentication; the token is proof of identity.  

I'd recommend connecting with auth by default and having clients opt-into anonymous if you must support that.  In you code you can handle the auth exception which you expect and fall back to anonymous.  Although this pattern will work, I'd encourage you to explore using authenticated access which is more secure (see above documentation).

**Comment by teo-tsirpanis** [comment]
Thanks. I understand changing the semantics of `AccessToken` for such use case is not an option. But I found another way to implement the fallback:

```cpp
try {
  auto credential = make_shared<::Azure::Identity::ChainedTokenCredential>(
    std::vector<
      std::shared_ptr<::Azure::Core::Credentials::TokenCredential>>{
      std::make_shared<::Azure::Identity::EnvironmentCredential>(),
      std::make_shared<::Azure::Identity::AzureCliCredential>(),
      std::make_shared<::Azure::Identity::ManagedIdentityCredential>()});

  // If a token is not available we wouldn't know it until we make a request
  // and it would be too late. Try getting a token, and if it fails fall
  // back to anonymous authentication.
  ::Azure::Core::Credentials::TokenRequestContext tokenContext;
  tokenContext.Scopes.emplace_back("https://storage.azure.com/.default");
  std::ignore = credential->GetToken(tokenContext, {});
  client_ =
    std::make_unique<::Azure::Storage::Blobs::BlobServiceClient>(
      blob_endpoint,
      credential,
      options);
  return;
} catch (...) {
  LOG_INFO(
      "Failed to get Azure AD token, falling back to anonymous authentication");
}
}
client_ = std::make_unique<::Azure::Storage::Blobs::BlobServiceClient>(blob_endpoint, options);
```

/resolve
