### ISSUE TITLE
[Storage File Service] Get File Ranges Diff

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#471]

**Comment by vikasjio** [comment]
Does this package supports Bytes Range Download?
If not, any roadmap for support?

**Comment by JinmingHu-MSFT** [comment]
@vikasjio Yes, we support downloading to [stream](https://github.com/Azure/azure-sdk-for-cpp/blob/67abbb37281504782090b3c6b23cb81867ac9507/sdk/storage/inc/blobs/blob_client.hpp#L233), [buffer](https://github.com/Azure/azure-sdk-for-cpp/blob/67abbb37281504782090b3c6b23cb81867ac9507/sdk/storage/inc/blobs/blob_client.hpp#L246) and [file](https://github.com/Azure/azure-sdk-for-cpp/blob/67abbb37281504782090b3c6b23cb81867ac9507/sdk/storage/inc/blobs/blob_client.hpp#L259). All of these functions accept an `options` as parameter, where you can provide an offset and length to specify the range you want to download.
