### ISSUE TITLE
[Storage File Service] Jumbo Files Test

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#472]

**Comment by vikasjio** [comment]
What is the largest file size currently supported for Download via this package?

**Comment by JinmingHu-MSFT** [comment]
@vikasjio We support nearly 200TB(209,715,200,000,000 bytes) blob, which is the maximum size supported by storage server.

**Comment by JinmingHu-MSFT** [comment]
@vikasjio File support is not finished yet, but we certainly support whatever size storage server supports.

**Comment by vikasjio** [comment]
Thanks for quick clarifications.

**Comment by katmsft** [comment]
Mostly validation works left.

**Comment by katmsft** [comment]
Need to validate. Functionality is ready.

**Comment by Jinming-Hu** [comment]
close in favor of https://github.com/Azure/azure-sdk-for-cpp/issues/3592
