### ISSUE TITLE
[Storage DataLake Service] Concurrent Append

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#473]

**Comment by katmsft** [comment]
Not in .NET: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs

**Comment by Jinming-Hu** [comment]
close in favor of https://github.com/Azure/azure-sdk-for-cpp/issues/3566
