### ISSUE TITLE
Unable to manually trigger pipelines for other packages in PRs using `/azp run`

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4779]
We can't manually trigger CI pipelines for other packages in a PR.

For example, I wanted to run the keyvault legs using `/azp run cpp - keyvault` in this PR and I got the following response:
https://github.com/Azure/azure-sdk-for-cpp/pull/4778#issuecomment-1629879165

> No commit pushedDate could be found for PR 4778 in repo Azure/azure-sdk-for-cpp

This is similar to what happened here: https://github.com/Azure/azure-sdk-for-cpp/pull/4772#issuecomment-1629628218
cc @antkmsft

**Comment by MaceWindu** [comment]
`pushedDate` was removed from Github API https://docs.github.com/en/graphql/overview/breaking-changes#changes-scheduled-for-2023-07-01, so azp bot authors should update its code..

**Comment by danieljurek** [comment]
Workaround while this is being fixed: Navigate to the pipeline you wish to run in Azure DevOps, run it manually, for the `Branch` field set `refs/pull/<pr#>/merge` 

In `internal` pipelines (e.g. those that don't have `- ci` at the end like `cpp - storage`) set the variable `Skip.AllRelease` to `true` to avoid being prompted to do a release.

**Comment by danieljurek** [comment]
This issue should be mitigated on the service side. It's possible you may see the error message again even though the build started successfully.
