### ISSUE TITLE
Missing screenshots of IDEs in the root readme doc should be fixed

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4790]
I believe the intent initially by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/3614 was to add images for the IDEs to showcase as examples, but they are missing/were never added. We should add them or restructure the doc to remove them.

We see placeholders today, like:
> -IMAGE HERE Visual Studio-

https://github.com/Azure/azure-sdk-for-cpp#cmake-project--vcpkg---manifest-mode

cc @ronniegeraghty

**Comment by RickWinter** [comment]
No longer relevant to the current document

**Comment by ahsonkhan** [comment]
Agreed, this issue no longer applies after the doc changes made by @ronniegeraghty in https://github.com/Azure/azure-sdk-for-cpp/pull/5339
