### ISSUE TITLE
Minimum required curl version should be updated.

### ISSUE THREAD

**Issue by teo-tsirpanis** [Azure/azure-sdk-for-cpp#4792]
We specify the minimum supported version of curl as 7.44 in https://github.com/Azure/azure-sdk-for-cpp/blob/6c616bd518b9842eed03c7aeac01efd08c404137/sdk/core/azure-core/CMakeLists.txt#L31 but in https://github.com/Azure/azure-sdk-for-cpp/blob/6c616bd518b9842eed03c7aeac01efd08c404137/sdk/core/azure-core/src/http/curl/curl.cpp#L2318 we use `CURLOPT_CAINFO_BLOB` [which is not available until 7.77](https://curl.se/libcurl/c/CURLOPT_CAINFO_BLOB.html).

The minimum version should be updated and tests should use it.

**Comment by RickWinter** [comment]
Thanks for pointing this out.  We will investigate.

//cc: @LarryOsterman
