### ISSUE TITLE
EventHubs has a different paradigm for creating and sending EventDataBatch

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-cpp#4868]
There are some interesting bits about EventDataBatch that are different in C++ vs other languages:

* EventDataBatch gets it's initial size from the producer link, which is why other languages force creation from the ProducerClient. This also means the link has to be initialized when you create the batch. 
* Part of EventDataBatch is that it checks the size of the messages as they are added via TryAdd(). This makes it so the customer can choose when to send the batch. We typically don't throw an exception for this (most of them use a `Try` style where it'll return a true/false). This might be different in Python (@l0lawrence can answer on this).
* SendEventDataBatch() returns a bool. I'm not entirely sure what is intended there, but I would probably expect a void, and a thrown exception if it fails.

**Comment by l0lawrence** [comment]
In python it looks like we will raise a value error when we hit the max batch size limit

**Comment by LarryOsterman** [comment]
IIRC, in Python, exceptions aren't considered ... exceptional, which is different from most other languages.

I think I'm leaning towards going with TryAdd. Also changing SendBatchData to just Send (and then potentially adding an immediate send option for a single message).

**Comment by richardpark-msft** [comment]
> I think I'm leaning towards going with TryAdd. Also changing SendBatchData to just Send (and then potentially adding an immediate send option for a single message).

In JS they let you send two types of data - an array of events or an event data batch. The array version basically creates the batch for you, and if it doesn't fit in a single batch it throws (ie, no partial send or leftovers allowed). CC: @deyaaeldeen if I'm wrong.

Maybe that's a useful model for C++ as well? 

```typescript
sendBatch(batch: EventData[] | AmqpAnnotatedMessage[], options?: SendBatchOptions): Promise<void>;
sendBatch(batch: EventDataBatch, options?: OperationOptions): Promise<void>;
```

**Comment by LarryOsterman** [comment]
Jesse had already suggested a similar paradigm.

That's part of why I renamed `SendEventDataBatch` to `Send` - that way in the future, we can add overloads for string, vector of uint8 and vector of vector of uint8.

**Comment by richardpark-msft** [comment]
> vector of uint8

Just the payload then? Not the EventHubEvent?

**Comment by deyaaeldeen** [comment]
The array of events gets compiled to a batch message but I don't see any checking for batch size: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/eventhub/event-hubs/src/eventHubSender.ts#L746

**Comment by richardpark-msft** [comment]
@deyaaeldeen, it looks like SB uses the normal ServiceBusMessageBatch (which seems like the easier approach)

https://github.com/Azure/azure-sdk-for-js/blob/28b2618ab12cafac9f0ca7a59bbf8af09a867460/sdk/servicebus/service-bus/src/sender.ts#L247

I'm not sure why Event Hubs doesn't use it's own batch abstraction but it would have caught this problem. :|

(at any rate, I think the SB lib is doing the right thing - I think you get a detach of the link if you send a message that's too large).

**Comment by LarryOsterman** [comment]
> > vector of uint8
> 
> Just the payload then? Not the EventHubEvent?

Honestly, I haven't chased down all the details yet. My current thinking is:

`EventDataBatch`
`EventData`
`vector<EventData>`

`EventData` can be implicitly constructed from string and vector<uint8>, so that adds in string and uint8 as parameters. 

I'd need to see how if the `vector<EventData>` variant can be initialized with an array of bytes implicitly - I think it may be possible).

**Comment by LarryOsterman** [comment]
```cpp
  auto client = Azure::Messaging::EventHubs::ProducerClient(
      connStringEntityPath, eventHubName, producerOptions);

  client.Send(Azure::Messaging::EventHubs::Models::EventData{"This is a test message"});

  // Send using the implicit EventData constructor.
  client.Send(std::string{"String test message"});

  // Send using a vector of implicit EventData constructor with a binary buffer.
  client.Send({{12,13,14,15}, {16,17,18,19}});
  
```
