### ISSUE TITLE
Should the authority host be read from the environment variable `AZURE_AUTHORITY_HOST` if the user doesn't pass it in the options?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4875]
We currently default the authority host within the options which are used in the various credentials we have, and don't read it from the environment variable on behalf of the user.

https://github.com/Azure/azure-sdk-for-cpp/blob/69e5f1a6272b4122dd7d6300feb6ba1962d3b4d4/sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp#L43-L53

This is different from behaviors in other languages, like Go and .NET.
https://github.com/Azure/azure-sdk-for-net/blob/d90042d570a6531d7f7ed97e82ddfe95c730158b/sdk/identity/Azure.Identity/src/Credentials/TokenCredentialOptions.cs#L25-L32
https://github.com/Azure/azure-sdk-for-go/blob/514985a4c9d311c90b86c74c6ff779abcec1ffcd/sdk/azidentity/azidentity.go#L107-L111

Should we match the precedence and consider reading the environment variable on behalf of the user, if they don't provide an option and ? If so, we'd want to design a solution that's non-breaking, because we can't use "is the option not set" as a sentinel to read the environment variable.

cc @antkmsft, @LarryOsterman

**Comment by joshfree** [comment]
Related

- https://github.com/Azure/azure-sdk-for-net/issues/36001
