### ISSUE TITLE
DefaultAzureCredential should support empty constructor

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#4886]
https://github.com/Azure/azure-sdk-for-cpp/blob/efc0d8930a5f35b8d6558831c32ebaaf9cc75782/sdk/identity/azure-identity/inc/azure/identity/default_azure_credential.hpp#L53C95-L53C95

**Comment by ahsonkhan** [comment]
We already have a default parameterless ctor for DAC:
https://github.com/Azure/azure-sdk-for-cpp/blob/25f33e9800064bb02a08e94673595d1e498eceed/sdk/identity/azure-identity/inc/azure/identity/default_azure_credential.hpp#L40-L46

This works correctly, as expected:
```C++
#include <azure/identity/default_azure_credential.hpp>

#include <iostream>

int main()
{
  try
  {
    {
      Azure::Identity::DefaultAzureCredential defaultAzureCredential;
      std::cout << defaultAzureCredential.GetCredentialName() << std::endl;
    }
    {
      Azure::Identity::DefaultAzureCredential defaultAzureCredential{};
      std::cout << defaultAzureCredential.GetCredentialName() << std::endl;
    }
    {
      auto defaultAzureCredential = new Azure::Identity::DefaultAzureCredential();
      std::cout << defaultAzureCredential->GetCredentialName() << std::endl;
    }
    {
      auto defaultAzureCredential = std::make_shared<Azure::Identity::DefaultAzureCredential>();
      std::cout << defaultAzureCredential->GetCredentialName() << std::endl;
    }
  }
  catch (const Azure::Core::Credentials::AuthenticationException& exception)
  {
    std::cout << "Authentication error: " << exception.what() << std::endl;
    return 1;
  }

  return 0;
}
```

And tests/samples show it should work as expected:
https://github.com/Azure/azure-sdk-for-cpp/blob/bbf6c9c3ee5816de43a9ab0683ead222d01f8dbf/sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp#L38
https://github.com/Azure/azure-sdk-for-cpp/blob/bbf6c9c3ee5816de43a9ab0683ead222d01f8dbf/sdk/identity/azure-identity/samples/default_azure_credential.cpp#L18

What you can't do is use syntax like this, which ends up trying to call the **copy ctor,** which doesn't exist (the base class TokenCredential deleted that copy ctor):

```text
auto defaultAzureCredential = Azure::Identity::DefaultAzureCredential();
           ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ahkha/Git/vcpkg/installed/x64-osx/include/azure/identity/default_azure_credential.hpp:39:40: note: copy constructor of 'DefaultAzureCredential' is implicitly deleted because base class 'Core::Credentials::TokenCredential' has a deleted copy constructor
  class DefaultAzureCredential final : public Core::Credentials::TokenCredential {
                                       ^
/Users/ahkha/Git/vcpkg/installed/x64-osx/include/azure/core/credentials/credentials.hpp:125:5: note: 'TokenCredential' has been explicitly marked deleted here
    TokenCredential(TokenCredential const&) = delete;

```

**Comment by antkmsft** [comment]
We could enable this scenario more easily by enabling move constructor, but copy constructor can be written as well.
But who needs this semantics, since all the clients accept `TokenCredential` by `shared_ptr`?
This works:
```cpp
auto defaultAzureCredential = std::make_shared<Azure::Identity::DefaultAzureCredential>();
```
Assigning this back to you guys @RickWinter and @ahsonkhan to get the question answered - what do we want to achieve by enabling this semantics? Once we know what we want this for, we can make everything work if we need - I'd say even if you don't like the fact that the credentials basically have to be created via `make_shared`, we can change that too, without a breaking change, I have ideas how that can be done as well. But without the concrete goal and answer, why we need this, I'd not just enable semantics just to have one.

**Comment by antkmsft** [comment]
I suggest to close this item. I explained above. If there is something more that we want, please create a new work item, with another description and purpose. We do have a parameterless constructor for DAC.
