### ISSUE TITLE
ClientCertificateCredetial: make better exception description for non-.pem files

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#4907]
We currently only support `.pem` files. We should try to add support for `.pfx` files, but this work item is about another matter (#4909).
It must not be uncommon for people to try to use the credential with `.pfx` files.
Currently, the exception will read: "Authentication error: Failed to read certificate private key."
We shoud check the extension and say sonlthing like ".pfx certificates are not supported, only the .pem cretificates are supported. Please convert your .pfx to .pem using the command 'openssl pkcs12 -in file.pfx -out file.pem -nodes'. "

**Comment by LarryOsterman** [comment]
If it helps, a PFX file is an ASN.1 BER encoded object. Basically it's the decoded binary of the base64 payload in a PEM file. 

It works because the "type" part of a PEM file is redundant, the OIDs in the ASN.1 encoded payload should have the type of the object embedded in it.
