### ISSUE TITLE
ClientCertificateCredential: add support for .pfx files

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#4909]
This should work: https://stackoverflow.com/questions/6371775/how-to-load-a-pkcs12-file-in-openssl-programmatically

This is apart from using windows crypto stack on Windows (#4084) - even on Linux you should be able to use .pfx certificate.

**Comment by antkmsft** [comment]
See https://github.com/Azure/azure-sdk-for-cpp/issues/4907#issuecomment-1688894456

**Comment by RickWinter** [comment]
The security first approach encourages the use of ManagedIdentity, WorkloadIdentity, and other TokenCredential auth patterns. We will not be adding this support.

Should you come across this issue and desire this support, please open a new issue describing your workflow.

//cc: @scottaddie
