### ISSUE TITLE
Regenerate KeyVault SDK using the latest swagger version

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-cpp#4956]
The fix for key rotation for code generators has been merged. Use commit 5dd1107d5f2be8d600325d795450e1d854fbe7e8 for codegen

**Comment by gearama** [comment]
There is no functional difference  between 7.5 and 7.3(currently supported in c++), from diffing the latest and greatest swaggers  beyond the version for either keys, certs or secrets.
