### ISSUE TITLE
KeyVault Secrets samples do not compile due to incorrect return type name for `GetSecret`

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4991]
For example, these samples need to be updated so that the calls to `GetSecret` return the correct type, named `KeyVaultSecret`, and not `Secret`.

```diff
-Secret secret = client.GetSecret("some_secret").Value;
+KeyVaultSecret secret = client.GetSecret("some_secret").Value;
```

https://github.com/Azure/azure-sdk-for-cpp/blob/daa36f1650865fd4cd4c445233b9a72909ca3db6/sdk/keyvault/azure-security-keyvault-secrets/README.md?plain=1#L147

There are quite a few such samples that we should validate for correctness and fix. For example, here is another:
https://github.com/Azure/azure-sdk-for-cpp/blob/daa36f1650865fd4cd4c445233b9a72909ca3db6/sdk/keyvault/azure-security-keyvault-secrets/samples/sample2_backup_restore.md?plain=1#L44

See others:
https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-cpp+GetSecret+language%3AMarkdown&type=code&l=Markdown

@LarryOsterman catching such things would be a great addition to the "compile samples and extract snippets" work :)

**Comment by LarryOsterman** [comment]
I'm quite confused. All samples are supposed to be built in the CI pipeline and nightly pipelines.

Why were these samples not built?

Or is it possible that these aren't samples, but instead are snippets of code manually pasted into markdown files?

If it's the latter, then that is the *entire* reason why I want to create a snippet tool - to ensure that snippets of code in our markdown files or doxygen comments are kept up-to-date.

**Comment by ahsonkhan** [comment]
> If it's the latter, then that is the _entire_ reason why I want to create a snippet tool - to ensure that snippets of code in our markdown files or doxygen comments are kept up-to-date.

In this case, it is precisely that.

I discovered it when trying the samples from this doc, which seems to have been inspired from our READMEs:
https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=cpp
