### ISSUE TITLE
Add authority host url options validation to reject non-HTTPS schemes

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4999]
Doing so will make the semantics consistent with other language SDKs:
https://github.com/Azure/azure-sdk-for-net/blob/bc5e855008db838982fc6f9dbd6cacb011bea3f1/sdk/identity/Azure.Identity/src/Validations.cs#L51
https://github.com/Azure/azure-sdk-for-go/blob/6bb9bb9b61fad6912fe463ad3b5a2dee5816c1bd/sdk/azidentity/azidentity.go#L71-L73
https://github.com/Azure/azure-sdk-for-java/blob/8c2577692d0b3900ddaee2dcf154ab6f8db30ca4/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/util/ValidationUtil.java#L55-L66

This is similar to the validation that occurs in the bearer token authentication policy:
https://github.com/Azure/azure-sdk-for-cpp/blob/35e42b99cfcc5b2797aa278a39694030732da2bc/sdk/core/azure-core/src/http/bearer_token_authentication_policy.cpp#L24-L28

**Comment by RickWinter** [comment]
We should hold off on adding these options.  Azure uses https endpoints.  Airgapped clouds could drive the need for this at some point.
