### ISSUE TITLE
[Question] What's the use of `m_retryHeaders` and `m_retryQueryParameters` in Core::Http::Request?

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#503]
https://github.com/Azure/azure-sdk-for-cpp/blob/755085f25d8096661bf09852bb2b620fede5a911/sdk/core/azure-core/inc/http/http.hpp#L216
https://github.com/Azure/azure-sdk-for-cpp/blob/755085f25d8096661bf09852bb2b620fede5a911/sdk/core/azure-core/inc/http/http.hpp#L217

seems they're never used

**Comment by vhvb1989** [comment]
it is used by the retry policy.
Any header or query parameter added there is cleaned before retrying a request.

This is because some policies after the retry policy might add some headers/query for the request.  Those headers need to be per retry.  Policy should add it everytime and retry policy just cleans the list

**Comment by JinmingHu-MSFT** [comment]
> it is used by the retry policy.
> Any header or query parameter added there is cleaned before retrying a request.
> 
> This is because some policies after the retry policy might add some headers/query for the request. Those headers need to be per retry. Policy should add it everytime and retry policy just cleans the list

Storage code doesn't use this feature, but I'm okay with it.

**Comment by JeffreyRichter** [comment]
The storage retry policy must reset the headers and query parameters. You should start by copying or retry policy and then enhace it to read from the secondary data centers.

**Comment by JinmingHu-MSFT** [comment]
> The storage retry policy must reset the headers and query parameters. You should start by copying or retry policy and then enhace it to read from the secondary data centers.

This is not about storage retry policy or failover to secondary data center.

i'm working on Blob batch feature. Normally for Delete and SetAccessTier request, threre's an `x-ms-version` header. But for subrequest in batch, we cannot include this header or server will return error. So i need a policy to remove this header.

**Comment by vhvb1989** [comment]
@JinmingHu-MSFT , but a pipeline policy applies to all requests (all APIs) from client.
If the header you mentioned needs to be set just for the first request and then it shouldn't be removed, can we just update the request before calling `send(request)` function again?

I can review the issue you create to make sure `AddHeader` overrides previous value.
We could also have a `RemoveHeader` function if what we need is to remove it from the list of headers right?

**Comment by vhvb1989** [comment]
@Jinming-Hu is the mentioned answer OK to close this issue?
