### ISSUE TITLE
Mutex isn't correctly used in CurlSession::GetCurlConnection

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#505]
Here https://github.com/Azure/azure-sdk-for-cpp/blob/70eeec598496de78ba5f6a5ccd7bdb4b4724fd87/sdk/core/azure-core/src/http/curl/curl.cpp#L799
we are accessing the object without holding the mutex.

In the current implementation, we acquire the mutex before writing the data, but we don't acquire the mutex before reading the data. I don't think this is the right way of using mutex.

@vhvb1989 You also mentioned double checked locking in the comments. https://github.com/Azure/azure-sdk-for-cpp/blob/70eeec598496de78ba5f6a5ccd7bdb4b4724fd87/sdk/core/azure-core/src/http/curl/curl.cpp#L798 I'm not an expert but you can find some results if you google "double checked locking is broken".

**Comment by vhvb1989** [comment]
think the pattern is said to be broken on Java.
We do double read. First read without mutex, here 2 threads could get same results (that's fine).
Then, if condition is true, we get the mutex to check the condition again.

The benefit is to avoid getting always the mutex, because if there is no connections available, there is no point to lock the mutex (expensive op).

**Comment by vhvb1989** [comment]
@JeffreyRichter

**Comment by JinmingHu-MSFT** [comment]
> think the pattern is said to be broken on Java.

but it's not said to be working in C++.

> We do double read. First read without mutex, here 2 threads could get same results (that's fine).

My point is, the variable is being written in another thread, reading from such a variable without mutex is unsafe. given this is not an atomic variable.

> The benefit is to avoid getting always the mutex, because if there is no connections available, there is no point to lock the mutex (expensive op).

Isn't this another kind of premature optimization?

**Comment by JeffreyRichter** [comment]
Jinming is correct
