### ISSUE TITLE
Is it safe to initialize mutex and STL containers during DLL initialization?

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#506]
https://github.com/Azure/azure-sdk-for-cpp/blob/70eeec598496de78ba5f6a5ccd7bdb4b4724fd87/sdk/core/azure-core/inc/http/curl/curl.hpp#L68
https://github.com/Azure/azure-sdk-for-cpp/blob/70eeec598496de78ba5f6a5ccd7bdb4b4724fd87/sdk/core/azure-core/inc/http/curl/curl.hpp#L71

In [this](https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain) page, it says

**The entry-point function should perform only simple initialization or termination tasks.** It must not call the LoadLibrary or LoadLibraryEx function (or a function that calls these functions)...

... Therefore, the entry-point function can call functions in Kernel32.dll that do not load other DLLs. For example, **DllMain can create synchronization objects such as critical sections and mutexes, and use TLS. Unfortunately, there is not a comprehensive list of safe functions in Kernel32.dll.**

So I wonder, is initialization of STL container considered safe in this situation?

**Comment by vhvb1989** [comment]
@CaseyCarter  and @BillyONeal  help for this

**Comment by BillyONeal** [comment]
Our `std::mutex` will create a ConcRT lock on Windows XP, a CRITICAL_SECTION on Vista, or an SRWLOCK on 7+. I'm sure Vista+s should be OK.

You are vulnerable to the "static initialization order fiasco" though since we don't implement std::mutex's constexpr constructor (and can't in an ABI compatible way).

**Comment by JinmingHu-MSFT** [comment]
> Our `std::mutex` will create a ConcRT lock on Windows XP, a CRITICAL_SECTION on Vista, or an SRWLOCK on 7+. I'm sure Vista+s should be OK.
> 
> You are vulnerable to the "static initialization order fiasco" though since we don't implement std::mutex's constexpr constructor (and can't in an ABI compatible way).

Thanks @BillyONeal . I'll take it to mean, there's no problem with current implementation.

I have another question, just our of curiosity, is it okay to allocate memory on heap during dll initialization? I mean in this case, we're using global `std::map`, which I guess won't allocate memory. What if it was a `std::vector` or `std::string` which by default allocates some memory?

**Comment by BillyONeal** [comment]
> we're using global std::map, which I guess won't allocate memory.

`std::map`, at least in MSVC++'s implementation, *does* allocate memory in its default ctor, for the `end()` sentinel node. (This is true for all node-based containers in MSVC's implementation, including `list`, `unordered_map`, etc.)

>What if it was a std::vector or std::string which by default allocates some memory?

These allocate memory in their default ctors in debug modes but not in release modes.

As far as I know HeapAlloc (and therefore malloc) are safe in DllMain but I'm not having great luck finding that in msdn :/

**Comment by JinmingHu-MSFT** [comment]
Thank you very much @BillyONeal . I think I can close this now.
