### ISSUE TITLE
Enable mockable HTTP testing

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#508]

**Comment by vhvb1989** [comment]
See an example approach of mocking Http response for a test case here: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/keyvault/azure-security-keyvault-keys/test/mocked_transport_adapter_test.hpp

The mock is manually constructed for the mock and the client needs to be updated to bypass auth, but it might help for someone wanting to test client responses without taking care about auth or other things.
