### ISSUE TITLE
KeyVault: Fix test failures

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#5112]
The reason for this, **I think**, is that after the change that enabled running live tests against WinHTTP transport, and a few subsequent fixes to record and playback (updated regex for secrets, removed cookie from recordings), KeyVault pipeline started to fail, and we need to update the recordings (Storage did that - https://github.com/Azure/azure-sdk-for-cpp/pull/5070/files#diff-8197b617f0faa3471ca4ae5d7bc8ed10aaf1c67656cdd7071570cd08994d3a88R5).
Possibility number 2 - we need to update WinHTTP transport to closer align with the libcurl transport (see https://github.com/Azure/azure-sdk-for-cpp/pull/5071/files#r1373997631).

Either way, please make the `/azp run cpp - keyvault - ci` and `/azp run cpp - keyvault` green.

**Comment by LarryOsterman** [comment]
If there is ever a question about whether the winhttp or curl behavior is correct, the winhttp behavior should be assumed to be correct.  Curl is a HTTP client written by the Azure SDK for C++ team. WinHTTP is an HTTP client written by the Windows HTTP client transport team (who also writes the .Net HTTP client).

So IMHO possiblity #2 should be worded as "we need to update the libcurl transport to closer align with the winhttp transport".
