### ISSUE TITLE
Test recording infra broken 

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#5126]
**Describe the bug**
Record test with libcurl , playback fails with winhttp after the latest fixes. the other way around fails also . Please fix the diffrences that were created due to the fixes put in. 
***Exception or Stack Trace***
Keyvault and HSM areNotSameunknown file: error: C++ exception with description "Received an HTTP unsuccessful status code: 404 Reason: Not Found" thrown in the test body.
    
Failiing test 

TEST_F(KeyVaultKeyHSMClient, GetRandomBytes)

**To Reproduce**
BUILD WITH LIBCURL 
RECORD TEST 
BUILD WITH WINHTTP
PLAYBACK FAILS 

TEST_F(KeyVaultKeyHSMClient, GetRandomBytes)

Keyvault and HSM areNotSameunknown file: error: C++ exception with description "Received an HTTP unsuccessful status code: 404 Reason: Not Found" thrown in the test body.
 
RECORD/PLAYBACk with libcurl    works
RECORD/PLAYBACK with WINHTTP works

cross does not work. 
***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by LarryOsterman** [comment]
Could you please attach the test proxy logs that reproduce the problem? Without the test proxy logs, it will be extremely difficult to identify why the proxy is not finding the recorded entry.
