### ISSUE TITLE
Update most of our samples to use `DefaultAzureCredential`.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#5133]
... unless it really makes sense to use any other specific credential.

The current pattern we have, the ClientSecretCredential + reading its parameters from the environment, was good when we did not have options, but now let's use easier+more powerful credentials that draw less attention to themselves, so sample focuses more on the client library.

See also #5132

**Comment by LarryOsterman** [comment]
+1 to this. Moving from CSC is an azure-wide (really Microsoft-wide) initiative to move away from passwords towards some form of passwordless managed identity. Our samples should reflect that initiative.
