### ISSUE TITLE
[azure-core-tracing-opentelemetry] uber [Ge] task

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-cpp#5164]
- [ ] https://github.com/Azure/azure-sdk-for-cpp/issues/5162
- [ ] https://github.com/Azure/azure-sdk-for-cpp/issues/5163
- [ ] https://github.com/Azure/azure-sdk-for-cpp/issues/4120 - any remaining work left on tests/docs/samples

**Comment by RickWinter** [comment]
Closing this rollup task.  Items are tracked individually and in Issue #4120
