### ISSUE TITLE
What is "CMakeGenerate" CI leg doing?

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#5190]
What do we need it for? Inside the job, it looks like it is repeating the "cmake generate" step 16 times. Is it really necessary?
I can't find the purpose in the build logs, and with my limited understanding of yml files, I can't find the purpose or difference between 16 steps either.

See also #5191

**Comment by antkmsft** [comment]
So, for example, `azure-identity`'s CI would run cmake generate for `core`, `keyvault`, `storage` and so on?
If so, why would we do that? Is it helping us to catch anything?
If every CI runs cmake generqate for all packages, there will be a time when it won't scale, because hopefully we'll have more and more packages.

**Comment by antkmsft** [comment]
And if it is needed, I think we need a better descriptions for the step that gets repeated 8 times - "cmake generate core", "cmake generate identity"... and so on. It is not immediately clear from the console output either. I would suggest the step should print in the very first lines, all the context of what it is about to do.
![image](https://github.com/Azure/azure-sdk-for-cpp/assets/41349689/d77af9f0-05dc-4b65-b804-c3998d2e2f36)

**Comment by LarryOsterman** [comment]
Btw, my snippets PR has a couple of enhancements to this to add a bit more clarity to the subitems. ADO doesn't have the ability to group Jobs, but I've added the package name to a number of the steps which are run in this step.

**Comment by antkmsft** [comment]
#5213
