### ISSUE TITLE
Mac builds in CI are way too slow

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#5191]
For example, take the "CMakeGenerate" CI leg. IT takes 5 minutes on Linux, 10 minutes on WIndows, close to 2 hours for Mac, sometimes gets aborted because it exceeds the 2 hours limit. That impacts every PR.

BVasically, we won't be able to check in anything in faster than in 2 hours.
And we come to these 2 hours pretty close, even now we sometimes time out by 2 hour limit, and shoud we add a bit more code, then more PRs will be timing out.

If there's nothing we can do, maybe we should move the Mac+CmakeGenerate CI leg
to nighty runs with 4 hours timeout, and remove it from being run against every PR, but I hope there are other options.

See also #5190 - maybe the step itself is also unnecessarily long.

**Comment by antkmsft** [comment]
This started on November 21st. 
Prior to that, "CmakeGenerate Mac" was taking 10 minutes.

**Comment by weshaggard** [comment]
Having a quick look at the logs this seems to correspond with your change to update vcpkg version in https://github.com/Azure/azure-sdk-for-cpp/pull/5175.

Looking at the logs of a recent run https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3302185&view=logs&j=5b40fe45-3be6-55b8-8b6c-da8150e7e0d7&t=11993ae9-0d33-503c-0a4e-62d7d35853c8 it seems there are a number of "curl failures" which I believe causes vcpkg to download and build from source.

**Comment by antkmsft** [comment]
Thank you, Wes! I think that explains it. I will ask @danieljurek to update vcpkg cache for Mac, if that is necessary (I could be mistaking, but it could be that one successful build would be sufficient for the vcpkg bits to get cached automatically). We will have to update vcpkg once again in about a week. And in the meantime, I have a PR to extend CI timeouts from 2 to 3 hours (#5212) - so in the worst case, it will be taking longer for some time, but in the end the build is successful. And in best scenario, it will run for ~130 minutes once, and after that the builds will be faster again automatically.
