### ISSUE TITLE
[Storage team] DownloadTo Api should make first request to Server with a Range when InitialChunkSize is set

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#520]
The issue is that if I set value `InitialChunkSize` to something like `8MB` :
```cpp
      Blobs::DownloadBlobToOptions options;
      options.InitialChunkSize = 8_MB;
      options.ChunkSize = 8_MB;
      auto res = blockBlobClient.DownloadTo(buffer.data(), buffer.size(), options);
```

The Request sent to Server does not include a Range.  `offset` and `range` should be set to the response from server is size = InitialChunkSize.

Right now, the response from server is equal to the blobSize.

This is an issue because the connection won't be re-used it because the response won't be read entirely. (only InitialChunkSize  wiil be read).

This is a change I made to DownloadTo implementation in blob_client.cpp as a workaround
https://github.com/Azure/azure-sdk-for-cpp/pull/519

**Comment by JinmingHu-MSFT** [comment]
No, we can't do this. This will lead to problem when the blob is empty.

**Comment by vhvb1989** [comment]
Range can't be used because blob size needs to be known in advance to avoid trying to get a range bigger than blob size.

The only way to keep first connection alive to be re-used would be by doing a Head request first. However, that would be just a very small improvement when customer is using only thread only.  So, probably not worth it.
