### ISSUE TITLE
Please Tag a Pre-Release

### ISSUE THREAD

**Issue by dtsmith2001** [Azure/azure-sdk-for-cpp#527]
**Query/Question**
Would you please tag a working build as Pre-Release?

***Why is this not a Bug or a feature Request?***
This gives those of us who want a "stable" build a tag to pull.

**Setup (please complete the following information if applicable):**
 N/A

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by RickWinter** [comment]
Thanks for the interest in this SDK.  We have not declared a stable pre-release yet.  Once we reach that milestone we will tag the release.  Stay tuned.

**Comment by RickWinter** [comment]
https://github.com/Azure/azure-sdk-for-cpp/releases/tag/azure-core_1.0.0-beta.1
