### ISSUE TITLE
[Storage] Consider adding support for Batch Delete of Blob Versions

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-cpp#5301]
Related - https://github.com/Azure/azure-sdk-for-net/issues/40849

This is not time sensitive.  Use this issue to determine if there is customer demand for this feature.

**Comment by Jinming-Hu** [comment]
This is already supported in C++. We have two variants for batch delete operation, one taking a blob name, one taking a URL. https://github.com/Azure/azure-sdk-for-cpp/blob/27aab786c2908138cb3a6ae528af05fc63e0ec5f/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_batch.hpp#L97

Blob version and snapshots can be deleted with URL.

**Comment by seanmcc-msft** [comment]
@Jinming-Hu I think we can safely close this issue then.
