### ISSUE TITLE
Reading inexistent Blob with `BlockBlobClient` throws `RequestFailedException` with no ErrorCode

### ISSUE THREAD

**Issue by muhammadhamzasajjad** [Azure/azure-sdk-for-cpp#5369]
**Describe the bug**
I am trying to read a blob that does not exist. I use `BlockBlobClient` to read the blob and, as expected, a `Azure::Core::RequestFailedException e` is thrown. According to the [error code docs](https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes) `e.ErrorCode` should be set to `BlobNotFound`, but I find that it is set to empty string.

**To Reproduce**

***Code Snippet***

```cpp

Azure::Storage::Blobs::BlobContainerClient container_client;
// setup your azure connection with container_client

Azure::Core::Context get_context(unsigned int request_timeout){
    Azure::Core::Context requestContext;
    return requestContext.WithDeadline(std::chrono::system_clock::now() + std::chrono::milliseconds(request_timeout));
}

std::shared_ptr<Buffer> read_blob(
        const std::string& blob_name,
        const Azure::Storage::Blobs::DownloadBlobToOptions& download_option,
        unsigned int request_timeout) {

    auto blob_client = container_client.GetBlockBlobClient(blob_name);
    auto properties = blob_client.GetProperties(Azure::Storage::Blobs::GetBlobPropertiesOptions{}, get_context(request_timeout)).Value; // exception thrown at this line
    std::shared_ptr<Buffer> buffer = std::make_shared<Buffer>(properties.BlobSize);
    blob_client.DownloadTo(buffer->preamble(), buffer->available(), download_option, get_context(request_timeout));

    return buffer;
}

try {
  read_blob("inexistent/blob/name", Azure::Storage::Blobs::DownloadBlobToOptions(), 60000);
}
catch ((const Azure::Core::RequestFailedException& e)) {
  std::cout << e.ErrorCode << std::endl; // e.ErrorCode is empty
  std::cout << e.StatusCode << std::endl; // e.StatusCode is correctly set to 404 
  std::cout << e.RawResponse.get()->GetHeaders().find("x-ms-error-code")->second << std::endl; // prints BlobNotFound
}

```

The exception is thrown at line `auto properties = blob_client.GetProperties(...)` and the ErrorCode is empty. StatusCode is correctly set to 404. If I read the headers of the raw response(last line of catch clause), I get that the header `x-ms-error-code` is correctly set to `BlobNotFound` but this is not copied to `e.ErrorCode`. This suggests that `BlockBlobClient` may not be correctly setting up the exception before throwing it.

**Expected behavior**
`RequestFailedException::ErrorCode`  should be set to `"BlobNotFound"`, instead of `""`.

**Setup (please complete the following information):**
 - OS: Ubuntu
 - IDE : CLion
 - Version of the Library used `12.10.0` (downloaded with vcpkg)

**Additional context**
Setting `e.ErrorCode` is important for consistency with the docs and for correct error handling.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Jinming-Hu** [comment]
@muhammadhamzasajjad can you try to catch the exception as `StorageException` and check the error code there?
```C++
catch (Azure::Storage::StorageException& e)
{
  // exception handling
}
```

**Comment by muhammadhamzasajjad** [comment]
Thanks for the reply @Jinming-Hu.
I have tried catch with `Azure::Storage::StorageException` as well, but the behaviour remains the same as it is with `Azure::Core::RequestFailedException`

**Comment by Jinming-Hu** [comment]
This believe this is a bug when parsing 404 response of `HEAD` request.

Usually error code is parsed from XML response body, but there's no response body for `HEAD` requests. In this case, we should directly read from `x-ms-error-code` header.

**Comment by Jinming-Hu** [comment]
will be fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/5372

**Comment by muhammadhamzasajjad** [comment]
@Jinming-Hu, thanks for the update. Looking forward to the fix.

**Comment by muhammadhamzasajjad** [comment]
@Jinming-Hu, could you please tell me when the release for this fix might be out in vcpkg? The last one I see was in [November 2023](https://github.com/microsoft/vcpkg/tree/master/ports/azure-storage-blobs-cpp).

**Comment by Jinming-Hu** [comment]
@muhammadhamzasajjad I think it'll be released soon. We have release plan in late April or early May.
