### ISSUE TITLE
[Storage] [Common] Add sample for usage on checksum.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#538]

**Comment by JinmingHu-MSFT** [comment]
is there a customer ask?

**Comment by JinmingHu-MSFT** [comment]
As we've discussed in the meeting, this is a controversial feature. Some people think it's not much useful (which I agree), while some people think it's necessary.

So I think such a sample will give our customers the impression that we encourage them to use it. But actually we do not.

**Comment by JinmingHu-MSFT** [comment]
i'll just close this issue, if you still think it's necessary to write such a sample. Reopen it and we can  discuss further.
