### ISSUE TITLE
[Storage] Add sample for SAS.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#542]

**Comment by hpourreza** [comment]
any update on this sample? I tried the same connection string with a SAS token that used to work with the older C++ library but could not get `BlobContainerClient::CreateFromConnectionString`  working.

**Comment by Jinming-Hu** [comment]
hi @hpourreza  This issue is for a sample demonstrating how to generate a SAS token.

What does your SAS token look like and what kind of error did you encounter?

**Comment by Jinming-Hu** [comment]
blocked by https://github.com/Azure/azure-sdk-for-cpp/issues/769 and https://github.com/Azure/azure-sdk-for-cpp/issues/776
