### ISSUE TITLE
[Storage] Discuss about where to store service version, version.hpp or version.txt

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#543]

**Comment by RickWinter** [comment]
@JinmingHu-MSFT @katmsft Where this goes is worth standardizing in the guidelines.

**Comment by Jinming-Hu** [comment]
@RickWinter i'm okay if we decide to put version info in `version.hpp`. I was looking https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/template/azure-template/inc/azure/template/version.hpp and have a few questions though.


why do we need those macros? why not just write

```
static constexpr int Major = 1;
static constexpr int Minor = 0;
static constexpr int Patch = 0;
static constexpr const char* prerelease = "beta.1";
```

it's much simpler.

**Comment by danieljurek** [comment]
The engineering system requires a consistent format for version.hpp to automatically update after release. Changes here are using the format specified in the template project: https://github.com/Azure/azure-sdk-for-cpp/pull/567

**Comment by Jinming-Hu** [comment]
> The engineering system requires a consistent format for version.hpp to automatically update after release. Changes here are using the format specified in the template project: #567

yes, i know, i skimmed your PR and I know how it works. You're extracting the version with a regex.  I also agree the format has to be consistent so that we can use the same regex for each service. I just think the `version.hpp` can be simplified. for example,

```
static constexpr int AzureCoreMajorVersion = 1;
static constexpr int AzureCoreMinorVersion = 0;
static constexpr int AzureCorePatchVersion = 0;
static constexpr const char* AzureCorePrereleaseVersion = "beta.1";
```

i'm also okay if you don't want to change.

**Comment by katmsft** [comment]
https://github.com/Azure/azure-sdk-for-cpp/issues/708
