### ISSUE TITLE
Move SAS generation into core from the various services 

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#5436]
**Describe the bug**
we have SAS tokens in mutiple places. It would be a good candidate for Azure::Core we should look into moving it there. 
We need to keep in mind the various permission enums , service enums etc . look into either template or parameters etc. 

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by ahsonkhan** [comment]
Which services that we support currently use SAS tokens for authentication? We should be cautious in moving things to core that may not be as forward looking compared to other auth mechanisms.

**Comment by gearama** [comment]
not in scope as we want to move towards passwordless auth methods
