### ISSUE TITLE
How to integrate Azure SDK for C++ into existing Visual Studio MSVC (.vcxproj) project

### ISSUE THREAD

**Issue by MrHaelscheir** [Azure/azure-sdk-for-cpp#5457]
**Query/Question**
https://azure.github.io/azure-sdk-for-cpp/ and other documentation assume that the user is able to integrate the SDK into a new or existing CMake and vcpkg project. Our use case involves an existing C++ Visual Studio MSVC (.vcxproj) for which conversion to CMake is currently not an option. How can we leverage the Azure SDK for C++ with this project as a static dependency? Particularly, we would like to be able to build this SDK statically with our own internal non-CMake library.

***Why is this not a Bug or a feature Request?***
This is not a bug insofar as our present issues with building a fresh Visual Studio CMake project is incurring some errors likely due to remaining knowledge holes on our end, and that this issue request is open to the possibility of bypassing needing to do the CMake build on our end.
This is not a feature request unless the resolution requires work on the SDK developers' end to deploy a version or library build for integration with existing Visual Studio MSVC (.vcxproj) projects.

**Setup:**
 - OS: Windows 10
 - IDE : Visual Studio 2019 (can also use Visual Studio 2022)
 - Using the latest version of Azure SDK for C++.

**Comment by ahsonkhan** [comment]
We don't currently have tests to support the scenario of integrating with an existing Visual Studio MSVC (.vcxproj) project setup. Our model is to distribute the SDK, as source, via vcpkg, and support building as a CMake project.

That said here's some guidance on incorporating a vcpkg package into an MSBuild project, which might be helpful to try:
https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-msbuild?pivots=shell-cmd

**Comment by ahsonkhan** [comment]
Vcpkg supports installing/integrating libraries within a Visual Studio MSVC project (.vcxproj), even if they are CMake-based.

Can you share a [minimal, reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example) of an application which showcases exactly the error you are hitting when following the vcpkg steps. That would be helpful in investigating the issue and provide guidance to your question.

**Comment by MrHaelscheir** [comment]
Hello. We are currently investigating the provided link for incorporating vckpg into MSBuild projects.

**Comment by ahsonkhan** [comment]
Here's a walkthrough video on how to install the Azure SDK packages, using vcpkg, into an MSBuild project in VS: https://aka.ms/azsdk/cpp/gettingstarted-vcpkg-msbuild-video
