### ISSUE TITLE
Improve Tables doc comments based on what is available in the OpenAPI spec

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#5464]
Here's the rest API spec for it, which has _some_ good descriptions for doc comments, that we can use:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/data-plane/Microsoft.Tables/preview/2019-02-02/table.json

For example, we have this description for the response of `GetEntity`:
https://github.com/Azure/azure-rest-api-specs/blob/1aebb2dbe4fe12a555f8bf67ae89435c036ef387/specification/cosmos-db/data-plane/Microsoft.Tables/preview/2019-02-02/table.json#L411-L484

https://github.com/Azure/azure-sdk-for-go/blob/b7816620792994eafbc880bed20ef334e4ac73c3/sdk/data/aztables/client.go#L210-L213
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/aztables#GetEntityResponse

The C++ Tables SDK has the following doc comments for it:
https://github.com/Azure/azure-sdk-for-cpp/blob/8973c6c9fbf025eb05ca41ce645cff3c2566a980/sdk/tables/azure-data-tables/inc/azure/data/tables/tables_clients.hpp#L304-L315

**Comment by gearama** [comment]
this was fixed on Jun 4
