### ISSUE TITLE
Is there a way I can install azure-storage-sdk with conan?

### ISSUE THREAD

**Issue by xiaofan-luan** [Azure/azure-sdk-for-cpp#5485]
**Is your feature request related to a problem? Please describe.**
Currently we are try to use azure sdk for azure blob store access. But it's depend on vcpkg and seems to be a lot of works for user to setup the compilation environment

**Describe the solution you'd like**
We are currently using Conan as our pkg management so seeking for a conan pkg support for the latest v12 package

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by trns1997** [comment]
Up this issue, we would also like to install the azure-storage-sdk using conan, any active work is being done on this?

**Comment by trns1997** [comment]
If i get a green light from someone from the azure community, i do not mind doing it as i have created conan reciepes in the past.

**Comment by trns1997** [comment]
@xiaofan-luan are you using conan on linux or another OS?

**Comment by xiaofan-luan** [comment]
we mainly offer support on:
macos, ubuntu 20.04 or above, rockylinux8

**Comment by xiaofan-luan** [comment]
thanks for the help. We can remove the dependency of vcpkg with the support of conan

**Comment by xiaofan-luan** [comment]
> > we mainly offer support on: macos, ubuntu 20.04 or above, rockylinux8
> 
> ah I've only supported Linux with gcc for the moment, you are open to contribute. If you are really not familiar with creating a conan recipe then i could look into adding macos and windows later on

Thanks for the contribution!
Not an expert on conan. But this helps us a lot already

**Comment by trns1997** [comment]
@xiaofan-luan quick question, for now I've only added support for azure-core and azure-storage modules. Do you use anything else other than these 2 sdk modules?

**Comment by xiaofan-luan** [comment]
i only use azure blob storage, so  azure-storage should be what I need.

**Comment by trns1997** [comment]
> i only use azure blob storage, so azure-storage should be what I need.

Oh nice, you are in luck, I've added azure core and storage support for Conan. Hopefully people from Conan merge it soon :)
