### ISSUE TITLE
Symbol name collision with pkcs11.h identifier CKM_RSA_AES_KEY_WRAP

### ISSUE THREAD

**Issue by jepio** [Azure/azure-sdk-for-cpp#5588]
**Describe the bug**
Building an application that includes both `sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp` and OASIS `pkcs11.h` fails due to both defining a symbol named `CKM_RSA_AES_KEY_WRAP`. Namespacing is irrelevant here, as `pkcs11.h` defines a macro.

***Exception or Stack Trace***
gcc compiler error:
```
In file included from /workspaces/azure_kms_pkcs11/pkcs11_compat.h:12,
                 from /workspaces/azure_kms_pkcs11/attributes.h:1,
                 from /workspaces/azure_kms_pkcs11/aws_kms_pkcs11.cpp:11:
/usr/include/p11-kit-1/p11-kit/pkcs11.h:802:42: error: expected unqualified-id before numeric constant
  802 | #define CKM_RSA_AES_KEY_WRAP            (0x1054UL)
      |                                          ^~~~~~~~
/usr/include/p11-kit-1/p11-kit/pkcs11.h:802:42: error: expected ')' before numeric constant
  802 | #define CKM_RSA_AES_KEY_WRAP            (0x1054UL)
      |                                         ~^~~~~~~~
```

**To Reproduce**
```
apt-get install gcc g++ p11-kit libp11-kit-dev
g++ -c snippet.cpp -I/usr/include/p11-kit-1/p11-kit -I<path to azure-sdk-for-cpp>
```

***Code Snippet***
Add the code snippet that causes the issue.

```
#include <pkcs11.h>
#include <azure/keyvault/keys/key_client_models.hpp>
```

**Expected behavior**
pkcs11 and Azure sdk can be used in the same compilation unit.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04
 - IDE : no
 - Version of the Library used: main bd08d226e1726825ee43cff219b3cba45126910d

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gearama** [comment]
Thank you for submitting this issue. Looking into it .

**Comment by gearama** [comment]
as a temporary workaround reverse the includes 

#include <azure/keyvault/keys/key_client_models.hpp>
#include <pkcs11.h>

Also you might need to call the macro as such KeyEncryptionAlgorithm::(CKM_RSA_AES_KEY_WRAP) – taking macro in braces disables macro expansion.
