### ISSUE TITLE
azure-storage-blobs_12.11.0 fails to build

### ISSUE THREAD

**Issue by avivanoff** [Azure/azure-sdk-for-cpp#5607]
Our Windows build started to fail after upgrading to azure-storage-blobs_12.11.0:

C:/Windows/ServiceProfiles/NetworkService/AppData/Local/vcpkg/downloads/tools/clang/clang-15.0.6  was an extraction target, but it already exists.

The same scripts work with azure-storage-blobs_12.10.0.

**Comment by Jinming-Hu** [comment]
what is the error message? @avivanoff

**Comment by avivanoff** [comment]
C:/Windows/ServiceProfiles/NetworkService/AppData/Local/vcpkg/downloads/tools/clang/clang-15.0.6 was an extraction target, but it already exists.

**Comment by Jinming-Hu** [comment]
This looks like a vcpkg issue

**Comment by Jinming-Hu** [comment]
@avivanoff Can you share the steps to repro this?

**Comment by avivanoff** [comment]
As I said, azure-storage-blobs_12.11.0 works just fine.

It happens on our build server only. I can send you build logs privately.

**Comment by Jinming-Hu** [comment]
https://github.com/microsoft/vcpkg/issues/37431

I think this is a vcpkg issue. It also happens when installing other packages.

**Comment by avivanoff** [comment]
How do I fix it?

**Comment by Jinming-Hu** [comment]
You can try clean build first. If it doesn't fix the problem, you can open an issue in https://github.com/microsoft/vcpkg
