### ISSUE TITLE
Add support for providing Resource ID within ManagedIdentityCredential

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#5648]
Other language SDKs (such as Java/.NET/GoLang) have the ability to pass in the `ResourceIdentifier` parameter to the `ManagedIdentityCredential` ctor.
https://github.com/Azure/azure-sdk-for-net/blob/790d2faf82ae49e37d829ef53bfa92695037a377/sdk/identity/Azure.Identity/api/Azure.Identity.netstandard2.0.cs#L317

Add a similar capability for C++.

**Comment by RickWinter** [comment]
@ahsonkhan Is this OID feature that only python currently supports?

**Comment by ahsonkhan** [comment]
No, that's object ID. This is different, it is about **resource** ID.
I have added more details to the issue description.
