### ISSUE TITLE
DataLakeFileClient is initialized with a blob endpoint URL, regardless of whether the path provided uses a dfs URL format.

### ISSUE THREAD

**Issue by sharmaplkt** [Azure/azure-sdk-for-cpp#5729]
In our scenario, we are attempting to instantiate a DataLakeFileClient using a storage URL formatted as https://adlsgen2account.dfs.core.windows.net/*. However, the DataLakeFileClient consistently converts this URL to a blob URL (https://adlsgen2account.blob.core.windows.net/*) before creating the object.

Our storage account is situated within a virtual network (VNet), and we have established a managed private endpoint from our workspace to the storage account. The default schema configured for this endpoint is `dfs`. 

https://github.com/Azure/azure-sdk-for-cpp/blob/bbfc93fcaef31f4f67acb56ee749a94bf2a7ead3/sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp#L82C33-L82C68

`DataLakeFileClient` is always initialized using the blob endpoint URL (https://adlsgen2account.blob.core.windows.net/*). Is there a workaround for this.

**Comment by Jinming-Hu** [comment]
@sharmaplkt you should always instantiate your datalake clients with `.dfs.` endpoint. The clients will use `.dfs` endpoint for some operations and `.blob.` endpoint for the others. There's no way to modify or get around this. If you have a firewall, you should add both `.dfs` and `.blob.` endpoints into the rule set.

**Comment by sharmaplkt** [comment]
@Jinming-Hu 
`If you have a firewall, you should add both .dfs and .blob. endpoints into the rule set.` Regarding this. Can you point me to the Azure documentation for adding both endpoints.

**Comment by Jinming-Hu** [comment]
@sharmaplkt There's no documentation for this. This is how storage SDK works, not just C++, but all languages (.Net, Java, etc.)

**Comment by sharmaplkt** [comment]
@Jinming-Hu For Java, We are able to connect to storage account without adding endpoint for `.blob`. But we need to add this specifically only for C++.

**Comment by Jinming-Hu** [comment]
@sharmaplkt That's kind of surprising to me. I'm checking Java's source code. Java SDK also transforms datalake operations into blobs. For example, `GetPathProperties` is transformed to `GetBlobProperties` https://github.com/Azure/azure-sdk-for-java/blob/2d5157baab234be4ebf990b4f8a1ec1ec1134992/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakePathClient.java#L1522C5-L1529C6
