### ISSUE TITLE
`SIO_IDEAL_SEND_BACKLOG_QUERY` fails to compile under MinGW-w64

### ISSUE THREAD

**Issue by sharadhr** [Azure/azure-sdk-for-cpp#5745]
Hi!

At work, we are using vcpkg to compile [`azure-core-cpp`](https://vcpkg.link/ports/azure-core-cpp) with a custom CMake toolchain that uses [llvm-mingw](https://github.com/mstorsjo/llvm-mingw).  The following line fails to compile, with an error:
https://github.com/Azure/azure-sdk-for-cpp/blob/55c241902d6897f9c8b9aee2668c76c5d0723ba4/sdk/core/azure-core/src/http/curl/curl.cpp#L192

```
vcpkg/buildtrees/azure-core-cpp/src/ore_1.11.2-51f61b141e.clean/_/_/_/src/http/curl/curl.cpp:191:24: error: use of undeclared identifier 'SIO_IDEAL_SEND_BACKLOG_QUERY'
  191 |   if (WSAIoctl(socket, SIO_IDEAL_SEND_BACKLOG_QUERY, 0, 0, &ideal, sizeof(ideal), &ideallen, 0, 0)
```

As far as I've seen, this symbol is undefined on MinGW-w64, and libcurl seems to have a [workaround](https://github.com/curl/curl/blob/ff92e3b13ce34f8c00410eea0ffbba4d7c20e679/lib/cf-socket.c#L1478), by manually defining the value. Until MinGW defines this (I've made a mailing list request), could the ioctl be `#define`d with an include guard? Perhaps:

```diff
#if defined(AZ_PLATFORM_WINDOWS)
+#  if defined(__MINGW64__)
+// In Windows SDK, this is defined to _IOR('t', 123, ULONG)
+#  define SIO_IDEAL_SEND_BACKLOG_QUERY _IOR('t', 123, ULONG)
+#  endif
// Windows needs this after every write to socket or performance would be reduced to 1/4 for
// uploading operation.
// https://github.com/Azure/azure-sdk-for-cpp/issues/644
void WinSocketSetBuffSize(curl_socket_t socket)
{
  ULONG ideal{};
  DWORD ideallen{};
  // WSAloctl would get the ideal size for the socket buffer.
  if (WSAIoctl(socket, SIO_IDEAL_SEND_BACKLOG_QUERY, 0, 0, &ideal, sizeof(ideal), &ideallen, 0, 0)
      == 0)
  {
    // if WSAloctl succeeded (returned 0), set the socket buffer size.
    // Specifies the total per-socket buffer space reserved for sends.
    // https://docs.microsoft.com/windows/win32/api/winsock/nf-winsock-setsockopt
    setsockopt(socket, SOL_SOCKET, SO_SNDBUF, (const char*)&ideal, sizeof(ideal));
  }
}
#endif
```

**Comment by sharadhr** [comment]
Closing; MinGW has implemented these definitions.

**Comment by dg0yt** [comment]
Maybe closed too fast. Might take a long while until it reaches all mingw users.

**Comment by LarryOsterman** [comment]
In general, we welcome community contributions to the repository. If the MinGW changes aren't available everywhere, we would welcome a contribution to help address the issue there.

**Comment by sharadhr** [comment]
I see this as a MinGW shortcoming, not ours. MinGW is meant to expose Windows APIs as-is, which it didn't (and _still_ doesn't, since the [Windows Implementation Library](https://github.com/microsoft/wil/issues/117)—which this depends on—doesn't compile correctly against MinGW). 

Upstream has fixed this particular issue, so I don't see a reason to keep this open or write a workaround.

**Comment by RickWinter** [comment]
Closing per request
