### ISSUE TITLE
Azure pipeline creds can't be used with chained token creds

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#5769]
**Describe the bug**
when the proper vaslues are not passed to the pipeline creds the create fails 

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by ahsonkhan** [comment]
@gearama can you please provide more here, or a code snippet for what you expect?

> when the proper vaslues are not passed to the pipeline creds the create fails

What are you trying to achieve here, and what values do you need to pass in?
If the required parameters are not provided or aren't valid, it is expected for the credential ctor to fail.
