### ISSUE TITLE
Cloud Shell ManagedIdentitySource should throw if a user-assigned managed identity clientID or resourceID is supplied

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-cpp#5783]
If the Cloud Shell ManagedIdentitySource is detected via MSAL and a user-assigned managed identity clientID or resourceID is supplied, the ManagedIdentityCredential should throw.

The rationale for taking this minor breaking change is that CloudShell does not support specifying a clientID or ResourceID and the current behavior of silently falling back to attempting to use a system-assigned identity could be unexpected.

**Comment by ahsonkhan** [comment]
I suspect this is the wrong behavior (putting the `client_id` value into the request body):
https://github.com/Azure/azure-sdk-for-cpp/blob/4dd4b18af947ea063ace9ad82cdbe872c1cf7699/sdk/identity/azure-identity/src/managed_identity_source.cpp#L268-L271

**Comment by ahsonkhan** [comment]
Issues from other languages (for reference):
https://github.com/Azure/azure-sdk-for-go/issues/23179
https://github.com/Azure/azure-sdk-for-java/issues/41119
https://github.com/Azure/azure-sdk-for-python/issues/36438
https://github.com/Azure/azure-sdk-for-js/issues/30380
