### ISSUE TITLE
Replace std::tolower from storage code and use Azure::Core::Details::ToLower()

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#581]
std::tolower can be problematic due to locale.

Use the implementation from Azure core for toLower() from `azure.hpp`

```cpp
  std::string const ToLower(const std::string& src) noexcept;
  unsigned char ToLower(const unsigned char src) noexcept;
```

Files:
sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
sdk/storage/azure-storage-common/src/shared_key_policy.cpp
sdk/storage/azure-storage-common/src/storage_uri_builder.cpp
sdk/storage/azure-storage-common/test/test_base.cpp
sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/protocol/share_rest_client.hpp

**Comment by Jinming-Hu** [comment]
almost done in https://github.com/Azure/azure-sdk-for-cpp/pull/793 except for file service.

**Comment by Jinming-Hu** [comment]
cannot use functions in `Details` namespace according to https://github.com/Azure/azure-sdk-for-cpp/pull/793#discussion_r506588059

**Comment by Jinming-Hu** [comment]
@vhvb1989 transfer this issue back to core team, either move `ToLower` out of `Details` namespace or close this issue

**Comment by Jinming-Hu** [comment]
partially done in PR https://github.com/Azure/azure-sdk-for-cpp/pull/834, @katmsft should do the rest
