### ISSUE TITLE
AzureCliCredential stores the wrong AzureDate when 'az account get-access-token' contains expire_on field

### ISSUE THREAD

**Issue by tcoserea-msft** [Azure/azure-sdk-for-cpp#5827]
**Describe the bug**
Similar with https://github.com/Azure/azure-sdk-for-cpp/issues/5075#issue-1964510239 . That issue was fixed only for the case where 'az account get-access-token' returns only ExpireOn field (which was localtime).  'expire_on' field is in universal time (GMT+0) and it does not need local time correction.
***Exception or Stack Trace***
No exception or stack trace available. For PST time (GMT-8) the observed behavior is that the token is renewed before each http request and the new token is assumed it is valid just to be replaced again and again and again. For core running  in front of the GMT+1 probably it would end up using expired tokens. 

**To Reproduce**
1) Install latest az cli (see https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) 
2) run 'az login' 
3) Make sure 'az account get-access-token' returns expire_on in its response.
4. Change your time to be GMT+k (k != {0, -1, 1}) 
4) Use sdk example to create an AzureCliCredential object. Observe that for all k positive your token is expired already. 

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

The cached token is used until it is not "fresh" anymore. 

**Screenshots**
![image](https://github.com/user-attachments/assets/ae67baa2-67eb-445c-9b9e-204df6083f8e)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : [e.g. IntelliJ]
 - Version of the Library used : user-agent : azsdk-cpp-storage-blobs/12.11.0 (Windows Server 2022 Datacenter 6.3 20348 20348.1.amd64fre.fe_release.210507-1500)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ahsonkhan** [comment]
I am unable to repro the issue using a newer version of the SDK. Please try with the latest `azure-identity-cpp` GA'd package, version 1.8.0 or higher (or what's in main) and let me know if you still see the bug.

Before the time change - token expires on `2024-07-18T16:58:35Z`
After changing the machine time to be 10 hours ahead, the same access token is returned from `AzureCliCredential` - token expires on `2024-07-19T02:58:35Z`

Repeated runs of the sample test app return the same access token and expiry date.

**Comment by tcoserea-msft** [comment]
Upgraded to 1.8.0 (using "builtin-baseline" : "adb391bd2cb05fdaef1ccef375dd50d998f01cc0" in vcpkg.json) and the issue went away. 

Thanks,
    Tudor.
