### ISSUE TITLE
Support "x5c" in the JWT for ClientCertificateCredentials

### ISSUE THREAD

**Issue by DavidS-msft** [Azure/azure-sdk-for-cpp#5848]
**Is your feature request related to a problem? Please describe.**
Currently the C++ SDK for Azure doesn't support sending the certificate chain when getting an authentication token from Azure as it is missing the "x5c" parameter. This results in Azure failing with 401 Unauthorized - "Please ensure that client assertion is being sent with the x5c claim in the JWT header using MSAL's WithSendX5C() method so that Azure Active Directory can validate the certificate being
 used."

**Describe the solution you'd like**
Add a flag that adds the "x5c" parameter to the JWT headers

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by ahsonkhan** [comment]
Hi @DavidS-msft,
We’ve added the feature requested by you, as a beta release, last week (1.10.0-beta.1). Please give it a try and let me know how it goes, or if you uncover any blockers 😊
https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/CHANGELOG.md#1100-beta1-2024-09-17

If you use vcpkg, it is available via our vcpkg beta registry:
https://github.com/Azure/azure-sdk-vcpkg-betas/tree/main

I would like to gather some feedback on our design choices/documentation here and understand your needs a bit better:
Regarding x5c support, we expect and send the PEM encoded signing certificate from the file provided (without the begin/end headers). We expect a **single** private key and the corresponding signing certificate in the file. We don’t expect the file to contain multiple, intermediate certificates and only send the leaf cert of the chain. That x5c JWT header is sent to the eSTS/identity endpoint only when you set the `SendCertificateChain` option in `ClientCertificateCredential` to true. Does that expectation and semantics work for you? Or do you expect to pass in an array/chain of certificates? Does the PEM encoded file you have contain exactly one private key and one certificate?

https://github.com/Azure/azure-sdk-for-cpp/blob/610c85d7684f9a384c3e72bb9a41068d41f521d1/sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp#L64-L72

Thanks!
