### ISSUE TITLE
How to find out if hierarchical namespace is enabled or not using OAuth with Azure sdk for cpp

### ISSUE THREAD

**Issue by stasasekulic** [Azure/azure-sdk-for-cpp#5867]
**Describe the bug**
When using OAuth GetAccountInfo throws exceptions that The resource does not exist

***Exception or Stack Trace***
The resource does not exist

**To Reproduce**
Use any example with OAuth authorization 
Or just use code form unit tests but with TokenCredentials

***Code Snippet***
TEST_F(BlobServiceClientTest, AccountInfo_LIVEONLY_)
  {
    // This operation doesn't support OAuth-based authorization.
    auto serviceClient
        = Blobs::BlobServiceClient::CreateFromConnectionString(StandardStorageConnectionString());

    auto accountInfo = serviceClient.GetAccountInfo().Value;
    EXPECT_FALSE(accountInfo.SkuName.ToString().empty());
    EXPECT_FALSE(accountInfo.AccountKind.ToString().empty());
    EXPECT_FALSE(accountInfo.IsHierarchicalNamespaceEnabled);

    auto containerClient = serviceClient.GetBlobContainerClient(LowercaseRandomString());

    accountInfo = containerClient.GetAccountInfo().Value;
    EXPECT_FALSE(accountInfo.SkuName.ToString().empty());
    EXPECT_FALSE(accountInfo.AccountKind.ToString().empty());
    EXPECT_FALSE(accountInfo.IsHierarchicalNamespaceEnabled);

    auto blobClient = containerClient.GetBlobClient(RandomString());

    accountInfo = blobClient.GetAccountInfo().Value;
    EXPECT_FALSE(accountInfo.SkuName.ToString().empty());
    EXPECT_FALSE(accountInfo.AccountKind.ToString().empty());
    EXPECT_FALSE(accountInfo.IsHierarchicalNamespaceEnabled);
  }
**Expected behavior**
GetAccountInfo is available
**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : VSCode
 - Version of the Library used
BlobStorage 12.10. 
**Additional context**
Is there maybe a workaround for this, to somehow find out if HNS is enabled?
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by Jinming-Hu** [comment]
according to the [REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/get-account-information?tabs=shared-access-signatures), `Get Account Information` doesn't support OAuth. This is by design.
