### ISSUE TITLE
New artifact layout

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#587]
Consider organizing artifacts like: 

```
- packages
  - azure-core
    - package.json
    - CHANGELOG.md
    - docs
      - docs.ms
        - api-docs.md
      - api
        - <doxygen files> 
```

So we don't put docs in a separate location... This will also obviate the need to put package.json in the doxygen docs. 

This will affect downstream publishing pipelines.

**Comment by RickWinter** [comment]
@danieljurek We've settled on a layout.  If additional specific changes are warranted please reopen or file a new issue
