### ISSUE TITLE
retry policy doesn't work if connection is reset/dropped

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#589]
https://github.com/Azure/azure-sdk-for-cpp/blob/8aa289667a7b1ab0d094ff915d2c7d9b25fdf705/sdk/core/azure-core/src/http/curl/curl.cpp#L884

we throw `std::runtime_error` here, which cannot be caught by retry policy.

**Comment by vhvb1989** [comment]
Fixed by PR #640
