### ISSUE TITLE
Consider returning encoded query parameters in Azure::Core::Http::Url::GetQuery

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#590]
https://github.com/Azure/azure-sdk-for-cpp/blob/3e4fa183772dee1e8c6b5add7e7b4b48882f7b32/sdk/core/azure-core/inc/azure/core/http/http.hpp#L284

also need to make `Decode` public available.

as talked offline with @ahsonkhan and @katmsft

**Comment by vhvb1989** [comment]
Will be fixed by : https://github.com/Azure/azure-sdk-for-cpp/pull/598.
Since we will expose Encode and Decode, and the query parameters will be in URL as they were added (api docs expected to be encoded)
