### ISSUE TITLE
Make Url to keep url-encoded query parameters

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#592]
Invert the way queries are keep inside Url to always be url-encoded.

If anyone needs non url encoded values, Url should expose an public static helper to Decode values.

Same way, there should be a public static Encode function that can accept more than default symbols to encode as parameter (similar to .Net)

**Comment by Jinming-Hu** [comment]
relevant to https://github.com/Azure/azure-sdk-for-cpp/issues/590
