### ISSUE TITLE
Static analysis is disabled during check-in CI tests

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-for-cpp#5922]
C++ compiler static analysis is disabled during pre-check-in CI tests.

This means that pull requests can be completed but then fail the nightly verification builds because static analysis is enabled there.

To enable static analysis in the CI pipeline, the `AZURE_ENABLE_STATIC_ANALYSIS` environment variable needs to be added in the job configuration (ci.tests.yml).

**Comment by RickWinter** [comment]
Lets add this to the CI gates.
