### ISSUE TITLE
[Bearer token] Bearer token authentication does not work.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#595]
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/core/azure-core/src/credentials/credentials.cpp#L53

`m_authority` is the full URL, shouldn't use set path to initialize it.

Otherwise, curl would try to connect to something like '/https://login.microsoftonline.com/xxxx/oauth2/v2.0/token'

**Comment by katmsft** [comment]
@danieljurek This is the issue that's currently failing the storage E2E test.

**Comment by Jinming-Hu** [comment]
Suggested changes

```
HttpUrl url(m_authority);
url.AppendPath(UrlEncode(m_tenantId));
url.AppendPath("oauth2/v2.0/token");
```
