### ISSUE TITLE
rare random failure

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#596]
```
unknown file: Failure
C++ exception with description "Fail to get a new connection for: standardstoragev2ut.blob.core.windows.net. Timeout was reached" thrown in the test body.
```

**Comment by Jinming-Hu** [comment]
@vhvb1989 What caused this failure and how can we avoid it?

**Comment by vhvb1989** [comment]
It is a libcurl error for making a request and taking more than 24 hours.
Can you elaborate about when you are seeing it?

Any way to reproduce?, Windows only?   Linux?

The more info we can get, the better

**Comment by Jinming-Hu** [comment]
very hard to reproduce. i'm sure it takes less than a few minutes.

**Comment by ahsonkhan** [comment]
> very hard to reproduce

Hence, this shouldn't be considered blocking. We should understand the impact and reproducibility of the issue first and then try to address any underlying bugs.

**Comment by Jinming-Hu** [comment]
i'll reopen this issue if i can reproduce
