### ISSUE TITLE
Allow certain response headers coming from AzurePipelinesCredential to be logged

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#5992]
These two response headers are useful for the service team to debug and diagnose issues, and hence it is requested that we do log them. For example, the e2e id is needed to understand the behavior observed in https://github.com/Azure/azure-sdk-for-cpp/issues/5786 / https://github.com/Azure/azure-sdk-for-cpp/pull/5875
- x-vss-e2eid
- x-msedge-ref

We decided, other than logging them, to also add these header values to the exception message that is thrown, so they are always visible, even with logging disabled.

Given our logged headers are based on an allow list, currently these two headers are REDACTED.

https://github.com/Azure/azure-sdk-for-cpp/blob/639fc9f59490d60d0390425ac82ccc9b5a6245f6/sdk/core/azure-core/src/http/log_policy.cpp#L73-L105

The open questions we're diving into with the service team, are:
1) Which headers are safe to log?  `x-vss-e2eid`, `activityid`, `x-msedge-ref`, `x-tfs-session`
2) Which headers do the service team need and would benefit from being logged for troubleshooting and diagnostics? `x-vss-e2eid`, `x-msedge-ref`
3) Are these headers unique/specific to Azure Pipelines, and only used by them, or are they used by any other services. For example, are all `x-vss-*` headers safe to log and ones only used/needed by them? `x-vss-e2eid` is used by ADO, but `x-msedge-ref` and `activityid` might be used by others.

Tracking issues across languages:
https://github.com/Azure/azure-sdk-for-net/issues/45993
https://github.com/Azure/azure-sdk-for-java/issues/41871
https://github.com/Azure/azure-sdk-for-go/issues/23444
https://github.com/Azure/azure-sdk-for-js/issues/31130
https://github.com/Azure/azure-sdk-for-python/issues/37412

cc @manolerazvan, @geekzter, @kboom

**Comment by LarryOsterman** [comment]
QQ: Which customers are asking for this and what are the semantics of these two headers? 

If this is only a single customer, would it be better to allow the customer to add them to the allow list themselves rather than making a global change which affects all customers?

**Comment by ahsonkhan** [comment]
This is coming from the Azure Pipelines team, since that info is useful for them to track down and debug service issues or questions that customers might report.

Most logging of the SDK is there to provide sufficient information to service teams and CSAs to help troubleshoot issues that customers might report, so such requests don't typically come directly from end customers.

In this case, we don't expect or want end users to have to enable logging of certain headers that are necessary for troubleshooting, after an issue has occurred, retry repro-ing, and submitting more info. This isn't a customer facing customization. For headers that are safe to log, and are necessary for troubleshooting, it is a good idea to log them pre-emptively.

The service team can better answer the question about what the header semantics are, but I don't think that detail is necessary for our purposes (and could vary from service to service).

The open questions we're diving into with the service team, are:
1) Which headers are safe to log?
2) Which headers do the service team need and would benefit from being logged for troubleshooting and diagnostics?
3) Are these headers unique/specific to Azure Pipelines, and only used by them, or are they used by any other services. For example, are all `x-vss-*` headers safe to log and once only needed by them?

That said, we _could_ consider allowing these headers to logged only in identity, or only for this credential type by having the internal implementation add to the loggable headers, rather than adding them to the global list of headers that are logged by all SDK clients.

**Comment by LarryOsterman** [comment]
In general, I'm quite leery of adding service-specific headers to the set of global inclusions.

This is explicitly why we allow service clients (and identity clients fall into this category) to specify service client specific exceptions. Storage does this extensively (example)[https://github.com/Azure/azure-sdk-for-cpp/blob/e7420dfd0441bf279c1d48409e4598630ed802c4/sdk/storage/azure-storage-common/test/ut/test_base.cpp#L331].
