### ISSUE TITLE
Wrap definition of PemEncodeFromBase64 with libcurl version >= 7.77

### ISSUE THREAD

**Issue by jasperrxzhu** [Azure/azure-sdk-for-cpp#6070]
**Describe the bug**
I cannot build `azure-storage-blobs` version 12.12.0 on RHEL 9.2 with curl and OpenSSL from the system manager (following instructions on https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/) due to unused function errors. Specifically, I get an unused function error with `PemEncodeFromBase64` defined in `azure-sdk-for-cpp/sdk/core/azure-core/src/http/curl/curl.cpp`.

This function is only called once on `azure-sdk-for-cpp/sdk/core/azure-core/src/http/curl/curl.cpp:315`, and this code is wrapped by `#if LIBCURL_VERSION_NUM >= 0x074D00 // 7.77.0`. However, the version of curl shipped with RHEL9.2 is `7.76.1`. I can build successfully after similarly wrapping the definition of `PemEncodeFromBase64` with `#if LIBCURL_VERSION_NUM >= 0x074D00 // 7.77.0`.

***Exception or Stack Trace***
```
cmake --build . --target azure-storage-blobs
[  0%] Building CXX object sdk/core/azure-core/CMakeFiles/azure-core.dir/src/http/curl/curl.cpp.o
~/azure-sdk-for-cpp/sdk/core/azure-core/src/http/curl/curl.cpp:278:13: error: ‘std::string {anonymous}::PemEncodeFromBase64(const string&, const string&’ defined but not used [-Werror=unused-function]
  278 | std::string PemEncodeFromBase64(std::string const& base64, std::string const& pemType)
      |             ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
gmake[3]: *** [sdk/core/azure-core/CMakeFiles/azure-core.dir/build.make:76: sdk/core/azure-core/CMakeFiles/azure-core.dir/src/http/curl/curl.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:558: sdk/core/azure-core/CMakeFiles/azure-core.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:910: sdk/storage/azure-storage-blobs/CMakeFiles/azure-storage-blobs.dir/rule] Error 2
gmake: *** [Makefile:338: azure-storage-blobs] Error 
```

**To Reproduce**
I am building `azure-storage-blobs` version 12.12.0 on RHEL 9.2 as shared libraries with curl and OpenSSL from the system manager.
1. Update the following CMakeLists.txt files to have the SHARED flag in their add_library lines:
```
azure-sdk-for-cpp/sdk/core/azure-core/CMakeLists.txt
azure-sdk-for-cpp/sdk/storage/azure-storage-blobs/CMakeLists.txt
azure-sdk-for-cpp/sdk/storage/azure-storage-common/CMakeLists.txt
```
2. Add overlay files as described in https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/ to use the system managed versions of curl and OpenSSL.
```
// azure-sdk-for-cpp/overlays/curl/vcpkg.json
{
    "name": "curl",
    "version": "7.76.0",
    "port-version": 0,
    "features": {
        "ssl": {
            "description": ""
        }
    }
}

// azure-sdk-for-cpp/overlays/curl/portfile.cmake
set(VCPKG_POLICY_EMPTY_PACKAGE enabled)

// azure-sdk-for-cpp/overlays/openssl/vcpkg.json
{
    "name": "openssl",
    "version": "3.0.7"
}

// azure-sdk-for-cpp/overlays/openssl/portfile.cmake
set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
```
3. Build the `azure-storage-blobs` target
```
cd ~/azure-sdk-for-cpp
mkdir build
cd build
cmake .. -DVCPKG_MANIFEST_MODE=ON -DVCPKG_OVERLAY_PORTS=/root/azure-sdk-for-cpp/overlays -DVCPKG_MANIFEST_DIR=/root/azure-sdk-for-cpp/
cmake --build . --target azure-storage-blobs
```

***Code Snippet***
In `azure-sdk-for-cpp/sdk/core/azure-core/src/http/curl/curl.cpp`:
```
std::string PemEncodeFromBase64(std::string const& base64, std::string const& pemType)
{
  std::stringstream rv;
  rv << "-----BEGIN " << pemType << "-----" << std::endl;
  std::string encodedValue(base64);

  // Insert crlf characters every 80 characters into the base64 encoded key to make it
  // prettier.
  size_t insertPos = 80;
  while (insertPos < encodedValue.length())
  {
    encodedValue.insert(insertPos, "\r\n");
    insertPos += 82; /* 80 characters plus the \r\n we just inserted */
  }

  rv << encodedValue << std::endl << "-----END " << pemType << "-----" << std::endl;
  return rv.str();
}
```
```
#if LIBCURL_VERSION_NUM >= 0x074D00 // 7.77.0
  if (!transportOptions.ExpectedTlsRootCertificate.empty())
  {
    curlOptions.SslOptions.PemEncodedExpectedRootCertificates
        = PemEncodeFromBase64(transportOptions.ExpectedTlsRootCertificate, "CERTIFICATE");
  }
#endif
```

**Expected behavior**
I expect to be able to build the `azure-storage-blobs` version 12.12.0 on RHEL 9.2 with curl and OpenSSL from the system manager without changes to the source code.

**Screenshots**

**Setup (please complete the following information):**
 - OS: RHEL 9.2
 - IDE : N/A
 - Version of the Library used: Azure storage blobs 12.12.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ahsonkhan** [comment]
Thank you @jasperrxzhu for filing the issue and providing a detailed explanation of your use case and the build issue you experienced. Though we don't have CI legs that build on RHEL, having an unused method due to the ifdef is easily fixable here.

Fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/6073
