### ISSUE TITLE
apiVersion param needs to be moved away from the method definition to use the param on the client. 

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#6072]
The code generated from typespec has an extra param attached to the APIs that is not in the current code: 
Generated code :
Azure::Response<FullBackupOperation> FullBackupStatus(
     **_std::string const& apiVersion,_**
     std::string const& jobId,
     Azure::Core::Context const& context = {});
 
Current code :
 
    Response<Models::BackupOperationStatus> FullBackupStatus(
        std::string const& jobId,
        Core::Context const& context = {});

in the current code the client wide version param is used 
url.SetQueryParameters({{"api-version", m_apiVersion}}); <-- this is a memeber of the client class set as part of the constructor

as opposed to the generated code : 

  url.AppendQueryParameter("api-version", Azure::Core::Url::Encode(apiVersion));

**Comment by ahsonkhan** [comment]
The same issue occurs in appconfig generation.

We expect the apiVersion to be elevated into a client-level param/options, and not a member/operation-level param.

Current:
```C++
  Azure::Response<CheckKeysResult> CheckKeys(
      std::string const& apiVersion,
      CheckKeysOptions const& options = {},
      Azure::Core::Context const& context = {});
```

Expected:
```C++
  Azure::Response<CheckKeysResult> CheckKeys(
      CheckKeysOptions const& options = {},
      Azure::Core::Context const& context = {});
```

**Comment by antkmsft** [comment]
Fixed in https://github.com/Azure/autorest.cpp/pull/405
