### ISSUE TITLE
Use regex defined in SemVer.ps1 instead of manually defined regex in SdkVersion-Common.ps1

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#609]
We should consider using the regex defined in the SemVer.ps1 script. We can add the extra parts around it if needed.

https://github.com/Azure/azure-sdk-for-cpp/pull/572#pullrequestreview-481495530

**Comment by RickWinter** [comment]
@danieljurek Is this still an active issue?

**Comment by RickWinter** [comment]
Issue has been addressed.
