### ISSUE TITLE
Certain members properties from the generated code should have different names

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#6112]
in thhe keyvault secrets tsp 
  /**
   * Expiry date in UTC.
   */
  @encodedName("application/json", "exp")
  @encode("unixTimestamp", int32)
  expires?: utcDateTime;
 
gets emitted as Exp in the cpp ,

**Comment by RickWinter** [comment]
Tracked in the TypeSpec-cpp work
