### ISSUE TITLE
ApiVersion field within client options for keyvault secret, key, and settings need to be settable.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#6126]
For some reason, these option fields are marked as `const` which means the user can't set them. They should likely be non-const. Making this change is non-breaking (unlike the other way around)
https://github.com/Azure/azure-sdk-for-cpp/blob/22c52996f34099af7e1ef871cef45da29bc39c13/sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_options.hpp#L19-L26
https://github.com/Azure/azure-sdk-for-cpp/blob/22c52996f34099af7e1ef871cef45da29bc39c13/sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_options.hpp#L56-L63
https://github.com/Azure/azure-sdk-for-cpp/blob/22c52996f34099af7e1ef871cef45da29bc39c13/sdk/keyvault/azure-security-keyvault-administration/inc/azure/keyvault/administration/settings_client_options.hpp#L24-L31

See other languages which allow setting this:
https://github.com/Azure/azure-sdk-for-net/blob/e665cae9b336d64732a570d0deec209c5d3b7ddf/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClientOptions.cs#L73

Other C++ SDK clients allow customizing the options:
https://github.com/Azure/azure-sdk-for-cpp/blob/22c52996f34099af7e1ef871cef45da29bc39c13/sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client_options.hpp#L94-L98
https://github.com/Azure/azure-sdk-for-cpp/blob/22c52996f34099af7e1ef871cef45da29bc39c13/sdk/keyvault/azure-security-keyvault-administration/inc/azure/keyvault/administration/backup_client.hpp#L29-L36

**Comment by LarryOsterman** [comment]
A minor nit: I 100% agree that these fields should not be declared as "const", but they *can* be set in the constructor for the structure.

This should work:

```cpp
auto options = SettingsClientOptions{"2020-01-01"};
```

However it doesn't change the fact that the ApiVersion field 100% should be mutable - the same applies to all Options properties.

**Comment by ahsonkhan** [comment]
We don't have a ctor. So, the following doesn't build:
```C++
auto options = Azure::Security::KeyVault::Administration::SettingsClientOptions{"2020-01-01"};
```

> Error (active)	E0289	no instance of constructor "Azure::Security::KeyVault::Administration::SettingsClientOptions::SettingsClientOptions" matches the argument list

**Comment by LarryOsterman** [comment]
> We don't have a ctor. So, the following doesn't build:
> 
> auto options = Azure::Security::KeyVault::Administration::SettingsClientOptions{"2020-01-01"};
> > Error (active)	E0289	no instance of constructor "Azure::Security::KeyVault::Administration::SettingsClientOptions::SettingsClientOptions" matches the argument list

That is so interesting...

https://godbolt.org/z/4TW7fxfo6

I believe the error you are seeing is because you are using function style initialization, and not initialization syntax.

And FWIW, that's a part of why the guidelines strongly prefer initialization syntax (`{...}`) over function syntax (`(...)`).

**Comment by ahsonkhan** [comment]
I don't believe that's the reason. I did use initialization syntax here.

I think it's because our options derive from ClientOptions which has a defaulted virtual destructor, unlike the example you shared above:
https://godbolt.org/z/YdcT1osMG
> \<source\>:21:30: error: no matching function for call to 'Meow::Meow(<brace-enclosed initializer list>)'

**Comment by LarryOsterman** [comment]
It's not the virtualized destructor. It's that you need to explicitly construct the base class (I didn't know this until I played with your example):

https://godbolt.org/z/r9KG73d1E

**Comment by antkmsft** [comment]
From https://azure.github.io/azure-sdk/cpp_implementation.html :

"Const and Reference members [⛔️](https://azure.github.io/azure-sdk/cpp_implementation.html#cpp-design-logical-no-const-or-reference-members) DO NOT declare types with const or reference members. Const and reference members artificially make your types non-Regular as they aren't assignable, and have surprising interactions with C++ Core language rules."
