### ISSUE TITLE
Add `Azure::AzureNamedKeyCredential` to Azure::Core and replace `Azure::Data::Tables::Credential::NamedKeyCredential` with it

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#6143]
We currently have `NamedKeyCredential` in Azure::Data::Tables::Credential.
https://github.com/Azure/azure-sdk-for-cpp/blob/d835e1a3b1970e53ceda94ef1c6d0596cd103d02/sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/named_key_credential.hpp#L20-L26

**Only IF** we are planning to keep this auth mechanism (https://github.com/Azure/azure-sdk-for-cpp/pull/6132), the [APIView and archboard review discussion](https://apiview.dev/Assemblies/Conversation/de3cd5b4510341e6ae1221af4525bd82#f4dafd3539eb4794aaa29abba210b622) was to move this to core since other service SDKs would end up using it (including [EventHubs, ServiceBus, Batch, etc.](https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-net%20AzureNamedKeyCredential&type=code))

Assuming we are keeping the ctor overloads for TableClient that accepts this, we'd want to make the move to core prior to GA, to avoid a breaking change.

Other tier-1 languages have an `AzureNamedKeyCredential` within the Azure.Core package (`Azure`/`azure.core.credential` namespace):
https://github.com/Azure/azure-sdk-for-python/blob/cc4162744239a89bb846891cd1299546d9acad34/sdk/core/azure-core/azure/core/credentials.py#L221
https://github.com/Azure/azure-sdk-for-js/blob/d74b28cf794bc85ac95142867d4cc49f95982d3e/sdk/core/core-auth/src/azureNamedKeyCredential.ts#L24
https://github.com/Azure/azure-sdk-for-java/blob/a1c1c26272b2fc555fddd28fca78a5e9a229dd7a/sdk/core/azure-core/src/main/java/com/azure/core/credential/AzureNamedKeyCredential.java#L46
https://github.com/Azure/azure-sdk-for-net/blob/b1644182ddd5c19a004cb57551cc26835ebbc685/sdk/core/Azure.Core/src/AzureNamedKeyCredential.cs#L15

cc @gearama, @RickWinter, @LarryOsterman, @ronniegeraghty

**Comment by gearama** [comment]
NO , until someone else needs it , no
