### ISSUE TITLE
Update flags enums within tables to follow precedence/guideline by adding Flags suffix keeping specific operators (&, &=, |, |=)

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#6153]
Use this as an example, from Storage:
https://github.com/Azure/azure-sdk-for-cpp/blob/c168d736dddeaf0e589ba9fc1c415184c000715c/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp#L441-L477

1) Flags enums should be suffixed with `Flags`:
https://github.com/Azure/azure-sdk/issues/2315

2) If we are keeping these flags enum, I believe we should keep the operators specific to the two enums, duplicating them, rather than "templatizing" them. That's what Storage did for their Flags enums, so there's precedence.

And rather than having all the extra bitwise operators (like XOR or NOT), we can simplify to only the 4 that's most likely to be needed by customers (OR/AND): &, &=, |, |=

Here are the set of enums that need to be updated:
- enum class AccountSasPermissions
- enum class AccountSasServices
- enum class AccountSasResourceType
- enum class TablesSasPermissions

This one is correct (although it doesn't seem to be used anywhere within `QueryTables()` - https://github.com/Azure/azure-sdk-for-cpp/issues/6155):
- enum class QueryTablesIncludeFlags

https://github.com/Azure/azure-sdk-for-cpp/blob/c168d736dddeaf0e589ba9fc1c415184c000715c/sdk/tables/azure-data-tables/inc/azure/data/tables/account_sas_builder.hpp#L89-L128

cc @gearama, @LarryOsterman, @RickWinter

**Comment by gearama** [comment]
API names were approved by the API review
