### ISSUE TITLE
QueryTablesIncludeFlags doesn't seem to be used anywhere within the QueryTables operation

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#6155]
This option doesn't seem to be used by the SDK, in the implementation detail, but is publicly exposed:
https://github.com/Azure/azure-sdk-for-cpp/pull/6154

It's probably worth going back to a source of truth and investigating. What does the REST API specs or service docs say here?

Maybe it was carried over from storage, where `"include"` is added as query parameter. Should the same be done here?
https://github.com/Azure/azure-sdk-for-cpp/blob/c168d736dddeaf0e589ba9fc1c415184c000715c/sdk/storage/azure-storage-blobs/src/rest_client.cpp#L788-L795

GoLang doesn't seem to have this option, though I am not familiar with the service or specifics of Go's implementation:
https://github.com/Azure/azure-sdk-for-go/blob/0387c89ceebae256c9ea717533c739b7a875d996/sdk/data/aztables/options.go#L115-L145

**Comment by ahsonkhan** [comment]
Marking as blocking release if we need to remove it, since this is public surface area, and can't be fixed after.

cc @RickWinter, @LarryOsterman

**Comment by ahsonkhan** [comment]
The REST docs for query tables don't mention any use of the `include` query param.
https://learn.microsoft.com/en-us/rest/api/storageservices/query-tables

But, they do mention setting the `Accept` request header to one of a few sets of Metadata values (one of `application/json;odata=nometadata`, `application/json;odata=minimalmetadata`, `application/json;odata=fullmetadata`:
https://learn.microsoft.com/en-us/rest/api/storageservices/query-tables#request-headers

We seem to hardcode it to minimalmetadata always (and only in the PrepXEntity operations).
https://github.com/Azure/azure-sdk-for-cpp/blob/c168d736dddeaf0e589ba9fc1c415184c000715c/sdk/tables/azure-data-tables/src/tables_clients.cpp#L1027

GoLang exposes this via options:
https://github.com/Azure/azure-sdk-for-go/blob/0387c89ceebae256c9ea717533c739b7a875d996/sdk/data/aztables/options.go#L129-L131
https://github.com/Azure/azure-sdk-for-go/blob/0387c89ceebae256c9ea717533c739b7a875d996/sdk/data/aztables/constants.go#L59-L67

cc @jhendrixMSFT

**Comment by ahsonkhan** [comment]
The other languages expose the `Metadata` option which let's users modify the accept request header when calling QueryTables. The REST API doc linked above mentions it.

Re-opening to consider what we want to do here.

**Comment by gearama** [comment]
done

**Comment by ahsonkhan** [comment]
https://github.com/Azure/azure-sdk-for-cpp/issues/6155#issuecomment-2448679389
Can you please link where this was fixed? What's the conclusion here.
