### ISSUE TITLE
Expand testing of Response with malformed responses

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#616]
Plug in the framework that simulates varieties of invalid reponses.

**Comment by RickWinter** [comment]
@antkmsft , Mike Harder has a framework that allows validating the system with partial, incomplete, invalid responses.  We need to automate using that system and run it against both WinHttp and Curl.

**Comment by vhvb1989** [comment]
http-fault-injector: https://github.com/Azure/azure-sdk-tools/tree/master/tools/http-fault-injector

I will build the C++ sample in the azure-sdk-tools repo next to java and .net.  

Things to be done:
  - Create CMake project which consumes the Azure SDK for C++ libraries.  Start by consuming only Azure Core to test a general request directly performed by the Azure Core transport adapters (libcurl on Lin, winHttp on Win).
  - Implement sample application and the  `FaultInjectionClientHandler` class to redirect the requests.
  - Test all responses provided by the fault-injector.
  - Optionally, and if time allows it, create a sample for using Storage client, similar to .NET

The estimated time for all the implementation and test (without fixing any possible bugs in the adapters) is 2 days.

**Comment by vhvb1989** [comment]
LibCurl results:

## f: Full response

./sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
Status Code: 200

## p: Partial Response (full headers, 50% of body), then wait indefinitely

./sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Timeout waiting for socket to read.

## pc: Partial Response (full headers, 50% of body), then close (TCP FIN)

./sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer

## pa: Partial Response (full headers, 50% of body), then abort (TCP RST)

/sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer

## pn: Partial Response (full headers, 50% of body), then finish normally

./sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer

## n: No response, then wait indefinitely

./sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Timeout waiting for socket to read.

## nc: No response, then close (TCP FIN)

./sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer

## na: No response, then abort (TCP RST)

./sdk/core/azure-core/test/fault-injector/azure-core-test-fault-injector 
Sending request...
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer

**Comment by ahsonkhan** [comment]
@vhvb1989 what are the expected results for each of those scenarios and what do other languages like .NET do?
Does what's happening match what we want?

**Comment by vhvb1989** [comment]
> @vhvb1989 what are the expected results for each of those scenarios and what do other languages like .NET do?
> Does what's happening match what we want?

I've asked @mikeharder to take a look to these results. I believe they are fine.  Mike can correct me if I am wrong, but I think what we want is to make sure that our transport adapter:
 1.  Can be used with the fault-injector. Means it can send the request and waits until we manually chose what response to return from the fault injector.  While we wait for that, the transport adapter should just keep waiting for the server response.
 2.  Throw an exception or somehow recognize the returned response from the server is invalid/incompleted/etc.  We want to make sure that the transport adapter won't consider an invalid response as OK and gives the buffer back to the protocol layer which will try to parse an invalid response.
 3.  Make sure there's a request timeout for the cases when the Server won't finish a response. We don't want to keep waiting for the server forever.

**Comment by mikeharder** [comment]
These results look correct for a single request (with no retries).  One issue we've seen in other languages is that the retry policy was not being applied correctly in some of these cases.  For example, if you were downloading a blob and the response is closed/aborted in the middle of the body, the client should retry automatically (and only download the remaining data, at least in .NET).

Another note is you can pre-select the response from the fault injection server using a special header:

https://github.com/Azure/azure-sdk-tools/blob/9ea6ba9c57116fa68ebbcc988adf8bccf58595dd/tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Program.cs#L48
