### ISSUE TITLE
windows authentification

### ISSUE THREAD

**Issue by mickae1** [Azure/azure-sdk-for-cpp#6201]
I would like to know if it's possible to use the windows account to authenticate ?

**Comment by ahsonkhan** [comment]
Hi @mickae1, can you share more information of what you are trying to do? Which Azure service are you trying to authenticate to, and which SDK/programming language are you trying to use?

**Comment by mickae1** [comment]
> > Hi [@mickae1](https://github.com/mickae1), can you share more information of what you are trying to do? Which Azure service are you trying to authenticate to, and which SDK/programming language are you trying to use?
> > The C++ SDK authenticates requests to Azure services (such as Storage, KeyVault), using mechanisms such as [ManagedIdentityCredential](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview).
> 
> Piling onto Ahson's response: Typically Windows authentication is either tied to a local user account or an Active Directory managed account. Neither of those accounts can work natively with Azure services because there is no mechanism that allows the Azure service to authenticate the local user account or the Active Directory account.
> 
> As Ahson asked, could you help us understand your scenario better?

Thx you answered my question.

**Comment by ahsonkhan** [comment]
I am not sure if this could help you @mickae1 or if it is the type of thing you are looking for in your question, but there is a capability called web account manager (WAM) to authenticate using authentication brokers from the OS (can be done interactively):
https://learn.microsoft.com/en-us/entra/identity-platform/scenario-desktop-acquire-token-wam

That said, the capability isn't exposed via an SDK in C++. 
The Microsoft Authentication Library (MSAL) in certain languages, [like .NET](https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/wam), provide support for this.
