### ISSUE TITLE
Rewrite installation paragraph in the combined release notes

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#6207]
See "Installation Instructions" in https://azure.github.io/azure-sdk/releases/2024-10/cpp.html as example.

```
Installation Instructions
To install any of our packages, copy and paste the following commands into a terminal:

# From Source
git clone https://github.com/Azure/azure-sdk-for-cpp
# git checkout <tag_name>
# For example:
git checkout azure-storage-blobs_12.0.0
```

Why isn't there a vcpkg instead of git clone? We do not even promote building the repo as main consumption mechanism.

**Comment by ahsonkhan** [comment]
@ronniegeraghty - I recall there was an existing work item tracking this somewhere, but I couldn't find it

**Comment by ronniegeraghty** [comment]
> [@ronniegeraghty](https://github.com/ronniegeraghty) - I recall there was an existing work item tracking this somewhere, but I couldn't find it

Here's the old one: https://github.com/Azure/azure-sdk-for-cpp/issues/3106

**Comment by gearama** [comment]
Can't find the "To install any of our packages, copy and paste the following commands into a terminal"  string in our repo
