### ISSUE TITLE
Add Bearer Challenge auth policy

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#641]
At the moment, it is a bit client-specific, and Core has everything to write a support for it (ClientSecretCredential, parsing headers from a response), so I can see the reasons for it to fall into Client team area. However, as more services adopt it, I don't see why it wouldn't be moved to Code/Irentity area and used by more than one client.

In other SDKs it is currently the Client libraries who implement a credential that handles "www-authenticate" header (it seems to be only in KeyValult for now, but in our case Storage wants it). 

I see how I would've implemented it, probably without any more additional information.

**Comment by Jinming-Hu** [comment]
I think we can refer to JS implementation. Core or identity library provides a `ChallengeBasedAuthenticationPolicy` and also make some necessary changes to `TokenCredential` or have another credential type inherited from `TokenCredential`. Then storage client will use this new `TokenCredential` to replace `ClientSecretCredential` which we're currently using.

**Comment by Jinming-Hu** [comment]
But anyway this isn't an urgent task. We can hold it until other sdk has implemented it so that we can have more information to refer to.

**Comment by RickWinter** [comment]
@Jinming-Hu per your comment of this isn't urgent and can wait for other SDKs to implement first.  I don't see this as blocking-release.  Please confirm

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu per your comment of this isn't urgent and can wait for other SDKs to implement first. I don't see this as blocking-release. Please confirm

yeah, i removed the `blocking-release` tag. but it's still in core sdk's backlog.

**Comment by antkmsft** [comment]
Part of, and basically is #1601.
