### ISSUE TITLE
Improve performance on Windows

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#644]
basically, we don't see any perf issue on Linux, but we can still see about 20% gap between Track2 and Track1 on Windows.

details in email thread

**Comment by vhvb1989** [comment]
@Jinming-Hu  can you share a program that we can use on windows as a reference?

Please share instructions on how to run the program and the results you see with it on Windows v/s track 1.  We can then use that sample for profiling and improving

**Comment by Jinming-Hu** [comment]
@vhvb1989 I believed i sent you an email on Sept. 11.

**Comment by vhvb1989** [comment]
Some info about investigation:
UploadFrom is the API that take longer on Windows, it doesn't escalate after 8 threads.
Uploading 50Mb with 1 thread takes ~50sec
Uploading 50Mb with 2 threads takes ~25sec
Uploading 50Mb with 4 threads takes ~15sec
Uploading 50Mb with 8 threads takes ~9sec  // From here ahead, API does not escalates any more...
Uploading 50Mb with 16 threads takes ~9sec

**Comment by vhvb1989** [comment]
Some more info.
curl_easy_send can send up to 64K per req on Linux, while on Windows, it is no more than 16K.
This creates a bottleneck for uploading on Windows, since uploading a 8MB chunk is taking ~9 sec

**Comment by vhvb1989** [comment]
> 
> 
> Some info about investigation:
> UploadFrom is the API that take longer on Windows, it doesn't escalate after 8 threads.
> Uploading 50Mb with 1 thread takes ~50sec
> Uploading 50Mb with 2 threads takes ~25sec
> Uploading 50Mb with 4 threads takes ~15sec
> Uploading 50Mb with 8 threads takes ~9sec // From here ahead, API does not escalates any more...
> Uploading 50Mb with 16 threads takes ~9sec

No escalation is because each thread would upload 8MB, so as soon as 7 threads are used (7x8MB ) would be enough to upload the 50MB.
each 8MB chunk is taking ~9sec to be uploaded.

I am investigating why it takes 9sec for 8MB.
It takes 512 uploads of 16k to complete the 8Mb upload. that would means that uploading 16k is taking ~16 milliseconds.
However, debugging a simple 16k upload is taking one 1ms per uploading on debug mode.  So, this is something weir

**Comment by Jinming-Hu** [comment]
@vhvb1989 where did you run your test? You should find a Azure VM with fast enough network.

**Comment by vhvb1989** [comment]
@Jinming-Hu  I am running EastUS VM

Size
Standard D4s v3
vCPUs
4
RAM
16 GiB

Connecting to storage account 
West US, East US

I haven't compared against track 1
First I got the numbers I mentioned below to have a reference on where track 2 is taking more time.

As I mentioned, in windows, only 16k are sent at a time and that's taking about 16ms. Still need to investigate more about it. Even reusing same connection, writing to socket is slow

**Comment by Jinming-Hu** [comment]
@vhvb1989 You should use a storage account in the same region as the VM.

**Comment by vhvb1989** [comment]
Opened new issue to libcurl
https://github.com/curl/curl/issues/6009

`curl_easy_send` is uploading only 16K on windows. I have been doing more experiments trying to increase the upload size to 64k (as it is on linux and on Windows-with-libcurl-easy-callbacks)
