### ISSUE TITLE
Create release permission securitry groups

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#65]
Other releases are gated by membership in a security group. Create the corresponding security group and associate it with the appropriate pipelines.

**Comment by gilbertw** [comment]
@danieljurek Do we have these groups on the C and C++ repos?

**Comment by danieljurek** [comment]
I have a group configured for the C repo. Need to set one up for C++

**Comment by danieljurek** [comment]
C++ group is created and properly associated with environments.
