### ISSUE TITLE
[Storage STG74] Container Soft Delete.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#651]

**Comment by Jinming-Hu** [comment]
nothing needs to be done from client side given [undelete](https://github.com/Azure/azure-sdk-for-cpp/blob/21214f9e387375ad32791dca4464273de6eeda9e/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp#L159) is already implemented.
