### ISSUE TITLE
Storage live tests are failing

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#663]
Storage live tests are failing

* There is something wrong with the proposed ARM template. Tests are assuming that settings are present which are not present in the ARM template. 
* There may be other failures that should be investigated. 

Until these issues are addressed merging the Live Test Framework will turn the nightly pipelines red (https://github.com/Azure/azure-sdk-for-cpp/pull/608) 

If there are problems with tests that cannot be immediately solved, those failing tests should be disabled in the test framework and issues opened to track fixing the root cause of the test failures and reenabling the tests. 

Test failure logs: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=525746&view=results

**Comment by danieljurek** [comment]
This issue is causing the storage pipeline to fail to be red: https://github.com/azure/azure-sdk-for-cpp/issues/663

**Comment by Jinming-Hu** [comment]
@katmsft has been working on this live tests integration.

**Comment by katmsft** [comment]
The failing is due to some features not enabled by ARM template. I'll try to do some modifications to enable those features. Is fetching all your changes in the mentioned PR going to trigger storage live test for me to validate that my change is sufficient?

**Comment by danieljurek** [comment]
We just chatted in the C++ meeting. I'll merge my PR and you can iterate on the live tests in the `master` branch. Live tests run in the `cpp - storage` pipeline.

**Comment by katmsft** [comment]
this is already resolved as live test framework has been integrated.
