### ISSUE TITLE
Storage README needs updates to follow guidelines

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#691]
The storage docs need to be split up into README's for each package.  The toplevel README should link to each of the packages.

For reference you can refer to the other languages for storage:
https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage

In each of the package specific readme's they should follow the standard doc structure.
https://review.docs.microsoft.com/en-us/help/contribute-ref/contribute-ref-how-to-document-sdk?branch=master#readme

**Comment by RickWinter** [comment]
@vinjiang @Jinming-Hu , Can you prioritize this work for Zn.

**Comment by Jinming-Hu** [comment]
working on it https://github.com/Azure/azure-sdk-for-cpp/pull/4183

**Comment by Jinming-Hu** [comment]
and https://github.com/Azure/azure-sdk-for-cpp/pull/4318
