### ISSUE TITLE
We need to call `curl_global_init` and `curl_global_cleanup`

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#70]
According to [this page](https://curl.haxx.se/libcurl/c/curl_global_init.html) and GLOBAL CONSTANTS section in [this page](https://curl.haxx.se/libcurl/c/libcurl.html), we need to call `curl_global_init` to set up libcurl environments. To put it simply, **this function must be called before any other threads are created in current process**. 

Although `curl_easy_perform` will call `curl_global_init` automatically, in [this page](https://curl.haxx.se/libcurl/c/curl_easy_init.html), it says **This may be lethal in multi-threaded cases**. And we recently did come across some connection issues due to not calling `curl_global_init` in cpplite sdk which also uses libcurl as HTTP backend.

Currently the only solution I can think of is to add two functions like `azure_core_global_init` and `azure_core_global_cleanup`, and call `curl_global_init` and `curl_global_cleanup` in these two functions respectively. Our customers are to call `azure_core_global_init` at the very beginning of `main()` function and call `azure_core_global_cleanup` before process exits. The drawback of this solution is that 1. it's an additional responsibility for our customers, which worsens user experience 2. init and cleanup are very C-style stuff in my opinion.

Do you guys have good ideas to resolve this issue?

PS: Defining a global class and call `curl_global_init` in its constructor won't work in this case.

**Comment by RickWinter** [comment]
The customer is expected to call this method before calling into the SDK.
