### ISSUE TITLE
Storage version should be 12.0.0

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#708]
Storage versions in track2 started at version 12.0.0.
Storage needs to switch to standard version.hpp header.

**Comment by Jinming-Hu** [comment]
> Storage needs to switch to standard version.hpp header.

I still have some concern about the format of `version.hpp`, which i already said before in [this](https://github.com/Azure/azure-sdk-for-cpp/issues/543) issue but didn't get any response from eng/sys or core team. so i'd like to repeat here.

According to the [guidelines](https://azure.github.io/azure-sdk/cpp_design.html#macros), we should avoid using macros except for in the following situations, or we should get approval from Azure Review Board.

* Platform, compiler, or other environment detection (for example, _WIN32 or _MSC_VER).
* Emission or suppression of diagnostics.
* Emission or supression of debugging asserts.
* Import declarations. (__declspec(dllimport), __declspec(dllexport))

I don't think the version strings fall into any of the four situations above. I don't think the macros here are necessary at all. We can totally do it in an easier and more idiomatic to C++ way like

```
static constexpr int AzureCoreMajorVersion = 1;
static constexpr int AzureCoreMinorVersion = 0;
static constexpr int AzureCorePatchVersion = 0;
static constexpr const char* AzureCorePrereleaseVersion = "beta.1";
```

**Comment by Jinming-Hu** [comment]
So @RickWinter , are we going to make this case an exception? Should we get approval from Azure Review Board first?

**Comment by RickWinter** [comment]
Are you asking if we need an exception to be 12.0.0?  If so the answer is NO.  We would need an exception if we planned to be something other than 12.0.0 

For reference I've included links to other language package versions.

js:
```
{
  "name": "@azure/storage-blob",
  "sdk-type": "client",
  "version": "12.3.0-beta.2",
```
python:
```
12.0.0b1 (2019-07-02)
Version 12.0.0b1 is the first preview of our efforts to create a user-friendly and Pythonic client library for Azure Storage Blobs. For more information about this, and preview releases of other Azure SDK libraries, please visit https://aka.ms/azure-sdk-preview1-python.
```
java:
```
12.0.0-preview.1 (2019-06-28)
Version 12.0.0-preview.1 is a preview of our efforts in creating a client library that is developer-friendly, idiomatic to the Java ecosystem, and as consistent across different languages and platforms as possible. The principles that guide our efforts can be found in the Azure SDK Design Guidelines for Java.
```

**Comment by Jinming-Hu** [comment]
> Are you asking if we need an exception to be 12.0.0? If so the answer is NO. We would need an exception if we planned to be something other than 12.0.0
> 
> For reference I've included links to other language package versions.
> 
> js:
> 
> ```
> {
>   "name": "@azure/storage-blob",
>   "sdk-type": "client",
>   "version": "12.3.0-beta.2",
> ```
> 
> python:
> 
> ```
> 12.0.0b1 (2019-07-02)
> Version 12.0.0b1 is the first preview of our efforts to create a user-friendly and Pythonic client library for Azure Storage Blobs. For more information about this, and preview releases of other Azure SDK libraries, please visit https://aka.ms/azure-sdk-preview1-python.
> ```
> 
> java:
> 
> ```
> 12.0.0-preview.1 (2019-06-28)
> Version 12.0.0-preview.1 is a preview of our efforts in creating a client library that is developer-friendly, idiomatic to the Java ecosystem, and as consistent across different languages and platforms as possible. The principles that guide our efforts can be found in the Azure SDK Design Guidelines for Java.
> ```

No, i have no objection to change version to 12

**Comment by Jinming-Hu** [comment]
@RickWinter i meant using macros here violates guidelines. Should we make this exception?

**Comment by RickWinter** [comment]
> @RickWinter i meant using macros here violates guidelines. Should we make this exception?

That guideline is referring to macros in the sense of functions.  These are string literals and constants.  I'll get the guidelines updated to clarify.

**Comment by Jinming-Hu** [comment]
> That guideline is referring to macros in the sense of functions. These are string literals and constants. I'll get the guidelines updated to clarify.

Hi @RickWinter ,  I'm trying to change string literals and constants from `constexpr` to macros in this PR https://github.com/Azure/azure-sdk-for-cpp/pull/804 since you've reinterpreted that macros aren't prohibited according to C++ guidelines. This way, all the definitions, no matter version strings or other string literals will be defined in the same way and be consistent within storage SDK.

But there seems to be a lot of objections. What do you suggest we should do in this case?

**Comment by ahsonkhan** [comment]
> What do you suggest we should do in this case?

While the issue of constexpr vs macro (for strings) is being discussed as an open guidelines topic, I recommend storage **not** block on that, and move to version 12.0.0 **AND** to the version.hpp format that core is already following.

This way, you can leverage and feed into the auto-release update PRs and have the SDK release in a consistent manner.

We can continue and settle on the constexpr discussion separately, and depending on the agreed decision update all the version.hpp as necessary, including core's.

So, for now, please follow and mirror what is already there as an example, to make forward progress and remote the dependency on a `version.txt` file:
https://github.com/Azure/azure-sdk-for-cpp/blob/2d8694a8f4e14edfa85f057472ca8f967b239f29/sdk/core/azure-core/inc/azure/core/version.hpp#L1-L54

**Comment by Jinming-Hu** [comment]
> While the issue of constexpr vs macro (for strings) is being discussed as an open guidelines topic, I recommend storage **not** block on that, and move to version 12.0.0 **AND** to the version.hpp format that core is already following.

Sure we can change the version to 12.0.0, which we never have any objections to. I believe we're going to do it in next release.

But updating version.hpp and updating the version to 12.0.0 are two separate things. Technically we can do either one or both or neither. I don't think they depend on each other.

Like you've already said this is still an open guideline topic (which by the way i don't agree, because we've already talked about this in guidelines meeting a few months ago and have the conclusion [here](https://azure.github.io/azure-sdk/cpp_design.html#macros), but i'm totally fine if you want to revisit this conclusion), so it's possible that we would have to change the code twice if we changed it before we have a final conclusion. We've been through situations like this several times, and to avoid changing code twice is always our choice, right?

Furthermore if I changed the code like you've suggested, we'd be doing something obviously violating current C++ guidelines, which I believe nobody wants to. Especially when we cannot see the benefit of doing so.

**Comment by ahsonkhan** [comment]
Makes sense. What do you propose as the next step? Would you prefer creating a version.hpp change (separate from the version bump), using constexpr instead?

We may need to make changes to engsys, or at least validate that the release and version update changes still continue to work.

**Comment by Jinming-Hu** [comment]
> Makes sense. What do you propose as the next step? Would you prefer creating a version.hpp change (separate from the version bump), using constexpr instead?
> 
> We may need to make changes to engsys, or at least validate that the release and version update changes still continue to work.

I suggest we finalize on the format of `version.hpp` first, about whether we should use macros or `constexpr`s. I have a proposal in [this](https://github.com/Azure/azure-sdk-for-cpp/issues/708#issuecomment-709704950) comment.

**Comment by RickWinter** [comment]
Please move to the new header.  We will not publicly expose macros.  Whether we use them internally in the header is a question we can solve/fix later.

**Comment by Jinming-Hu** [comment]
> Please move to the new header. We will not publicly expose macros. Whether we use them internally in the header is a question we can solve/fix later.

Sure, if you say so.
