### ISSUE TITLE
Create Identity e2e tests for running in Azure Service Fabric

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-cpp#716]
Tracking item to create new /sdk/e2e Azure.Identity smoke tests for running in Azure Service Fabric hosted environment.

1. Add new /sdk/e2e tests for Azure Service Fabric
2. Update Parent issue https://github.com/Azure/azure-sdk/issues/901 with instructions for Test team

**Comment by antkmsft** [comment]
Pre-requisite: #2498

**Comment by antkmsft** [comment]
// NOTE: Azure Service Fabric is Managed Identity Credential, and we do have an E2E test executable written for ManagedIdentityCredential: https://github.com/Azure/azure-sdk-for-cpp/blob/b54d509c72fb76598832bcf1fcd5c4a89b245782/sdk/identity/azure-identity/test/e2e/azure_identity_e2e_test.cpp

Still, our ManagedIdentityCredential does not support Service Fabric at this time.
