### ISSUE TITLE
Only run tests for the package

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#724]
Currently the pipelines are running all tests for every package.  The pipelines should only run the tests for the package they are building.

**Comment by danieljurek** [comment]
We have `CtestRegex` for CI testing (doesn't communicate with external services) and `LiveTestCtestRegex` for live testing. These can be set in ci.yml (https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/ci.yml#L41) ... With proper recording in place we can consolidate these down to a single regex paramater. 

I think this issue can be closed.

**Comment by danieljurek** [comment]
@antkmsft updated me on the new package build infrastructure. This could change how/where we run ctest.

**Comment by danieljurek** [comment]
We're already scoping tests today.
