### ISSUE TITLE
Consider updating the ctor of HttpPipeline to take a separate, required TransportPolicy

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#727]
Having the API accept a transport policy explicitly outside of the other policies makes it easier to discover what is needed in the pipeline.

Currently, as a user, I would need to know to provide a transport policy as the **last** one in the vector and read docs:
https://github.com/Azure/azure-sdk-for-cpp/blob/e3503f8575cc67d5663683071755d0ea1aff5625/sdk/core/azure-core/inc/azure/core/http/pipeline.hpp#L41-L48

See this design, which makes it more self-documenting and allows for better argument validation up front:
https://github.com/Azure/azure-sdk-for-net/blob/c38318e69b5f2b6ede64250138cbcb0f84c611f2/sdk/core/Azure.Core/src/Pipeline/HttpPipeline.cs#L25-L37

cc @RickWinter, @JeffreyRichter

**Comment by RickWinter** [comment]
Bear in mind customizing the pipeline is an advanced user scenario.  Even with the extra argument you'd need to read the docs :).  

Hearing you like the extra argument is one more vote for my original design.  My original impl mirrored .NET.  Jeff pushed back that he wanted it simpler and for the sake of unblocking the boot strapping I did a single array.  I support bringing back the argument.

**Comment by JeffreyRichter** [comment]
The customer passes a bunch of already initialized polices to create a pipeline.
A Transport Policy is actually optional; there are scenarios (like client-side cashing or playing back HTTP recordings) where a network request HTTP won't be made.

**Comment by ahsonkhan** [comment]
> A Transport Policy is actually optional;

Interesting. In that case, should we support pipelines with no policy provided, which instead of throwing, do a no-op? 

What is the desired behavior when someone provides a retry or other policy but no transport policy?

**Comment by JeffreyRichter** [comment]
There may be confusion here. There is a TransportPolicy and there is also a TransportAdapter.
The Azure SDK defines the TransportPolicy (TP) and the customer provides the TransportAdapter as an option to the TP.
We could always apply our TransportPolicy to the end of the customer's pipeline and expose the TransportAdapter parameter as the option to configure it. Although it would be better to expose a TransportPolicyOptions (which the TransportAdapter as a field inside it). If we did this, the customer still might provide a pipeline whose last policy doesn't call our TransportPolicy and, in this case, the TransportPolicyOptions are effectively ignored but we'd be forcing the customer to pass them.

**Comment by JeffreyRichter** [comment]
All policies are equal: the pipeline doesn't know that a policy is a retry policy or a transport policy. So, we can't have any logic related to this. A pipeline just takes in an HTTP request object, passes down the policies, and returns an HTTP response back up the policies.  A TransportPolicy just happens to send it across the network and does NOT forward the request to another policy. A client-side caching policy would check the cache if the data being requested is available locally and, if so, return a response. If the data is not available, then it could forward the request to the TransportPolicy.

Each Policy controls its own behavior and can short-circuit other policies and their behavior.

**Comment by vhvb1989** [comment]
>There may be confusion here. There is a TransportPolicy and there is also a TransportAdapter.

Can we have a Transport Adapter that is not inherited from TransportPolicy?
My understanding is that a transport adapter is a concrete class of a Transport policy.

for cpp:
```cpp
class CurlTransport : public HttpTransport {
}
``` 
>  playing back HTTP recordings

I though that the playback frameworl uses a concrete class as well for TransportPolicy that is used for unit test when playback is enabled instead of the regular curl/http transport

something like
```cpp
class PlayBackTransport : public HttpTransport {
}
```

In terms of usability and simplicity, I do prefer Jeff's design that won't ask for a Transport policy in the Pipeline's constructor.
To me, it is an endless  journey when we start going into `unlikely scenarios` ,  it looks like the more unlikely is something, the bigger is also the complexity that comes to it for avoiding the unknown behavior.

**Comment by JeffreyRichter** [comment]
Our TransportPolicy should call the HttpTransport to make the HTTP request and it should also download the entire HTTP response into a buffer (unless we're downloading a blob or file) and return the HTTP response up the pipeline. 

We expect the policy behavior to be very common but we expect the transport to change (based on OS or configuration, etc.).

But, the customer (or us in the future) might want to alter the policy. For example, in the future we could make a transport policy that just makes the request and NOT download the entire response at this time.

**Comment by RickWinter** [comment]
I don't disagree with your design Jeff.  I think what ahson is getting at (and why I did it in the other way in the beginning) is that some languages such as .NET treat the Transport as a parameter.  Every language does it a little bit different.  Its reasonable to want to understand the principle design goals for our implementation.  I don't consider this an approved change (yet).

**Comment by JeffreyRichter** [comment]
.NET doesn't allow the customer to fully replace the pipeline only allows the customer to insert some policies just before or after the retry policy. This is why .NET has the different design - you cannot replace the Transport policy. 

In C++ we need more flexibility for advanced scenarios since the customer can replace the transport entirely and only ever use HttpClient. .NET doesn't support other HTTP stacks.

**Comment by vhvb1989** [comment]
@ahsonkhan we added a constructor for HttpPipeline which hides the order of the transport adapter and other policies. I think we could close this issue after that.
