### ISSUE TITLE
Consider renaming the cmake options and remove `BUILD` to be consistent with Embedded C SDK

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#732]
For example:
`BUILD_TRANSPORT_CURL` -> `TRANSPORT_CURL`
https://github.com/Azure/azure-sdk-for-c#cmake-options

Apply similar renaming to all other options and update docs.

See https://github.com/Azure/azure-sdk-for-cpp/pull/706#discussion_r502601333

**Comment by Jinming-Hu** [comment]
I think BUILD prefix is more idiomatic to CMake. For example, we have built-in [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) option. Why not make changes in C sdk so that it's consistent with C++ SDK?

**Comment by ahsonkhan** [comment]
> I think BUILD prefix is more idiomatic to CMake.

I am not sure if that is actually true but open to seeing more examples "in-practice" that showcase that. Simpler/smaller names has a plus.

> Why not make changes in C sdk so that it's consistent with C++ SDK?

C has already shipped GA so that would introduce more user friction. Theoretically, we could, if we are convinced that's the right way to go.

**Comment by Jinming-Hu** [comment]
[BUILD_TESTING](https://cmake.org/cmake/help/v3.7/module/CTest.html)

**Comment by ahsonkhan** [comment]
Here are some more examples from popular OSS C++ repos:
https://github.com/google/googletest/blob/07f4869221012b16b7f9ee685d94856e1fc9f361/CMakeLists.txt#L25
https://github.com/opencv/opencv/blob/78476a0fe25b761dfda813f9ba030e5d7f1aa82f/CMakeLists.txt#L214-L229
https://github.com/apple/swift/blob/5f5d9e41a08e58a0f18d2600d6263b06ac383a05/CMakeLists.txt#L57-L85
https://github.com/taskflow/taskflow/blob/c75c05f3d549534e8bd05d6e9afdac82829ea786/CMakeLists.txt#L11-L15
https://github.com/pytorch/pytorch/blob/66505b64a5f26094b9b037c9777fec2706b2e5ad/CMakeLists.txt#L119-L124
https://github.com/monero-project/monero/blob/3cbb44a2fd79ce9c667006e2e42e61513993e59a/CMakeLists.txt#L262-L270
