### ISSUE TITLE
Add ARM64 into support matrix.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#74]
**Is your feature request related to a problem? Please describe.**
Azure Storage CPP SDK is heavily used by Microsoft internal customers, especially customers within the Azure Storage team. It is necessary for Azure CPP SDK to be built within Onebranch, where all the XStore code will be built on. Hence, it is a hard requirement for Azure Storage CPP SDK to support ARM64 platforms.

**Describe the solution you'd like**
Adding ARM64 as an official support matrix and figure out the validation plan.

**Describe alternatives you've considered**
None.

**Additional context**
There are also some internal customers from other teams who have asked for the ARM64 platform's support.

**Comment by gilbertw** [comment]
@BillyONeal as discussed in the meeting.  Please add back the row to the design guidelines.

**Comment by BillyONeal** [comment]
@gilbertw Already done :) https://github.com/Azure/azure-sdk/pull/1243
