### ISSUE TITLE
[Storage] Check if subscription that hasn't turned on smb-multichannel rejects returned xml is correct behavior.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#740]
Currently, the service is rejecting `ProtocolSettings` to be set for subscriptions that haven't turned this feature on, although this field is returned in the response body.
We are trying to communicate with the service team if this is correct behavior, but in the meantime, this line needs to exist.

_Originally posted by @katmsft in https://github.com/Azure/azure-sdk-for-cpp/pull/737#discussion_r503004762_

**Comment by katmsft** [comment]
Checked, this is a service bug. Tracking with email on progress.

**Comment by RickWinter** [comment]
@vinjiang , @Jinming-Hu Any update on this issue.  Has the service been fixed?  Can this issue be closed?
