### ISSUE TITLE
XML serializer/deserializer support.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#75]
**Is your feature request related to a problem? Please describe.**
Azure Storage services rely heavily on XML for data transfers. It has a higher priority than other transfer protocols (JSON/Avro).

**Describe the solution you'd like**
A newly implemented/existing dependency that provides XML serializing/deserializing support. Libxml2 sounds fine.

**Describe alternatives you've considered**
Other dependencies.

**Comment by gilbertw** [comment]
Per working group discussion, initially the XML serializer/deserializer will reside in the storage SDK.  
Using LibXML2 is tentatively the POR.

**Comment by JinmingHu-MSFT** [comment]
done
