### ISSUE TITLE
Read library versions from header files.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#750]
See https://github.com/Azure/azure-sdk-for-cpp/pull/748/files#r503419607 comment for details.

Libraries still using the version.txt method:
* azure-storage-blobs
* azure-storage-common
* azure-storage-files-datalake
* azure-storage-files-shares

**Comment by Jinming-Hu** [comment]
duplicate as https://github.com/Azure/azure-sdk-for-cpp/issues/708
