### ISSUE TITLE
Add support for recording and playback in GTest framework for Http request/response.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#768]
Other languages support recording/playback in tests for CI.

**Comment by katmsft** [comment]
https://github.com/Azure/azure-sdk-for-js/tree/e251ff8a8eab126fbc7f849db37f526f207532f2/sdk/test-utils/recorder

**Comment by vhvb1989** [comment]
related: https://github.com/Azure/azure-sdk-for-cpp/pull/843/files

**Comment by vhvb1989** [comment]
PlayBack and recored is already implemented as part of azure-core-test
