### ISSUE TITLE
Datetime needs to support more advanced ISO8601 conversion

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#776]
1. do not trim trailing zeros when converted to ISO8601 with decimals.

`DateTime::FromString("2020-10-13T21:06:15Z", DateTime::DateFormat::Iso8601).ToString(DateTime::DateFormat::Iso8601WithDecimals)` should return `2020-10-13T21:06:15.0000000Z`

`DateTime::FromString("2020-10-13T21:06:15.12345Z", DateTime::DateFormat::Iso8601).ToString(DateTime::DateFormat::Iso8601WithDecimals)` should return `2020-10-13T21:06:15.1234500Z`

2. truncate when converted to ISO8601 without decimals

`DateTime::FromString("2020-10-13T21:06:15Z", DateTime::DateFormat::Iso8601).ToString(DateTime::DateFormat::Iso8601WithoutDecimals)` should return `2020-10-13T21:06:15Z`

`DateTime::FromString("2020-10-13T21:06:15.99999Z", DateTime::DateFormat::Iso8601).ToString(DateTime::DateFormat::Iso8601WithoutDecimals)` should return `2020-10-13T21:06:15Z`

**Comment by ahsonkhan** [comment]
@Jinming-Hu - please add a motivating scenario for this feature request. Why do you need this fractional seconds truncation behavior and retention of trailing zeros and where will it be used?

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu - please add a motivating scenario for this feature request. Why do you need this fractional seconds truncation behavior and retention of trailing zeros and where will it be used?

because storage server side support four kinds of ISO8601 formats.

```
"yyyy'-'MM'-'dd'T'HH':'mm':'ss'Z'",
"yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffff'Z'",
"yyyy'-'MM'-'dd'T'HH':'mm'Z'",
"yyyy'-'MM'-'dd"
```

it doesn't support fractional seconds with less than or more than 7 digits. So the original implementation before this PR is simply unusable.

**Comment by ahsonkhan** [comment]
Thanks for that detail. That's quite helpful.

**Comment by ahsonkhan** [comment]
Do you need support for RFC 1123 as a datetime (at least for parsing), for example: `Mon, 15 Jun 2009 20:45:30 GMT`?

**Comment by Jinming-Hu** [comment]
> Do you need support for RFC 1123 as a datetime (at least for parsing), which is of the form `DAY, DD MON YYYY hh:mm:ss GMT`. For example: `Mon, 15 Jun 2009 20:45:30 GMT`?

yes, both parsing from string and converting to string.

**Comment by katmsft** [comment]
Why is this one closed? I think we still need this to be implemented. @Jinming-Hu can you provide the APIs that needs the format you mentioned?

**Comment by ahsonkhan** [comment]
It was already fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/936

Please re-open if you find issues after using it.

**Comment by vhvb1989** [comment]
On current master, you need to call `GetRfc3339String(TimeFractionFormat format)` for this feature. Where:
`TimeFractionFormat::DropTrailingZeros` ->  same old behavior
`TimeFractionFormat::AllDigits` ->  Will add 7 digits all the time
`TimeFractionFormat::Truncate ->  Will remove the 7 digits all the time.
