### ISSUE TITLE
Add broken link verifier to Ci like the one from C

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#783]
Check all links are valid on Readme and docs

**Comment by ahsonkhan** [comment]
Don't we already have that? See https://github.com/Azure/azure-sdk-for-cpp/pull/668

cc @sima-zhu

**Comment by sima-zhu** [comment]
Yes, we already have broken link scan for all lang repo. 
Are there any markdown files we do not cover for cpp?

**Comment by sima-zhu** [comment]
We currently check the markdown files only. There is no src code documentation validation.

**Comment by vhvb1989** [comment]
oh. My bad then.
I got confused. Will close it now. Thanks for looking into it @sima-zhu

**Comment by vhvb1989** [comment]
marckdown is enough 👍
