### ISSUE TITLE
Simplify CMake for generating ASTs for API review

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#786]
Add a CMake configuration for building the API review assets

**Comment by vhvb1989** [comment]
@RickWinter please elaborate about the expectation of this issue.
What do you mean by configuration?  a CMake option?  a CMake target?  How would you like to use it?

is it something like
```bash
cmake -DBUILD_AST=ON ..
make azure-core-ast //then the AST is generated in /build? 
make azure-storage
```

**Comment by RickWinter** [comment]
Yes, My thought here is it runs the steps to produce the AST and then zip as cppast.  That way the services can generate the assets for APIView of their service and upload without needing to manually figure out the right command line.

**Comment by RickWinter** [comment]
Closing as this is no longer relevant with the new APIView for C++.
