### ISSUE TITLE
uploading failed on Linux

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#814]
I'm trying to upload a blob with 50000 blocks, each block is 4000MiB. The whole blob is about 200TB. After uploading about 80TB, the program crashed due to this exception

```
$ ./azure-storage-sample BlobsGettingStarted
terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Connection was closed by the server while trying to read a response
Aborted (core dumped)
```

looks like this exception was thrown from transport layer. The VM and the storage account is in the same region, so the network is highly reliable and stable. I didn't find any network or storage service issue during that period. @vhvb1989 can core team help us understand why this exception was thrown?

**Comment by Jinming-Hu** [comment]
i'm using latest master branch, commit a1385518a2bb7b36816804efd729d008f663d9be

**Comment by Jinming-Hu** [comment]
looks like a different issue from #815

**Comment by vhvb1989** [comment]
That's libcurl reporting that the server closed the connection
You might want to compile with libcurl verbose (uncomment this line: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/core/azure-core/src/http/curl/curl.cpp#L1071)  and compile.

You will see more info about the failure in the logs
*my guessing is that it is I/O fault. 

Can you also share your source code?  
Also provide the CMake generate command you are using.

Also wondering,,, For a case like this, when customers want to upload big data, isn't it better to use appendBlob?

**Comment by ahsonkhan** [comment]
Please also share your vcpkg dependency versions.

**Comment by Jinming-Hu** [comment]
I changed `MaxRetries` from `3` to `10`, now everything looks fine.

**Comment by Jinming-Hu** [comment]
> Also wondering,,, For a case like this, when customers want to upload big data, isn't it better to use appendBlob?

Once we declare we support something in API reference, we should support it. We cannot say "although we say we support it, but actually it doesn't work, please use another way."
