### ISSUE TITLE
GCC 4.8 is not supported

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#829]
https://azure.github.io/azure-sdk/cpp_implementation.html#supported-platforms

this project cannot build with GCC 4.8

**Comment by Jinming-Hu** [comment]
Fixing build errors under GCC 4.8 is a solution, but removing GCC 4.8 from platform matrix seems easier.

**Comment by RickWinter** [comment]
Removing 4.8 would drop support for RHEL 7.

**Comment by Jinming-Hu** [comment]
> Removing 4.8 would drop support for RHEL 7.

and SLES 12

**Comment by RickWinter** [comment]
@antkmsft Anton can you can you update this issue with the changes necessary to build with gcc 4.8.
@danieljurek Are RHEL 7 or SLES 12 supported in our pipelines?

**Comment by antkmsft** [comment]
Given there are no compilation failures, #2023 will close this issue.

**Comment by antkmsft** [comment]
We do rely on VcPkg, and VcPkg's minimum requirements https://github.com/microsoft/vcpkg#quick-start-unix :
```
Prerequisites for Linux:

Git
g++ >= 6
Prerequisites for macOS:

Apple Developer Tools
On macOS 10.14 or below, you will also need:
Homebrew
g++ >= 6 from Homebrew
```
