### ISSUE TITLE
Storage clients should take an http transport adapter as an option

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#852]
The http transport adapter is currently hardcoded to use the libcurl one.

Please update clients implementations to set the transport adapter from the clientOptions so the customer can set it.
You can let libcurl as default on the options when customers didn't set this option.

This is required for record/playback tests, since the test cases will choose the playback adapter  if playback is Set.

This is only required to validate that we can replace the HTTP stack (once we have winHTTP).

**Comment by Jinming-Hu** [comment]
@vhvb1989 Can you give us an example of how our customers are going to replace HTTP transport layer, with source code?

**Comment by vhvb1989** [comment]
@Jinming-Hu , I believe this is usually something defined by each service.
I can share some options. Then you can define how Storage team would implement this and ask @JeffreyRichter  to review it.

So, option 1.
Let the final user select the transport adapter in client options
```cpp
 // Customer code...
  BlobContainerClientOptions options;
  // Ask the transport adapter as a unique_ptr so we can transer is ownership to the pipeline.
  // It can also be a shared_ptr if customer wants to use the same in multiple clients
  options.transportAdapter = std::make_unique<Azure::Core::Http::CurlTransport>();
  auto containerClient
      = BlobContainerClient::CreateFromConnectionString(GetConnectionString(), containerName, options);

 // Client init - Creating the pipeline for the client
   policies.emplace_back(std::make_unique<Azure::Core::Http::TransportPolicy>(
        options.transportAdapter));
    m_pipeline = std::make_shared<Azure::Core::Http::HttpPipeline>(policies);
```

This option enables final users to define what is the transport adapter (HTTP client) they want to use with the storage client they are creating. This option does not cover replacing the HTTP client for the same client/pipeline.  If the final user would like to use a different http client, they would need to create a new storage client. 

However, Storage team could add one method to the client to set the transport adapter (replace whatever was initially set) if you want.  This is not a required feature (like the one above to let the final user to set the initial HTTP client).

```cpp
  // This would be only if you want to let the final users to replace the http client
  containerClient.setHttpClient(std::make_unique<Azure::Core::Http::CurlTransport>());
```

You will need to manually remove the last policy from the pipeline and insert a new one with this value.

This option also enables any final user to create its own transport adapter (a derived class from HTTPTransport) and use it for creating a client.

Options 2.
Use enum for the transport adapter.
This would block the end users from creating and easily using its own http client.
```cpp
/ Customer code...
  BlobContainerClientOptions options;
  // Use enum to pick what transport to use
  options.transportAdapter = CURL_ADAPTER;
  auto containerClient
      = BlobContainerClient::CreateFromConnectionString(GetConnectionString(), containerName, options);

 // Client init - Creating the pipeline for the client
// Depending on the enum ssetting, you will create the http client to be used
   auto httpClient = GetTheAdapterfor(options.transportAdapter);
   policies.emplace_back(std::make_unique<Azure::Core::Http::TransportPolicy>(
        httpClient));
    m_pipeline = std::make_shared<Azure::Core::Http::HttpPipeline>(policies);
```
The end users would need to update the enum class if they would like to use its own http client.


You can also see how other languages do it.
Java has a builder to create a client which takes an HTTP client. 
see: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClientBuilder.java#L355

I think this is the general design that all languages are following.


The important requiriment is not to support the http client replacement, but to allow the final user to pick the initial value for it.

**Comment by JeffreyRichter** [comment]
Only option 1 is valid.
Option 2 is too limiting – it means the SDK MUST know all possible transports but we want to allow customers to create & use their own.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<http://aka.ms/RichterCloudApps>)

**Comment by Jinming-Hu** [comment]
> Only option 1 is valid. Option 2 is too limiting – it means the SDK MUST know all possible transports but we want to allow customers to create & use their own.

Agree, I prefer option 1.
