### ISSUE TITLE
[Core][Storage] Run pre-validation test cases for storage test set to ensure server end data readiness.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#856]
After the deployment is done and before the ctest gets triggered, there needs to be an additional phase to validate that the service properties can be correctly got and role assignment has taken effect.

**Comment by katmsft** [comment]
This can be achieved by a special regex for gtest command. However this needs to be supported by engsys.

**Comment by danieljurek** [comment]
@katmsft -- What regex needs to be supplied to the command? I can help wire this up.
