### ISSUE TITLE
Azure Service Bus c++ client support

### ISSUE THREAD

**Issue by BenyErnest** [Azure/azure-sdk-for-cpp#858]
**Is your feature request related to a problem? Please describe.**
Hi there,
Are there any alternative to register a message handler to an Azure Service Bus topic with a c++ client?. I'm using Qt framework, developing a webassembly app and I would like to register a message handler to handle messages published to a topic, like .net core sdk do, but currently I can't find a solution for c++.

**Describe the solution you'd like**
A c++ sdk for azure service bus like the ones that exist for other languages.

**Describe alternatives you've considered**
I haven't found any alternatives.

**Comment by RickWinter** [comment]
Thank you for the feedback.  Unfortunately at this time, this project does not have Service Bus support.  We will be considering it in one of the future releases.  We are currently working on the initial release which will include support for Storage::Blobs, Storage::Files::DataLake, Storage::Files::Shares.  We are looking to add more services to the SDK over time.

**Comment by BenyErnest** [comment]
Thanks for the response and kudos to the team for the excellent work. It'll be welcome a more complete c++ azure sdk since we are being struggle trying to connect to some azure service from c++.

**Comment by zsfarkas** [comment]
+1

**Comment by gh-andre** [comment]
REST API is the only way to use Service Bus from C++ and there's a lot of low-level stuff to add to a client written this way, even with a good HTTP client library. Very unfortunate. Amazon does provide a C++ SDK for services like AWS SQS.
