### ISSUE TITLE
Add a simplified storage common header just like the rest.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#876]
Is the header files in azure-storage-common meant to be public and used by end users? Do we apply the same breaking change bar to them as our other public headers? If so, we may want to add a simplified header for it, just like:
https://github.com/Azure/azure-sdk-for-cpp/blob/36ea25db7ff2c57fd65be3305bf4367c4816d12b/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake.hpp#L6
https://github.com/Azure/azure-sdk-for-cpp/blob/36ea25db7ff2c57fd65be3305bf4367c4816d12b/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares.hpp#L6
https://github.com/Azure/azure-sdk-for-cpp/blob/36ea25db7ff2c57fd65be3305bf4367c4816d12b/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs.hpp#L6

Maybe in `azure-sdk-for-cpp\sdk\storage\azure-storage-common\inc\azure\storage\common.hpp`:
```C++
// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

#pragma once

#include "azure/storage/common/access_conditions.hpp"
#include "azure/storage/common/account_sas_builder.hpp"
#include "azure/storage/common/concurrent_transfer.hpp"
#include "azure/storage/common/constants.hpp"
#include "azure/storage/common/crypt.hpp"
#include "azure/storage/common/file_io.hpp"
#include "azure/storage/common/json.hpp"
#include "azure/storage/common/reliable_stream.hpp"
#include "azure/storage/common/shared_key_policy.hpp"
#include "azure/storage/common/storage_common.hpp"
#include "azure/storage/common/storage_credential.hpp"
#include "azure/storage/common/storage_error.hpp"
#include "azure/storage/common/storage_per_retry_policy.hpp"
#include "azure/storage/common/storage_retry_policy.hpp"
#include "azure/storage/common/xml_wrapper.hpp"

```

cc @katmsft, @Jinming-Hu, @JeffreyRichter

**Comment by Jinming-Hu** [comment]
I doubt it is useful

**Comment by Jinming-Hu** [comment]
I don't think this is necessary because most of the time customers won't use common headers directly. If they do want to use some functionalities from common package (like account SAS), they can include the specific header.
