### ISSUE TITLE
[Storage] The test cases are reusing the same http connections.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#890]
The test cases are reusing the same http connections.
We should run each test independently (that's how I updated azure core)
Each test should be expected to be an independent case of creating a connection, creating a client and running the test.

Having one single client to run all tests makes tests interfere between them and there could be always some intermittent issues. Like, if a test pass but let the storage client in some specific state that the next test is not expecting.
And when using curl, ech curl connection will be in a pool to be re-used.  The server is more likely to close a connection when the channel have been open for a long time (then the retry policy will help us, but what if it does not).

I guess, if you really expect to create this relation between tests cases is fine, but I think that's not a good unit testing model.

When adding ctests, you can just use `gtest_add_tests` instead of `add_gtest` and gtest would create one unique test for each of your tests. (see azure core: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/core/azure-core/test/ut/CMakeLists.txt#L45)

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/608#issuecomment-719828787_

**Comment by katmsft** [comment]
I think one of the purposes of the reused client is to save env preparation time for each test case (Create a container, create blobs, etc). Other than this I don't have strong objections. We should also check with @Jinming-Hu when his back.

**Comment by Jinming-Hu** [comment]
I don't think such a feature would be necessary
