### ISSUE TITLE
Remove the c_ usage patterns in code

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#898]
It was decided to not use c_ in the code.  Constants should follow standard naming conventions, 

- PascalNamed for public
- pascalNamed for private

**Comment by Jinming-Hu** [comment]
@katmsft Are you aware of this decision?

**Comment by TarenLewis** [comment]
I am working on this now, I assume this applies to constexpr as well?

**Comment by Jinming-Hu** [comment]
@TarenLewis Yes, I think so.

**Comment by RickWinter** [comment]
That is correct.  We are using PascalCase for the constants including constexpr.
https://azure.github.io/azure-sdk/cpp_introduction.html#naming
