### ISSUE TITLE
Expose options for HTTP Stack

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#90]
**Is your feature request related to a problem? Please describe.**
The current HTTP client is hidden under a wrapper, where all the options are not exposed to customer, this needs to be changed so that customer can customize CA cert path or enable/disable keep-alive and so on.

**Comment by gilbertw** [comment]
@katmsft As discussed, please add a specific list of the required options

**Comment by JinmingHu-MSFT** [comment]
> @katmsft As discussed, please add a specific list of the required options

1. Customized CA_CERT location
2. Proxy
3. Disable cert validation
4. Disable Cert revocation list check
5. Enable/disable keep-alive options on http client

**Comment by katmsft** [comment]
Customized CA_CERT location: https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html
Proxy: https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html
Disable cert validation: https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html
Disable Cert revocation list check: https://curl.haxx.se/libcurl/c/CURLOPT_SSL_OPTIONS.html , CURLSSLOPT_NO_REVOKE
Enable/disable keep-alive options on http client: https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html

**Comment by JinmingHu-MSFT** [comment]
> Enable/disable keep-alive options on http client: https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html

This isn't HTTP keep alive we request. This is TCP keep alive.

**Comment by vhvb1989** [comment]
@katmsft , HTTP keep alive is currently done by default by Azure Core.
Do we have customers who might want to turn this feature off?

**Comment by ahsonkhan** [comment]
Also, can you please share a sample code snippet of how you envision the end user (customer) would write their code to opt-into and customize these options, to showcase how you (an author of the client library) would expose these.
