### ISSUE TITLE
Use vcpkg cache from 2020.11 version on CI

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#917]

**Comment by danieljurek** [comment]
This change doesn't really require `Central-EngSys` .. It can be done at any time by updating https://github.com/Azure/azure-sdk-for-cpp/blob/master/eng/vcpkg-commit.txt 

cc @vhvb1989 

You'll want to run all test pipelines by adding comments like `/azp run cpp - core` in the PR to kick off all of the pipelines. To be most confident I recommend running live tests.

**Comment by RickWinter** [comment]
@antkmsft Lets make this change early this week, please prioritize this.

**Comment by antkmsft** [comment]
@vhvb1989, we are now on the latest release, 2020.11: https://github.com/Azure/azure-sdk-for-cpp/blob/master/eng/vcpkg-commit.txt + https://github.com/microsoft/vcpkg/releases

**Comment by vhvb1989** [comment]
@antkmsft yes, that's correct, but we are still using the build cache from Azure-DevOps: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=822762&view=logs&j=0fa9045b-9773-5caa-2289-e9e87f13f3cb&t=880ba5cd-f074-5f56-2cef-dc78056bb3a5

The Azure devops caches uses 4 strings to build a key for the cache:
   Resolving key:
     - Validate Linux_x64_gcc8   [string]
     - "tags/2020.11"            [string]
     - Linux                     [string]
     - curl[ssl] libxml2 openssl [string]

This issue was created to ask Eng Sys (@danieljurek ) to remove the azure devops cache and use the VCPKG cache that is available in the version we are using. We need to set it up to where the cache will be persisted.

**Comment by antkmsft** [comment]
@danieljurek, my understanding is that we are either where we want to be already, then please close this issue. Otherwise, please either fix it, or let us know how we can get it fixed (and if we should).

**Comment by ahsonkhan** [comment]
This the binary caching feature in vcpkg: https://vcpkg.readthedocs.io/en/stable/users/binarycaching/

It isn't required for GA.
