### ISSUE TITLE
Updated link from http to https is wrong

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#934]
Some urls were updated from https://github.com/Azure/azure-sdk-for-cpp/commit/ef15be36afa9874d64bc26b3cda5330e2b1f2475

However the one for `http://xmlsoft.org/` shouldn't have changed since the https version does not exists.

**Comment by ahsonkhan** [comment]
Why didn't link verifier catch that, @sima-zhu ?

cc @weshaggard

**Comment by ahsonkhan** [comment]
Looks like link verification is failing now, from https://github.com/Azure/azure-sdk-for-cpp/pull/933:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=611878&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=ccad100f-2904-5913-2083-c525ad929a03&l=46

**Comment by weshaggard** [comment]
Looks like xlsoft.org recently had their certificate expire so it is no longer value which is why the https link started failing.
