### ISSUE TITLE
Remove unused structs in Datalake protocol layer or at lease make it inaccessible to customers

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#944]
https://github.com/Azure/azure-sdk-for-cpp/blob/f99e4a57c7528ef6138686f9b3e0c9e8d87cf635/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/protocol/datalake_rest_client.hpp#L334

**Comment by katmsft** [comment]
Fixed.
