### ISSUE TITLE
Identity links and docs don't show up in the index page

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#954]
See https://azure.github.io/azure-sdk-for-cpp/core.html
![image](https://user-images.githubusercontent.com/6527137/98892744-cd4b0d00-2455-11eb-8b9c-bccf109e2771.png)

Even though we have the docs published, the index page doesn't have a section for azure-identity:
https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-identity/1.0.0-beta.1/index.html

Part of the beta.1 release: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=616379&view=logs&j=b5a21550-4ef8-5e71-0e6c-dbbbd38cec49&t=68dc4038-80a7-578f-578a-83a705da57ac

cc @antkmsft, @weshaggard

**Comment by weshaggard** [comment]
cc @sima-zhu 

@ahsonkhan looks like azure-identity just released yesterday afternoon, and our doc-index is only built once a day (https://dev.azure.com/azure-sdk/internal/_build?definitionId=1976&_a=summary). I expect it will show up today after that pipeline runs. However it will initially show up under "Other" until it gets a better service name in the csv file at https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/cpp-packages.csv which currently also doesn't contain this new package. The new package should get added there today but we will need to update the ServiceName manually once it shows up there.

**Comment by sima-zhu** [comment]
@weshaggard I set the schedule build in noon time 12:00pm. I have changed to nightly build to 00:00 in the midnight right now. Just queue a build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=617152&view=results. We can check the docs under Other page after this.

**Comment by sima-zhu** [comment]
https://azure.github.io/azure-sdk-for-cpp/other.html

It is there now.

**Comment by ahsonkhan** [comment]
Closing as this has been fixed.

https://azure.github.io/azure-sdk-for-cpp/identity.html
![image](https://user-images.githubusercontent.com/6527137/104111296-2805b700-5295-11eb-9de0-6b1d004e7549.png)

**Comment by weshaggard** [comment]
@sima-zhu do we have a bug to clean up the "Other" section in all the languages? For C++ we should just hide the azure-template docs from the landing page here but setting it hide=true in the csv file.

**Comment by sima-zhu** [comment]
@weshaggard Not yet. I will create issues in each repo to address this.
