### ISSUE TITLE
Be consistent about private or protect in DataLake clients

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#963]
https://github.com/Azure/azure-sdk-for-cpp/blob/78e34a218926ac43fb06d54190b6c746eeb63692/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_file_client.hpp#L242

https://github.com/Azure/azure-sdk-for-cpp/blob/78e34a218926ac43fb06d54190b6c746eeb63692/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_path_client.hpp#L246

**Comment by katmsft** [comment]
As talked offline, this is by design due to `datalake_path_client` having child classes that need access to the members.
