### ISSUE TITLE
BlobServiceClientTest.Statistics failing live test with GeoReplication.LastSyncTime.HasValue() returning false

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#968]
Live test failing on `Validate Win_x86_with_unit_test` and `Validate MacOS_x64_with_unit_test`:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=617252&view=logs&j=ddb28780-e8af-530a-eff5-5360f22a15cb&t=2d6865e5-8b1d-55bc-bd31-c956ff709149&l=118

```text
120: [ RUN      ] BlobServiceClientTest.Statistics
120: D:\a\1\s\sdk\storage\azure-storage-blobs\test\blob_service_client_test.cpp(326): error: Value of: serviceStatistics.GeoReplication.LastSyncTime.HasValue()
120:   Actual: false
120: Expected: true
```

cc @Jinming-Hu

**Comment by Jinming-Hu** [comment]
Does it always fail or only fail occasionally?

**Comment by Jinming-Hu** [comment]
Can anybody identify what kind of storage accounts are being used for this test?

**Comment by ahsonkhan** [comment]
Maybe @katmsft knows those details since he worked on setting up the daily live tests

**Comment by Jinming-Hu** [comment]
> Maybe @katmsft knows those details since he worked on setting up the daily live tests

Okay then, assigned to @katmsft

**Comment by katmsft** [comment]
Please reference [this doc](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-service-stats#response-body), LastSyncTime can be empty in some scenarios, the test case shouldn't treat it as a non-empty value by default.

**Comment by Jinming-Hu** [comment]
> Please reference [this doc](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-service-stats#response-body), LastSyncTime can be empty in some scenarios, the test case shouldn't treat it as a non-empty value by default.

then i'm gonna fix it
