### ISSUE TITLE
No reference on the anchor link #vcpkg

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-cpp#972]
While working on building Github IO docfx site, it throws a warning about the anchor link below.
```
(CONTRIBUTING.md#L88)Invalid link: '<a href="#vcpkg">above</a>'. The file CONTRIBUTING.md doesn't contain a bookmark named 'vcpkg'.
```
![Screenshot 2020-11-12 180756](https://user-images.githubusercontent.com/48036328/99019848-24aeb300-2512-11eb-9d0e-c92db38d53e0.jpg)

Underneath is the unreferenced anchor link (#vcpkg).

Could you please review and check if it needs to fix?
cc:// @ahsonkhan

**Comment by ahsonkhan** [comment]
FYI @vhvb1989. I had mentioned this here: https://github.com/Azure/azure-sdk-for-cpp/pull/712#discussion_r502716789

In the meantime, we can update the link to point to `#### Third Party Dependencies` or remove the anchor link all together.

**Comment by vhvb1989** [comment]
Thank you for finding this @sima-zhu . I have created a PR.
