### ISSUE TITLE
Add some basic tests for the simplified storage header that customers use as a sanity check.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#976]
Similar to #824, add some basic tests for the simplified storage headers.

Specifically for:
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs.hpp
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake.hpp
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares.hpp

And soon to be added, common.hpp:
https://github.com/Azure/azure-sdk-for-cpp/issues/876

cc @Jinming-Hu, @katmsft

**Comment by Jinming-Hu** [comment]
close in favor of https://github.com/Azure/azure-sdk-for-cpp/issues/3592
